### ISSUE TITLE
add raw data in Json answer in V3

### ISSUE THREAD

**Issue by GCyrielle** [Microsoft/BotBuilder#1059]
Hi,
My bot communicates with an IOS app making the interface between the bot and the user. In v1 I used to work a lot with **dialogData** to send data to my app as it was sent with the Json answer. This way I could build widgets to display those data.
For example:
`session.dialogData.action="reponse";
session.dialogData.widget="resultCompteSolde";
session.dialogData.comptes=comptesResultat;
session.send("Voici le solde de votre compte : "); `

My app would call: _http://localhost:3978/api/messages_ with the question "How much do I have in my banking account?" and get the following answer:
`{
  "text": "Here is the money you have : ",
  "language": "fr-FR",
  "botConversationData": {
    "BotBuilder.Data.SessionId": "xxxxxxxxxxxxxxxxxxxxx"
  },
  "botUserData": {
    "favori": "CCP"
  },
  "botPerUserInConversationData": {
    "BotBuilder.Data.SessionState": {
      "callstack": [
        {
          "id": "/",
          "state": {
            "BotBuilder.Data.Group": "BotBuilder.Id.DefaultGroup",
            "BotBuilder.Data.Intent": "ConsulterSolde",
            "BotBuilder.Data.WaterfallStep": 1,
            "action": "reponse",
            "widget": "resultCompteSolde",
            "comptes": {
              "62246518748": {
                "nom_titulaire": "M.       JEAN DUPONT",
                "solde_compte": "300€"
              }
            }
          }
        }
      ],
      "lastAccess": 
    }
  }
}
`

It will then print the "text" field, use the "widget" one to know what kind of widget to display and read the "comptes" one to get the data to show in this widget.

As dialogData is not sent in the bot answer in V3, I don't know how to send those kind of values to my app anymore.  I've been looking in the documentation again and again but I can't find anything relevant. Am I missing something? 
By the way, I use Node.JS for my bot.

My thanks in advance for your help,

**Comment by willportnoy** [comment]
You're correct - instead of passing the dialog data through the message instance, in V3 the dialog data is stored using the state client.  You could provide a new implementation of the state client interface if you want access to the dialog data.  The reason for this change is that now messages are uniformly always sent on the outgoing http request - see https://docs.botframework.com/en-us/technical-faq/#what-is-the-model-for-how-user-messages-relate-to-https-method-calls for more information.

You might consider the DirectLine api for direct communication with your bot - when deployed, you shouldn't be able to use the normal messaging endpoint because that will expose your bot on the internet without authentication and JwtToken provided by the Bot Framework Connector.

**Comment by GCyrielle** [comment]
I'll see what I can I do with that then.
Thanks for your answer.
