### ISSUE TITLE
Feature requests for Direct Line

### ISSUE THREAD

**Issue by rzmoz** [Microsoft/BotBuilder#1063]
Hi,

I'm adding a custom sms channel using direct line and the question I have is regarding long running conversations and conversation ids.

It's stated that you must initiate a new conversation before having any "conversation". The POST command creates a new conversation with a new unique ID: https://docs.botframework.com/en-us/restapi/directline/#!/Conversations/Conversations_Upload (This is the most updated documentation I've found on direct line)

My question is how to re-use this newly generated conversation in future messages if the client should remain stateless.

Current scenario:
1. get sms from user
2. create new conversation
3. post message to direct line conversation
4. long poll messages and wait for reply from bot
5. send reply to user

My issue is if my client dies before the entire conversation is over For example, if my client is running on an azure web app and the instance gets recycled thus loosing the conversation id.

**Two scenarios I 'm having issues with:**
New sms from user: The client has lost the original conversation id thus have to generate a new id,
This results in that the boot sees this as a new conversation thus loose state data

Reply from bot: The client has lost the original conversation id thus it doesn't know which conversation to listen for replies to. This results in replies are never sent to the user 

**How to go about this scenario without implementing complex state keeping logic on the client side?**
This scenario being that the reply from the bot can come after a long time in which the client can be recycled. In other words, its all good that the bot framework and bot side is stateless but it seems the clients for direct lines are not well suited for long running conversations

suggested fixes:
#1 new sms'es - New Conversation POST accepts conversation id so it can be generated based on client context.

#2 reply - add support for reply web hook and not just long polling. Replies from direct line calls a web hook as most other APIs does including the bot builder framework.

Or should I use the bot api directly even though it's meant to be used from the bot side? That api supports creating conversations specifying conversation Id and service url webhooks

https://docs.botframework.com/en-us/restapi/connector/#!/Conversations/Conversations_CreateConversation

**Comment by Andrea-Orimoto** [comment]
This feature request has been added to our backlog, thanks!

**Comment by hpksp** [comment]
Hi, I would love to know the status of this feature request :) 

Having the option to register a web hook per conversation/all conversations (in addition to long polling or web socket) would help greatly for proactive bot scenarios.

For example when an event is triggered on our application side, we can send a notification to the respective user. Let's assume that the user is using Direct Line client and he/she is offline at the time of the notification being sent. When he/she comes back online (resume conversation + use  watermark) after 3 days that notification is no longer available in the Direct Line cache. 

If we can have a web hook in place, we can at least store the notification for the user to access it later. In my opinion, maintaining an intermediate server would be a waste, that's why I think web hook would be a great feature :)

Would love to know what you guys think. If there's another approach. please let me know. Thanks in advance.
