### ISSUE TITLE
Getting warning when using intentDialog, but input doesn't match.

### ISSUE THREAD

**Issue by zkahmad1** [Microsoft/BotBuilder#1066]
Hi,

I've implemented intentDialog, but when inputting something that doesn't match, I get the following warning:

> / - WARN: IntentDialog - no intent handler found for null

Is there a way to make this warning stop appearing? I'm currently testing using terminal, but I don't want it to occur when the bot is actually in use in chats. 

Thanks.

**Comment by andy0323** [comment]
Hi, I have this issue too. Have you resolve it?

**Comment by stevengum97** [comment]
Since this wasn't answered, I'm answering it now...

I recently came across this issue in my own code, except it was reporting to me the intent I had setup in LUIS; e.g. / - WARN: IntentDialog - no intent handler for _IntentName_. 

In my scenario, I had provided my dialog.matches() with the wrong string (_on initial setup I had typed in an entity for the intent as opposed to the actual intent_). On my next run through I ran a string that I knew would match with another intent on LUIS, one that I purposely did not yet write into my code...

I received the same message again, with _IntentName_ being the new-but-not-yet implemented intent. 

You're receiving the null message because you don't have anything setup for non-matched inputs. To fix this you need to have a [dialog.onDefault](https://docs.botframework.com/en-us/node/builder/chat-reference/classes/_botbuilder_d_.intentdialog.html#ondefault) which is used to handle non-matched inputs. For an example of this in action, view the ["Understanding Natural Language"](https://docs.botframework.com/en-us/node/builder/guides/understanding-natural-language/#navtitle) example code at line 98.

Here is the line of code:
`dialog.onDefault(builder.DialogAction.send("I'm sorry I didn't understand. I can only create & delete alarms."));`

P.S.
I believe that it reporting "_no intent handler for_ **null**" is deprecated. It now will say "_no intent handler for_ **None**".
