### ISSUE TITLE
Show large description type data in Facebook Thumbnail card

### ISSUE THREAD

**Issue by afficionaddo** [Microsoft/BotBuilder#1076]
Hi,

I want to show some data in Thumbnail card. But I am facing issues:

1. Text: "xxxxx" --> This field data is never shown in FB messenger
1. Title: "xxxx" --> If this title is too long, the FB messenger shows '......' in front.

So which field should i use if I want to show large description type data.

**Comment by reyesrico** [comment]
1. Text: "xxxxx" -> Facebook Messenger channel does not support "text" name property, that's why you will not see the text inside the Thumbnail Card. (I suggest to send the text outside the Thumbnail Card).
2. Title: "xxxx" -> Facebook Messenger channel has a limit of 80 character for the "title" name property, that's why you will see "..." after 77 character of your title text.  (I suggest to change the title of the card and use the long text outside the card).

Facebook Messenger - Generic Template Reference:
https://developers.facebook.com/docs/messenger-platform/send-api-reference/generic-template

**Comment by Andrea-Orimoto** [comment]
@afficionaddo  it looks like reyesrico answered your question, so I'm closing this issue. Please feel free to reopen this or create a new one if you still need help. Thanks!
