### ISSUE TITLE
Skype calling - chat demo doesn't work

### ISSUE THREAD

**Issue by 0GiS0** [Microsoft/BotBuilder#1093]
Hi,

I was testing this demo for Skype calling with Node.JS: https://github.com/Microsoft/BotBuilder/blob/master/Node/examples/demo-skype-calling/app.js but the chat dialog doesn't work. chatBot.send is Forbidden with that address object.

Any ideas? Thanks!

**Comment by Andrea-Orimoto** [comment]
Hi @0GiS0, it's probably because there is n inconsistency in the sample. At the top we tell you to set the calling endpoint as /api/calling, and in code we actually set it as /api/calls. We fixed the sample inconsistency, now both reference to /api/calls. So if you go into the developer portal skype configuration and change the calling endpoint appropriately ( I think you have now /api/calling, change it to /api/calls), it should work. 

Sometimes it takes a while for the config change to take effect. Regardless, make sure that the ngrok request matches the endpoint you set in code. So if you have

`var bot = new calling.UniversalCallBot(connector);
server.post('/api/calls', connector.listen());`

you should see this request in ngrok

`POST /api/calls              200 OK`

If you still see /api/calling in the ngrok log, it means the change did not take effect. Try to disable/enable calling in the dev portal skype configuration and save multiple times.

If this doesn't resolve your issue, please reopen it. Thanks!

**Comment by 0GiS0** [comment]
Hi Andrea,

The issue that I meant is not there... The conversation with the bot via call is working, but there is a dialog '/chat' which doesn't work:

bot.dialog('/chat', [
    function (session) {
        session.send(prompts.chat.intro);
        calling.Prompts.confirm(session, prompts.chat.confirm);        
    },
    function (session, results) {
        if (results.response) {
            // Delete conversation field from address to trigger starting a new conversation.
            var address = session.message.address;
            delete address.conversation;

            // Create a new chat message and pass it callers address
            var msg = new builder.Message()
                .address(address)
                .attachments([
                    new builder.HeroCard(session)
                        .title("Hero Card")
                        .subtitle("Space Needle")
                        .text("The <b>Space Needle</b> is an observation tower in Seattle, Washington, a landmark of the Pacific Northwest, and an icon of Seattle.")
                        .images([
                            builder.CardImage.create(session, "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Seattlenighttimequeenanne.jpg/320px-Seattlenighttimequeenanne.jpg")
                        ])
                        .tap(builder.CardAction.openUrl(session, "https://en.wikipedia.org/wiki/Space_Needle"))
                ]);

            // Send message through chat bot
            chatBot.send(msg, function (err) {
                session.endDialog(err ? prompts.chat.failed : prompts.chat.sent);
            });
        } else {
            session.endDialog(prompts.canceled);
        }
    }

It seems that the session.message.address in that context doesn't fit with chatBot.send, it says forbidden.

Thanks!

**Comment by muzahmed** [comment]
@0GiS0 Wow, great catch! Just pushed a fix -- should have a new patch ready in a day or two.

**Comment by 0GiS0** [comment]
Great! thanks @muzahmed :+1:
