### ISSUE TITLE
Private Bots?

### ISSUE THREAD

**Issue by jstrobel** [Microsoft/BotBuilder#1123]
Will it be possible in the future, to "hide" bots from the directory? Some Bots e.g. for customers wouldn't be for all users of skype but for a company or so, so it would be great to mark them as "private".

**Comment by ankitbko** [comment]
A bot is not visible in directory unless you explicitly _publish_ it. However in case of skype, if anyone has the bot contact address on skype, they can communicate with the bot. One way I see is that you check the `From` field and only reply to the users who are your customers.

You have more flexibility in Facebook messenger where you can explicitly add users to the app who can access the facebook app.

**Comment by jstrobel** [comment]
@ankitbko Thanks. But if i am right, only published bots can be added and used, so this wouldn't be a option. Yes i can check the from, but it would be nicer to prevent them from beeing visible in the directory.

**Comment by ankitbko** [comment]
@jstrobel You don't need to publish your bots to use them. Publishing a bot, post a review, will only list the bot in Bot Directory so that it is publicly available. You may very well have a bot and not publish it, but privately share the contact detail of the bot with your users. Check [this](https://docs.botframework.com/en-us/faq/#do-i-have-to-publish-my-bot-to-the-bot-directory-in-order-for-my-bot-to-be-available-to-users) faq.

**Comment by jstrobel** [comment]
@ankitbko Ah haven't seen the entry in the FAQ. Thanks.
