### ISSUE TITLE
redundant code

### ISSUE THREAD

**Issue by ranjan-ranjan** [Microsoft/BotBuilder#1141]
isn't https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Dialogs/BotData.cs#L74 to https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Dialogs/BotData.cs#L77 redundant code?

and this https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Dialogs/BotData.cs#L342 ?

**Comment by msft-shahins** [comment]
They are not redundant code because they are used for key comparison for implementation of [InMemoryDataStore](https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Dialogs/BotData.cs#L97). That is a generic implementation and considers a single instance of that can be shared between different bots and conversations. As a result that key comparison is necessary. 

Also [SetCacheValue](https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Dialogs/BotData.cs#L342) call is necessary to set the value that is being saved to the right data store on the entry.
