### ISSUE TITLE
LUIS: Intents are limite to only 20 ?

### ISSUE THREAD

**Issue by JpEncausse** [Microsoft/BotBuilder#1160]
Using LUIS as a NLP for our Bot it seems the intents are limited to 20. It's very few for a bot ...

I know we can provide multiple LUIS Id (but I assume it makes multiple HTTP Request ?)

How bot creator handle that ? Is it a technical limit ?

**Comment by willportnoy** [comment]
https://docs.botframework.com/en-us/technical-faq/#how-can-i-use-more-than-the-maximum-number-of-luis-intents

Feel free to ask more questions.

**Comment by JpEncausse** [comment]
Yes in a Nutshell Dialog send an HTTP request for each model.
My question is more why only 20 / model ?

**Comment by CarolHanna** [comment]
This limit is set due to performance reasons. But relaxing it is one of the top priorities on our roadmap, stay tuned :)

**Comment by andrew-kennedy** [comment]
Is there an easy way to add models more programmatically? besides just stacking up [LuisModel] annotations?

**Comment by willportnoy** [comment]
You can use the constructor that takes a number of ILuisService:

https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Dialogs/LuisDialog.cs#L146

There's no requirement to use the LuisModelAttribute on the class - you can construct a LuisService from the LuisModelAttribute and then pass that ILuisService to the constructor.

If you're using autofac or equivalent, you should be able to resolve all ILuisService implementations from the container.

**Comment by cglong** [comment]
@willportnoy Would it be possible to refactor `LuisModelAttribute` into a new `ILuisModel` interface and have the `LuisService` constructor take that as a parameter instead? I feel like that would be more scalable and would help for projects like ours that load these values from a config.

I can look into a PR for this if there's interest :)

**Comment by willportnoy** [comment]
@cglong LuisModelAttribute is just the POCO container for the configuration - as in those items, you can instantiate the LuisService with LuisModelAttribute instances that you obtain from whatever source you like (e.g. your DI container).

I'm not adverse to the interface, if you feel inheriting from attribute makes the LuisModelAttribute too heavy.

**Comment by willportnoy** [comment]
@cglong thank you for the pull request - we've merged it, so I'm going to close this issue.  Feel free to open a new issue for further discussion.

**Comment by mikob** [comment]
@CarolHanna It seems the limit has been raised, I currently have 23 intents. But what exactly is the new maximum? I can't find anything in the docs.

**Comment by rnjailamba** [comment]
@mikob any update on the maximum?

**Comment by willportnoy** [comment]
@rnjailamba I don't see it documented on https://www.luis.ai/Help - if you open a top-level issue, we can ask the appropriate people to respond.

**Comment by MohammedAbdulMateen** [comment]
Hey!, check this out https://docs.microsoft.com/en-in/azure/cognitive-services/luis/luis-boundaries
The limit for intents was raised from 80 to 500 that is a massive improvement hurray! 🥇 

Please check the mention link for the limits on other things as well such as entities, I recommend to go with a single LUIS app and a single LuisDialog instead of choosing a top level (RootDialog) and multiple child level dialogs or the factory pattern for finding the best fit intent method from a number of LuisDialogs until unless you are about/near to reach the limit, when you are about to reach the limit only then think of the design changes, don't overcomplicate from the beginning itself and try to focus on the development, that's what I would suggest :)

Happy coding!
