### ISSUE TITLE
Time required for the review before publish

### ISSUE THREAD

**Issue by naeemshaikh27** [Microsoft/BotBuilder#1202]
As the publish screen states,

`Publishing your bot opens it up to the world and lets people find it in the Bot Directory or through search. We need to do a quick review of your bot before it’s published. Make sure you take a look at our review guidelines before submitting.`

How quick is this quick review. Just want to know it because I dont find it documented anywhere! Thanks.

**Comment by jameslew** [comment]
It turns out the publishing phase is a little variable at the moment.  We've been adjusting how we do it and we've quite a backlog.

In the interim though, the review does not in any way hinder your bot from operating, just from having a place in the Bot Framework directory.  You can still try to publish it to other directories and so on.

**Comment by alokraj68** [comment]
Hello,
Can anyone say how much time will it take for publishing your first bot?
Is it less after we put up our first bot?
