### ISSUE TITLE
Bot Builder for node.js , Normal Button Instead of account_link for FB Messenger

### ISSUE THREAD

**Issue by txappmkr** [Microsoft/BotBuilder#1207]
Created a Bot with MS Bot Framework. Added Facebook Channel, When the Signin Card is sent on FB Messenger, the Connect me Button is being send as a normal button with Web URL but not being sent as a "account_link" button as facebook documentation mandates.
https://developers.facebook.com/docs/messenger-platform/account-linking/link-account

```
var msg = new builder.Message(session) 
        .attachments([ 
            new builder.SigninCard(session) 
                .text("please sign in to your account.") 
                .button("Login", "https://b1a27f14.ngrok.io/login") 
        ]); 
    session.send(msg);
```

Looking at the Card Actions.js @ \core\lib\cards\CardAction.js , i dont see the type = signin implemented.
C# SDK seems to have this logic implemented as explained in the example
CardAction plButton = new CardAction()
{
    Value = "https://<OAuthSignInURL>",
    Type = "signin",
    Title = "Connect"
};
cardButtons.Add(plButton);
SigninCard plCard = new SigninCard(title: "You need to authorize me", button: plButton);

**Comment by jameslew** [comment]
Thanks for the report, I'll get it in front of the devs and we'll take a look.

**Comment by Stevenic** [comment]
If you look at the implementation for `SigninCard.button()` you'll see that it adds the signin button for you. This action type is only valid for SigninCards which is why it's not a static off the CardActions class:

```

    public button(title: string|string[], url: string): this {
        if (title && url) {
            this.data.content.buttons = [{
                type: 'signin',
                title: msg.fmtText(this.session, title),
                value: url
            }];
        }
        return this;
    }
```

I'll add the dev for the facebook channel as it sounds like any bug would be at that layer...

**Comment by telkomops** [comment]
Thanks Stevenic, the facebook support mentioned that with the above code, the card went as a normal web url instead of account_link, option.

**Comment by palashjhabak** [comment]
Hi,

any update on this ?

Thanks,
Palash

**Comment by Stevenic** [comment]
I'll raise this issue internally. We'll need to decide if that's expected behavior.

**Comment by chrimc62** [comment]
@tomlm @Stevenic @maxpert was this resolved? Can you comment on the status?

**Comment by msft-shahins** [comment]
you can send the account_link button using channel data aka message.SourceEvent in node.js SDK. Note that since this is a channel specific feature your bot require to implement the required behavior/protocol over channel data.

**Comment by MrOnyancha** [comment]
This issue is not yet resolved
![screen shot 2017-02-16 at 12 26 18 am](https://cloud.githubusercontent.com/assets/5436153/23008597/accd31ba-f421-11e6-86c1-00dcc2abe807.png) 
It's actually showing that this is to  be coming screens but thus not the case. Instead of this 
![screen shot 2017-02-16 at 12 26 26 am](https://cloud.githubusercontent.com/assets/5436153/23008598/accd66bc-f421-11e6-9c1d-e3d17939ca30.png)
It redirects out side which makes the experience horrible.
