### ISSUE TITLE
 send external message to my bot

### ISSUE THREAD

**Issue by andrecordeiro** [Microsoft/BotBuilder#1224]
How do I get a php script, access my endpoint that is in azure, and send a message to my bot ?

**Comment by willportnoy** [comment]
Since the bot is a web service, you can always open up another web endpoint to reach your bot's code.

If you want your custom message to come in on the same activity endpoint as used by the Bot Framework, it's more involved since you can't impersonate the authentication added by the Connector.  In that case, DirectLine might be a method to contact your bot on that endpoint.

**Comment by willportnoy** [comment]
I'm going to close this issue for now, but feel free to open a new issue for further discussions.
