### ISSUE TITLE
SetUserDataAsync throws a "MissingProperty" error

### ISSUE THREAD

**Issue by jakobpn** [Microsoft/BotBuilder#124]
I'm working on adding authentication to a basic bot using code from Jeff Hollan's VSTS Bot sample (https://github.com/jeffhollan/BotFrameworkSample).

My login controller is using SetUserDataAsync to save the access token for the user.

```
                var client = new ConnectorClient(Constants.botId, Constants.botSecret);
                BotData getData;
                try
                {
                    getData = await client.Bots.GetUserDataAsync(Constants.botId, userid);
                }
                catch
                {
                    getData = new BotData();
                }
                getData.Data = ar.Serialize();
                await client.Bots.SetUserDataAsync(Constants.botId, userid, getData); 
```

Unfortunately, the SetUserDataAsync method throws a "MissingProperty" error.

I'm running the bot locally and I am talking to it through the Bot emulator.

Here is the request that is sent to the Bot service:

POST https://api.botframework.com/bot/v1.0/bots/{removed}Bot/users/2c1c7fa3 HTTP/1.1
Ocp-Apim-Subscription-Key: {removed}
Authorization: Basic {removed}
User-Agent: Microsoft.Bot.Connector.ConnectorClient/1.0.0.0
Content-Type: application/json; charset=utf-8
Host: api.botframework.com
Content-Length: 3823
Expect: 100-continue

{
  "data": "{\"AccessToken\":\"{removed}}"
}

This is the response from the service:

HTTP/1.1 400 Bad Request
Cache-Control: no-cache
Pragma: no-cache
Content-Length: 144
Content-Type: application/json; charset=utf-8
Expires: -1
X-Content-Type-Options: nosniff
Set-Cookie: ARRAffinity={removed};Path=/;Domain=bc-api.trafficmanager.net
X-Powered-By: ASP.NET
Date: Sat, 16 Apr 2016 15:48:57 GMT

{
  "error": {
    "code": "MissingProperty",
    "message": "You have to specificy userId or conversationId",
    "statusCode": 400
  }
}

And here is the exception:

{
  "message": "An error has occurred.",
  "exceptionMessage": "You have to specificy userId or conversationId",
  "exceptionType": "Microsoft.Rest.HttpOperationException",
  "stackTrace": "   at Microsoft.Bot.Connector.ErrorHandling.HandleError[ObjectT](HttpOperationResponse`1 result)\r\n   at Microsoft.Bot.Connector.BotsExtensions.<SetUserDataAsync>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Bot_Application1.LoginController.<Authorize>d__1.MoveNext() in C:\\Users\\jakobpn\\Scratch\\Bot Application1\\Bot Application1\\Controllers\\LoginController.cs:line 49\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"
}

**Comment by wiltodelta** [comment]
@jakobpn Workaround: After login, you can send a message with the updated UserData:

```
var connector = new ConnectorClient();

Message message = new Message
{
  Text = "LOGIN_SUCCESS"
  // Cleared
};

BotData botUserData = await connector.Bots.GetUserDataAsync(botId, userId);
message.BotUserData = botUserData.Data;
message.SetBotUserData("AccessToken", accessToken);
await connector.Messages.SendMessageAsync(message);
```

P.S.

**Comment by jakobpn** [comment]
Thanks @wiltodelta. I was wondering how I could send a message in the chat once the login succeded and I will give your code a try to see how it works. However, in my case the call to GetUserDataAsync throws an "object not found" error, so I will also need a workaround for that.

**Comment by jakobpn** [comment]
@wiltodelta Tried the code and got a "Object reference not set to an instance of an object" exception from SendMessageAsync. I don't think the message object has enough info in it to send a message back to the conversation with the user.

**Comment by willportnoy** [comment]
Does your userid passed to GetUserDataAsync/SetUserDataAsync have a non-null value?

**Comment by jakobpn** [comment]
@willportnoy yes, it is "2c1c7fa3", a value I grabbed from the message.From.Id property.

**Comment by willportnoy** [comment]
I believe we resolved this offline as a mismatch between production and the emulator - feel free to reopen if not.

**Comment by ejadib** [comment]
@jakobpn @willportnoy I'm having the same issue. Could you please share what was the resolution?

Thanks in advance!

**Comment by duscott** [comment]
I'm also having the same issue. The getting and setting of data using connector.Bots doesn't seem to work. It's not a difference between the emulator and production as far as I can tell since if I deploy my bot to Telegram, I can see it's also not working.

My particular issue is using connector.Bots.SetConversationDataAsync(ReceivedMessage.To.Id, ReceivedMessage.ConversationId, botData)

Calling this I get:
Microsoft.Rest.HttpOperationException: You have to specificy userId or conversationId

In the debugger I can see that both ReceivedMessage.To.Id and ReceivedMessage.ConversationId are not null, they both have reasonable values. The ReceivedMessage object is the one the user has sent me, so is populated correctly.

Creating a reply message and setting the data on that does work fine, however it's not a good workaround since the reason I wanted to use this API is because I can have concurrency problems and for Concurrency it's recommended to use ConnectorClient in the docs.

**Comment by jakobpn** [comment]
@duscott Try using RecievedMessage.From.Id instead of RecievedMessage.To.Id.

**Comment by tomlm** [comment]
No that’s not right, you need to use the userid of the user you are wanting to store it with

This is a bug on our side, I am about to check in a fix for it

**Comment by tomlm** [comment]
OK, I have the resolution for this and it is not a bug on our side but a documentation bug. (I will update the code to give better error message)

You will get this behavior if you are trying to use a BotData with a null etag.

The correct pattern should always be:
                // get the BotDAta
                Var botData = Client.Bots.GetXXXData(…);
                // change the botDAta
botData.Data = {…};
// Submite the new botData
client.Bots.SetXXXData(botData);

If you do this you always get concurrent behavior, because the botData that is returned will have the ETag and round-trip it.

What you can’t do is
                Clients.Bots.SetXXXData(new BotData() { Data = {….}} );
Because the ETag will be null.

**Comment by ahmettaha** [comment]
Hello,

I tried your sample, it still doesnt work for me. What am I missing? I still get this error:

 You have to specificy valid userId or conversationId

    string botAppId = CloudConfigurationManager.GetSetting("BotAppId");

            DirectLineClient client = new DirectLineClient(CloudConfigurationManager.GetSetting("BotDirectLineSecret"));
            Conversation conversation = await client.Conversations.NewConversationAsync();

            BotClientModel model = new BotClientModel();
            model.ConversationId = conversation.ConversationId;
            model.ETag = conversation.ETag;
            model.Token = conversation.Token;

            ConnectorClient connectorClient = new ConnectorClient(botAppId, CloudConfigurationManager.GetSetting("BotSecret"));

            BotData botData = await connectorClient.Bots.GetConversationDataAsync(botAppId, model.ConversationId);
            botData.SetProperty("MemberId", this.CurrentMember.Id);

            await connectorClient.Bots.SetConversationDataAsync(botAppId, model.ConversationId, botData);

**Comment by duscott** [comment]
There's a mismatch between the emulator and what happens in Azure. If you deploy to Azure, you don't get that message, it only happens when testing locally via the emulator. This still happens for me for version 1.0.0.64 of the emulator.

My hack at the moment is to store the data on the message when I'm in Debug and working locally, and then switching to using the REST services in Release. This isn't a nice solution and still makes it hard to test, but I believe the team are aware of the issue and I imagine the next update will fix it.

**Comment by ahmettaha** [comment]
I'm not using the emulator though. This code is executed by a regular http request. I assume this code should work even on a console app. am I wrong?

**Comment by ahmettaha** [comment]
moved to #241 since this issue is closed.
