### ISSUE TITLE
Redirect following Slack bot installation

### ISSUE THREAD

**Issue by hughcameron** [Microsoft/BotBuilder#1316]
Hey there, we've received some feedback from Slack regarding our submission to the Slack App Directory:
"After the app is installed, it redirects back to a user's Slack team. It's best to redirect to a page on your site indicating success instead."
Is it possible to change the redirect URL using settings within the bot framework?

**Comment by dandriscoll** [comment]
Hi @hughcameron, you can configure this URL in the "Landing Page URL" field in the Slack configuration page on your bot's dashboard.

1. Open dev.botframework.com
2. Open your bot's dashboard
3. Click "Edit" on the Slack channel
4. Add your landing page URL into the field

**Comment by hughcameron** [comment]
Thanks for your help @dandriscoll - that's working!

**Comment by stanleycyang** [comment]
Submitting my slack app with this fix! Hope it works!

**Comment by eliotwinder** [comment]
@dandriscoll I'm still having this problem with my bot - I've updated the Landing Page URL, but i am being redirected to https://bots.botframework.com/ Any ideas?

**Comment by shahen94** [comment]
i'm still having this issue, adding landing page url doesn't help

**Comment by craigjensen** [comment]
Please add your botid and we'll investigate

**Comment by EricDahlvang** [comment]
This issue not currently repeatable, and has been open for thirty days or longer without response from the last poster.

**Comment by bilby91** [comment]
I'm having the same problem, the redirect url is not working. botid is "suttna"

**Comment by haacked** [comment]
Same I'm also having this problem. I documented my repro steps here: https://github.com/microsoft/botframework-sdk/issues/5025

The main issue is the redirect does not redirect to the Landing Page Url if I click the "Add to Slack" button in the Slack Portal. It does work if I use the "Add to Slack" button generated by the Azure Bot Service for the Slack Channel. It probably works because it contains a `redirect_uri` query string parameter.

I would expect that the former should work. Otherwise things break if someone installs the app from the Slack portal.

**Comment by Morhpeuss** [comment]
Hello, I have the same problem. I added a Landing Page Url in Slack Channel Registration.  

I expected that after the application installation from the Slack portal I will be redirected to my Landing Page with the authorization code, but I was redirected to https://dev.botframework.com/. 

This is a big problem If you need information from the user during app registration. 

I understand that the first Url in Redirect Urls has to be https://slack.botframework.com because the Azure Bot Service needs to store the tokens etc. 

I am developing a bot but I need some information from a user after/before app installation (teamid, team name, etc.). How could I solve it with the bot framework?
