### ISSUE TITLE
Not seeing notifications in mobile messenger 

### ISSUE THREAD

**Issue by piotrwitkowski** [Microsoft/BotBuilder#1339]
Not sure this is directly related to the framework, but I can't trigger mobile notification from my bot (for FB messenger). Messages are being delivered ok, the notification is present if I run messenger in a web browser, but not in the mobile - no toast or sound. 

I tried ReplyToActivityAsync as well as CreateDirectConversationAsync +  SendToConversationAsync.
Also tried to push notification_type = "REGULAR" to the channel data.

Notification settings in the messenger are all on, but there's no toast notification. Tried that on WindowsPhone and iPhone for different user accounts. Is anyone seeing similar behaviour? Is there something specific I should take care of?

**Comment by piotrwitkowski** [comment]
Hm... I got the notifications back if I return responses to the user within the POST call (I was using ConfigureAwait(false); on that call to return immediately as the response generation happens on a separate service (service fabric). So the other question is - how do I initiate bot->user conversation that triggers notification on mobile device for FB messenger?

**Comment by piotrwitkowski** [comment]
BTW, notifications in Skype appear regardless of using ConfigureAwait(false); or not.

**Comment by dandriscoll** [comment]
Hi @piotrwitkowski, the use of .ConfigureAwait(false) is unrelated to notifications. ConfigureAwait(false) is necessary to prevent deadlocks in some situations. You can find more information here: http://stackoverflow.com/a/13494570 or by searching for ConfigureAwait.

Facebook says the "notification_type" field defaults to REGULAR. I'm not sure why the notification isn't showing up. Have you asked Facebook? https://developers.facebook.com/docs/messenger-platform/send-api-reference

**Comment by piotrwitkowski** [comment]
Hi @dandriscoll, It looks like it is indirectly related to the .ConfigureAwait and it is not a facebook issue. Let me clarify. In the first case, I receive POST request in my bot controller, pass it further to my backend and wait for the backend to send to a user a few messages. Then the controller returns from the POST method. In this case, notifications work OK. In the second case, I receive POST request, pass it further to my backend using FireAndForget approach (.ConfigureAwait(false)) and return immediately from the controller. The back end then slowly send some messages to the user, they arrive OK, but do not trigger notifications.

**Comment by awyl** [comment]
I have a similar issue.  SendToConversationAsync do not trigger notification on mobile clients, but the message delivered just fine.

Not sure if it is relevant, but In detail I construct an Activity, Activity.CreateReply, then replace the Recipient.Id and Conversation.Id I previously stored, and then send with SendToConversationAsync with .ConfigureAwait(false).

**Comment by piotrwitkowski** [comment]
I got the notifications working by getting rid of the FireAndForget approach (.ConfigureAwait(false)). Not ideal, but will do for now.

**Comment by awyl** [comment]
Thanks.

Tried to remove .ConfigureAwait(false) for the entire call stack.
Tried setting notification_type to REGULAR or SLIENT_PUSH.

And tried combination of both. Still no notification. =/

**Comment by piotrwitkowski** [comment]
I switched to using CreateReply exclusively, even for communication initiated by the bot. Not sure if that is a factor.

**Comment by tomlm** [comment]
Closing due to age, reopen if you are still having issues.

**Comment by oflahero** [comment]
I would like to see this reopened if possible, as I am currently encountering this issue. I'm sending messages via a dialog - I've investigated using both

    ConnectorClient.Conversations.ReplyToActivityAsync(Actvity); and 
    IDialogContext.PostAsync(IMessageActivity);

Neither triggers notifications in Facebook Messenger (on Android) - whereas new messages from real people have always triggered and continue to trigger new message notifications.

Since messages are channel-agnostic, I have to assume that the answer lies in the way the framework 'translates' an IMessageActivity onto the Facebook Messenger channel somewhere. One shouldn't have to add channel-specific data to a message in order to trigger a notification - notifications should be controlled only by user settings on the client side. Or do I have it wrong?

**Comment by oflahero** [comment]
Update: the following worked for me:

            message.ChannelData = JObject.FromObject(new
            {
                notification_type = "REGULAR"
            });

The key point is that you need to specify a ChannelData in order to get a notification on the Facebook channel.

I would have expected that it would be the other way around - that a notification would be the default for messages on the Messenger channel, and the framework should be doing this for us. It should be up to the user to replace this if required with a SILENT_PUSH or NO_PUSH instead.

**Comment by kevinport** [comment]
Any news here? I think the framework should do this for us... the channel specific BotConnector should translate it for us..

**Comment by oflahero** [comment]
According to https://github.com/Microsoft/BotBuilder/issues/3714, 'SILENT_PUSH" is the default.
