### ISSUE TITLE
[Feature Request] Button enbaled/disabled state for Card Buttons

### ISSUE THREAD

**Issue by rohanbadlani** [Microsoft/BotBuilder#1369]
Hi,

I have been extensively using cards and I noticed that once the conversation is finished, the buttons on the card still remain active. There should be a way for the developer using Bot Framework to disable/enable buttons through code or set an active time on the buttons for a particular Card. 

My main issue occurs because I am using Imback with buttons, and once my user moves to another state, and still goes back to the conv and clicks on the previous card, I receive an imback message. It would have been great if I could disable the buttons on the prev card so as to avoid this.

Regards,
Rohan

**Comment by LarsLiden** [comment]
This is a limitation of the channels - none of which currently support an active / inactive buttons states.  When they do, we will add that support to bot framework.   Some channels have recently added the ability to edit posts (i.e. Telegram & Facebook).  This allows you (among other things) to delete buttons. Work to support this is on our road map.

In the mean time, a number of channels support keyboards (i.e. Telegram, Kik, Facebook) which are buttons that disappear after they have been pressed.  On those channels you can use a keyboard instead of a button.

**Comment by dillonong** [comment]
Hi Lars, I know this is an old post but do you know if this has been implemented in your road map?

The following statement:
"This is a limitation of the channels - none of which currently support an active / inactive buttons states. When they do, we will add that support to bot framework. Some channels have recently added the ability to edit posts (i.e. Telegram & Facebook). This allows you (among other things) to delete buttons. **Work to support this is on our road map**."
