### ISSUE TITLE
session.send(...) throws silent error when receiving not an array or string

### ISSUE THREAD

**Issue by mvakoc** [Microsoft/BotBuilder#1404]
when the user calls `session.send(0)` it will throw an error saying `cannot read "conversation" of undefined` this happens with every data type that is not a string or an integer. I propose, that when the user calls `session.send()` the input parameter is casted to a string if it's not an array. This way we could prevent this non-descriptive error. The user doesn't expect that `session.send(0)` doesn't work, since other output options like `console.log` work without a flaw.

**Comment by palmerabollo** [comment]
I'm not sure about whether this is a good idea. The `send` function is currently defined as `send(message: string | string[] | IMessage | IIsMessage, ...)`. Changing the signature to `send(message: any, ...)` would make lifes of typescript developers a bit more painful.

**Comment by chrimc62** [comment]
@Stevenic or @maxpert can you comment or close as appropriate?

**Comment by Stevenic** [comment]
I agree with @palmerabollo to a degree. This isn't `console.log()` and opening it up so that you can technically pass anything makes it difficult to enforce what you SHOULD pass. I'm closing this issue for now but let me noodle on it. Feel free to way in with other examples of where this is more the nom than the exception. In particular I want to look at what other libraries like Express do. Thanks you for raising the issue.
