### ISSUE TITLE
[nodejs] Handling Events from Emulator / Emulator support debuging

### ISSUE THREAD

**Issue by khrome83** [Microsoft/BotBuilder#143]
I was trying to act on events to start building out how the bot should handler certain situations. When applying the following code to listen to all events, this was my discovery between the emulator and what the framework can support (node.js).

```javascript

// On Error
bot.on('error', function(message) {
    console.log('[error] called');
});

// On Reply
bot.on('reply', function(message) {
    console.log('[reply] called');
});

// On Send
bot.on('send', function(message) {
    console.log('[send] called');
});

// On Quite
bot.on('quit', function(message) {
    console.log('[quit] called');
});

// On Message
bot.on('message', function(message) {
    console.log('[message] called');
});

// On DeleteUserData
bot.on('DeleteUserData', function(message) {
    console.log('[DeleteUserData] called');
});

// On BotAddedToConversation
bot.on('BotAddedToConversation', function(message) {
    console.log('[BotAddedToConversation] called');
});

// On BotRemovedFromConversation
bot.on('BotRemovedFromConversation', function(message) {
    console.log('[BotRemovedFromConversation] called');
});

// On UserAddedToConversation
bot.on('UserAddedToConversation', function(message) {
    console.log('[UserAddedToConversation] called');
});

// On UserRemovedFromConversation
bot.on('UserRemovedFromConversation', function(message) {
    console.log('[UserRemovedFromConversation] called');
});

// On EndOfConversation
bot.on('EndOfConversation', function(message) {
    console.log('[EndOfConversation] called');
});
```

Using the emulator, there are a few events that do not seem to have a "event" type in the `botConnectorBot` or it is unknown how to trigger those events even though they are available. 

**From Emulator**
1. Ping - Clicking the ping event does not seem to trigger any event that can be listened too through `.on()`. 

Using the framework, there are a few events that are unclear how to test and trigger. These are available as strings for the `botConnectorBot.on()` method.

**From Framework**
1. `send` - Does not seem to trigger when using a prompt. All entries are instead flagged as `reply` event.
2. `message` - No correspondence seems to trigger the `message` event.
3. `error` - No way in emulator to force a error response?

**Configuration**
I was also not able to do anything to see these messages that were configured. It was not clear how to test these within the emulator.

```javascript
bot.configure({
    userWelcomeMessage: "Hello... Welcome to the group.",
    groupWelcomeMessage: "Hello Group!",
    goodbyeMessage: "Goodbye..."
});
```

**Comment by Stevenic** [comment]
So let me try to break this apart:
* __ping__ from the emulator isn't supported by the BotConnectorBot because it will never actually receive that in production. Ping is an internal thing used by the team to ensure everything is making through. You could possibly argue this shouldn't be in the emulator.
* __send__ from the BotConnectorBot would only ever get fired if the bot started the conversation via a call to BotConnectorBot and even then it would only ever be called once for the initial message. You can make an argument that we should probably combine __reply__ with __send_ since the differences are subtle.
* __error__ is actually an exception triggered in your bots code so to test it throw an exception. And please let me know the cases where you don't get the error. :)
* __configuration__ I'm not sure why these aren't being returned to the emulator. I'll try to dig into that.

**Comment by khrome83** [comment]
@Stevenic thank you for the response. Do you know if `message` event should be triggered during any transaction within the emulator?

**Comment by Stevenic** [comment]
Sorry... Yes that should fire. I'll take a look as to why its not.

**Comment by Stevenic** [comment]
I just fixed a bug preventing the configured messages from being returned nice catch.

**Comment by Stevenic** [comment]
I've tested that everything the emulator supports we can catch.

**Comment by xialisun** [comment]
I am using version 3.8.2, 'endOfConversation' event seems not trigger
