### ISSUE TITLE
Uniqueness of context.userId

### ISSUE THREAD

**Issue by palashjhabak** [Microsoft/BotBuilder#1433]
Hi,

As per my understanding the user id which comes from the channel is used in context.userId. And the same userId is used as key in MemoryBotStorage class to store userdata in userStore object. Since userId cannot be unique across channels for a bot, how is it used as the key?

PS: Excuse me if my understanding is wrong.

Thanks,
Palash

**Comment by palmerabollo** [comment]
You're right but you shouldn't use the `MemoryBotStorage` (your bots should be stateless).

If you use the `ChatConnector`, that is already an implementation of the `IBotStorage` interface (bad design IMHO) you don't have that problem because it uses a more advanced algorithm that takes the channel into account (see the [code](https://github.com/Microsoft/BotBuilder/blob/master/Node/core/src/bots/ChatConnector.ts#L329), specifically how `getStoragePath` works)

**Comment by palashjhabak** [comment]
but UniversalBot class is using MemoryBotStorage. How does that work?

**Comment by palmerabollo** [comment]
It doesn't depend on the UniversalBot class. It depends on the [`storage` value](https://github.com/Microsoft/BotBuilder/blob/9a1d8e78b9fe1d81bd9b481d2743006a6032f7b9/Node/core/src/bots/UniversalBot.ts#L55) you pass to the [UniversalBot constructor](https://github.com/Microsoft/BotBuilder/blob/9a1d8e78b9fe1d81bd9b481d2743006a6032f7b9/Node/core/src/bots/UniversalBot.ts#L98).

If you don't use the settings (I don't because implementing your own `IBotStorage` is not an easy task), the `UniversalBot` will try to check [if a `IConnector` that looks like a IBotStorage is present](https://github.com/Microsoft/BotBuilder/blob/9a1d8e78b9fe1d81bd9b481d2743006a6032f7b9/Node/core/src/bots/UniversalBot.ts#L140). The ChatConnector is a IBotStorage so, if you use it, you'll use it instead of the default `MemoryBotStorage`.

Last, if you bind the `IConnector` to the `UniversalBot` calling `UniversalBot#connector(...)` you have to use the latest 3.3.0 BotBuilder version. Previous 3.2.x versions were affected by a bug (see https://github.com/Microsoft/BotBuilder/pull/1383) and don't support late binding.

Please show me some code (how you create the UniversalBot, etc) if you need more help.

**Comment by tomlm** [comment]
And regarding the question about the keys, we actually use the channel + bot + userId as our key
