### ISSUE TITLE
Is BotData.Data serialized by the Bot Framework?

### ISSUE THREAD

**Issue by jakobpn** [Microsoft/BotBuilder#147]
Does the Bot Framework serialize/deserialize the Data property of the BotData object or does the data need to be serialized by the bot before if is handed off to SetUserData?

**Comment by willportnoy** [comment]
It looks like you are using the connector APIs versus the builder sdk.

It looks like the connector client will serialize the BotData object as a json object.

Since the Data property is an opaque object, in the builder sdk, we happen to use a JObject as this opaque object.  Many things will serialize properly, though it's possible there are some types that will require additional preparation to be serialized as json.

**Comment by jakobpn** [comment]
Yes. I am using the Connector api. Let me know if you recommend that I switch to the builder sdk.

And yes, I also see that BotData is being serialized and that GetUserData is returning a JObject that I can then deserialize.
