### ISSUE TITLE
How does State API save data?

### ISSUE THREAD

**Issue by JamesLouieTallan** [Microsoft/BotBuilder#1501]
In reference to the Bot Framework's [State API](https://docs.botframework.com/en-us/csharp/builder/sdkreference/stateapi.html ), how does Microsoft save the state information within the state service.  Currently we are building an app that may contain sensitive data, and we were determining the security of this feature.  

1. Is the state being stored in memory, or in some database?  
2. How long does this data persist in the state service?  
3. Is this state information stored within its own container, or does it share it with other bots?

Thank you!

**Comment by willportnoy** [comment]
https://docs.botframework.com/en-us/technical-faq/#where-is-conversation-state-stored has some information - happy to answer further questions.

**Comment by willportnoy** [comment]
Because the state service is persistent (i.e. for a long time), it obviously does get stored on a disk somewhere.  You're free to implement that state service APIs differently (e.g. for saving the dialog stack) to persist that state elsewhere (e.g. some database of your own, even running in Azure).  You might consider additional encryption, etc, based on your requirements around PII.

**Comment by MCKRUZ** [comment]
Is there some way we can purge that information from the database at Microsoft?

**Comment by willportnoy** [comment]
Yes, the state service has "delete" methods for the various bot data bags: https://docs.botframework.com/en-us/csharp/builder/sdkreference/stateapi.html

**Comment by willportnoy** [comment]
I'm going to close this issue, but feel free to open a new issue for further discussion.
