### ISSUE TITLE
IAddress must be interface extend by serviceUrl property.

### ISSUE THREAD

**Issue by cejixo3** [Microsoft/BotBuilder#1506]
Need to extend IAddress interface by non required property.
For exmaple.
    /**
     * Specify service url
     */
    serviceUrl?:string;
https://github.com/Microsoft/BotBuilder/blob/master/Node/core/lib/botbuilder.d.ts#L117

**Comment by willportnoy** [comment]
Is this related to https://github.com/Microsoft/BotBuilder/issues/1509 ?

**Comment by cejixo3** [comment]
yep.
This also related to useAuth

**Comment by Stevenic** [comment]
Why do you need that on the interface? You're not supposed to be building address objects by hand.

**Comment by cejixo3** [comment]
I need to build this object because I use event notifaction sustem with subscribe/unsubscribe actions and a dont want to keep Session in-memory. 
I want to init dialog from Bot side and dialog initiation await for IAdress type.

**Comment by Stevenic** [comment]
You should just save a valid `address` object as a serialized string using `JSON.stringify()` and then simply reload it using `JSON.parse()`. I'd avoid trying to muck with the internal fields of the address object as they can technically change on a per/connector basis.  The address object is intended to be an opaque blob that connectors can add anything they want to which is why there are properties missing from `IAddress`. This is by design.

**Comment by cejixo3** [comment]
I got you point of view. I'll save It as json. Thank's for answer

**Comment by Stevenic** [comment]
No problem... I tried to document with IAddress the well known fields of the address object but other fields are possible.
