### ISSUE TITLE
Conversation Begin and End

### ISSUE THREAD

**Issue by JoeMayo** [Microsoft/BotBuilder#1515]
A few questions on conversation begin and end:

1. What causes a conversation to end? 
2. Does a bot receive an indication that the conversation ended or do you just detect that when the bot receives a new conversation ID?
3. If a user starts a new conversation with a bot, does a previous conversation end? e.g. chat with bot, join group conversation, leave group conversation, chat with bot again (is new or previous conversation)?
4. Is it correct to assume that a conversation begins when either: 1) This is the first conversation a user has with a bot, or 2) A previous conversation has ended?, or 3) A user joins a new group conversation?

Thanks

p.s. I would ask in SO, but run the risk of this type of question being voted down and closed before answer. :)

**Comment by jameslew** [comment]
Hey Joe,

ConversationId lifetime is deliberately ambiguous.  For the channels we currently have, they're basically durable so long as the user maintains the relationship with the Bot (ie a conversation in SMS lives for the life of the bot/user relationship unless the Bot creates a new one explicitly.)

We do foresee having a channel desire to be able to end a conversation; should we get to that point we'll add an ActivityType to let the bot know the conversation has ended.

For the current channels, the old conversation id still exists and would be responded to.  I'm less sure of what happens if for example you delete the channel in a Slack group that the conversation id was associated with - possibly a not found error.

**Comment by JoeMayo** [comment]
Thanks James - good to know.
