### ISSUE TITLE
Use multiple LUIS apps (different languages) with LuisRecognizer

### ISSUE THREAD

**Issue by palmerabollo** [Microsoft/BotBuilder#1532]
To overcome the limit in the number of intents that a single LUIS app can handle (20) I'd need to create a LuisRecognizer that uses more than one LUIS app per language.

I can't figure out how to do it because [the locale is used as the key](https://github.com/Microsoft/BotBuilder/blob/c35f421389671c1f786d4c0f5b6ab6a41c715321/Node/core/src/dialogs/LuisRecognizer.ts#L39) in `ILuisModelMap`.

This is what I'd like to do, but it won't work since you can't have a duplicated key in a map: 

```
let models = {
    'en-us': 'https://luis-app-english-1'
    'en-us': 'https://luis-app-english-2' // same key, this won't work
    'es-es': 'https://luis-app-spanish-1'
}
new BotBuilder.LuisRecognizer(modelMap)
```

What's the best way to do this?

**Comment by kbrimble** [comment]
@palmerabollo the option we took was rather than having a bot that can recognise more than one LUIS app, we have a hierarchy of LUIS models and dialogs that match. That means we still have a 1-1 LUIS model to dialog mapping.

We have a `RootDialog` which uses a `RootModel`. That model only has intents for the next level of LUIS models. In essence, it does a first classification of an utterance and tells the `RootDialog` which child dialog to forward to. Forwarding an utterance to another LUIS dialog will then call the more specific LUIS model.

I'm happy to discuss how we achieved this if you want to go down that route.

**Comment by Stevenic** [comment]
So @kbrimble is correct. You need to actually use a separate `LuisRecognizer` per model. If you're using the `IntentDialog` you can pass in an array of your models.  In 3.5 there will be a new [IntentRecognizerSet](https://github.com/Microsoft/BotBuilder/blob/master/Node/core/src/dialogs/IntentRecognizerSet.ts) which will let you essentially bundle together a set of recognizers which you can call as if they were a single model.  If you're trying to manually use multiple `LuisRecognizers` today you could copy that code and do something similar.  We're also adding a new [RegExpRecognizer](https://github.com/Microsoft/BotBuilder/blob/master/Node/core/src/dialogs/RegExpRecognizer.ts) class in 3.5 that will let you mix in per language regular expressions into your set.

**Comment by jdnichollsc** [comment]
Hi guys, any example to switching between LUIS apps at runtime to support multi-language?
I'm creating a template with Express here https://github.com/proyecto26/Bot-Framework

Thanks in advance
