### ISSUE TITLE
Bot Authentication with Google OAuth causing Redirect_uri mismatch

### ISSUE THREAD

**Issue by sivakishorejvv** [Microsoft/BotBuilder#1536]
I am trying to authenticate Bot using Google OAuth and taken existing Facebook Auth Sample as a base. I changed the required Oauth Urls and implementation but while requesting authorization code it is not coming back to OAuthcallbackController's OAuthCallback method and its giving like redirect_uri is not matching, Can anyone help me on this.

Can't we send multiple parameters to redirect_uri while doing google OAuth?

**Comment by matvelloso** [comment]
When you register your application at google you set the redirect URI. That has to match whatever your code uses when it calls it. Your code is specifically directing the redirect URL to land into that callback controller in the web API. So that URL has to be the URL you use in your google application. And yes, generally speaking OAuth providers let you use multiple redirect URI in their configuration, then the app asks for which one it wants to use in that particular moment.
