### ISSUE TITLE
[c# and node] Could I get activity class in NodeJs.

### ISSUE THREAD

**Issue by zongbingwang** [Microsoft/BotBuilder#1544]
We use nodejs to develop service, and use c# to develp micro service, so that, the service will call micro service. And the problem is that, I need to get activity in nodejs then transfer to c#, but I can't get that request like activity in c#. It will take some time to do convert Session to Activity and reconvert Activity to Session. Or, I rewrite the NodeJs code like c# code, but It also need some effort. So, I want to know that, do you have some general method to solve it. Thank you very much.

**Comment by Stevenic** [comment]
Can you clarify what it is you're trying to do? Are you trying to forward a message from node to c#?  Some have used Direct Line to do that.

**Comment by zongbingwang** [comment]
ok. Got it, thank you very much.

**Comment by zongbingwang** [comment]
I am trying to forward activicy from node to c#,  c# deal with this request, then forward activity from c# to node, then node send response to emulator.

**Comment by Stevenic** [comment]
Is the C# code using Bot Builder as well?  Because if both compute nodes are using Bot Builder to process the same conversation that's probably not going to work. The reason for that is that Bot Builder needs to store tracking information about the conversation. Bot versions of the SDK by default use the same Bot State service to store this tracking info and they would end up clobbering each others tracking information.

**Comment by chrimc62** [comment]
Closing due to lack of response.  If you still have an issue please let us know.
