### ISSUE TITLE
How to call multi dialogs from LUISDialog i.e. calling AzureAuthDialog as a child

### ISSUE THREAD

**Issue by sameerinfodb** [Microsoft/BotBuilder#1573]
we are trying to connect Microsoft Graph therefore we need to authenticate to access Office 365 . Therefore we are using Authbot package.  

We have a LuisIntent method to read the excel file in Office 365, so we are trying to do this from LUISDialog

 await context.Forward(new AzureAuthDialog(AuthSettings.Scopes), this.ResumeAfterAuth, message, CancellationToken.None); 

but we are getting Stack is empty error. Therefore we tried below code as well

 var authDialog = new AzureAuthDialog(AuthSettings.Scopes);
 var loop = authDialog.Loop();
 context.Call(loop, async (ctx, arg) => ctx.Wait(MessageReceived));

when we do this , LuisIntent method is not invoking the AzureAuthDialog and subsequent call to LuisIntent Method is invoking the AzureAuthDialog. How do we invoke AzureAuthDialog in very first call.

**Comment by willportnoy** [comment]
If you want to have authentication occur before calls to LUIS, it might make more sense to have a root dialog that calls the authentication dialog if necessary otherwise it forwards the message to a child LUIS dialog.

**Comment by sameerinfodb** [comment]
@willportnoy 
Basically , bot conservation sequence is as below.
General conversion like introduction , feature enquiry etc., does not need the authentication .
Office 365 specific conversion is initiated by user with bot like requesting tolist worksheet in workbook then we need a authdialog to shoot up.  Any code snippet or example will help.

**Comment by duckwaffle** [comment]
Just out of curiosity, when forwarding to the AzureAuthDialog are you using a LuisIntent method with the following signature?

`[LuisIntent("Authenticate")]
public async Task Authenticate(IDialogContext context, IAwaitable<IMessageActivity> activity, LuisResult luisResult)`

Because that is how we have done it, and it works perfectly.

**Comment by duckwaffle** [comment]
Further to my comment above, luisintent methods can either be

`public async Task ShowMenu(IDialogContext context, LuisResult luisResult)`

or

`public async Task Authenticate(IDialogContext context, IAwaitable<IMessageActivity> activity, LuisResult luisResult)`

It's not documented very well, but the second type is much easier to work with because you always have access to the original MessageActivity, which is required to create the ResumptionCookie in AuthBot.

**Comment by sameerinfodb** [comment]
To be precise , this is what we are doing 

>  [LuisIntent("GenerateSummaryChart")]
>   public async Task IReport(IDialogContext context,LuisResult result)
>   {       
>             //Assume this is a query for OneDrive so let's get an access token
>             if (string.IsNullOrEmpty(await context.GetAccessToken(AuthSettings.Scopes)))
>             {
>                 var authDialog = new AzureAuthDialog(AuthSettings.Scopes);
> 
>                 var loop = authDialog.Loop();
> 
>                 context.Call(loop, async (ctx, arg) => ctx.Wait(MessageReceived));
>            
>             }
> ....
> }
@duckwaffle , what is your working solution. do you have any github repo to check the working code.

**Comment by sameerinfodb** [comment]
To be precise , this is what we are doing 

>  [LuisIntent("GenerateSummaryChart")]
>   public async Task IReport(IDialogContext context,LuisResult result)
>   {       
>             //Assume this is a query for OneDrive so let's get an access token
>             if (string.IsNullOrEmpty(await context.GetAccessToken(AuthSettings.Scopes)))
>             {
>                 var authDialog = new AzureAuthDialog(AuthSettings.Scopes);
> 
>                 var loop = authDialog.Loop();
> 
>                 context.Call(loop, async (ctx, arg) => ctx.Wait(MessageReceived));
>            
>             }
> ....
> }
@duckwaffle , what is your working solution. do you have any github repo to check the working code.

**Comment by duckwaffle** [comment]
@sameerinfodb You can change the signature of your LuisIntent method to include the original IMessageActivity, and then use the azureauthdialog like so:

`[LuisIntent("Authenticate")]
public async Task Authenticate(IDialogContext context, IAwaitable<IMessageActivity> activity, LuisResult luisResult)
{
var message = await activity;
if (string.IsNullOrWhiteSpace(await context.GetAccessToken(AuthSettings.Scopes)))
{
await context.Forward(new MultiChannelAuthDialog(AuthSettings.Scopes), ResumeAfterAuth, message, CancellationToken.None);
}
else
await context.PostAsync("You are already logged in.");
context.Wait(MessageReceived);
}
}`

Obviously, this example is just for a standalone "Authenticate" LuisIntent, I find it easier to handle user authentication in its own intent (getting the user to type "Sign in" or "Login" or something like that), instead of trying to make logging part of the process of doing an authenticated action, but thats just our design decision. The project we are using this in is closed source, so I cant link you to a repo unfortunately, but happy to help if you're still stuck.

**Comment by sameerinfodb** [comment]
Thank you @duckwaffle , will try this approach and will update the comment.

**Comment by sameerinfodb** [comment]
This suggestion works for me , thanks you#duckwaffle
