### ISSUE TITLE
Facebook is missing as a trusted hostname

### ISSUE THREAD

**Issue by vossccp** [Microsoft/BotBuilder#1597]
Beginning wit 3.3.1, the connector is checking against a list of trusted hostnames. As of 3.3.1 this only includes call to state.botframework.com. Calls to facebook.botframework.com get rejected.

Source MicrosoftAppCredentials#TrustedUri()

**Comment by tomlm** [comment]
The deal with the trusted service urls is that it is not an exhaustive list.  We regularly add new channels and endpoints for channels.  Whenever an incoming activity comes in and is a trusted service because it is signed with the appropriate Jwt token, we add the url to our trusted list, with a 24 hour expiration.

As long as you are getting signed data from that url you should be good.  You will only end up trouble if:
 you are proactively sending a message to a channel 
AND 
it has not received any signed activities in the last 24 hours.

**Comment by vossccp** [comment]
I believe, the issue we encounter is related to the way, we deal with messages from the Bot Framework: When we receive a message, we route the message into a queue; we have different endpoints (each of them representing specialised bots) which then process the message.

Adding the URLs when the message arrives, will not work in such distributed scenarios because the instances dont share the same memory space.

I think, the framework should generally be able to support this, so I suggest reconsidering the setup
