### ISSUE TITLE
Can't change default description translate

### ISSUE THREAD

**Issue by AndrewBryukhov** [Microsoft/BotBuilder#1605]
For example i have i dialog not in english, and i see "Options:" message

**Comment by AndrewBryukhov** [comment]
I was translate messages by this:
```
var bot = new builder.UniversalBot(connector, {
    localizerSettings: {
        botLocalePath: "./locale",
        defaultLocale: "ru"
    }
});
```

But see "options:" in telegram. May be problem now is outside botbuilder.

**Comment by chrimc62** [comment]
@AndrewBryukhov are you still having an issue?

**Comment by Stevenic** [comment]
You need to make sure you specify a Title for the card you're sending or if you're calling `Prompts.choice()` you have to pass a prompt.

**Comment by dandriscoll** [comment]
Hi @AndrewBryukhov, does adding a Title resolve this issue for you?

**Comment by AndrewBryukhov** [comment]
no

**Comment by dandriscoll** [comment]
@Stevenic, is there an easy way to see what the bot is generating on the wire?

**Comment by maxpert** [comment]
One way could be to use [Fiddler](https://www.telerik.com/download/fiddler) and point to Node.JS process and see the traffic.

**Comment by Stevenic** [comment]
Adding eric to investigate.

**Comment by nwhitmont** [comment]
Hi @AndrewBryukhov - Are you still having this issue in [BotBuilder v3.7.0](https://www.npmjs.com/package/botbuilder)?

As described in the interface `IDefaultLocalizerSettings` the [`botLocalePath`](https://github.com/Microsoft/BotBuilder/blob/d51e893/Node/core/src/botbuilder.d.ts#L316) is defined as `/** The path to the parent of the bot's locale directory  */` - Did you try setting this to the parent instead of the `.locale` folder itself? Also, this parameter is optional, try removing it and let the framework find the locale folder in its default location.
