### ISSUE TITLE
Integrating a bot into an existing .net application

### ISSUE THREAD

**Issue by samskhan** [Microsoft/BotBuilder#1665]
Hello guys, i have been working with the bot framework for a few weeks now and have made a stand alone example on how we can use the bot in our current .net application. Now i am trying to integrate it into our current app, but it seems i am having some issues, since our app requires us to authenticate in order to gain access to the website. I am trying to figure out how i can host the bot and the application side by side so i can access our current app's methods and functions using the bot. Has anyone here done something like this or anyone have any insight on what's a good way of doing that?

**Comment by chrimc62** [comment]
@msft-shahins can you help with this?

**Comment by dandriscoll** [comment]
Hi @samskhan, our Direct Line API is designed to allow you to easily embed your bot within an existing mobile application, a desktop application, or a web page. Since you're using .Net, you can use our Direct Line client directly from nuget: https://www.nuget.org/packages/Microsoft.Bot.Connector.DirectLine

Direct Line has a key/token mechanism so you can secure your bot within a client application.

Let me know if you've got any questions. Thanks!

**Comment by dandriscoll** [comment]
Please at-mention or file a new issue if you'd like to discuss further. Thanks
