### ISSUE TITLE
[NodeJS] ERROR: Too many calls to session.endDialog()

### ISSUE THREAD

**Issue by deubaka** [Microsoft/BotBuilder#167]
I've been refactoring our full `Botkit` code to `botbuilder` this past days and so far it has been and it has been great in taking a major load of the code in managing dialogs (-ues).

I'm currently working with `v0.9.x`, and while its been great, I'd like to ask on why and what plans are ahead on the `ERROR: Too many calls to session.endDialog().`-response I get when an error is thrown within the code.

Reason being, it doesn't give me any meaningful idea on what caused the issue. Are there any tips or commands I'm missing?

Thanks! #

**Comment by chrimc62** [comment]
Glad to hear you are finding it useful.  It is hard to tell without looking at your code, but usually that issue is caused by calling endDialog more times than the number of dialogs you have open.  Dialogs go on a stack and endDialog pops off the most recent dialog.

**Comment by deubaka** [comment]
However, I don't have any explicitly called `session.endDialog` on my code, if there is, its usually at the end of my waterfall. Here's an excerpt of our code,

```javascript
// ... LuisDialog
dialog.on('FooIntent', resolveQuery);

function resolveQuery(session, args) {
    resolveQuery(session.message.text, entity, function (err, dialogRoute, results) {
        if (err || !dialogRoute) {
            session.endDialog(Prompts.OnDefaultInstalls);
        } else {
            session.beginDialog(dialogRoute, results);
        }
    });
}
```

In which case, I have declared the routes as this,
```javascript
bot.add(DialogRoutes.Foo.SpecificFoo, [handleSpecificFoo, respondToSpecificFoo]);
```

```javascript
function handleSpecificFoo(session, args, next) {
    var targetDate = args.date;
    // ... some manipulation code here
    next({
        response: {
            date: targetDate
        }
    });
}

function respondToSpecificFoo(session, results) {
    var targetDate = moment(results.response.date);

    SomeApi.getSpecificFoos(targetDate, function (err, totalFoos) {
        var queryResponse = '';

        if (moment().isSame(targetDate, 'day')) {
            queryResponse = 'You have ' + totalFoos.toLocaleString() + ' foos for today!';
        } else {
            queryResponse = 'You have ' + totalFoos.toLocaleString() + ' foos for ' + moment(targetDate).format('MMMM D, YYYY') + '!';
        }

        session.send(queryResponse);
    });

    session.endDialog();
}
```

From my understanding from the docs, `session.endDialog` its used in `Prompts`, however, I don't use them in this specific use case, and would just call them after an `onDefault` or after a callback (to prevent receiving inputs). Let me know if I misunderstood something. But from the last issue that caused it, `SomeApi.getSpecificFoos` had internally missing a `require`-statement for `fs` which was used internally for loading up a file, however, I didn't get any clue that it was a missing `require`-statement.

**Comment by Stevenic** [comment]
I was going to say... Where I've been seeing that specific error message its been related to an exception being thrown and us being overly aggressive about the way we handle the exception. We end up triggering multiple calls to endDialog(). I just fixed an issues around this in the LUIS dialog but sounds like I have a couple of other cases I need to track down. That's actually why I added the error message because before it wasn't saying anything and I couldn't figure out why the bot wasn't replying. 

So from you're sample code what you're saying is SomeApi.getSpecificFoo() threw an exception which tells me the waterfall is probably over catching like the LUIS dialog. I'll look into it.

There is another issue I see in your code which I'll reply to separately.

**Comment by Stevenic** [comment]
So the other issue I noticed is with your `respondToSpecificFoo()` function. You call session.endDialog() which of itself is fine. It will pop that dialog off the stack and return control to the dialog you came from (think of it as calling close window.) The issue is in your async callback for `SomeApi.getSpecificFoo()` you're then calling `session.send()`. I'm assuming this is working ok but it's a little dangerous.

The reason why its dangerous is that you've already ended your dialog (closed the window) and now you're trying to say stuff in that context. In most cases nothing overly bad is going to happen, especially with `send()` but say you tried to call `beginDialog()` instead, you would totally jackup your callstack. So as a best practice you should avoid doing stuff like this. So how to do this the right way? You should move your 'endDialog()` call into your callback and combine it with the `send()`:

```
function respondToSpecificFoo(session, results) {
    var targetDate = moment(results.response.date);

    SomeApi.getSpecificFoos(targetDate, function (err, totalFoos) {
        var queryResponse = '';

        if (moment().isSame(targetDate, 'day')) {
            queryResponse = 'You have ' + totalFoos.toLocaleString() + ' foos for today!';
        } else {
            queryResponse = 'You have ' + totalFoos.toLocaleString() + ' foos for ' + moment(targetDate).format('MMMM D, YYYY') + '!';
        }

        session.endDialog(queryResponse);
    });
}
```

**Comment by deubaka** [comment]
@Stevenic Thank you for tip. I've changed the code and yes, it does go away so far.

I'll go ahead and make changes to our code accordingly if any, and await for a new release. Thanks! :)
