### ISSUE TITLE
Web Chat message to Skype

### ISSUE THREAD

**Issue by inornos** [Microsoft/BotBuilder#1671]
We have a website which is used by registered users only, We are trying to develop support system use of **web chat** but we didn't find any solution to communicate **web chat** with skype end user and also we want pass unique current user id to web chat message so we can track chat history also.

**Comment by chrimc62** [comment]
@dandriscoll can answer how you do this.

**Comment by dandriscoll** [comment]
Hi @inornos, you can organize your code into one bot (that serves bot Customers and Support Agents), or you can organize your code into two bots (one for Customers, and one for Support Agents).

From there, the Support Agent side must be connected to the Web Chat control. The Web Chat control must be hosted as a JS control or React component, because that's the only way to pass your user's ID into the control. Your bot code should require a valid user ID when accepting requests from the Web Chat channel.

Your bot code for interacting with Customers can be simple -- just communicate directly with the Skype channel. It sounds like it's acceptable to treat all Skype users as Customers, so you don't need to wire through any additional IDs.

Inside the bot, you can manually record messages, or you can use the Bot Logger system to intercept and log messages for you.

**Comment by dandriscoll** [comment]
Please at-mention or file a new issue if you'd like to discuss further.
