### ISSUE TITLE
Question: How does the Bot Connector serialize/deserialize and run code under the hood?

### ISSUE THREAD

**Issue by willemodendaal** [Microsoft/BotBuilder#1696]
Could someone please explain what the Bot Connector does with a dialog under the hood? I'm curious about where my bot code runs. I expected it to run on my Bot's webservice, but I notice that the bot framework emulator can still interact with my bot, even if the website is not running (at least after the dialog has entered "waiting" state and resumes with another message). 

Does my bot code also execute within the connector itself?

Sorry if this is a stupid question, couldn't find documentation that describes exactly what happens under the hood.

**Comment by willportnoy** [comment]
https://docs.botframework.com/en-us/technical-faq/#where-is-conversation-state-stored has some extra information.

We serialize the dialog state so that it can be resumed across waiting for a user's messages.  But it does still require that the web services runs.

Your bot code only executes within your web service.
