### ISSUE TITLE
issue with bot for slack.

### ISSUE THREAD

**Issue by chgc** [Microsoft/BotBuilder#17]
I follow the steps to set up slack channel. and I had bot join the slack channel as well.
However, when i tried to talk to bot. It message me back "Unauthorized".....
I am sure the secret is correct. anyone knows why?
![31_x_31_21-58-36](https://cloud.githubusercontent.com/assets/4550568/14178146/ee68bbb4-f78b-11e5-9f02-a0a9f3f9b63b.png)

**Comment by KapuzenSohn** [comment]
Did you follow all the instructions? It worked yesterday for me.

The only think that didn´t worked was to get a Api Token from the application so that the Bot couldn´t connect to my server.

**Comment by chgc** [comment]
Yes, I followed all the instructions. and done it three times. 
I can't sure which step I did wrong. 
1. create an app in slack. with Redirect Url.
2. add bot User
3. get client id & Secret paste into "MyBot Slack Channel configuration"
4. save

**Comment by KapuzenSohn** [comment]
After you pasted in the Client Id and Client Secret, did you clicked on the button under the input boxes? The button should be named "Autorize" or similar

**Comment by tomlm** [comment]
does it work in the test panel ? 
Try pointing the emulator at your deployed url to validate that it is the right url and right appid/appsecret.
Then make sure that the portal has same url with same appid/appsecret
Also note that the url needs to be HTTPS if you have basic auth turned on (if it is HTTP we don't send the appId/AppSecret because it would be in the clear, which means you need to disable basic auth if you are going to use HTTP)

**Comment by chgc** [comment]
It Works.
the reason cause my problem is I Use http not https. Once I Change to Https://...... 
Everything is working.
Thanks for Help
