### ISSUE TITLE
Using validatedPrompt together with PromptType.choice

### ISSUE THREAD

**Issue by vjrantal** [Microsoft/BotBuilder#1706]
This issue relates to the Node.js botbuilder SDK version 3.4.4.

I am defining a dialog like this:

```
bot.dialog('/destination', builder.DialogAction.validatedPrompt(builder.PromptType.choice, function (response) {
  // Here I'd like to validate the response for the choice - see issue 1. below
}));
```

And using it like this:

```
    session.beginDialog(
      '/destination',
      {
        prompt: 'Choose or send location to set the destination'
      }
      // How to pass choices - see issue 2. below
    );
```

I have two issues that I didn't yet manage to solve:

1. The custom validator function doesn't seem to get called at all when user responds to the choice (works as expected when using PromptType.text)
2. How to pass the choices to the underlying choice prompt

My use case is such that I'd like to give the user the possibility to set destination from a pre-defined set of locations that I'd send as choices via the prompt, but also allow the user to respond with any location outside of the pre-defined choices (and in the custom validator, check that user responded either with one of the choices or with a message containing a location).

**Comment by Stevenic** [comment]
So I just added a new [basics-customChoicePrompt](https://github.com/Microsoft/BotBuilder/tree/master/Node/examples/basics-customChoicePrompt) example that shows how you'd do this.  You can't really use a validated prompt because it requires you successfully chose an option from the set.  The sample shows how to use `Prompts.choice()` with `maxRetries = 0`.

**Comment by chrimc62** [comment]
If this does not work for you, please let us know.
