### ISSUE TITLE
Strategy for catching errors

### ISSUE THREAD

**Issue by cesarvarela** [Microsoft/BotBuilder#1710]
How should I handle random errors through the use of the bot?

All I see is `Oops. Something went wrong and we need to start over.`, but I wonder.. is there a global event for handling these?

thanks!

**Comment by Stevenic** [comment]
That error message is only shown when `Session.error()` is called and the message itself can be customized by you.  Typically this is only called in two situations: 1) we called some external service like LUIS and encountered a problem. 2) your bots code threw an exception that you didn't catch.

You can avoid the second case by simply adding `try{}catch{}` statements to you code.  You can also add `bot.on('error', function (err) {});` to your code and you'll be told anytime an error is detected although you can't prevent the default logic from executing.  

The other thing you should know about `session.error()` is that it ends the current conversation to prevent the user from getting stuck. That's why it sends a message to them to tell them that something went wrong.  If you truly want to alter this behavior you can use a piece of middleware to provide your own implementation:

```
bot.use({
     botbuilder: function (session, next) {
          session.error = function (err) {
              // Do something custom
          };
          next(); 
     }
});
```

**Comment by cesarvarela** [comment]
Awesome, this should definitively be in the docs.
