### ISSUE TITLE
Mattermost integration?

### ISSUE THREAD

**Issue by ThisWillDoIt** [Microsoft/BotBuilder#1715]
Are there any plans to extend the Bot Framework channels with support for Mattermost?

**Comment by dandriscoll** [comment]
At the moment, no, we don't have plans to support Mattermost.

Because Mattermost instances are self-hosted, there's additional setup required to configure each endpoint, and this is pretty close to the Direct Line provisioning model, where each installation can have its own ID and key. I know of developers who have used Direct Line to integrate into other channels, so that may be an option for you. The community may be interested in a Direct Line <-> Mattermost adapter.
