### ISSUE TITLE
Payload ignored in Facebook quick reply using KeyboardCard and channel data

### ISSUE THREAD

**Issue by gioffyx** [Microsoft/BotBuilder#1719]
Bot Framework 3.3.3

I have created a KeyboardCard to provide quick reply to my Facebook bot.
Right now I'm using the following code to create them:
```
var keyCard = new KeyboardCard(text, new List<CardAction>
{
   new CardAction(ActionTypes.PostBack,"Option 1", null, "opt§1"),
   new CardAction(ActionTypes.PostBack,"Option 2", null, "opt§2"),
});

var r = context.MakeMessage();                               
r.ChannelData = keyCard.ToFacebookMessage();

await context.PostAsync(r);
```

I expected that when the quick reply buttons were pressed there will be an incoming message with text equals to the payload provided in the definition.

Unfortunatly, when I press the quick reply buttons the activity contains a text message with the CardAction title (ie. "Option 1") only. No payload found.

**Comment by msft-shahins** [comment]
This is by design based on the facebook message sent to connector when a quick reply button is tapped. 

https://developers.facebook.com/docs/messenger-platform/send-api-reference/quick-replies#callback
> When a Quick Reply is tapped, a text message will be sent to your webhook Message Received Callback. The text of the message will correspond to the title of the Quick Reply. The message object will also contain a field named quick_reply containing the payload data on the Quick Reply.

Connector will promote the text in the Facebook message to the text field in the activity. If you want to access the payload, you can reach it through the channel data on the activity sent to your bot when the quick reply is tapped, e.g. ``activity.ChannelData.message.quick_reply``

**Comment by xjose97x** [comment]
@msft-shahins  is this still the behavior on Facebook?
