### ISSUE TITLE
Watson recognizer

### ISSUE THREAD

**Issue by cesarvarela** [Microsoft/BotBuilder#1720]
Are there any plans for a recognizer like LuisRecognizer but with IBM's Watson?

**Comment by palmerabollo** [comment]
@cesarvarela It's a very good idea but I don't think MS will put much effort into it, since Watson (IBM) and LUIS (MS) are kind of competitors in the NLP arena. Let's see what they say.

Another recognizers such as WitRecognizer (wit.ai) of ApiAiRecognizer (api.ai) would be interesting as well. I think that it is something we (the community and third parties) could start as a separate project/repository once MS releases botbuilder 3.5.x that comes with some changes such as the new IRecognizerSet (that –fingers crossed– might break backwards compatibility).

What do you think? Sound like something you could contribute some time to?

**Comment by chrimc62** [comment]
We would love contributions to leverage other frameworks.  Our primary goal is to support developers in writing great bots--whatever the technology.  Understandably our development efforts are spent on improving the platform and supporting Microsoft's solutions.  We believe Microsoft's solutions are great and will continue to improve, but it is ultimately up to developers to pick the best technology for their solution.  You can see this same philosophy in how we make Azure easy to use, but have factored things in such a way to support deploying to any cloud location.

**Comment by palmerabollo** [comment]
Thanks, that's good to know !

**Comment by cesarvarela** [comment]
Good to know, indeed.

Me and my team might want to develop one for Watson, I'll let you know if this is the case.

**Comment by dkenzik** [comment]
@cesarvarela - Keep me posted regarding a Watson recognizer. It's the only thing really keeping me from coming back to BotBuilder (on botkit now since it has a Watson middleware.) I was considering working on my own, so I'd be happy to contribute, too.

**Comment by rnjailamba** [comment]
@cesarvarela any update on the same?

**Comment by cesarvarela** [comment]
Guys we have a working version already, I'll release tomorrow once I add some documentation.

**Comment by rnjailamba** [comment]
@cesarvarela  really looking forward to this !!

**Comment by cesarvarela** [comment]
@palmerabollo @chrimc62 @dkenzik @rnjailamba 

This is an initial version:

https://github.com/thebotmakers/botframework-watson-recognizer

It works with Entities and Intents. Doesn't support Watson's dialogs yet, because we like to have our dialogs in code, but if anyone is interested feel free to contribute to.

**Comment by rnjailamba** [comment]
@cesarvarela looks good , ill give it a shot today and give you feedback for the same...
