### ISSUE TITLE
Need Help removing tax and total in receipt card

### ISSUE THREAD

**Issue by Masssluis** [Microsoft/BotBuilder#1733]
I want to display the key value pairs one by one in the card.I tried with receipt card but in that it is showing tax and total.I don't want to display the tax and total.Is there any way to do that or else with any other card i can able to do the same?
![capture](https://cloud.githubusercontent.com/assets/22141654/20615321/9a024232-b2fe-11e6-9eb4-aae5a64fb1d0.PNG)

**Comment by chrimc62** [comment]
What SDK and channel are you using?

**Comment by AnandChitale** [comment]
I had also seen this behavior in Web Chat Channel. Even if Tax and Total are not set ,they are shown in Receipt card

**Comment by Masssluis** [comment]
yes , it is there , but one thing i noticed that when the channel is Skype or Facebook and if the tax and total column is empty the card does not shows it .

________________________________

**Comment by chrimc62** [comment]
Adding @LarsLiden to comment on the channel differences.

**Comment by LarsLiden** [comment]
@eanders-MS can you take a look?  This seems like a bug.

**Comment by dandriscoll** [comment]
Hi @Masssluis, I've opened an issue on the Web Chat repo to track the issue for the Web Chat channel.

Which other channels are you interested in?

I know Facebook drops the card if empty; we unfortunately don't have the ability to modify the Facebook UI to change that behavior.

**Comment by piffarettig** [comment]
If I don't set the Total property when building a ReceiptCard (using C# and Skype Channel), the card does not get shown. I saw this is a mandatory field as we re talking bout a Receipt. However, I would like to achieve something like a receipt card but without Total field. Like this:

<img width="310" alt="screen shot 2017-01-02 at 12 46 19" src="https://cloud.githubusercontent.com/assets/16963208/21592120/809eb0b0-d0e9-11e6-8d70-4a770fd17a03.png">

How can I indent text to the right using a HeroCard for instance? Is that possible? 

@dandriscoll  maybe you know the best way to tackle this.

Thanks in advance!

**Comment by dandriscoll** [comment]
Adding the Skype label to get help from Skype experts. We'll continue to track the Web Chat issue on the other repo.

**Comment by stenoid** [comment]
I have a similar requirement with being able to use a hero card to mimic a receipt card. In my case (using node.js) I have been using a receipt card to ask for confirmation for scanning in actual receipt values. This works fine in Slack and the emulator, but Messenger displays lots of spurious values that I'm not interested in and it also doesn't display half of what I do want (when I define them as facts), it also doesn't display the five buttons I want. However, I can't currently use a hero card because most of the text is truncated and the buttons cause it to display as a carousel. Presumably this is just a limitation of the Messenger cards that are out of your control?

If I could at least display the values in a card and then display the buttons in a standard choice prompt, then that would be a help, but the example by @piffarettig above is very close to what I'm after!

**Comment by nwhitmont** [comment]
Note: Please only submit Bot Builder SDK bugs here. If you have general questions or implementation issues, please submit a question on Stack Overflow at http://stackoverflow.com/questions/tagged/botframework.

**Comment by Daddymarto01** [comment]
This issue is not fixed yet? Still have the same problem here
