### ISSUE TITLE
#<UniversalBot> has no method 'listenerCount'.

### ISSUE THREAD

**Issue by duthientandeveloper** [Microsoft/BotBuilder#1734]
When I use with nodejs version 0.10.36. module "events.Emitter" not have function listenerCount. How I can fix this error

**Comment by chrimc62** [comment]
Is this from the Bot Builder node SDK?

**Comment by duthientandeveloper** [comment]
yes.When i use botbuilder with node version 0.10.36

**Comment by maxpert** [comment]
Seems like you are using quite old version, going back and looking at docs turns out for events object in this 0.10.x has `listeners` method (that returns you array of listeners) [from documentation] (https://nodejs.org/docs/latest-v0.10.x/api/events.html#events_emitter_listeners_event), there also a class static `EventEmitter.listenerCount(emitter, event)`.
