### ISSUE TITLE
Dialog localization

### ISSUE THREAD

**Issue by marcoamendola** [Microsoft/BotBuilder#175]
I noticed that the PromptDialog.Confirm dialog only understands replies in English. I would like to contribute the Italian localization. Are you accepting pull requests in this area?

**Comment by wiltodelta** [comment]
And how about add yep, nope to Dialog in English?

**Comment by chrimc62** [comment]
The most recent release adds a resource file for all strings.  We would love to get contributions to localize that resource file.  I am also working on making it so that you can generate a resource file from the automatically generated stuff in FormFlow.  (I actually have a good chunk of the code checked-in, but it is disabled for now.)  I will also add yep and nope to the resource file, but it is also easy to override the matched terms by changing FormConfiguation to reflect what you think should be there for your program.
