### ISSUE TITLE
[Question] context.Wait<T>(ResumeAfter<T> method) doesn't coerce from IMessageActivity -> T

### ISSUE THREAD

**Issue by brandonh-msft** [Microsoft/BotBuilder#1768]
If you create a `ResumeAfter<T>` delegate say for `string` like:
```
        private async Task UserChoice(IDialogContext context, IAwaitable<string> result)
```
but try to use that same delegate with `context.Wait<string>(UserChoice)` at runtime you'll be met with an exception like this:
```
Microsoft.Bot.Builder.Internals.Fibers.InvalidTypeException occurred
  HResult=-2146233079
  Message=invalid type: expected System.String, have IMessageActivity
  Source=mscorlib
  StackTrace:
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at Microsoft.Bot.Builder.Internals.Fibers.Wait`2.Microsoft.Bot.Builder.Internals.Fibers.IAwaiter<T>.GetResult()
...
```
when you try to `await result` w/in the handler. This means that instead of passing `string` to the delegate as intended (and as outlined by `context.Wait<T>()`'s signature) it's still passing an `IMessageActivity` w/in the `IAwaitable` object.

Wondering why `PromptDialog...` works fine w/ these `ResumeHandler<string>` signatures I dug in to the source and found that `PromptDialog` uses `context.Call` instead of `context.Wait`, so it seems we've got a disconnect in those implementations.

**Comment by willportnoy** [comment]
You're likely using this overload:
https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Dialogs/IDialogContext.cs#L111

versus the generic method that doesn't overload:
https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Dialogs/IDialogTask.cs#L55

If you specify the generic parameter explicitly, it should work.

However, who is satisfying that wait?  Will you be posting a string rather than an activity to the IPostToBot?

**Comment by brandonh-msft** [comment]
No I specified the type parameter as well, still didn’t work.

The idea is that the Method satisfying the wait would take an IAwaitable<T> instead of being forced to take an IAwaitable<IMessageActivity> a la the ResumeHandlers for PromptDialog. If you create a ResumeHandler for PromptDialog and then want to use it with Wait, you can’t.

B

**Comment by willportnoy** [comment]
@brandonh-msft are you saying you want to create a ResumeAfter<T> delegate instance that doesn't have T specified yet (i.e. it's left generic)?  I'm not sure if that's possible.

**Comment by brandonh-msft** [comment]
Nah the issue I was seeing was if i created a `ResumeAfter<string>` delegate, and specified `context.Wait<string>(aforementionedDelegate)`, it would bomb out saying it was given `IMessageActivity` :/

**Comment by willportnoy** [comment]
@brandonh-msft we don't automatically coerce from IMessageActivity to string when satisfying waits.

There is some reflection-based "magic" in the dispatch dialog (e.g. so that Luis entities can be received as parameters typed as strings), but we don't do any coercion when satisfying the wait created by IDialogStack.Wait.

(perhaps we could, though I've had mixed experiences with type coercion in languages like perl, etc)

**Comment by brandonh-msft** [comment]
then what is the purpose of `context.Wait<T>()`?

**Comment by willportnoy** [comment]
The purpose of context.Wait<T> is to allow bot code to broken into two pieces, with a wait for some T value to start the second piece.

Generally, T is IMessageActivity, which is why we provide a non-generic context.Wait that defaults to IMessageActivity.

We left PostAsync generic in IPostToBot so that you could hypothetically post other types to complete waits (but we're likely to move that standardize on IActivity).

(but yes, you're right, Wait's generic type **could** be used to coerce types from IMessageActivity to string - it's just not designed that way)

**Comment by brandonh-msft** [comment]
"some T value" ... that T must be coerced from IMessageActivity somewhere in the Connector, then - that's exactly what the error message I saw at start of this issue says is trying to happen. If T is expected to implement IMessageActivity, we should have a generic constraint on it.

**Comment by brandonh-msft** [comment]
⏲

**Comment by nwhitmont** [comment]
@brandonh-msft Do you need more info? Or is this resolved? Or would you like to open a feature request to address this?
