### ISSUE TITLE
If the FormDialog choice values have numbers and/or parentheses in them, the form does not accept the choice

### ISSUE THREAD

**Issue by etiago** [Microsoft/BotBuilder#1779]
The title is pretty self explanatory, but essentially we're facing an issue where if the choices for a particular FormDialog field have numbers and/or parentheses in them, the FormDialog will not accept them as valid choices.

Interestingly enough, when our choices had values like "Foobar (ABC123-2)" it would take the "-2" as a positional argument and take the second choice on the list...

**Comment by danmarshall** [comment]
I am guessing C# ?

**Comment by etiago** [comment]
@danmarshall sorry, I forgot to mention. Yes, this is for the C# version of the SDK.

**Comment by chrimc62** [comment]
Are you saying that your descriptions at like "Foobar (ABC123-2)" or that your terms look like that?  If terms, they are regular expressions so you would need to escape them, i.e. "Foobar \(ABC123-2\)".  Otherwise it will not match "Foobar (ABC123-2)" because the parens will not match.  Let me know if this fixes your issue.

**Comment by chrimc62** [comment]
Actually digging into this a bit further, there is a bug for terms that start of end with a non-word character like () that will prevent matching on the whole expression.  I will go ahead and fix that and it should be in the next release.
