### ISSUE TITLE
Dialog created using FormFlow keeps sending the same message

### ISSUE THREAD

**Issue by hamadycisse** [Microsoft/BotBuilder#179]
I have  created a dialog using a the FormFlow API but I don't know how to flag the conversation as completed in order to initiate a new flow.

Here is the implementation of the OnCompletionAsyncDelegate delegate

`private static async Task BookAppointment(IDialogContext context, RendezVous state) => await context.PostAsync("Success!");`

What am I missing?

**Comment by chrimc62** [comment]
There isn't enough information here to tell for sure.  Generally speaking a dialog call context.Done to finish a dialog, but FormFlow takes care of that for you.  If you mean you keep seeing your success message, I suspect that is because your dialog is the root one and you are not creating a new dialog each time.  That means that you have the same completed form which gets passed in and you keep executing that to your completion point.

**Comment by hamadycisse** [comment]
After multiple attempts, I was able to start a new Form flow when I wrap the declaration of the new FormDialog inside a Chain.From

Before: 
`public static IDialog<Type> MakeRootDialog() => new FormDialog<Type>(startingState, Type.BuildForm);`

After:
`public static IDialog<Type> MakeRootDialog() => Chain.From(() => new FormDialog<Type>(startingState, Type.BuildForm));`

I notice that the class Chain has been added recently. Do I have to use  it or can I go around it?

**Comment by chrimc62** [comment]
Chain is optional, but it does provide a simple way to compose and write dialog flows.

**Comment by hamadycisse** [comment]
How should I implement my MakeRootDialog without using Chain?

I need to pass an initial state to my Form but I get the following exception when I use 'Chain'

Microsoft.Bot.Builder.Internals.Fibers.ClosureCaptureException occurred
  HResult=-2146233076
  Message=anonymous method closures that capture the environment are not serializable, consider removing environment capture or using a reflection serialization surrogate: 

What should I do if my form depends on an initial state which needs to be evaluated every time a new for should be started?

**Comment by hamadycisse** [comment]
I have found this chapter about using the reflection-base serialization for types which were not marked as serializable: [http://docs.botframework.com/sdkreference/csharp/dialogs.html#Serialization](url)

Now my question is where should I plug the following snippet of code?

```
        public static IContainer Build(bool includeReflection = true)
        {
            var builder = new ContainerBuilder();
            builder.RegisterModule(new DialogModule());
            if (includeReflection)
            {
                builder.RegisterModule(new ReflectionSurrogateModule());
            }
```

**Comment by willportnoy** [comment]
It sounds like in your code you have some initial state that you want to initiate the form dialog with, and this initial state varies over time.

The simplest method to avoid using the reflection serialization surrogate is to make your Chain.From delegate not refer to the environment (this might be desirable anyway since with delegates you risk capturing a lot of variables available in containing environments).  You might choose to do this by inheriting from FormDialog (or use composition, implementing your own IDialog that contains a FormDialog) and have the constructor (or StartAsync in case of composition) create your initial state and pass it to FormDialog.

However, if you want to use the reflection serialization surrogate, you can look at how we use the container in the implementation for Conversation.SendAsync.  Instead of the container referenced statically there, you would initialize your own container as above and use that to resolve the implementations you need.

**Comment by hamadycisse** [comment]
Thank you for the detailed answer.

It turns out that after many trials, I ended up using your second option before even seeing your answer! 
I created an implementation of the IDialog and declared the FormDialog<T> as a child dialog and compute my starting state in the StartAsync.

It helped me a lot to be able to see the implementation of Chain.From (love Open Source!)

Regards
