### ISSUE TITLE
How to write unit testing for bot application?

### ISSUE THREAD

**Issue by Masssluis** [Microsoft/BotBuilder#1793]
I am new to creating bot application using Luis. i want to write the unit test cases for simple bot application using Luis. I already gone through the examples and spend a lot of time on this to understand the test cases which are given in this website.Still didn't understand anyone.Can anyone please give me the very simple test case for bot application using Luis for understanding purpose.

**Comment by danmarshall** [comment]
in Node.js or C# ?

**Comment by Masssluis** [comment]
In C#

**Comment by vossccp** [comment]
We based ours on an adaptation from https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Tests/Microsoft.Bot.Builder.Tests/DialogTaskTests.cs

**Comment by willportnoy** [comment]
@Masssluis we have a full example test that mocks the LUIS service here:
https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Tests/Microsoft.Bot.Sample.Tests/AlarmBotTests.cs#L72

otherwise, we tend to use AssertScriptAsync:
https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Tests/Microsoft.Bot.Builder.Tests/ChainTests.cs#L513

**Comment by willportnoy** [comment]
I'm going to close this issue for now, but feel free to open a new issue for further discussion.
