### ISSUE TITLE
[LUIS] Entity Resolution Data format

### ISSUE THREAD

**Issue by miaosenwang** [Microsoft/BotBuilder#1797]
In Microsoft.Bot.Builder.Resolution.cs

    public sealed class ResolutionParser : IResolutionParser
    {
        bool IResolutionParser.TryParse(IDictionary<string, string> properties, out Resolution resolution)
        {
            string resolution_type;
            if (properties != null)
            {
                if (properties.TryGetValue("resolution_type", out resolution_type))

The last line of this code won't work because, in the current Luis output json, resolution_type is not part of the resolution dictionary object. Instead, it is stored as the "type" property on EntityRecommendation. 

See example:
{
      "entity": "tomorrow",
      "type": "builtin.datetime.date",
      "startIndex": 51,
      "endIndex": 58,
      "resolution": {
        "date": "2016-12-07"
      }
}

So the fix should be changing the input parameter from IDictionary to  EntityRecommendation.

I can create a pull request for this change, but I want to ask the team first to confirm if this is correct.

**Comment by willportnoy** [comment]
Is this the V2 version of the API?

**Comment by miaosenwang** [comment]
Yes. It is V2.0.  https://api.projectoxford.ai/luis/v2.0/apps/....

**Comment by jsiegmund** [comment]
I see the same thing. The dictionary it's trying to parse contains this for a date time entity (at my end at least): 

`{[date, 2017-01-21]}`

I concur with @miaosenwang that the EntityRecommendation should be passed in for checking the resolution type.

**Comment by willportnoy** [comment]
When fetching this url:
https://api.projectoxford.ai/luis/v2.0/apps/c413b2ef-382c-45bd-8ff0-f76d60e2a821?subscription-key=6d0966209c6e4f6b835ce34492f3e6d9&q=can%20you%20set%20an%20alarm%20for%2010%20am

This is the response I see:

~~~
{
  "query": "can you set an alarm for 10 am",
  "intents": [
    {
      "intent": "builtin.intent.alarm.set_alarm"
    }
  ],
  "entities": [
    {
      "entity": "10 am",
      "type": "builtin.alarm.start_time",
      "resolution": {
        "resolution_type": "builtin.datetime.time",
        "time": "T10"
      }
    }
  ]
}
~~~

Based on this json, it looks like the existing code is correct (look at resolution_type instead of entity type, particularly since entity type is alarm-model specific).  Can you explain further?

**Comment by jsiegmund** [comment]
Strange, you're right. I'm seeing the same directly calling the URL. Will investigate further and get back on this, this is not what I was seeing in my debug session.

**Comment by jsiegmund** [comment]
Did some more research, not sure whats going on here. When I sent a query to the LUIS app I am using, I'm getting this in response: 

URL: /luis/v2.0/apps/<<APPID>>?subscription-key=<<KEY>>&q=i%20want%20to%20book%20a%20holiday%20from%20today%20to%20tomorrow

`{
  "query": "i want to book a holiday from today to tomorrow",
  "topScoringIntent": {
    "intent": "LeaveRequest",
    "score": 0.979348958
  },
  "entities": [
    {
      "entity": "today",
      "type": "builtin.datetime.date",
      "startIndex": 30,
      "endIndex": 34,
      "resolution": {
        "date": "2017-01-26"
      }
    },
    {
      "entity": "tomorrow",
      "type": "builtin.datetime.date",
      "startIndex": 39,
      "endIndex": 46,
      "resolution": {
        "date": "2017-01-27"
      }
    }
  ]
}`

Note how there is no 'resolution_type' key in the resolution dictionary and so the ResolutionParser routine fails. 

I expect this might be due to changes in LUIS. If I recall correctly one of the previous versions allowed you to rename a prebuilt entity. This is not possible in the UI any more (at least I can't find it). I'm guessing your LUIS app is based on such a definition where the "builtin.alarm.start_time" is a custom label and "builtin.datetime.time" is the prebuilt entity.

This invalidates my PR since the above won't be handled correctly.

**Comment by miaosenwang** [comment]
I think we need the Luis team to comment on what is going on here

**Comment by JasonSowers** [comment]
@miaosenwang Is this still a problem for you or has the issue been resolved?

**Comment by nwhitmont** [comment]
@jameslew Any thoughts?

**Comment by alecrt** [comment]
As far as I can read in LUIS official docs, the json format DOES NOT include "resolution_type" key inside "resolution -> values" object

https://docs.microsoft.com/en-us/azure/cognitive-services/luis/pre-builtentities
