### ISSUE TITLE
Running multiple scorables

### ISSUE THREAD

**Issue by grbinho** [Microsoft/BotBuilder#1801]
Hi!

Is it possible to run multiple scorables for the same command? I'm trying to run additional cleanup logic on "/deleteprofile" command. My logic needs access to private conversation data to get some values that will cleanup our internal cache. 

Only options I can see are:

- Build custom scorable that has both, logic from `DeleteProfileScorable` and my custom logic.
- Do something in the `MessageController` by getting `StateClient` (suggestions form this issue #1086)
- Add additional key to my internal cache that maps ChannelId, ConversationId, and UserId to my cache key(s)

Framework options look like hacks to me and the third one like a workaround.

**Comment by willportnoy** [comment]
Generally only one scorable "wins" based on user input.  Your first option doesn't seem unreasonable - you could compose your CustomScorable on top of DeleteProfileScorable, delegating to DeleteProfileScorable as necessary, and register your CustomScorable instead of DeleteProfileScorable.

I'm happy to hear feedback on the design.

**Comment by willportnoy** [comment]
I'm going to close this issue for now, but feel free to open a new issue for further discussion.
