### ISSUE TITLE
Microft Bot Framwork throw 500 internal server error.

### ISSUE THREAD

**Issue by sencsk1** [Microsoft/BotBuilder#1866]
I got 500 internal server error  Method not found. i dont know what i missed
I refer the link http://stackoverflow.com/questions/38277691/latest-project-template-and-emulator-for-bot-framework-v3-throws-500-internal-se

im also having the same configuration but i'm getting error in Microsoft Bot and Emulator
Microsoft.Rest.ClientRuntime - 1.8.2
Newtonsoft.Json - 8.0.3
System.IdentityModel.Tokens.Jwt - 4.0.2.206221351

**Comment by msft-shahins** [comment]
Bot builder 3.4 which is the latest version is dependent on Microsoft.Rest.ClientRuntime - 2.3.2: https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Microsoft.Bot.Builder/Microsoft.Bot.Builder.nuspec#L28

I guess you get the 500 because bot builder cannot load the right version of assemblies.
