### ISSUE TITLE
Get slack time stamp to delete messages

### ISSUE THREAD

**Issue by bluekite2000** [Microsoft/BotBuilder#187]
I integrated my bot w/ slack and would like to delete all chat history once a dialogue is finished. What is the best way to do this?
I m reading slack's api 
https://api.slack.com/methods/chat.delete
and it s asking for timestamps of the slack messages. Where can I get that info (in my c# project)?

**Comment by Stevenic** [comment]
Shahin can provide specifics but off the message object is a field called `channelData` which should have the original slack message your bot received. You should be able to get the timestamp from that.

**Comment by bluekite2000** [comment]
@Stevenic I dont want just to delete the received message. I want to delete all messages (ie bot messages too). Also how do I debug this channeldata in the emulator? It shows null right now since I m not in slack.

**Comment by msft-shahins** [comment]
@bluekite2000 currently there is no way to get the timestamp for the messages your bot posts to slack through connector. What you can do is modifying your but to talk to slack api directly. On the incoming message channel data from slack you can find the channel id of the specific slack channel that your bot is mentioned. You can find a sample test message sent to a bot over slack channel id of `C0LSQ8BA4`.

```json
"ChannelData" : {
  "type": "message",
  "channel": "C0LSQ8BA4",
  "user": "U0LT19MV1",
  "text": "<@U14JFH57D>: test",
  "ts": "1461868745.000014",
  "team": "T0LSPCL6B"
}
```

Then you can use [channel.history](https://api.slack.com/methods/channels.history) api of slack to query all the messages your bot sent on that channel id and then use [channel.delete](https://api.slack.com/methods/chat.delete) to delete those messages.

**Comment by jabarjung** [comment]
I am stuck in this problem. Would you be able to help me with it? Whenever my app posts ephemeral message to Slack channel in response to a query by a user, I am unable to delete my Slack app response once the user has made a selection using one of the buttons. Although I have subscribed to 'message.channels' but I don't get a notification to my app whenever my app posts in the channel in response to the user input, therefore, I am unable to get the timestamp of the message which I want to delete. All I want is the timestamp of the message posted by my app so that I can delete it but I am unable to receive the timestamp. Please help!

**Comment by jabarjung** [comment]
I got the issue resolved.

**Comment by RajeshMKs** [comment]
How?

**Comment by jabarjung** [comment]
> How?

You don't need the time stamp in order to delete the ephemeral messages. Just send a similar response as given below to the response URL and it will suffice:
```
var response = {
    "text": null,
    "response_type": "ephemeral",
    "replace_original": true,
    "delete_original": true
  };
```
