### ISSUE TITLE
Guidance on correct way to manage contexts between dialogs

### ISSUE THREAD

**Issue by gregk** [Microsoft/BotBuilder#1898]
We are the bot framework on node, and we would like to know, what is the best way to solve following scenario:

User says: I want to schedule haircut at 11:00 AM.
Bot Says: Sorry, this time is not available, choose any time from 10:00 AM, 1:00 PM and 5:00 PM.
User says: 25:00 PM please.
Bot Says: Sorry, I didn't understand, can you please repeat?
User says: 5:00 PM please.
Bot Says: Ok, I scheduled the haircut.

We are currently solving it in a way, that we have dialog "/haircut" and subdialog "getValidTime", which is using replaceDialog to loop until it gets valid data.

The issue we have been facing is, how we can keep context of the original dialog in the "getValidTime" subdialog. For instance, in the original sentence the bot knows that there is an entity of type time. When the bot is asking to specify the time, the information, that we are expecting time type is lost. So when the user responds with invalid data "25:00", we have two options:
1. Parse it manually and determine, that it is not valid time - in that case we are losing the power of the AI framework.
2. Taking the response from the user, putting it back in the original sentence and rerunning it through the original dialog handler again. - in that case we are risking that the query would be recognized as something else than scheduling haircut. Also the usage of this response could make in incomprehensible to the LUIS and not classify it as any intent at all.

There would be possibility of training LUIS to recognize time entries as single utterances and then it would be recognized as time, but this doesn't solve the general case... For example the utterance "25:00" could also mean a score of volleyball match in different context.

We know, that there is a possibility of adding custom prompts to missing parameters, but in this case, we have the time right in the original utterance, which is later recognized by our logic as invalid. Also when the data is missing in the original utterance an appropriate prompt would be "What would be the time for the haircut?", on the other hand, when time is invalid, we would need different prompt, e.g. "Sorry, I didn't understand, could you specify the time once more?" - which doesn't seem to be possible with the prompts.

Another thing we would like to accomplish with the context is, that when user says for example "Never mind, forget it." or "Let's do the scheduling another time" to discard this subdialog and original dialog. Again, this sentence should be only recognized when we are in the context of scheduling a haircut, it should not be recognized as general utterance, since in different contexts it can have different meainig.

Are we missing something? What would be the recommended way to solve this?

**Comment by willportnoy** [comment]
I'm sorry I'm having a little bit of trouble understanding the question.

We often use the stack of dialogs (and the current callback within each dialog) as the "context" that helps express what the bot expects to hear next.  You could also use the dialog data as a form of "control flow" state tracking.

In Node, if you want more persistently available actions like cancellation, you might consider attaching the cancelAction to your stack.

**Comment by nwhitmont** [comment]
Hi @gregk  - One approach to solving this is to look at the problem from a different perspective.  For example, instead of validating the user-provided time value, I recommend creating a helper function or service that generates an array populated with the available times, and then passing that array of appointment times to a `builder.Prompt.choice()` style prompt.  This way, the user can choose from a list of available times which reduces the amount of typing on the user side, as well as saving you time on the input validation side.  

**For more information:**
- [Read more about using Prompt.choice()](https://docs.botframework.com/en-us/node/builder/chat/prompts/#promptschoice)
- [Check out the detailed Prompt class reference here](https://docs.botframework.com/en-us/node/builder/chat-reference/classes/_botbuilder_d_.prompts.html#attachment)
