### ISSUE TITLE
Directline V3 messages not emitted to socket 

### ISSUE THREAD

**Issue by tahsintahsin** [Microsoft/BotBuilder#1921]
Hello, 
For our bot we use directline V3 with websockets and with our custom web ui. We listen to to socket messages emitted from directline to us by node.js ws module and redirect those messages to our clients via socket.io. 
When a user starts chatting with our bot, everything works as expected. A behaviour we observed is after several seconds of inactivity from the users side, and then user types sth new, which is again successfully sent to our server and then to directline, the socket end listening in our server doesn't receive any response message from our bot. When I check the same conversation's activities with get request, I can see that out bot replied and the response is in activities list, but nothing is emitted on the socket side (I log all the events on our server which is listening to the wsUrl provided when initiating the conversation). To see if this is a disconnection issue, I put a socket disconnect event listener on our server which never fired and it seems that ws connection is still open (also checked the status of socket every two seconds). So the first question is, is it possible that the activities are not emitted properly by directline? 
Second question is, this is not clearly documented, I dont receive any disconnect events from your side, and I put a function runs every two seconds to check the socket connection state, which says it is open always in my case. I also send pings (empty messages) to directline, but dont receive anything back which can help me check the connection state. Do you have a ping mechanism? Btw i dont receive any answer to my empty messages even if my user chats properly with the bot, so sending packets cant help me understand the connections state, since it never responds to my pings.
Thanks for the help !

**Comment by tahsintahsin** [comment]
An example of it can be seen in conversation id 6z3tJGgb0me. Hope someone can investiagate. @dandriscoll maybe?

**Comment by dandriscoll** [comment]
Hi @tahsintahsin, I've taken a look at the traces for that conversation. Let me start by sharing what I'm seeing so you can see if there are any discrepancies in what we observed. (I hope you don't mind me sharing these general statements about the conversation. We can discuss offline if so.)

- The conversation included 13 messages: 5 from the user and 8 from the bot
- All 13 messages were sent in the first 5 minutes of the conversation
- Your client was connected to the WebSocket for 806 seconds (~13m)
- We sent 10 ping messages, 8 of which happened in the 8 minutes after the last message
- On my side, I see all 13 messages successfully sent to the WebSocket. I know you did not see them all :) but I have successful writes for all messages, for what that's worth.

If anything seems very strange, let me know.

Since I'm seeing successful writes (which would hint that a TCP ACK is being sent), I think the next step is to verify TCP-level traffic coming in to your client. Is this something you can do with a tool like Fiddler, WireShark, or NetMon?

On to your questions.

1. **Is it possible the activities are not being emitted?** It's certainly possible, but my logs indicate successful writes. We should dig a level deeper.

2. **How is disconnect communicated?** We disconnect the socket with a standard 1000 code. (https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent) In this case, we did not close the socket on our own.

3. **How can I send pings?** Simply send an empty message (with zero length). If your client can successfully send the ping, the connection is alive. WebSockets work over TCP and each frame is not delivered until the recipient sends an ACK. If the client never receives an ACK, it surfaces an error or exception back to your client.

In fact, WebSocket implements *its own ping mechanism* under the cover to make sure the connection is alive. However, most WebSocket clients do not expose functionality to control this ping, so many protocols that build on WebSocket use their own ping. Because we have two layers of ACK built in already, we don't need another application-layer response.

Let me know if those answer your questions. If I were debugging this problem on my machine, I would definitely focus on WebSocket traffic back to the client. If you find that WebSocket frames aren't being sent, we should investigate further on my side. Thanks!

**Comment by tahsintahsin** [comment]
Thank you @dandriscoll for the great explanation. I checked all the traffic to my server and saw again that message is not sent, even though I continued receiving and sending ACK. I saved the wireshark records, and conversation id in case it helps solving the issue. Is that possible you check on your side as well?  If you need the logs let me know how I can send them to you.

**Comment by dandriscoll** [comment]
Hi @tahsintahsin, please mail it to me at dandris@microsoft.com.

**Comment by tahsintahsin** [comment]
Hello, 
It seems like the issue was due to a package we used, 
So I am closing the issue for now. 
Thank you @dandriscoll for your valuable help.
