### ISSUE TITLE
Rendering of Markdown table is not as expected and not legible on Teams

### ISSUE THREAD

**Issue by manums** [Microsoft/BotBuilder#1932]
Rendering of Markdown table is not as expected on Teams. The same markdown text on Skype works as expected. Please see the screenshot.

Markdown text looks something like below:

### Transaction history : 0040708876
Tier | Name\Alias | Date | Status | Comments
--- | --- | --- | --- | --- 
0 | Sourabh Jain soujain | 12/30/2016 2:28:00 AM | Submitted | 
1 of 3 | BCWeb VL Test1 bcwebvl1 | 12/30/2016 2:29:00 AM | Approved | 
2 of 3 | BCWeb VL Test1 bcwebvl1 | 12/30/2016 2:30:00 AM | Approved | 
3 of 3 | BCWeb VL Test1 bcwebvl1 | 12/30/2016 2:30:00 AM | Approved | 
0 | Sourabh Jain soujain | 12/30/2016 2:33:00 AM | Submitted | test for extend 2
1 of 3 | BCWeb VL Test1 bcwebvl1 | 12/30/2016 2:39:00 AM | Approved | 
2 of 3 | BCWeb VL Test1 bcwebvl1 | 12/30/2016 2:40:00 AM | Approved | 
3 of 3 | BCWeb VL Test1 bcwebvl1 | 12/30/2016 2:40:00 AM | Approved | 
0 | Sourabh Jain soujain | 12/30/2016 2:42:00 AM | Submitted | test complete

On Teams:
![image](https://cloud.githubusercontent.com/assets/3592179/21563997/f513761c-cead-11e6-9bbc-91d45e07bcd7.png)

On Skype:
![image](https://cloud.githubusercontent.com/assets/3592179/21564002/0bd0deb2-ceae-11e6-9a2f-e710c19d570e.png)

**Comment by RichMoeMSFT** [comment]
This is indeed not as expected.  I'll log a bug on this.

**Comment by nwhitmont** [comment]
You might find more useful information in the MS Teams docs rather than here.  I found a related forum post here: https://techcommunity.microsoft.com/t5/Microsoft-Teams/Microsoft-Teams-Incoming-Webhook-Message-Formatting/td-p/31984

Note: Please only submit Bot Builder SDK bugs here. If you have general questions or implementation issues, please submit a question on Stack Overflow at http://stackoverflow.com/questions/tagged/botframework.

**Comment by ChristopherLyon** [comment]
This is still a bug. Any update?

**Comment by colin-broderick** [comment]
This is still an issue as of March 2022, five and a half years since first report.
