### ISSUE TITLE
Botbuilder: using builder.Prompts.confirm with an IMessage object does not render Yes/No buttons

### ISSUE THREAD

**Issue by admeister** [Microsoft/BotBuilder#1979]
When using builder.Prompts.confirm with an IMessage object, rather than just a string, the Yes/No buttons do not get rendered.

e.g.
This displays the 'Are you sure?' message with Yes and No buttons:
```javascript
builder.Prompts.confirm(session, 'are_you_sure');
```

This displays the 'Are you sure?' message, but with no buttons:
```javascript
var message = new builder.Message(session)
    .text('are_you_sure');
builder.Prompts.confirm(session, message);
```

**Comment by willportnoy** [comment]
That may be "expected behavior" - if you provide a message yourself, it doesn't get overridden or augmented by the builder - here is the relevant code:

https://github.com/Microsoft/BotBuilder/blob/master/Node/core/src/dialogs/Prompts.ts#L256

**Comment by admeister** [comment]
Then how do you use the confirm prompt, with a message object, and include Yes/No buttons, without resorting to a choice prompt? This doesn't sound right to me.

**Comment by willportnoy** [comment]
@maxpert could @admeister call createPrompt() to create the message with yes/no buttons and pass that to the prompt?

**Comment by admeister** [comment]
Any alternative solution to this? I need to use an IMessage object as I need to interpolate some data into the message (with is from a translation file). Passing data for interpolation using the .confirm() method isn't supported AFAIK.

**Comment by Stevenic** [comment]
So as @willportnoy stated, anytime you pass an IMessage to a prompt (any prompt) the message is just passed through. This is by design to let you do things like create a `confirm()` prompt containing an image. That means that if you want to include yes/no buttons on the message you'll need to add them yourself. Just create a hero card with two `imBack` buttons for yes & no which is what we do internally. 

In the future we can explore making it easier to reuse our internal list building logic to do this but for now you'll have to do it yourself.
