### ISSUE TITLE
Using new Bing Location control in FormFlow

### ISSUE THREAD

**Issue by garypretty** [Microsoft/BotBuilder#1998]
Hi.

Is it possible to use the new Location Control within FormFlow at present?  For example, handing off to a location control dialog to populate a given field?

Thanks

Gary

**Comment by willportnoy** [comment]
We don't currently have mechanism to reuse the location control as a field within FormFlow directly.

It's something we'd like to improve to make possible.

One possible workaround is to compose some dialog that uses both FormFlow and the Bing Location control in a sequence or loop (until you get all of the fields you want).

**Comment by chrimc62** [comment]
You might also be able to make use of the SetDefine delegate and SetNext delegate to boost the location control information into the form flow machinery.  This would be kind of complicated though.  The real problem is that FormFlow predates a lot of our other machinery and as Will notes we are working to decompose it.

**Comment by garypretty** [comment]
Thanks for the response guys. I can work around for now as you suggest and good to hear that bringing FormFlow up to date with everything else in on the roadmap. To be clear, I love FormFlow - supper useful  and solves a key requirement for bots.

**Comment by willportnoy** [comment]
I'm going to close this issue for now, but feel free to open a new issue for further discussion.

(sorry about the delay in our responses)

**Comment by Ma3yTa** [comment]
Hi @garypretty could you please provide your solution?
