### ISSUE TITLE
Action not serializable + deprecation

### ISSUE THREAD

**Issue by srozga** [Microsoft/BotBuilder#1999]
Hello
Two things:
1. In C#, Luis.Models.Action is not marked as Serializable, even though IntentRecommendation is. So if we have a Dialog that calls another dialog and has local IntentRecommendation state with an action, we get the following exception: Exception: Type 'Microsoft.Bot.Builder.Luis.Models.Action' in Assembly 'Microsoft.Bot.Builder, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' is not marked as serializable.
2. I noticed that the LUIS UI states that actions are going to be deprecated. That was surprising. Are actions completely gone? Are they moving out of LUIS and into the Bot framework? Are they just gone forever? Any direction would be helpful as we have been utilizing this feature quite heavily and I know your library code uses the Action results and context as part of the LuisDialog. Any insight in here would be great.

Thanks!
-Szymon

**Comment by jameslew** [comment]
I'll leave @willportnoy to answer the first question.

Regarding the second, yes, actions are being removed from LUIS, first from the UI and eventually from the API as well.  We'll be extending our dialog support in the Bot Framework, and additionally will soon be providing samples that will enable you to perform the same action binding in your own service.

I understand this change can be difficult; our intent is to provide one great solution from Microsoft rather than several incompatible solutions.  We'll have more information soon.

**Comment by willportnoy** [comment]
IntentRecommendation is one of the few LUIS classes marked as serializable, because it was needed for FormFlow: https://github.com/Microsoft/BotBuilder/blob/497252e8d9949be20baa2cebaa6ce56de04461cf/CSharp/Library/Microsoft.Bot.Builder/FormFlow/FormDialog.cs#L837
