### ISSUE TITLE
Messaging endpoint URL in Microsoft Bot

### ISSUE THREAD

**Issue by sachinavinaw** [Microsoft/BotBuilder#2047]
Hi.

I am new to Microsoft Bot framework.

can anyone tell me what is messaging endpoint url?

**Comment by fingejo** [comment]
hey,
....yourbothere.azurewebsites.net/api/messages

this guide is very good:
https://docs.botframework.com/en-us/csharp/builder/sdkreference/gettingstarted.html

"Click the "Register a Bot" button and fill out the form. Many of the fields on this form can be changed later. Use a the endpoint generated from your Azure deployment, and don't forget that when using the Bot Application tempalate you'll need to extend the URL you pasted in with the path to the endpoint at / API / Messages. You should also prefix your URL with HTTPS instead of HTTP; Azure will take care of providing HTTPS support on your bot. Save your changes by hitting "Create" at the bottom of the form."

i hope i could help you

**Comment by EricDahlvang** [comment]
@rcarmo please explain in detail why you think the answer above is incorrect.  How did you arrive at the conclusion that /api/v1/messages is the messaging endpoint?  (Note: The question and answer are in reference to the bot's Messaging Endpoint, not the connector services.)

**Comment by ayanez17** [comment]
What if you are running the bot locally? How do you get the messaging endpoint ?
