### ISSUE TITLE
Microsoft Bot: Bot Data getProperty is returning null when I try to set Property

### ISSUE THREAD

**Issue by msBot1111** [Microsoft/BotBuilder#2075]
I'm trying to authenticate my Bot using my web project and I store the token in Bot Data using Bot State. But when I try to get thee token from my Bot using getProperty it always returns null. I'm using this sample: https://blogs.msdn.microsoft.com/tsmatsuz/2016/09/06/microsoft-bot-framework-bot-with-authentication-and-signin-login/ Here is my code in web:
var botCred = new MicrosoftAppCredentials(
ConfigurationManager.AppSettings["MicrosoftAppId"],
ConfigurationManager.AppSettings["MicrosoftAppPassword"]);
var stateClient = new StateClient(botCred);
BotState botState = new BotState(stateClient);
BotData botData = new BotData(eTag: "*");
botData.SetProperty("AccessToken", authResult.AuthenticationToken);
await stateClient.BotState.SetPrivateConversationDataAsync(TempData["channelid"].ToString(), TempData["conversationid"].ToString(), TempData["skypeuserid"].ToString(), botData);
And here is in my Bot:
ConnectorClient connector = new ConnectorClient(new Uri(activity.ServiceUrl));
StateClient stateClient = activity.GetStateClient();
BotState botState = new BotState(stateClient);
BotData botData = await botState.GetPrivateConversationDataAsync(activity.ChannelId,activity.Conversation.Id, activity.From.Id);
string token = botData.GetProperty("AccessToken");
The token is always null.

**Comment by willportnoy** [comment]
It seems very likely that (TempData["channelid"].ToString(), TempData["conversationid"].ToString(), TempData["skypeuserid"].ToString()) does not match (activity.ChannelId,activity.Conversation.Id, activity.From.Id) - can you check the values?

**Comment by msBot1111** [comment]
The values are the same..

**Comment by willportnoy** [comment]
Are the StateClient's ServiceURLs the same?

**Comment by msBot1111** [comment]
No, they are not the same.. In web app I have:
var botCred = new MicrosoftAppCredentials(
      ConfigurationManager.AppSettings["MicrosoftAppId"],
       ConfigurationManager.AppSettings["MicrosoftAppPassword"]);
       var stateClient = new StateClient(botCred);
       BotState botState = new BotState(stateClient);
this has state.botframework.com
And in Bot I use this:
StateClient stateClient = activity.GetStateClient();
BotState botState = new BotState(stateClient);
which has localhost url. But if I use the same code in Bot which is in the web app it gives 500 internal server error in this line 
BotData botData = await stateClient.BotState.GetPrivateConversationDataAsync(channel,conversation, id)

**Comment by willportnoy** [comment]
@msft-shahins I wonder if Activity.GetStateClient isn't propagating the MicrosoftAppCredentials?

**Comment by msft-shahins** [comment]
Code above is using this [implementation](https://github.com/Microsoft/BotBuilder/blob/a71e64c24bd40f8b99de0a3326ea1b79110c33e1/CSharp/Library/Microsoft.Bot.Connector.Shared/ActivityEx.cs#L164) of GetStateClient() which creates a new [MicrosoftAppCredentials](https://github.com/Microsoft/BotBuilder/blob/3a98a6b3d15962a57b5454bfb3f730d3588de3ef/CSharp/Library/Microsoft.Bot.Connector.Shared/MicrosoftAppCredentials.cs#L47). Notice that it load the MicrosoftAppId and MicrosoftAppPassword from configuration manager since they are passed as null to the constructor: https://github.com/Microsoft/BotBuilder/blob/3a98a6b3d15962a57b5454bfb3f730d3588de3ef/CSharp/Library/Microsoft.Bot.Connector.Shared/MicrosoftAppCredentials.cs#L54

You need a valid channel.id, conversation.id, user.id to call GetPrivateConversationData. Here is an example: https://github.com/Microsoft/BotBuilder/blob/10893730134135dd4af4250277de8e1b980f81c9/CSharp/Tests/Microsoft.Bot.Builder.Tests/BotDataTests.cs#L172

_Note_ that service url for state service when `channel.id == emulator` is the serviceUrl from the activity is since emulator is acting as state service during the emulation. But state.botframework.com will be used for other channels: https://github.com/Microsoft/BotBuilder/blob/a71e64c24bd40f8b99de0a3326ea1b79110c33e1/CSharp/Library/Microsoft.Bot.Connector.Shared/ActivityEx.cs#L146

 Closing this since we cannot repro the issue. Feel free to open another issue with the repro steps.
