### ISSUE TITLE
directline takes too long to get response.

### ISSUE THREAD

**Issue by zhou-xinghai** [Microsoft/BotBuilder#2089]
hi, 
  I use bot framework+ luis to provide the bot service and with directline 3.0 to access the ms framework. 
But it takes too long to get response around 12-20 seconds, each test takes different response time with the same query. I try to deploy the botframework on  aws and azure in China and the result is similar. I wonder is there some way to take shorter response time ?  Anyway, 20 secs is bad experience for user to wait the response.

**Comment by PrasadGautham** [comment]
hi,
   The same issue persists with me as well. Response time is too high

**Comment by zhou-xinghai** [comment]
hi @PrasadGautham Can you tell me how long do you take to get response commonly?

**Comment by PrasadGautham** [comment]
@zhou-xinghai  I think that is almost similar to yours.... 12-20 seconds and sometimes even more, it varies

**Comment by tomlm** [comment]
Have you determined if the latency is in your bot?  Depending on the services you talk to you can incur a lot of latency inside of the bot.  For example, the State API that we have is only in West US and really only for prototyping.  If you want better performance you should have state storage in a data center close to your bot.  You can easily do this by plugging in a state provider to the bot SDK

We have a nuget library with a number of implementations of the IBotDataStore storage provider for TableStorage, redis, DocumentDB, etc. https://www.nuget.org/packages/Microsoft.Bot.Builder.Azure/ 

Your latency can also be compromised by round-trips to LUIS.  So start with your bot and figure out the latency for your bot.  (Easy way of testing is to have a special word like "ECHOME" which the bot simple replies back with without using any language understanding etc.  That will give you a sense of overall transport latency.  Anything that takes longer is because of secondary services or logic inside of your bot.

**Comment by jameslew** [comment]
Closing due to no response.  Feel free to create a new issue as appropriate if you're still experiencing the problem.
