### ISSUE TITLE
[Question] Cancel PromptDialog after certain time

### ISSUE THREAD

**Issue by initions-wiebe** [Microsoft/BotBuilder#2102]
Hey,
I have a question about cancelling a prompt or a dialog if there is no input from the user within a certain period of time. I need a way to somehow have a time out within a PromptDialog.

Example:
Bot prompts the user: "How old are you?".
The Bot now awaits a response from the user, but the user never response and the bot is still waiting.
In my case the bot should only wait 20 seconds and then close the dialog. Is the `CancellationToken `or a timeout implementation in the `HandleSystemMessageAsync` Method any helpful for that purpose and how would I implement that for a prompt?
Thank you for any ideas!

**Comment by zxed** [comment]
Do not mean to hijack - but your question is similar to mine. I'd like to cancel the dialog.

Lets say "something" (timer, event, api) kicked off the dialog - and the dialog is pushed onto the stack; its prompted the user for a response.
Now the user doesnt respond - and over time, another timer/event/api is kicked of.

This ends up pushing another dialog onto the stack.

Now this might answer the op's question - but would the following, pop all dialogs of stack?


`using (var scope = DialogModule.BeginLifetimeScope(Conversation.Container, message))
            {
                var botData = scope.Resolve<IBotData>();
                await botData.LoadAsync(CancellationToken.None);
                var stack = scope.Resolve<IDialogStack>();
                stack.Reset();
.....`

**Comment by nwhitmont** [comment]
@initions-wiebe We have released some major upgrades to BotBuilder recently at //Build. Are you still experiencing the issue after upgrading to [BotBuilder 3.8.1](https://www.nuget.org/packages/Microsoft.Bot.Builder/)?

**Comment by Stevenic** [comment]
So the cleanest way to achieve this is to timeout the bots entire conversation state... No matter what you need to wait for the users next message to determine if it's been more then 20 seconds since you prompted them (although I'd personally give them like 20 - 30 minutes.) 

There's no great way for your bot to know where exactly the user is conversationally with the bot so my recommendation is to create a conversation state property called `lastMessageTime` or something which you check and then set at the begging of every turn with the user.  When the turn starts, read this property and if its either missing or less then your timeout value simply set it to be the current time and then route the users message as you normally would.  If the time stamp has expired then clear the current conversation state by calling `ConversationState.deleteAsync()` and then set it to be the current timestamp.
