### ISSUE TITLE
How to call another dialog using same activity ??

### ISSUE THREAD

**Issue by lonche** [Microsoft/BotBuilder#2110]
```
[LuisIntent("test")]
        public async Task test(IDialogContext context, IAwaitable<IMessageActivity> argument, LuisResult result)
        {
            await Conversation.SendAsync(context.MakeMessage(), () => SimpleFacebookAuthDialog.dialog);
        }
```

I tried this. But the problem occurs when i try to send simple string message 

` await context.PostAsync("msg");`

 from SimpleFacebookAuthDialog. It throws an exception

>  The data is changed.

Some help ?

**Comment by ejadib** [comment]
The question was addressed in [StackOverflow](http://stackoverflow.com/questions/41847737/how-to-call-another-dialog-using-same-activity).

**Comment by lonche** [comment]
Yes. I solve that but now how to forward result into handler method ?
This is original question : 
 https://github.com/Microsoft/BotBuilder/issues/1477

**Comment by ejadib** [comment]
The problem here is that you are copy/pasting code from everywhere instead of stopping the ball and try to learn the core concepts involved. Otherwise, you will keep asking questions no matter how many times I unblock you :). So my advice here is: the Facebook sample was just an example on how to solve OAuth; you might not have to use it as; and instead you might have to create a proper dialog instead of using chain. Also, my reco is to not duplicate questions here and in StackOverflow; it makes harder things.

**Comment by lonche** [comment]
I can't clone this authbot.

**Comment by ejadib** [comment]
Is a public repo... you should be able to clone it fine.

**Comment by lonche** [comment]
I cloned it. Thank you ejadib.

**Comment by msft-shahins** [comment]
@ejadib thanks for the help. Closing this since the question have been addressed.
