### ISSUE TITLE
NodeJs Prompts.confirm is not rendered as buttons for skype channel

### ISSUE THREAD

**Issue by hardsky** [Microsoft/BotBuilder#2127]
I used this snippet for confirm question

`builder.Prompts.confirm(session, 'label_from_locale_file');`

It's rendered as question + buttons for telegram and facebook, but rendered without buttons for skype.
I can add buttons if I directly set style as

`builder.Prompts.confirm(session, 'label_from_locale_file', {listStyle: builder.ListStyle["button"]});`

I guess, it would be more expected if it's rendered as buttons on all channels, that have such ability. What do you think?

**Comment by Stevenic** [comment]
This is by design. Buttons will only be used for channels that support quick replies or keyboard, like Facebook or Kik. You can force the use of buttons on skype although we recommend using caution when you do that. The issue is the user can press the button at anytime, even when your bot isn't listening for it to be pressed which can result in your bot doing something unexpected.
