### ISSUE TITLE
Custom fields with FormBuilder | Update broke this?

### ISSUE THREAD

**Issue by JPThorne** [Microsoft/BotBuilder#213]
**Context**: I'm attempting to hook into my LuisDialog from a FormFlow dialog, in the scenario where the users input doesn't match one of the FormFlow options for example. In this case I'd like to be able to check if the user is asking something other than what the current set of questions expects, and be able to handle giving them a response other than some version of "Not an option". 

I've implemented a custom field, based on this SO question: http://stackoverflow.com/questions/36361918/custom-fields-with-formbuilder-in-the-microsoft-bot-framework?rq=1 as well as this one: http://stackoverflow.com/questions/36438545/how-to-hook-luis-into-a-bot-framework-formdialog/36859323#36859323. 

**Problem**: Until updating to the latest release of the botbuilder, via nuget, I was successfully hitting my code in my custom field in overrides of Matches and Parse for example. However, now nothing is getting through to the custom fields overrides. 

**Questions**: 
- Has the update changed how we are able to derive from IRecognizer/RecognizePrimitive? 
- Are there any examples/samples of this type of functionality out there? 
- Will an easier way to jump from FormFlow dialogs to LuisDialogs be implemented in the future? 
- What is the timeline on this?

Any help much appreciated.

**Comment by chrimc62** [comment]
Looks like I broke this in the most recent release when I added the ability to dynamically define fields.  I will fix it in our next release.  Thanks for bringing it to our attention and sorry about that.

The reason we did not initially implement FormFlow sub dialogs is because of the inconsistency of supporting commands--i.e. if you had a sub dialog that didn't know anything about quit or help it would be weird from the user standpoint.  We have a more general solution to the problem of how dialogs fallback and we are actively working on that now.  When we finish that work, it should be much easier to do what you are doing.

**Comment by chrimc62** [comment]
If you need something quicker, you could also override        public virtual IPrompt<T> Prompt
 instead.  Just take the current _prompt and substitute your recognizer.

**Comment by chrimc62** [comment]
Actually simplest way in the current code is to dynamically define the field using SetDefine and put your SetRecognizer in there. I'm looking at how best to make this work if you explicitly specify in your form builder.  The issue is that with the new localization stuff about to come out you want to redefine recognizers that are based on value terms.  That means either SetRecognizer should take a closure, or explicitly specified recognizers will not pick up the change in ui culture.  In any case the dynamic solution works today and might be the best choice moving forward because of that issue.

**Comment by chrimc62** [comment]
OK, I have not made a change but I have added some documentation--you should do your SetRecognizer in your DefineAsyncDelegate for the reasons outlined above.  Let me know if that does not work for you for some reason.

**Comment by JPThorne** [comment]
Thanks, will give this a try!
