### ISSUE TITLE
invalid selection of promptchoice dialog for fb throwing error

### ISSUE THREAD

**Issue by jarmstrongnz** [Microsoft/BotBuilder#2141]
![screenshot 102](https://cloud.githubusercontent.com/assets/16697734/22450535/31e68d2c-e7cc-11e6-9807-aa5a741b61dd.png)

The attached error is thrown (and currently sent as a message to the user) when a PromptChoice is answered with a typed message, that does not contain one of the valid options.

This error occurs during the following part of the ResumeAfter<string> method

`var choiceResult = await result;`

Cheers,
Jonny

**Comment by willportnoy** [comment]
@msft-shahins is this related to the quick replies mapping?  or @craigjensen perhaps in the facebook connector?

**Comment by msft-shahins** [comment]
this is not related to the quick replies. I believe that you are not handling the [TooManyAttemptsException](https://github.com/Microsoft/BotBuilder/blob/8f0d6bbc1ef0fcef99b04560391384aba8fcde15/CSharp/Library/Microsoft.Bot.Builder/Dialogs/Exceptions.cs#L128) returned by PromptDialog, since ``Hey`` is not a valid response for the [PromptDialog.Confirm](https://github.com/Microsoft/BotBuilder/blob/3a98a6b3d15962a57b5454bfb3f730d3588de3ef/CSharp/Library/Microsoft.Bot.Builder/Dialogs/PromptDialog.cs#L296)

you can fix it by handling the exception instead of returning it to user: 

```csharp
try
{
    var choiceResult = await result;
}
catch(Exception)
{
///handle the error here.
}
```
