### ISSUE TITLE
Calling proactive conversation with WebChat

### ISSUE THREAD

**Issue by arieschwartzman** [Microsoft/BotBuilder#2149]
I'm able to start a dialog proactively by calling 
bot.beginDialog(address, dialog, params, function(){
});
It works in Skype.
In WebChat I get this error:
Request to ‘https://webchat.botframework.com/v3/conversations‘ failed: [405] Method Not Allowed

Thanks

**Comment by dandriscoll** [comment]
Hi @arieschwartzman, the API error is occurring because the bot is trying to create a new conversation, which Web Chat does not support (because there is no way to open a web browser for a user).

The correct behavior is for the SDK to send the message on an existing conversation.

Does your address object contain a `conversation` property?

**Comment by arieschwartzman** [comment]
Yes, I remove the conversation property just before calling the API. If I would leave the conversation for this channel and have the webchat window opened, will it work?

**Comment by dandriscoll** [comment]
Probably, although I don't know enough about that part of the SDK to say for sure.

**Comment by arieschwartzman** [comment]
I tried and it works.

**Comment by arieschwartzman** [comment]
I have another question Dan. Let me use the same thread please. 
I want to start a specific dialog once the webchat starts without typing anything.  Can I do that?

**Comment by dandriscoll** [comment]
Not at the moment, but you could request it over at the Web Chat repo: https://github.com/Microsoft/BotFramework-WebChat

**Comment by msft-shahins** [comment]
Closing this issue since it is resolved. Feel free to open a new issue for further issues that you might have.
