### ISSUE TITLE
CUSTOMIZE DEFAULT WEB CHAT

### ISSUE THREAD

**Issue by sayyednazeer** [Microsoft/BotBuilder#2153]
Can i customize the default web chat like its color and also can i add some more controls inside it..??

**Comment by eanders-MS** [comment]
Hi @sayyednazeer, Some basic customization of the IFRAME-embedded control is on our feature roadmap, but not yet available.

In order to customize WebChat: You must serve the control from your own site so that you have full reign to modify the CSS to your liking. [This page](https://github.com/Microsoft/BotFramework-WebChat#3-decide-how-to-run-webchat) covers the different hosting scenarios, including the topic of serving the WebChat control from your own site.

In order to add more controls to WebChat: You'll need to fork or clone the project's [GitHub repo](https://github.com/Microsoft/BotFramework-WebChat), make the necessary source code changes, and serve the control from your own site as in the previous paragraph.

**Comment by sayyednazeer** [comment]
Thanks for the information @eanders-MS
