### ISSUE TITLE
Change option to list bot in directory after it's been reviewed

### ISSUE THREAD

**Issue by wacton** [Microsoft/BotBuilder#2159]
Hi,

We submitted and had our bot reviewed recently. 
During the submission process we choose not to list the bot in the directory after it's been reviewed. Assuming we'll be able to change this later. I've had a look and can't find anywhere to change it.

Could somebody please point me in the right direction?

**Comment by Andrea-Orimoto** [comment]
Hi @wacton,

the only way to do that right now is to un-publish it, and then resubmit.
Let me know when you have resubmitted your bot, so that I can re-review and approve it. Send me the bot handle.
We're working to significantly improve the submission/review process in the future.

Thanks and sorry for the inconvenience.
Andrea

**Comment by wacton** [comment]
Hi @Andrea-Orimoto ,

Thank you! 
I've unpublished and republished the bot. 
The bot Id is AppsForOpsBot.

No inconvenience, thanks for the help.

Wayne

**Comment by Andrea-Orimoto** [comment]
Hi @wacton,

your bot has been approved again, let us know if you need anything else.

Closing this issue, feel free to re-open or create a new one if you still have issues.

Thanks
Andrea
