### ISSUE TITLE
IIS Application Pool Best Configuration Practices to publish Bots

### ISSUE THREAD

**Issue by Badolfo** [Microsoft/BotBuilder#2166]
Hi,

can you give some website as a reference or provide some specific guidance for IIS application pool best  configuration to publish Bot apps, like:

Idle Time-out
Load User profile
Recycling Regular Time Interval

Feel free to alert regarding other parameters that I should be aware. 
Thanks in advance.

**Comment by msft-shahins** [comment]
@willportnoy can you comment and provide some guidance?

**Comment by willportnoy** [comment]
Since the bot builder stores state outside of the web service

https://docs.botframework.com/en-us/technical-faq/#where-is-conversation-state-stored

the IIS web worker process should be stateless, so you don't need to configure any sorts of state-full session stores.

We generally don't have any recommendations for configuring IIS that are specific to bots.  Periodically recycling the app pools seems like good hygiene and timing out unused connections seems reasonable (though we'd expect a fair amount of connection reuse because it's primarily the Bot Framework connector service that posts to the bot's web service).

**Comment by Andrea-Orimoto** [comment]
Assuming @willportnoy's reply answered the question, if not feel free to reopen the issue. Thanks!
