### ISSUE TITLE
PromptDialog.Choice in StartAsync sends 2 messages

### ISSUE THREAD

**Issue by robertbaumann** [Microsoft/BotBuilder#2182]
I am writing a bot that needs to proactively message the user. When ConversationUpdate fires, we want to do this:

await Conversation.SendAsync(activity, () => new IntroDialog());

In the IntroDialog's StartAsync method, the bot should do this:
                var flowChoices = (IEnumerable<FlowChoices>)Enum.GetValues(typeof(FlowChoices));
                PromptDialog.Choice(context, FlowChoiceResult, flowChoices,
                    "Welcome. I can support these actions, which would you like?",
                    descriptions: FlowChoiceDescriptions);

However, the Prompt is being sent twice to the user in this case. Can you advise on the proper pattern to start a PromptDialog.Choice in the StartAsync of a proactive bot?

**Comment by msft-shahins** [comment]
Some channels, for example webchat and emulator, send 2 ConversationUpdate activity to the bot. One has the user in the MembersAdded field and the other one has the Bot itself in the MembersAdded field. Also when you start the PromptDialog in the StartAsync, you are pushing a new dialog to the stack without having the stack consume the new incoming activity posted to it. As a result the new PromptDialog added to stack will try to consume the incoming ConversationUpdate activity that is posted to stack. but it will fail since there is no valid choice posted to it and will reprompt with the DefaultRetry which is the prompt itself for the PromptDialog.Choice when you don't provide a retry message. 

Given above, you might see 2 or 3 prompts generated when ConversationUpdate acitivties posted to the bot depending on the channel. 

To fix this, you can follow the pattern below: 

```csharp

// the controller
[BotAuthentication]
public class MessagesController : ApiController
{
    /// <summary>
    /// POST: api/Messages
    /// receive a message from a user and send replies
    /// </summary>
    /// <param name="activity"></param>
    [ResponseType(typeof(void))]
    public virtual async Task<HttpResponseMessage> Post([FromBody] Activity activity)
    {
        if (activity != null)
        {
            if (activity.GetActivityType() == ActivityTypes.ConversationUpdate)
            {
                IConversationUpdateActivity update = activity;
                //remove bot from the members added
                update.MembersAdded = update.MembersAdded.Where(member => member.Id != update.Recipient.Id).ToList();

                if (update.MembersAdded.Count == 0)
                {
                    return new HttpResponseMessage(System.Net.HttpStatusCode.Accepted);
                }
            }
            await Conversation.SendAsync(activity, () => new IntroDialog());

        }
        return new HttpResponseMessage(System.Net.HttpStatusCode.Accepted);
    }
}

// the intro dialog
[Serializable]
public class IntroDialog : IDialog<object>
{
    public async Task StartAsync(IDialogContext context)
    {
        context.Wait(MessageReceivedAsync);
    }

    public virtual async Task MessageReceivedAsync(IDialogContext context, IAwaitable<IActivity> argument)
    {
        var activity = await argument;

        switch (activity.Type)
        {
            case ActivityTypes.ConversationUpdate:
                var flowChoices = (IEnumerable<FlowChoices>)Enum.GetValues(typeof(FlowChoices));
                PromptDialog.Choice(context, FlowChoiceResult, flowChoices,
                "Welcome. I can support these actions, which would you like?");
                break;
            case ActivityTypes.Message:
                var message = activity as IMessageActivity;
                await context.PostAsync($"You said {message.Text}");
                context.Wait(MessageReceivedAsync);
                break;
            default:
                context.Wait(MessageReceivedAsync);
                break;
        }
    }

    public async Task FlowChoiceResult(IDialogContext context, IAwaitable<FlowChoices> argument)
    {
        await context.PostAsync($"You selected {await argument}");
        context.Wait(MessageReceivedAsync);
    }
}

```
