### ISSUE TITLE
Question about using bot.beginDialog

### ISSUE THREAD

**Issue by michaelvol** [Microsoft/BotBuilder#2206]
Hi,

I have the following situation.
I start some prompt, waiting for user to send an attachment. This can take a while as he needs to put some time to prepare it.
At the same time, I have an out-of-band dialog spawned to the user. In my case it's caused by some external trigger (but it can also be setTimeout).
I want the user to answer the OOB question and then return to the previous dialog which waits for his attachment.

I start the OOB dialog using bot.beginDialog. 
It loads an empty session stack (which is ok for me), but then it stores it back and overwrites the user's original stack.
The result is that when the user eventually submits his attachments it's not caught by the waiting dialog...

AFAIU, when starting a dialog using bot.beginDialog, dispatch is called with newstack=true, which explains the situation. 

What's the correct way to implement my scenario...?
Should I use the newly introduced bot.loadSession(....) and then session.beginDialog() ... ? 

Thanks!

**Comment by Stevenic** [comment]
@michaelvol yes... I was just about to suggest that you use the new `bot.loadSession()` method as you describe. This will let you push a dialog onto the stack... 

The one thing to note is that you can still only have a single stack per conversation so that means the bot can only be waiting on one thing at a time (at least from a stack perspective.) If you start your proactive dialog and the user sends an attachment it's going to be missed because the bot is waiting for the user to reply to the proactive dialog. There is a way to listen for multiple things simultaneously though...

The better way to solve this problem is to try and flatten your bot out such that instead of using the stack to wait for a users reply, use a combination of recognizers and trigger actions.  Let me explain... You can create a custom recognizer that listens for a attachment to be uploaded and raises the AttachmentUploaded intent anytime it detects the user has sent an attachment.  You can then use a `triggerAction()` to automatically start a dialog to handle that attachment when its received.  What's nice about that is it doesn't matter where the user is conversationally with the bot. They can be in the middle of replying to your proactive dialog and if the bot receives an attachment it will be handled upon receipt.

**Comment by michaelvol** [comment]
@Stevenic Thanks! Will try that soon in our next version. Will update how it goes.

**Comment by Stevenic** [comment]
Cool. I'll close this for now but feel free to add comments.
