### ISSUE TITLE
New channels:  Viber, VK.com

### ISSUE THREAD

**Issue by Arimov** [Microsoft/BotBuilder#2219]
It would be great if you could add to the list of supported channels such as **Viber** and **VK.com**
(and Whatsapp when they open API)

**Comment by Andrea-Orimoto** [comment]
Hi @Arimov, great suggestions, we've added to our backlog for future consideration. No timeline at this point. Closing this issue for now, but feel free to reopen if needed. Thanks!

**Comment by SychevIgor** [comment]
Looks like nobody care about viber, because simula request were closed 5 times during last 2 years.
https://github.com/Microsoft/BotBuilder/issues/2495
https://github.com/Microsoft/BotBuilder/issues/2429
https://github.com/Microsoft/BotBuilder/issues/2219
https://github.com/Microsoft/BotBuilder/issues/2123
https://github.com/Microsoft/BotBuilder/issues/1917

**Comment by SychevIgor** [comment]
Still very interesting connector, especially after telegram was blocked in Russia.
