### ISSUE TITLE
Maximum number of intents?

### ISSUE THREAD

**Issue by mikob** [Microsoft/BotBuilder#2239]
The documentation used to state that there was a 20 intent limit. This has apparently been raised recently as people are able to create 40+ intents. What is the new limit? Can we document it in the help?
#1160

**Comment by jameslew** [comment]
It was recently updated to 80 intents.  Yes, we need to update our documentation; we're a little behind on that front.  Thanks!

**Comment by MohammedAbdulMateen** [comment]
Hey!, check this out https://docs.microsoft.com/en-in/azure/cognitive-services/luis/luis-boundaries
The limit for intents was raised from 80 to 500 that is a massive improvement hurray! 🥇 

Please check the mention link for the limits on other things as well such as entities, I recommend to go with a single LUIS app and a single LuisDialog instead of choosing a top level (RootDialog) and multiple child level dialogs or the factory pattern for finding the best fit intent method from a number of LuisDialogs until unless you are about/near to reach the limit, when you are about to reach the limit only then think of the design changes, don't overcomplicate from the beginning itself and try to focus on the development, that's what I would suggest :)

Happy coding!
