### ISSUE TITLE
[Question] need full control about sended text

### ISSUE THREAD

**Issue by pmizel** [Microsoft/BotBuilder#2241]
need to suppress ressource texts and use own retrytexts in dialogs.

**Comment by nwhitmont** [comment]
@pmizel are you using C# or Node SDK? Can you provide a code example demonstrating your issue?

**Comment by nwhitmont** [comment]
@pmizel if you're still experiencing the issue, reopen this issue. 

For more information on sending and receiving messages, [check out this guide](https://docs.botframework.com/en-us/core-concepts/messages/#navtitle)

## Environment

* Operating System: 
  * Windows
  * macOS
  * Linux
* SDK Platform:
  * C#/.NET
  * Node.js
* SDK version:
* Development environment:
  * localhost
  * Azure Web App
  * Azure Bot Service App
  * other
* If you are using the Node.js SDK:
  * Node.js version:
  * NPM version: 

## Issue

What the issue is, in broad strokes. Link to [Stack Overflow](http://stackoverflow.com/search?q=%23botframework) post.

## Example Code

The code snippet or complete bot example (preferred) that demonstrates the issue.

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

What you expected to happen.

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

**Comment by nwhitmont** [comment]
@pmizel reopen if you're still experiencing this issue
