### ISSUE TITLE
Tables and Markdown

### ISSUE THREAD

**Issue by jakobpn** [Microsoft/BotBuilder#225]
Are there any plans to support tables created with markdown?

**Comment by tomlm** [comment]
Our markdown parser supports tables and our text renderer will render char formatted rendering of tables

The problem is that only Html Bodies of emails supports tables, all other channels use variable width fonts and unknown width and so it is impossible for us to render it.

Until channels give us fixed width fonts and or consistent sizes we can’t really support it.

-Tom

**Comment by jakobpn** [comment]
Thx Tom!
