### ISSUE TITLE
Source code for the WebChat

### ISSUE THREAD

**Issue by DavePilks** [Microsoft/BotBuilder#229]
Is it possible to get the source code for the WebChat that is hosted in the iFrame when the bot starts up?

the one that gets hosted here : 

https://webchat.botframework.com/Dev/

**Comment by JPThorne** [comment]
+1 to this please. We'd need the html/css/js etc. and the capability of pointing the JS library for the chatbot to the relevant hosting server.

**Comment by dandriscoll** [comment]
Great suggestion! Moved to our feedback page, here: https://feedback.botframework.com/forums/354219-bot-connector/suggestions/13786374-open-source-the-web-chat-control

**Comment by retailhal** [comment]
This issue seems to be closed without resolution - is it possible to get this client code?

**Comment by DavePilks** [comment]
if it is ok with @dandriscoll I have the source for the V1 version. It wont work with a V3 bot but its a starting point

**Comment by retailhal** [comment]
Great I will take anything to start as a base - the latest live version seems to work on V3 though - so that would be ideal if possible.
Is it not public/gitbub at the moment?  Any reason why? Microsoft has been awesome at releasing code to public domain these days so it surprises me why not.

Thanks Dave

**Comment by retailhal** [comment]
Hi guys,
Any update on whether this code can be released or I can get a copy of it?

**Comment by sebnema** [comment]
Hi, My customer wants to see the code, because of security compliance. Any update on this?

**Comment by dandriscoll** [comment]
Hi @sebnema, we haven't published the code for this control yet, but it is coming soon. We'll make an announcement when we do.

**Comment by retailhal** [comment]
This is now available here: https://github.com/microsoft/botframework-webchat

**Comment by sebnema** [comment]
@dandriscoll When I checked the code, It seems webchat is still dependent on the dirrectline api, Is that correct? https://github.com/Microsoft/BotFramework-WebChat/blob/master/src/directLine.ts

If yes, That means we still have security compliance issue due to whole conversation will pass through DirectLine Api. Is there a plan to release source code?

I am trying to avoid an architecture like this.
![hybridbotcommunicationdiagram](https://cloud.githubusercontent.com/assets/10426499/21482260/19b3daac-cb7a-11e6-8019-85a00e11076b.jpg)
Thanks
