### ISSUE TITLE
How to have multiple LuisDialogs

### ISSUE THREAD

**Issue by chris31389** [Microsoft/BotBuilder#2296]
Hi,

I'm working on a large project where there will be hundreds of intents.  I want to be able to create new LuisDialogs and chain them together so that if the first LuisDialog have an attribute that matches the intent name, then it passes to the next LuisDialog.  The final LuisDialog would have the "None" intent.

Is this possible?

**Comment by andradedearthur** [comment]
Could you clarify a bit more? Do you mean chain multiple LuisDialogs or multiple LUIS Models? I'm also interested in something like this (using multiple LUIS Models to get around the 80 Intents per Model limit we have so far). 

I did some tests and wasn't able to achieve this, however when I did my tests I didn't use LuisDialog's, since I would need to check multiple LuisModels I wrote my own code to get a user utterance and check that utterance against multiple LUIS Models. 

The main problem as far as my tests went is the collision between intent's from different models, as the models have no knowledge of each other. Let's say a utterance it's checked against Model A and get's a 70% score, matching the correct intent in Model A, than that utterance it's checked against Model B, where there isn't a related intent, however LUIS could give a 80% score to a random intent within that model. (I don't know if I was able to properly explain the problem.)

This maybe could be solved with extensive training, however if you have hundreds of intents, I think the kind of training to solve this issue would be massive. In my case I gave up in doing anything like this using LUIS. 

Maybe using another service, like IBM Watson's Conversation API could be something that's worth look into for you. I haven't looked into it because this was an issue for me when LUIS limit was 20 intents, and so far I haven't needed anything close to the current 80 intents. But the IBM Watson's Conversation API provides the capability to 2.000 Intents.

**Comment by chris31389** [comment]
To clarify, I want to use the same LUIS Model, but I want to have different LUIS Dialogs classes.  Ideally so that I can adhere to the Open Closed Principle.  If we get a new requirement I don't want to have a monster class I need to update, id rather have a something that knows about all the LUIS Dialogs and can work out which Dialog to use based on the intent attribute.

**Comment by willportnoy** [comment]
I believe IDialogStack.Forward was added for reuse of dialogs (often LUIS dialogs):

https://docs.botframework.com/en-us/technical-faq/#what-is-idialogstack-forward-in-the-c-builder-sdk

**Comment by willportnoy** [comment]
I'm going to close this issue for now, but feel free to open a new issue for further discussion.
