### ISSUE TITLE
Using environment variables to specify the LuisModel attributes

### ISSUE THREAD

**Issue by adamgilmore** [Microsoft/BotBuilder#2297]
Hi,

I want to store the LuisModel attributes (ModelId and SubscriptionKey) in environment variables. Is this possible? I've looked for a LuisDialog source code and it looks like the only way is to override the MakeServicesFromAttributes method? 

Maybe this is a feature request to make it easier to implement?

Thanks,
adam

**Comment by willportnoy** [comment]
We're happy to take a pull request - I think you'd want to change LuisDialog to look for any attribute that implements the ILuisModel interface, and then you could supply whatever sort of logic you'd like for finding the keys.

But yes, otherwise, you'd have to override the MakeServicesFromAttributes method or just pass the instantiated ILuisServices into the LuisDialog constructor.

**Comment by willportnoy** [comment]
I'm going to close this issue for now, but feel free to open a new issue for further discussion.
