### ISSUE TITLE
[Feature Request] Allow bot to redirect to human agent?

### ISSUE THREAD

**Issue by SP00499532** [Microsoft/BotBuilder#2303]
The user has some query which the bot cannot answer or it doesn't have an answer to that. In that case the bot has to seek help of some assistant and redirect the question directly to that assistant and the assistant gets the question directly on his number.

**Comment by ankitbko** [comment]
Are you referring to "Agent Transfer"/"Live Chat" feature, where bot redirects to a human agent?

**Comment by Stevenic** [comment]
We've been calling this human handoff and we have some pieces needed to implement it in place but still need to add other pieces.  Which version of the SDK, Node or C#, are you using?

**Comment by carlosscastro** [comment]
@SP00499532 Which version of the SDK are you using? that is, Node or C#?

**Comment by ankitbko** [comment]
@Stevenic That's great. I had also implemented the human handoff in one of the project. I was thinking about writing a blog about how to do it.
Which pieces are you referring to (I may have missed the commit)? I am using C#.

**Comment by Stevenic** [comment]
@ankitbko the pieces added were on the Node side of things. We recently added a new `bot.loadSession()` method which lets you manage two sessions for proxying messages back and forth.

**Comment by cesarvarela** [comment]
@Stevenic any example of how to get the handoff working (I'm working with node.js)?

If is not ready, something that allows us to at least get the bot to ignore the user would be good for a POC too, we can send the message from outside of botbuilder.

**Comment by Stevenic** [comment]
@cesarvarela this is a really broad topic. What I added was the piece needed to load multiple sessions. So all the pieces needed to do handoff properly should be there. Here's a couple of additional pieces that would probably need to be added:

- `ConferenceDialog` to bridge the session between the user and agent. This dialog would keep the user in a queue while waiting for the agent and then once the agent joins it would relay messages between the two users. This is the biggest piece of code that needs to be wrote,
-  Custom `Recognizer` to disable recognizing random intents while in the bridge. You need this because you don't want the user saying something that causes the bot to randomly do something in response to a user message.  You can just wrap your bots recognizer with a custom recognizer that conditionally calls the other recognizer(s). You can also filter the intents allowed to return using a similar approach.

If you need to interface with a custom chat system for communicating with agents then you could do so by implementing a new custom `Connector`. Look at the `ConsoleConnector` for an example of this.

**Comment by ankitbko** [comment]
@Stevenic Very similar to what I was thinking. I was thinking of using `Scorable` in .net to intercept message to bot and transfer to agent. Couple of points I would like to discuss - 

- For the scenario when agent is not available, what is the best practice? In my case, if agent is not available I was just returning appropriate response to user to check back later and not have him wait in a queue. The reason being, due to inherent nature of chats, user may not be active at the time agent is available. He may have closed his browser, working on something else or crossing the road etc. In later stage, I may implement proactively sending message to bot of notifying him of agent availability. What do you think?

- Another question is when (and at what trigger) do you move out of "agent handover" scope and back to normal bot flow? If agent wants to disconnect, I could just send another event to stop the routing. But allowing user to stop the conversation seems tricky. Any suggestions?

**Comment by ankitbko** [comment]
@Stevenic @SP00499532 I wrote a blog post on how to perform human handoff in .Net - https://ankitbko.github.io/2017/03/human-handover-bot/

Source code - https://github.com/ankitbko/human-handoff-bot

**Comment by nwhitmont** [comment]
@ankitbko Thanks for sharing this article and code example!
