### ISSUE TITLE
Question: when Viber channel is coming?

### ISSUE THREAD

**Issue by AlexSenchenko** [Microsoft/BotBuilder#2429]
Hi,

Could you please tell when support for Viber channel is scheduled?

Thanks!

**Comment by Andrea-Orimoto** [comment]
Hi @AlexSenchenko, we currently have no plans for this, but I've added it to our backlog for future consideration. Thank you!

**Comment by AlexSenchenko** [comment]
@Andrea-Orimoto and @carlosscastro 
I have questions regarding this:

1)  Do you have a public road map with vote buttons where I can press vote to impact on this issue
2)  Will you accept pull request if I am implement it my self and what I need to look first for it.

Thanks

**Comment by SychevIgor** [comment]
Looks like nobody care about viber, because simula request were closed 5 times during last 2 years.
https://github.com/Microsoft/BotBuilder/issues/2495
https://github.com/Microsoft/BotBuilder/issues/2429
https://github.com/Microsoft/BotBuilder/issues/2219
https://github.com/Microsoft/BotBuilder/issues/2123
https://github.com/Microsoft/BotBuilder/issues/1917

**Comment by SychevIgor** [comment]
Still very interesting connector, especially after telegram was blocked in Russia.
