### ISSUE TITLE
Help Required - Luis Entity Recognize Error - Reg.

### ISSUE THREAD

**Issue by giriganapathy** [Microsoft/BotBuilder#2436]
Hello Team,

I am facing an issue where it says  "Oops. Something went wrong and we need to start over."  Looks like some error on the server side code.  And it is happening the moment I make a call to Luis:
builder.LuisDialog.recognize(session.message.text, modelUri, function (err, intents, entities) {

Could you please help me, what should I do to come out from this error.  

Here are my bot details:
Bot Id: VZChatBotAgent
Luis Url: 
var model = "https://westus.api.cognitive.microsoft.com/luis/v2.0/apps/588f2ecf-6889-42a9-9e42-6e345e692543?subscription-key=b27a7109bc1046fb9cc7cfa874e3f819&verbose=true&q=";

var modelUri = "https://westus.api.cognitive.microsoft.com/luis/v2.0/apps/588f2ecf-6889-42a9-9e42-6e345e692543?subscription-key=b27a7109bc1046fb9cc7cfa874e3f819&verbose=true";

Its a node js code.

Thanks in advance.

Regards,
Giri G.

**Comment by mgbennet** [comment]
You can see a proper error report in the console window you're running node in; in this case it will say `TypeError: builder.LuisDialog.recognize is not a function`. In your context, the fix is `builder.LuisRecognizer.recognize(session.message.text, modelUri, function(err, intents, entities)  { ... });`

Also, best practice is to keep your Luis endpoint URL private, as you are limited to 10000 endpoint hits per month.

**Comment by giriganapathy** [comment]
Thank you mgbennet, your suggestions resolved my issue.  Thanks.
