### ISSUE TITLE
reloadAction is not restarting the dialog on the second call (node)

### ISSUE THREAD

**Issue by amitbend** [Microsoft/BotBuilder#2447]
Hi, I'm using `reloadAction` on a dialog inside a library.
when i hit it the first time it's working just fine, but it always fails on the second time - it just won't reload the dialog.

I added a `onSelectAction` option to track the argument, and it does invoked on the second time as well. 
also args and dialogStack looks the same on both times.

It also seems like after it fails, the dialog is being changed to the root dialog (outside of the library)

- I do not get any error message

- It used to work fine in older versions.

**Comment by mgbennet** [comment]
Hi Amit, could you give us some code that's doing this? It's hard to reproduce with just a description of it.

**Comment by nwhitmont** [comment]
@amitbend are you still experiencing the problem? If yes, can you provide some additional details, for example:

## Environment

* Operating System: 
  * Windows
  * macOS
  * Linux
* SDK Platform:
  * C#/.NET
  * Node.js
* SDK version:
* Development environment:
  * localhost
  * Azure Web App
  * Azure Bot Service App
  * other
* If you are using the Node.js SDK:
  * Node.js version:
  * NPM version: 

## Issue

What the issue is, in broad strokes. Link to [Stack Overflow](http://stackoverflow.com/search?q=%23botframework) post.

## Example Code

The code snippet or complete bot example (preferred) that demonstrates the issue.

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

What you expected to happen.

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.
