### ISSUE TITLE
[Question] Using bot services without directline 

### ISSUE THREAD

**Issue by rakeshkeerthi** [Microsoft/BotBuilder#2448]
Hi, 

I'm making a website with a chat bot in it, and currently we are using bot services with LUIS and Qna maker service. And in the current scenario we are interacting with it using the directline api. But I'm really sorry to say that, we are very disappointed with the service, it is very slow, the average response time per message is 8-10 seconds, this is after me eliminating, the secret to token conversation and refresh token parts. I want to know how can I communicate with the bot service without using the Directline api. I searched a lot but everything points me back to the emulator, but here o want to check in my chat window... Can someone please let me know how can I do this. 

If I can find a way to optimize the time to 2-3 seconds(ain't sure if this is possible), nothing would be more greatful than this. 

One more thing, ain't using c# or node.js, I'm using just the plain old js(this is getting my job done in case if directline api) 
Thanks, 
Keerthi

**Comment by ivmos** [comment]
You mean "the average response time per message is 8-10 seconds" because you need to poll N times, right? If so, not so much but also worried about the polling approach, not sure if times improve with websockets. And not sure about imolementing websocket as I'm integrating server to server and feels weird maintaining a websocket during X time after sending a message. I would prefer a bidirectional api instead of that websocket approach so that I can configure the endpoint MS should send messages to.

**Comment by nwhitmont** [comment]
@rakeshkeerthi are you still experiencing the above reported latency problem with directline?  If yes, can you provide some additional details about your environment & issue?

## Environment

* Operating System: 
  * Windows
  * macOS
  * Linux
* SDK Platform:
  * C#/.NET
  * Node.js
* SDK version:
* Development environment:
  * localhost
  * Azure Web App
  * Azure Bot Service App
  * other
* If you are using the Node.js SDK:
  * Node.js version:
  * NPM version: 

## Issue

What the issue is, in broad strokes. Link to [Stack Overflow](http://stackoverflow.com/search?q=%23botframework) post.

## Example Code

The code snippet or complete bot example (preferred) that demonstrates the issue.

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

What you expected to happen.

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

**Comment by nwhitmont** [comment]
We recommend using the Direct Line client as it is the officially supported method of interacting bots outside WebChat.  You can learn more about the DirectLineJS client here: https://github.com/Microsoft/BotFramework-DirectLineJS
