### ISSUE TITLE
/api/conversations stop working sine 5/9

### ISSUE THREAD

**Issue by eddie1976** [Microsoft/BotBuilder#246]
No conversationId return after HTTP Post

**Comment by wbreza** [comment]
Seeing similar.  Used to return a 200, now returns a 201, but the DirectLine SDK expects 200 response and therefore is failing the request.

**Comment by wbreza** [comment]
Workaround until they either update the SDK or revert back to returning a 200.

```
try
{
    return await this.directLineClient.Conversations.NewConversationAsync();
}
catch (HttpOperationException ex)
{
    if (ex.Response.StatusCode == HttpStatusCode.Created)
    {
        var conversationJson = await ex.Response.Content.ReadAsStringAsync();
        var conversation = Microsoft.Rest.Serialization.SafeJsonConvert.DeserializeObject<Bot.Conversation>(conversationJson);
        return conversation;
    }

    throw;
}
```

**Comment by ahmettaha** [comment]
I just started having the same problem

**Comment by eddie1976** [comment]
Each conversation on the Direct Line channel must be explicitly started using a POST to the https://directline.botframework.com/api/conversations endpoint. If the call was authorized with a token, the conversation ID is the conversation ID in the scoped token. If a secret was used to start the conversation, the conversation will be started with a new, random ID.

The client may send messages to the bot by calling POST on https://directline.botframework.com/api/messages/conversationId.

**Comment by ahmettaha** [comment]
Are you referring to NewConversationAsync returning 201 instead of returning 200?

**Comment by eddie1976** [comment]
I got 201.

**Comment by ahmettaha** [comment]
ok. so what changed from last week. Last week same code was working and was returning 200. Now, it got broken because it is returning 201. Does this mean, DirectLine Api was changed but the nuget library hasnt updated yet?

**Comment by dandriscoll** [comment]
We just pushed out a new release of Direct Line but this broke older clients so I've changed it to return 200 in all cases. Existing clients should work with it for now. If we change its behavior in the future, we'll upgrade the Nuget package before changing the service.

**Comment by wbreza** [comment]
@dandriscoll  This type of change should be treated as a breaking change and versioned appropriately.  Take the BotConnector API as an example it has a versioned interface.  You guys should consider adopting a similar design practice for the DirectLine API.

Saying you'll update the Nuget package in the future will not solve this type of problem since people that have a dependency on the old Nuget package would still be negatively impacted.

**Comment by dandriscoll** [comment]
Sure, good suggestion. Thanks

**Comment by whatsdis** [comment]
I started noticing my bot stopped working and so I did an update to the latest version of Bot Framework and now it won't compile, everything is broken.

**Comment by wbreza** [comment]
@dandriscoll To be fair there have been breaking changes introduced that do not conform to standard semantic versioning which Nuget adheres to.  On the flip side I also understand that the bot framework is technically still in "preview" mode and that you guys are still finalizing the APIs.

I have also been bit in the recent past when I updated the Nuget packages which appears to only introduce minor version changes but actually included breaking API changes.

**Comment by whatsdis** [comment]
so how do we fix this? https://github.com/Microsoft/BotBuilder/issues/403

I don't even know what to do now, if I update the nuget package to the latest version my project won't even compile. 

I'm not sure what the error message is talking about since I explicitly include conversationId and userId in my urls.

**Comment by whatsdis** [comment]
@wbreza I see you posted a workaround where do I put that code?

**Comment by wbreza** [comment]
@whatsdis I don't know if that workaround is still required since they had rolled back the change with regard to the status code.  If that workaround is still required you would add it wherever you are calling into the direct line client.  If you're not using direct line client then this may be a different issue.
