### ISSUE TITLE
Slack interactive messages error - 500_service_error

### ISSUE THREAD

**Issue by mpn6060** [Microsoft/BotBuilder#2462]
I have posted messages with buttons, but when I click on the button it is not hitting my request URL and giving the error message as 500_Service_Error.

**Comment by mpn6060** [comment]
I have posted messages with buttons, but when I click on the button it is hitting my request URL and giving the error message as 500_Service_Error.

**Comment by mgbennet** [comment]
Thank you for your submission. This seems like a question better suited to the [Bot Framework tag of Stack Overflow](http://stackoverflow.com/questions/tagged/botframework) rather than this github account, where we're trying to use for bugs and feature requests. Also, some code examples are needed to answer your question. I have closed this issue. Please feel free to resubmit your question over on Stack Overflow with some code in it and one of our support engineers will help you out as soon as possible.
