### ISSUE TITLE
In Microsoft Teams mobile If hero card have one button that one button click not working (android)

### ISSUE THREAD

**Issue by Malith1994124** [Microsoft/BotBuilder#2488]
Note: Please only submit Bot Builder SDK bugs here. If you have general questions or implementation issues, please submit a question on Stack Overflow at http://stackoverflow.com/questions/tagged/botframework.

**Comment by Malith1994124** [comment]
need agent help

**Comment by RichMoeMSFT** [comment]
@Malith1994124 I am unable to duplicate this on Android.

**Comment by nwhitmont** [comment]
@Malith1994124 can you provide some additional details about your issue?

## Environment

* Operating System: 
  * Windows
  * macOS
  * Linux
* SDK Platform:
  * C#/.NET
  * Node.js
* SDK version:
* Development environment:
  * localhost
  * Azure Web App
  * Azure Bot Service App
  * other
* If you are using the Node.js SDK:
  * Node.js version:
  * NPM version: 

## Issue

What the issue is, in broad strokes. Link to [Stack Overflow](http://stackoverflow.com/search?q=%23botframework) post.

## Example Code

The code snippet or complete bot example (preferred) that demonstrates the issue.

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

What you expected to happen.

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

**Comment by nwhitmont** [comment]
Closing this as not related to BotBuilder SDK.
