### ISSUE TITLE
Q: Adding new channel

### ISSUE THREAD

**Issue by AlexSenchenko** [Microsoft/BotBuilder#2495]
I have questions regarding viber channel:

Do you have a public road map with vote buttons where I can press vote to impact on this issue priority
Will you accept pull request if I am implement viber channel my self and what I need to look first for doing it.
Thanks

**Comment by tomlm** [comment]
We don't currently allow channels to be created by 3rd parties.  That may change in the future but right now we are focusing on performance and reliability for our existing channels before we expand to more.

**Comment by SychevIgor** [comment]
Looks like nobody care about viber, because simula request were closed 5 times during last 2 years.
https://github.com/Microsoft/BotBuilder/issues/2495
https://github.com/Microsoft/BotBuilder/issues/2429
https://github.com/Microsoft/BotBuilder/issues/2219
https://github.com/Microsoft/BotBuilder/issues/2123
https://github.com/Microsoft/BotBuilder/issues/1917

**Comment by SychevIgor** [comment]
Still very interesting connector, especially after telegram was blocked in Russia.
