### ISSUE TITLE
Upgrade Dialog Id Bug node.js

### ISSUE THREAD

**Issue by slidenerd** [Microsoft/BotBuilder#2505]
When I change the version from say 1.0 to 2.0 , firstRun gets triggered but upgrade dialog is not called at all. Out of curiosity, I dug into the middleware.ts source code file and came across this
```

static firstRun(options: IFirstRunOptions): IMiddlewareMap {
        return {
            botbuilder: (session, next) => {
                if (session.sessionState.callstack.length == 0) {
                    // New conversation so check first run version
                    var cur = session.userData[consts.Data.FirstRunVersion] || 0.0;
                    var curMajor = Math.floor(cur);
                    var major = Math.floor(options.version);
                    if (major > curMajor) {
                        // Run user through full first run experience
                        session.beginDialog(consts.DialogId.FirstRun, <IFirstRunDialogArgs>{
                            version: options.version,
                            dialogId: options.dialogId,
                            dialogArgs: options.dialogArgs
                        });
                    } else if (options.version > cur && options.upgradeDialogId) {
                        // Run user through upgrade experience
                        session.beginDialog(consts.DialogId.FirstRun, <IFirstRunDialogArgs>{
                            version: options.version,
                            dialogId: options.upgradeDialogId,
                            dialogArgs: options.upgradeDialogArgs
                        });
                    } else {
                        next();
                    }
                } else {
                    next();
                }
            }
        }
    }
```

Isnt the second part where options.version > cur && options.upgradeDialogId supposed to call upgrade dialog id 
**session.beginDialog(consts.DialogId.FirstRun, <IFirstRunDialogArgs>{
    version: options.version,
    dialogId: options.upgradeDialogId,
    dialogArgs: options.upgradeDialogArgs
});**

Thank you

**Comment by nwhitmont** [comment]
@slidenerd can you provide additional details about the problem?

## Environment

* Operating System: 
  * Windows
  * macOS
  * Linux
* SDK Platform:
  * C#/.NET
  * Node.js
* SDK version:
* Development environment:
  * localhost
  * Azure Web App
  * Azure Bot Service App
  * other
* If you are using the Node.js SDK:
  * Node.js version:
  * NPM version: 

## Issue

What the issue is, in broad strokes. Link to [Stack Overflow](http://stackoverflow.com/search?q=%23botframework) post.

## Example Code

The code snippet or complete bot example (preferred) that demonstrates the issue.

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

What you expected to happen.

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.
