### ISSUE TITLE
PromptDialog: SMS channel: [CellNumber] has not been enabled for MMS - new error just today

### ISSUE THREAD

**Issue by oflahero** [Microsoft/BotBuilder#2517]
I have been using a PromptDialog with no issues over the SMS channel on BotFramework. Just today I noticed the above exception on calling PromptDialog.Confirm(...).

ERROR: initiating dialog - Microsoft.Rest.HttpOperationException: SendActivityToUserAsync FAILED: Number: +1855xxxxxxx has not been enabled for MMS

This has been working fine up til now, sending a * Yes, * No choice over SMS. Has there been any change in the backend very recently?

**Comment by oflahero** [comment]
More info: I can confirm PromptDialog was working correctly over SMS yesterday (2017-03-28 16:04 UTC)

**Comment by tomlm** [comment]
This was my fault.  We have a new feature for rendering complex cards as an image and it got turned on before it was supposed to.  The problem is that because we are sending an image it requires your twilio to be configured for MMS, which is why it failed to deliver.  I am updated our servers as we speak (eta 30 minutes).  Thank you for your patience

**Comment by oflahero** [comment]
Thanks @tomlm. My rollout is saved :) I'm assuming that when your hero card change DOES go live, it won't affect existing PromptDialogs over SMS again?
