### ISSUE TITLE
today onwards herocard attachments or image attachments are not working, actually it was working before

### ISSUE THREAD

**Issue by swathish** [Microsoft/BotBuilder#2518]

**Comment by oflahero** [comment]
@swathish : I feel your pain, I wouldn't be at all surprised if your issue was related to the one I just raised at #2517

**Comment by mdeshields** [comment]
I can confirm that using a HeroCard attachment in SMS is currently broken but was not as recently as yesterday.

**Comment by swathish** [comment]
I am  using HeroCard attachment with telegram . Yesterday it was working..

**Comment by tomlm** [comment]
This was my fault.  We have a new feature for rendering complex cards as an image and it got turned on before it was supposed to.  The problem is that because we are sending an image it requires your twilio to be configured for MMS, which is why it failed to deliver.  I am updated our servers as we speak.  Thank you for your patience

**Comment by swathish** [comment]
Thank you.. It is working now... 
Is it possible to add bot in skype for business?
