### ISSUE TITLE
[Facebook Messenger] Blocked users on FB and bot.send(...): no info about that circumstance in our bot

### ISSUE THREAD

**Issue by vorti2** [Microsoft/BotBuilder#2519]
Hi,

I have a NodeJS bot sending proactive messages with `bot.send(....)` to known users on Facebook.
If one of our previous Facebook user has blocked the communication with our bot, the information is  shown in the web console of Microsoft Bot Framework:
```
29.3.2017, 14:08:47	{"error":{"message":"(#200) This person isn't available right now.","type":"OAuthException","code":200,"error_subcode":1545041,"fbtrace_id":"xxxxxxxx"}}
```
These information is not delivered from Microsoft Bot Framework to our bot (or I did not know how ...)

CU

Wilhelm

**Comment by nwhitmont** [comment]
@vorti2 - can you provide additional details about your issue?

## Environment

* Operating System: 
  * Windows
  * macOS
  * Linux
* SDK Platform:
  * C#/.NET
  * Node.js
* SDK version:
* Development environment:
  * localhost
  * Azure Web App
  * Azure Bot Service App
  * other
* If you are using the Node.js SDK:
  * Node.js version:
  * NPM version: 

## Issue

What the issue is, in broad strokes. Link to [Stack Overflow](http://stackoverflow.com/search?q=%23botframework) post.

## Example Code

The code snippet or complete bot example (preferred) that demonstrates the issue.

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

What you expected to happen.

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

**Comment by xitij** [comment]
Hi I'm also having a similar problem, except I'm not receiving any errors or messages from Bot Framework as far as I can tell. The only indication of this problem I'm receiving is from Facebook on the developer page for my bot I receive this alert:
```
In the last three hours 50% of the calls to the method POST {page-id}/messages resulted in errors.

Error Code | 200
-- | --
Error Description | Permissions error
Error Count | 3
```

I'm not seeing a subcode so I can't be sure this is the same issue but @vorti2 mentioned that he was able to see the error in the web console for Bot Framework. Could someone please point me to that console?

I can specify the specs requested in @nwhitmont request if my case is the same as this.

Thanks.

**Comment by xitij** [comment]
Bump. This is a pretty big issue for me.

**Comment by xitij** [comment]
@nwhitmont I'm having the same issue, I posted details above. Should I create a new issue or continue to post here?

**Comment by vietsrc** [comment]
Same as xitij. Any step we should take ?

**Comment by NiteLordz** [comment]
As we have just launched proactive messaging on our Bot, we are now seeing this error populate the console as well.  Will the message be sent to the user after they turn messaging back on?  or is this message lost.

**Comment by JasonSowers** [comment]
@NiteLordz You would have to ask Facebook support about that.  We do not have any control over how the channel behave.

**Comment by xitij** [comment]
@JasonSowers Yes we understand that, but it was my assumption (I won't speak for others here) that we would get some sort of notification from bot framework that a user on Facebook had blocked the bot. Does Facebook not send a message to Bot Framework when the user blocks a bot? That is something that Bot Framework would receive if they are indeed sending some sort of message/notification.

**Comment by xitij** [comment]
@JasonSowers 

Bump. Still seeing this problem...

A simple solution that would allow the us to handle this would be BotBuilder forwarding along any errors they receive from the Messenger API. As far as I can tell this isn't currently happening.

**Comment by xitij** [comment]
Ok so I dig some digging on my own hopefully this is helpful. This issue is very easy to reproduce here are the steps:
1. Create a bot that uses the Facebook channel.
2. Start a conversation with the bot on messenger.
3. In Messenger "Turn off all messages" from the bot.
4. Send a proactive message from the bot.
5. Check Bot Framework Dev channel for error. The error is the same one mentioned above.

I dug into the code of both my callback (where I'm calling `UniversalBot.send()` which in my case is using `ChatConnector`) and the `ChatConnector.js` code itself. I added some breakpoints and the callstack is as follows:
1. `ChatConnector.send()`
2. `ChatConnector.postMessage()`
3. `ChatConnector.authenticatedRequest()`

Inside `ChatConnector.authenticatedRequest()` is where I think the problem is...
1. The authenticated request adds the User Agent and then add the Access Token [here](https://github.com/Microsoft/BotBuilder/blob/3091b073f38e7d2e699f468269711d96abde01b4/Node/core/lib/bots/ChatConnector.js#L539).
2. In the callback if there is no error it will make a `POST` via `request` [here](https://github.com/Microsoft/BotBuilder/blob/3091b073f38e7d2e699f468269711d96abde01b4/Node/core/lib/bots/ChatConnector.js#L541).
3. The response from the above request in these cases where the user has blocked the bots *does not* return an `err`, instead it returns a response with `statusCode === 403` (which we are seeing in the dev console, the image pasted in this thread).
4. [Here](https://github.com/Microsoft/BotBuilder/blob/3091b073f38e7d2e699f468269711d96abde01b4/Node/core/lib/bots/ChatConnector.js#L546) it checks for `statusCode  === 403` and attempts to refresh the request by recursively calling `_this.authenticatedRequest()` again.
5. The above steps 1-3 are happening again. However, this time in step 4 (above) `refresh === true` with a `statusCode === 403` which hits the else case [here](https://github.com/Microsoft/BotBuilder/blob/3091b073f38e7d2e699f468269711d96abde01b4/Node/core/lib/bots/ChatConnector.js#L550). This results in the no error being passed back to the callback and thus the sender never receiving the error in the callback.
6. My callback is hit with `err == null` and `addresses` an array of the addresses sent.

I believe this is a bug in the code but I could be mistaken since I don't know the intent. I do believe that this is the root of the problem and why users are never receiving any errors in these cases.

@nwhitmont @JasonSowers Please let me know if you need more details, or additional information.

Thanks
