### ISSUE TITLE
[Skype Mobile iOS] Notifications not coming from Bots on iOS

### ISSUE THREAD

**Issue by astutesoftware** [Microsoft/BotBuilder#2551]
Notifications are not appearing on IOS from Bots.
Only when it comes from a real skype contact the notifications are appearing.

**Comment by nwhitmont** [comment]
hi @astutesoftware - can you provide more details about your issue?

## Environment

* Operating System: 
  * Windows
  * macOS
  * Linux
* SDK Platform:
  * C#/.NET
  * Node.js
* SDK version:
* Development environment:
  * localhost
  * Azure Web App
  * Azure Bot Service App
  * other
* If you are using the Node.js SDK:
  * Node.js version:
  * NPM version: 

## Issue

What the issue is, in broad strokes. Link to [Stack Overflow](http://stackoverflow.com/search?q=%23botframework) post.

## Example Code

The code snippet or complete bot example (preferred) that demonstrates the issue.

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

What you expected to happen.

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

**Comment by nwhitmont** [comment]
Note: Please only submit Bot Builder SDK bugs here. If you have general questions or implementation issues, please submit a question on Stack Overflow at http://stackoverflow.com/questions/tagged/botframework.
