### ISSUE TITLE
HeroCard: can not break line in HeroCard.text

### ISSUE THREAD

**Issue by Rhaniel** [Microsoft/BotBuilder#2565]
How can i break line in text of HeroCard? I'm using web chat.

**Comment by nwhitmont** [comment]
hi @Rhaniel - can you provide more details on your issue?

## Environment

* Operating System: 
  * Windows
  * macOS
  * Linux
* SDK Platform:
  * C#/.NET
  * Node.js
* SDK version:
* Development environment:
  * localhost
  * Azure Web App
  * Azure Bot Service App
  * other
* If you are using the Node.js SDK:
  * Node.js version:
  * NPM version: 

## Issue

What the issue is, in broad strokes. Link to [Stack Overflow](http://stackoverflow.com/search?q=%23botframework) post.

## Example Code

The code snippet or complete bot example (preferred) that demonstrates the issue.

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

What you expected to happen.

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

**Comment by Rhaniel** [comment]
Hi @nwhitmont 

# Environment
- Operating System:
        Windows

- SDK Platform:
Node.js

- SDK version:
Last version

- Development environment:
localhost

- Node.js version:
v7.8

- NPM version:
v4.4.4

#What you expected to happen. 
On my second point "•" I want to skip a line, then write the next sentence, But it does not happen. I'm try use "\n \n"

#Actual Results 
![print](https://cloud.githubusercontent.com/assets/17090357/24874545/68a04c30-1dfb-11e7-8e15-83691f86c355.png)

**Comment by nwhitmont** [comment]
Per @LarsLiden on [Stack Overflow](https://stackoverflow.com/questions/41029035/how-to-insert-new-line-to-microsoft-bot-framework-thumbnail-card-subtitle) - The ability to insert line breaks in the HeroCard text is not currently a supported feature. :-(
