### ISSUE TITLE
[MS Teams Channel] Bot doesn't reply when I copy and paste 

### ISSUE THREAD

**Issue by alex182** [Microsoft/BotBuilder#2566]
When I copy and paste my prompt into MS teams the bot doesn't respond.  It works fine in the emulator, could there be some sort of hidden special character that's causing this issue?

**Comment by nwhitmont** [comment]
hi @alex182 - can you provide more details about your issue?

## Environment

* Operating System: 
  * Windows
  * macOS
  * Linux
* SDK Platform:
  * C#/.NET
  * Node.js
* SDK version:
* Development environment:
  * localhost
  * Azure Web App
  * Azure Bot Service App
  * other
* If you are using the Node.js SDK:
  * Node.js version:
  * NPM version: 

## Issue

What the issue is, in broad strokes. Link to [Stack Overflow](http://stackoverflow.com/search?q=%23botframework) post.

## Example Code

The code snippet or complete bot example (preferred) that demonstrates the issue.

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

What you expected to happen.

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

**Comment by nwhitmont** [comment]
@alex182 what text are you pasting into the prompt? Can you share a screenshot or example code?

**Comment by nwhitmont** [comment]
reopen if you're still having issues

**Comment by joshftx** [comment]
I have the same issue - using Hubot botframework adapter. Copy/paste into message provides no response. So strange.

**Comment by nwhitmont** [comment]
@joshftx You are commenting on a closed issue. Please open a new issue if you have a problem/question.
