### ISSUE TITLE
Bot c#: How can I store and load all conversations from iframe

### ISSUE THREAD

**Issue by msBot1111** [Microsoft/BotBuilder#2571]
I've inserted my Bot in xamarin app, and I'm using iframe for that. But when I start conversation with the bot it always starts new conversation. I want to keep the whole history in the chat. My question is where should I store the conversation and how can I load them when user opens the chat?

**Comment by nwhitmont** [comment]
hi @msBot1111 - can you provide more detail about your issue? for example:

## Environment

* Operating System: 
  * Windows
  * macOS
  * Linux
* SDK Platform:
  * C#/.NET
  * Node.js
* SDK version:
* Development environment:
  * localhost
  * Azure Web App
  * Azure Bot Service App
  * other
* If you are using the Node.js SDK:
  * Node.js version:
  * NPM version: 

## Issue

What the issue is, in broad strokes. Link to [Stack Overflow](http://stackoverflow.com/search?q=%23botframework) post.

## Example Code

The code snippet or complete bot example (preferred) that demonstrates the issue.

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

What you expected to happen.

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

**Comment by msBot1111** [comment]
I'm using Bot Framework c# for my Bot, and development environment is Azure Web App. I have also Xamarin Forms App and I've added my Bot into my app with iframe. When I open the chat with Bot it's working well, my Bot returns the answers. My problem is that I'm not keeping the conversations. Every time I reopen the chat it gives me new conversation. Is it possible to keep history of conversations per user and when I reopen the chat to load all conversations with that user as it is in skype channel.

**Comment by JasonSowers** [comment]
@msBot1111 This may help you get started on the right path here https://blog.botframework.com/2017/05/05/Saving-Bot-Actions-On-Azure-Sql-Server/

**Comment by msBot1111** [comment]
https://blog.botframework.com/2017/05/05/Saving-Bot-Actions-On-Azure-Sql-Server/ 
I've stored the conversation as it is in the example, but now how can I load the conversation when the chat is opened?

**Comment by JasonSowers** [comment]
@msBot1111 I do not have an exact code example but, in your messageController, in the `HandleSystemMessage()` method you could load it all up and display it instead of a welcome message like below 
```cs
            else if (message.Type == ActivityTypes.ConversationUpdate)
            {
                // Handle conversation state changes, like members being added and removed
                // Use Activity.MembersAdded and Activity.MembersRemoved and Activity.Action for info
                // Not available in all channels
                IConversationUpdateActivity iConversationUpdated = message as IConversationUpdateActivity;
                if (iConversationUpdated != null)
                {
                    ConnectorClient connector = new ConnectorClient(new System.Uri(message.ServiceUrl));

                    foreach (var member in iConversationUpdated.MembersAdded ?? System.Array.Empty<ChannelAccount>())
                    {
                        // if the bot is added, then
                        if (member.Id == iConversationUpdated.Recipient.Id)
                        {
                            var reply = ((Activity) iConversationUpdated).CreateReply(
                                $"Hi! I'm a Spotify bot! Ask me about your favorite artist.");
                            await connector.Conversations.ReplyToActivityAsync(reply);
                        }
                    }
                }
            }
```
