### ISSUE TITLE
[Facebook Messenger] Issue with PromptDialog.Choice and Facebook

### ISSUE THREAD

**Issue by yamifr07** [Microsoft/BotBuilder#2576]
I have my Facebook bot online and I am inspecting all the requests in my server. Sometimes my server is not receiving messages. If I retry and send a message many times, it works. If I use the emulator it works fine.

[Example image](http://bots.99uno.com/bug.png)
I wrote three times "pollo" to get the answer.

Any idea?

**Comment by nwhitmont** [comment]
hi @yamifr07 - can you provide more details about your issue?

## Pre-flight checklist
- [ ] I have reviewed the BotBuilder SDK [Contribution Guidelines](https://github.com/Microsoft/BotBuilder/blob/master/Contributing.md)
- [ ] I posted a question about this issue on [Stack Overflow](http://stackoverflow.com/search?q=%23botframework) using the tag `#botframework`.
- [ ] I have asked for help in the [Bot Framework Gitter group](https://gitter.im/Microsoft/BotBuilder) before filing this issue.
- [ ] I have [searched the existing issues](https://github.com/Microsoft/BotBuilder/issues?utf8=%E2%9C%93&q=is%3Aissue) before logging a new one.
---------------------------

## Environment

* Operating System: 
  * Windows
  * macOS
  * Linux
* SDK Platform:
  * C#/.NET
  * Node.js
* SDK version:
* Development environment:
  * localhost
  * Azure Web App
  * Azure Bot Service App
  * other
* If you are using the Node.js SDK:
  * Node.js version:
  * NPM version: 

## Issue

What the issue is, in broad strokes. Link to [Stack Overflow](http://stackoverflow.com/search?q=%23botframework) post.

## Example Code

The code snippet or complete bot example (preferred) that demonstrates the issue.

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

What you expected to happen.

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

**Comment by yamifr07** [comment]
**Pre-flight checklist**

 I have reviewed the BotBuilder SDK Contribution Guidelines
x I posted a question about this issue on Stack Overflow using the tag #botframework.
 I have asked for help in the Bot Framework Gitter group before filing this issue.
x I have searched the existing issues before logging a new one.

**Environment**

Operating System:
Windows
macOS
x Linux

SDK Platform:
C#/.NET
x Node.js

SDK version:
Development environment:
x localhost
Azure Web App
Azure Bot Service App
other

If you are using the Node.js SDK:
Node.js version: v6.6.0
NPM version: 3.10.3

**Issue**

What the issue is, in broad strokes. Link to Stack Overflow post.
[StackOverflow](http://stackoverflow.com/questions/43325604/bot-framework-facebook-prompt-issue)
I log everything in my server using morgan and I don't see messages when bot does not reply. The log when it works is: POST /api/messages 202 - [10/Apr/2017:20:03:30 +0000] - - - 1.624
I don't know if that 202 is the problem... When I develop a web, my server sends 200 to requests. But, just the propmts choice are not working fine. The other widgets such as HeroCard are ok.

[Example Code](http://stackoverflow.com/questions/43325604/bot-framework-facebook-prompt-issue)

**Steps to Reproduce**
Answer multiple Prompts choices quickly (reply as soon as you receive the options). Chat displays the answer but is not being received in the server.

Expected Behavior

What you expected to happen.
Receive user messages

Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.
Must send the message many times to receive it.
[Image](http://bots.99uno.com/bug.png)

**Comment by yamifr07** [comment]
I also tried the example code I found in this repository. Same problem... So you can run Microsoft example in Facebook messanger and some message are being ignore. Sometimes it replays ok and sometime doesn't.

**Comment by yamifr07** [comment]
So... Any updates. If it doesn't work on Facebook I must use another framework :(

**Comment by wiredwiz74** [comment]
I think this is the same issue I am currently having. Did you check for errors on your botframework login? The errors I am seeing are from the BotFramework showing unauthorized and then authorized and then unauthorized. StackOverflow [Here](http://stackoverflow.com/questions/43620553/unauthorized-then-endpoint-authorization-succeeded-then-unathorized) Now it appears to be working but any custom facebook channel data is still experiencing this problem. As a side note, I noticed Facebook released a new version of it's API on April 18th... Coincidence?

**Comment by nwhitmont** [comment]
Hi @yamifr07 We have just released many updates to the Bot Framework including a complete re-write of the prompts system available in botbuilder@3.8.x NPM module.  

Are you still experiencing the issue after upgrading botbuilder to v3.8.x? To upgrade use `npm upgrade --save botbuilder`.

If you are still having issues after upgrading the botbuilder module, can you post your complete bot code? This will help us debug the issue.

**Comment by yamifr07** [comment]
Yes, still having issue. I think it's easy to reproduce but here is my code:
`	bot.dialog('/menu', [
		(session) => {
			builder.Prompts.choice(session, 'Bots disponibles:', 'Horoscope|News', {listStyle: builder.ListStyle.button});
		},
		(session, results) => {
			let dialog;
			switch(results.response.index) {
				case 0:
					dialog = 'horoscope';
					break;
				case 1:
					dialog = 'news';
					break;
			}
			session.beginDialog('/' + dialog);
		},
		(session, results) => {
			session.replaceDialog('/menu');
		}
	])
	.reloadAction('reloadMenu', null, { matches: /^menu/i });`

**Comment by chitrang89** [comment]
Hi @yamifr07 ! Have you tried replaceDialog instead of beginDialog to see a change in behaviour?

**Comment by yamifr07** [comment]
@chitrang89 yes, same issue.

**Comment by akontsevich** [comment]
> Error: Request to 'https://state.botframework.com/v3/botstate/facebook/conversations/xxxxxxx-xxxxxxx/users/xxxxxxx' failed: [400] Bad Request

I Have this error if send 
`builder.Prompts.choice(session, ' ', 'Button1|Button2', {listStyle: builder.ListStyle.button});`
with empty or white space message. Is it possible just to show button without preceding message? Emulator and Web Channel allows white space message, fails with empty message however.

**Comment by JasonSowers** [comment]
please open a new issue if anyone is still facing this problem
