### ISSUE TITLE
[Facebook Messenger] Remote debugging with ngrok and facebook messenger is not working

### ISSUE THREAD

**Issue by wethil** [Microsoft/BotBuilder#2618]
I aplied every instruction on [node facebook example](https://github.com/Microsoft/BotBuilder/blob/master/Node/examples/demo-facebook/app.js) , I get no error, everything seems okay but i can not get respond on facebook messenger.

 But when i try to debug locally with localhost url by bot emulator, it is working. Is it a configuration problem related to page or ip identification informations? What can be wrong? 

It even does not work for web chat on bot dashboard page.

**Comment by amitbend** [comment]
@wethil can you see any errors on the bot page at [botframework website?](https://dev.botframework.com/bots)

**Comment by wethil** [comment]
No I can not see any error.

**Comment by amitbend** [comment]
Recently there are issues with ngrok, you should try one of the alternatives like localtunnel, see if it works

**Comment by nwhitmont** [comment]
@wethil Try deploying a basic bot example such as [this one](https://github.com/Microsoft/BotBuilder/blob/master/Node/examples/basics-menus/app.js), and see if you can get it working on FB, before moving on to troubleshoot the more complex FB example bot.  If the basic bot works, but the FB example bot does not, then we can know the problem is in the example code.
