### ISSUE TITLE
[Question] Bot c#: How can I get user location and time zone on the device from the bot

### ISSUE THREAD

**Issue by msBot1111** [Microsoft/BotBuilder#2626]
I need to get user location from bot without asking the user to writes address and also how can I get time zone of the users device to get the local time. My idea is when user says hi or hello bot to respond with good morning or good evening according to the time of the day. And for location, I want to use GPS from users phone to get me the location so I can suggest nearby places to user.

**Comment by nwhitmont** [comment]
@msBot1111 what channel are you using with your Bot? Eg. Slack, Telegram, Facebook Messenger, Kik?
 Depending on the channel, the capabilities and corresponding instructions will be different.  Most likely you will find the answer in the API docs for your specific channel.

**Comment by msBot1111** [comment]
@nwhitmont I am using Skype and I've integrated my bot in xamarin app

**Comment by alokraj68** [comment]
@nwhitmont Is it possible in any platform to get user location and time zone?

**Comment by msBot1111** [comment]
Is there a way I can get gps location from users device in bot? My bot is integrated in skype channel and in the xamarin app. When I try to get the location from skype it returns null.  I saw this link for messenger, but in skype it doesn't work. https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Samples/EchoBot/EchoLocationDialog.cs#L110

**Comment by alokraj68** [comment]
@msBot1111 It's all platform specific and hence its hard. you can ask the user to give his location and resolve it using google places.

**Comment by JasonSowers** [comment]
@msBot1111 can you try looking at these and see if they help for location. The data is not stored by the framework itself though.  I am going to close this because it is not exactly a bot framework issue, but a question on geolocation and time zones per device.  Feel free to continue the discussion here if you feel so inclined, we can always reopen.

https://stackoverflow.com/questions/38054783/get-user-location-for-bot-framework

https://stackoverflow.com/questions/42904014/reverse-geocoding-with-botframework-location/42913084#42913084

**Comment by karun-r** [comment]
@JasonSowers  Any plan to integrate this into the framework itself in near future?

**Comment by artemious7** [comment]
How about the time zone?! I'm getting UTC time allways if I use `DateTime.Now`

**Comment by Chaitanya1010** [comment]
So are we able to get the latitude and longitude of the user in Skype Channel by asking whenever we need it?
