### ISSUE TITLE
Deploying bot in Aws Windows 2012 server IIS 8

### ISSUE THREAD

**Issue by deepaksubramoniam14** [Microsoft/BotBuilder#2629]
hi all,

Can anyone help me to understand on following things.

Can my bot can be deployed in AWS windows 2012 server and configure the same in my bot framework like

https://<aws serverip>:<portno>/mybot/api/messages.

if so what is the method we should use to publish method like web deploy,filesystem,ftp,...

Request you to kindly clarify me and also kindly correct me if am wrong.

Thanks in Advance...
With Regards
Deepak Subramoniam
(M) : +91 98 40 10 68 89

**Comment by nwhitmont** [comment]
@deepaksubramoniam14 Yes, you bot is a web application and can be deployed to any cloud service provider. I recommend storing your bot code in GitHub and linking the repository to your AWS deployment method of choice.

**Comment by deepaksubramoniam14** [comment]
Can you please guide me the steps. am not aware of the method you are suggesting

**Comment by mohdkhan786** [comment]
Bot deployment works fine in IIS7 but I am having a Issue in deploying bot in IIS8 (Windows server 2012)

**Comment by deepaksubramoniam14** [comment]
@mohdkhan786  can u pls guide me to publish in iis

**Comment by mohdkhan786** [comment]
I will tell you steps what I did,
@deepaksubramoniam14 
1  run VS2015 with admin and create default bot with default template 
2  rght click on project name from solution explore and go to properties ---> Web --> select Local IIS from dropdown instead of IIS express [under Apply server settings to all users]
3 click on create virtual directory

that's all you can use local iis url in bot emulator

Note: I have done it in IIS7 

for me this is not working in IIS8 (windows server2012) but this may be issue of .net framework not sure .
