### ISSUE TITLE
[Question] C# Use of Advanced Field

### ISSUE THREAD

**Issue by jcalixte** [Microsoft/BotBuilder#264]
Hi :)

Is there an example of how we can properly use Advanced Field in FormFlow?

Thank you very much!

**Comment by chrimc62** [comment]
You can't actually use it directly since it does not implement IFieldState;  It is useful though to serve as a base class of both FieldReflector which does reflection on C# classes and the newly released FieldJson which derives a form from a JSON Schema.  It is also useful if you want to implement your own IField implementation--you derive from Field and implement IFieldState.
