### ISSUE TITLE
Don't tell people to use hashtags on Stack Overflow

### ISSUE THREAD

**Issue by stijnherreman** [Microsoft/BotBuilder#2658]
Both your documentation at https://docs.botframework.com/en-us/support/ and the issue template here on GH tells people to use a #botframework hashtag on Stack Overflow. That leads to people posting questions with titles such as *How to end a conversation with #botframework .Net*

Stack Overflow doesn't work that way, please don't tell people to do that. We do have tags, but they work differently: http://stackoverflow.com/help/tagging

As an aside, this isn't the first time that Microsoft employees give bad advice to users. It's quite embarrassing that such a company fails at simple usage instructions of Stack Overflow. Please consider making http://stackoverflow.com/tour and http://stackoverflow.com/help mandatory reading material for employees responsible for directing users to Stack Overflow.

**Comment by EricDahlvang** [comment]
Thanks for your feedback Stijn.  I see that Ezequiel has already submitted some pull requests to remove the #s. I've also updated our internal onboarding docs to include references to StackOverflow /tour and /help, and I've forwarded your comments to existing engineeers.  

I'm closing this issue, since it has been addressed. But, if you have any other suggested improvements: we are all ears.

**Comment by ejadib** [comment]
@EricDahlvang, please make sure to remove the # from the support docs pages too: https://docs.botframework.com/en-us/support/ & https://docs.microsoft.com/en-us/bot-framework/resources-support

**Comment by RobStand** [comment]
@ejadib This is done.
