### ISSUE TITLE
[LUIS] Issue in recognizing multiple intents

### ISSUE THREAD

**Issue by Chitma** [Microsoft/BotBuilder#2680]
Hi, 

I have a requirement in which user queries something like "What's the status of pizza, I wish to order another one two."

I have two intents for this. "OrderPizza"  "StatusPizza".

How Do I send the above queries and map to two intents in LUIS?
I tried creating new intent and mark the inner intents as entities and tried to send to LUIS but failed as each entity is going once to LUIS.

is it possible to use multiple intents in LUIS? if yes , then how?

Thanks,
Manish Chitre.

**Comment by stevengum97** [comment]
My initial thought is to create a hybrid intent, my reason is this: in LUIS you have capacity for 80 intents, and 30 entities. Unless you're at 79 intents, creating a "StatusAndOrderPizza" intent isn't pushing the limit.

I don't believe there is a straight forward way to do what you're asking. I'm not sure I follow in the sentence after your first question, you tried to;
> mark the inner intents as entities and tried to send to LUIS but failed as each entity is going once to LUIS.

Could you elaborate, perhaps show a screenshot of your setup on the LUIS portal for this?

If you're feeling up-to-task you can write your own middleware which would handle the LUIS response JSON, but then you need to manipulate the dialogstack to add the `"OrderPizza"` and `"StatusPizza"` intent matching dialogs. You can read more about Node middleware in [Issue #1677](https://github.com/Microsoft/BotBuilder/issues/1677).

*But*, if *I'm* going to manipulate the dialogstack, I'd rather just do it when I get the response from LUIS and it matches inside of my chatbot. I'm not sure which SDK you're using, but for the Node SDK, I'd use something like below:

```
intents.matches('StatusAndOrderPizza', 'StatusAndOrderPizzaDialog');

bot.dialog('StatusAndOrderPizzaDialog', [
  function(session, args) {
    session.beginDialog('StatusPizza');
  },
  function(session, results) {
    if (results.orderMorePizza == true) {
      // results from session.endDialogWithResult({ orderMorePizza: true }); inside the 'StatusPizza' dialog
      session.beginDialog('OrderPizza');
    } else {
      session.endDialog(); // Or something else
    }
  }
)
```

By doing it this way, I'll offload the work onto my LUIS model. As it gets more endpoint hits it'll become more accurate. And I don't worry as much about potential changes in the SDK requiring me to fix my middleware.

**Comment by nwhitmont** [comment]
@Chitma are you using C# or Node SDK?

**Comment by Chitma** [comment]
@nwhitmont I am using C# SDK.

@stevengum97 - Thanks for your answer and time.
Yes, I am using Hybrid Intent called "OrderAndStatusPizza" which contains two intents  (order and status) as entities.
          OrderPizza - intent 1
          StatusPizza- intent 2
          OrderAndStatusPizza(Hybrid Intent) - intent 1 + intent 2 as entities.

 Luis is able to recognize my intent is hybrid one and then I am searching for intents one by one(which in this case are entities) and forwarding control to LUIS.

`
        [LuisIntent("OrderAndStatusPizza")]
        private async Task MultipleIntentHandler(IDialogContext context, LuisResult result)
        {
            foreach (var entity in result.Entities)
            {
             //calling LuisDialog again.
            }

        }`

But , the problem with above method is I am unable to divide my query let's say user says.

"I need to know the status of the onion pizza" and "I need to order other one too."  

where 'status' and 'onion pizza' are entities for - StatusPizza intent.
where 'order' and 'one' are entities for OrderPizza intent.

I am able to send each entity only once because of foreach loop.

I know I am doing it wrong but is there any way to incorporate multiple LUIS intent in C# ??

Thanks.

**Comment by stevengum97** [comment]
To save the entities from the LuisResult, storing them inside your IDialogContext should work just fine. Then you should be able to access them as many times as needed (from ConversationData, UserData, etc). After a set amount of time, you can purge the entities from your bot.

### Using current setup (intents-as-entities):

In regards to divding the user's utterance... To split the utterance into two substrings it's possible split on punctuation or words like "and", "plus" etc. However, because LUIS also returns the `"startIndex"` and `"endIndex"` of your entities, it's better to split on those indices. 

#### Splitting/Dividing using LUIS:
It will probably be more accurate and easier to do the splitting on ending indices than splitting on punctuation or conjunctions. Here's an example utterance:

> "What's the status on my two pizzas? I want to order another pizza."

For your "StatusPizza"-entity, we're expecting its startIndex ("W") to be 0 and endIndex ("?") to be 35. We're also using the prebuilt number entity, so we have it recognizing "two", which has a startIndex of 25 and endIndex of 27. Since its endIndex is before the endIndex of the "StatusPizza"-entity, we can safely tie those two together. The user is asking about their order that has two pizzas in it between index 0 and index 27. Anything after that is related to the "OrderPizza"-entity.

___

If you ran a query against your LUIS endpoint in a browser and came back with the resulting JSON, seeing how the entities and intents are currently being recognized would help in getting a better answer for your situation.

**Comment by Chitma** [comment]
@stevengum97  - awesome ! thanks a lot . I am trying it out.

**Comment by b4usat** [comment]
@stevengum97 Can you please help me understand more about the logic you mentioned. I'm bit confused here. What if user is asking the same question in a different manner like below

> I would like to order one more pizza. By the way whats the status of my previous order

> Tell me the status of my ordered pizas. I need to order one more.
Actually we can ask in lot of types 👍

**Comment by stevengum97** [comment]
> "What's the status on my two pizzas? I want to order another pizza."
### vs
> "I would like to order one more pizza. By the way whats the status of my previous order"

The order won't matter, the logic still works the same. With training LUIS will recognize *"I would like to order one more pizza"* as the "OrderPizza"-entity.  Inside of this entity is "one" which should be recognized as a prebuilt number entity. Because it ("one") exists within the "OrderPizza" entity, it's a reasonable assumption that the "one" is tied to "OrderPizza". So we set those together in our IDialogContext for when we begin our OrderPizza dialog.

*"By the way whats the status of my previous order"* or *"whats the status of my previous order"* will still be recognized as the "StatusPizza"-entity. Likewise we store these for our StatusPizza dialog.

If we switched it around so that the utterance is *"Whats the status of my previous order? I would like to order one more pizza"*, LUIS will still be able to recognize which entity is which. In this reversed utterance, LUIS detects the "StatusPizza"-entity first, and then detects the "OrderPizza"-entity. 

People do ask for things in varying fashions, and accounting for this reversed order *may* require a few additional training utterances. But the logic of using entities' starting and ending indices to select which entities go with other entities is still valid.

**Comment by stevengum97** [comment]
Closing issue, if there are any questions or comments about this subject, please feel free to post them here.
