### ISSUE TITLE
[Feature Request] Image choice prompt

### ISSUE THREAD

**Issue by nwhitmont** [Microsoft/BotBuilder#2722]
As a user of Bot Framework, I would like to have the ability to prompt the user visually using image choices. Instead of a text button, the user would be prompted to click/tap on an image to make their selection.

**Comment by Stevenic** [comment]
You can do that. All prompts let you pass an Message which means you can send anything you want with the prompt. But w.8 you don't even need to do that. You can set your `listStyle` to `ListStyle.none` and then pass in your choices as cards using the `attachments` option. You'll still want to pass in a list of choices as that's used to perform the recognition of the tap/click.

**Comment by nwhitmont** [comment]
awesome, thanks @Stevenic !

**Comment by LieberGott** [comment]
would it be possible to get a code example on this?
thanks!

**Comment by DanielTizon** [comment]
Hi @Stevenic,
could you add an example about how can you do what you say? Im trying it:

const choices_test = [{ value: "Yes", action: builder.CardImage.create(session, 'https://cdn-images-1.medium.com/max/1600/1*QoCscxdXl2mkWqL7mGfALA.png') }, { value: "No" }];

And It's not working.

I don't want to use CarouselCards, because I am working with dynamic prompts generation, and I always need to use choices object. 

Thanks!
