### ISSUE TITLE
[Question] SkypeCall Bot with LUIS intent

### ISSUE THREAD

**Issue by wtam** [Microsoft/BotBuilder#2746]
I'm working on merging the existing chat bot + Luis with the skype call bot and found that there's no IntentDialog (support in ChatBot botbuilder) from the botbuilder-calling/lib/botbuilder.d.ts  So how do we do it?  At the same time the Bot portal has a new setting Speech recognition priming with LUIS.  So there must be a way to stick it together but I can't find any document.

**Comment by nwhitmont** [comment]
@wtam are you using C# or Node SDK?

**Comment by Stevenic** [comment]
The issue is that you don't ever get the raw user text with a call bot. You have to use the speech recognition features of the calling SDK.  If you look at the sample provided you can see how to create a menu that sort of works like an IntentDialog would but you pretty much have to create menu trees when building a call bot.

**Comment by wtam** [comment]
@Stevenic, thank again for your clarification and I guess I should also look into the Real-Time Media Calling SDK too but its hasn't had nodejs yet.  Will wait for it.  Ideally I like to get the Bot to recognize the speech of the Skype voice call like LUIS and handle its with different intent instead of Menu work flow like IVR.
