### ISSUE TITLE
[Question] Adaptive card Unknown Attachment Type

### ISSUE THREAD

**Issue by srozga** [Microsoft/BotBuilder#2803]
Hi there.
Using C# BotBuilder 3.8.0 and Microsoft.AdaptiveCards 0.5.0.  Was excited to get my hands on the Adaptive Cards feature. I noticed off the cuff that the Skype does not support these yet. 

Request to:
https://smba.trafficmanager.net/apis/v3/conversations/29:1c1Lw-kXULSSpl-AfpPSC-EIyTXHvb8Ls24OgliMuh1Q/activities/1495202872305
Response:
{"error":{"code":"BadArgument","message":"Unknown attachment type"}}

I followed these instructions:
https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-add-rich-card-attachments#a-idadaptive-carda-add-an-adaptive-card-to-a-message

What is the timeline in terms of supporting Adaptive Cards on Skype (and I suppose other platforms)?

Thanks
-Szymon

**Comment by EricDahlvang** [comment]
There isn't a timeline established right now, but as of 5/18/2017:

•	Emulator – full support
•	WebChat – Full support
•	facebook – render to image + limited mapping to  buttons
•	Slack – Image + limited mapping to buttons
•	Kik – render to Image + limited mapping to  keyboard
•	Telegram – Render to Image + limited mapping to keyboard
•	SMS – Image + text
•	GroupMe – Image + text
•	Email – Image + limited mapping to links
•	Bing – I think supports it via SkypeWeb Chat control which has implementation.  Not sure if it is in production yet.
•	Skype – Coming Soon
•	Teams – Coming Soon
•	Cortana – not supported 
•	Skype4B – Not supported

**Comment by jordanchang** [comment]
This is great info and needs to be on the home page on adaptivecards.io. I just tried my adaptivecard on slack and it doesn't render at all. Kind of disappointed, but I can wait since I see it's coming soon.

**Comment by AndreMantas** [comment]
I got completely baited by adaptivecards.io. Shows such cool cards working on skype, but then there's a tiny `* Comming soon to Skype` that just appears for a second. Well played.

**Comment by jrmcdona** [comment]
@EricDahlvang  What is the difference between Bing's Skype Webchat control and Skype in your list?  
I am trying to display Adaptive Card in Skype Web chat control and get the following in the bot settings logs.  Not sure how this differs from the Skype WC Bing is using but isn't working for me.
![image](https://user-images.githubusercontent.com/4327773/27034744-7e49535e-4f44-11e7-8d50-5e89ce400ee7.png)

**Comment by ream88** [comment]
Why is this closed? The example here is not working at all: https://docs.microsoft.com/en-us/bot-framework/rest-api/bot-framework-rest-connector-add-rich-cards#a-idadaptive-carda-add-an-adaptive-card-to-a-message

**Comment by JasonSowers** [comment]
@ream88 What channel are you using?

**Comment by ream88** [comment]
MS Teams

**Comment by EricDahlvang** [comment]
@ream88 This issue is closed because the question asked by the original user was answered.  The url you referenced does in fact work, in the emulator and in WebChat, but not in MS Teams.  This is a known feature that is currently being implemented (as mentioned earlier: Teams support is coming soon).

@jordanchang There is a documentation page that has this information currently in the pipeline.

@jrmcdona I was refering to this WebChat control: https://github.com/Microsoft/BotFramework-WebChat Please post your question on Stack Overflow with the SkypeDeveloper tag.

----

The Microsoft Bot Framework team prefers that **how to** questions be submitted on [Stack Overflow](http://stackoverflow.com/search?q=%23botframework). The official [Bot Framework Github](https://github.com/Microsoft/BotBuilder/issues) repo  is the preferred platform for submitting **bug fixes and feature requests**.

**Comment by weretygr** [comment]
Microsoft Teams

________________________________

**Comment by amikulich** [comment]
Hi guys. Could you please tell if Add an Adaptive card to a message example from https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-add-rich-card-attachments#adaptive-card is supposed to work on Skype channel?

**Comment by jrmcdona** [comment]
I don't think it is supported just yet on Skype.  Believe they are working on it @amikulich

**Comment by martinoss** [comment]
A hint on adaptivecards.io would be great, that skype is not supported yet.
![image](https://user-images.githubusercontent.com/2587942/29553923-95995cd2-871d-11e7-8c06-1b16fe9c564f.png)
