### ISSUE TITLE
Finding user location in botframework

### ISSUE THREAD

**Issue by JajatiMohanta** [Microsoft/BotBuilder#2850]
## Pre-flight checklist
- [x] I posted a question about this issue on [Stack Overflow](http://stackoverflow.com/search?q=%23botframework) using the tag `botframework`.
- [ ] I have [searched the existing issues](https://github.com/Microsoft/BotBuilder/issues?utf8=%E2%9C%93&q=is%3Aissue) before logging a new one.
---------------------------

## System Information (Required)
* SDK Platform: 
* SDK Version: 
* Development Environment: localhost | Azure Bot Service | Azure App Service | other

## Issue Description
Describe the issue here.

## Example Code
The complete bot code that reproduces the issue.

## Steps to Reproduce
1.
2.
3.

## Expected Behavior
What you expected to happen.

## Actual Results
What actually happened. Please give examples and support it with screenshots, copied output or error messages.

**Comment by JajatiMohanta** [comment]
hi,
Is it possible to find out user's current location in Microsoft bot ?
Thanks,
Jajati

**Comment by amitbend** [comment]
You can use : https://github.com/Microsoft/BotBuilder-Location

**Comment by EricDahlvang** [comment]
I'm closing this issue since amitbend has answered the question. 

 Please note: the Microsoft Bot Framework team prefers that **how to** questions be submitted on [Stack Overflow](http://stackoverflow.com/search?q=%23botframework) so the community can benefit from the answers. The official [Bot Framework Github](https://github.com/Microsoft/BotBuilder/issues) repo  is the preferred platform for submitting **bug fixes and feature requests**.
