### ISSUE TITLE
[Question] Prompts.choice unable to correctly parse datetimes

### ISSUE THREAD

**Issue by DavidJBarnes** [Microsoft/BotBuilder#2897]
My bot displays a list of datetimes via choice prompt such as below.

1. Thursday at 3:45 PM
2. Thursday at 4:15 PM
3. Friday at 3:00 PM

When a user enters: "thursday at 3", the bot thinks the user selects option #3. What is the best way to handle such an interaction?

I am using nodejs and building my choice prompt by:
`builder.Prompts.choice(session, "makeAptMain", choice, { maxRetries:3, listStyle: builder.ListStyle.list, retryPrompt:"Type the number that represents the time you wish to schedule." });`

**Comment by stevengum97** [comment]
Hi @DavidJBarnes, could you indicate which version of the SDK you're using? The Prompt system was reworked with the release of [3.8.0^](https://github.com/Microsoft/BotBuilder/commit/2818c6998f250b3ad3cef2f4581e8af99c36a70c).

**Comment by DavidJBarnes** [comment]
3.8.4

**Comment by stevengum97** [comment]
The SDK doesn't parse datetime in [**PromptChoice()**](https://github.com/Microsoft/BotBuilder/blob/master/Node/core/lib/dialogs/PromptChoice.js#L43), it only does in [**Prompts.time()**](https://docs.botframework.com/en-us/node/builder/chat-reference/interfaces/_botbuilder_d_.__global.iprompts.html#time) by default. 

If the choices you're providing to your users are fixed/comes from static data, I would recommend passing in an array of [**IChoices**](https://docs.botframework.com/en-us/node/builder/chat-reference/interfaces/_botbuilder_d_.ichoice.html) and adding to the [**synonyms**](https://docs.botframework.com/en-us/node/builder/chat-reference/interfaces/_botbuilder_d_.ichoice.html#synonyms) property. 

For example: 
```js
builder.Prompts.choice(session, 'Please choose a datetime:', 
        [
            {
                value: 'Thursday at 3:45 PM',
                synonyms: ['Thursday at 3', 'First', 'First One', '1st one', '1st' ]
            },
            {
                value: 'Thursday at 4:15 PM',
                synonyms: ['Thursday at 4', 'Second', 'Second One', '2nd one', '2nd' ]
            },
            {
                value: 'Friday at 4:00 PM',
                synonyms: ['Friday at 4', 'Third', 'Third One', '3rd one', '3rd' ]
            }
        ],
         { 
            maxRetries:3, 
            listStyle: builder.ListStyle.list, 
            retryPrompt:"Type the number that represents the time you wish to schedule." 
         }
);
```


Alternatively you could create a custom prompt and recognizers so that it matches to `Thursday at 3:45` as opposed to your third option. If you look at Issue #2741, there is a [example](https://github.com/Microsoft/BotBuilder/issues/2741#issuecomment-300946349) by @Stevenic on creating a custom prompt with the new prompt system. Does this help?

**Comment by DavidJBarnes** [comment]
Thanks, Steven.
