### ISSUE TITLE
[Question] Coloring for the cards with attachment ?

### ISSUE THREAD

**Issue by sowsan** [Microsoft/BotBuilder#2907]
Is there a way to make a different background colors for the cards and its content ? Its always rendering as grey background color in webchat. Look like even adaptivecard doesnt have the capabilty.

**Comment by nwhitmont** [comment]
@sowsan are you using .NET or Node SDK?

**Comment by sowsan** [comment]
.NET & WebChat Channel

**Comment by nwhitmont** [comment]
You can style adaptive cards by including a `hostconfig.json` file in your project. Check out this [sample hostconfig.json](http://adaptivecards.io/samples/themes/hostconfig.json) for reference.  The complete [host config specification can be found here.](http://adaptivecards.io/samples/themes/hostconfig.json)

**Comment by EricDahlvang** [comment]
Hi @Unders0n 

AdaptiveCardsHostConfig is still built into WebChat: https://github.com/Microsoft/BotFramework-WebChat/blob/master/packages/component/src/Styles/adaptiveCardHostConfig.js  However, with WebChat-V4 it is no longer necessary to rebuild in order to make styling changes.  Style Options can be provided as a parameter to window.WebChat.renderWebChat Here is an example: https://github.com/Microsoft/BotFramework-WebChat/blob/master/samples/05.a.branding-webchat-styling/index.html#L35  The defaultStyleOptions can be found here:
https://github.com/Microsoft/BotFramework-WebChat/blob/master/packages/component/src/Styles/defaultStyleSetOptions.js

---

This is the BotBuilder repository, and is only taking DCRs at this point.  The WebChat repository can be found here: https://github.com/Microsoft/BotFramework-WebChat/  or, please ask usage/howto questions on Stack Overflow: https://stackoverflow.com/questions/tagged/botframework

**Comment by EricDahlvang** [comment]
Please file an issue here for the mozilla/chrome difference: https://github.com/Microsoft/BotFramework-WebChat/issues/new

BotChat.js is the V3 WebChat version, and WebChat.js is the V4 WebChat version.

**Comment by Unders0n** [comment]
@EricDahlvang 

> BotChat.js is the V3 WebChat version, and WebChat.js is the V4 WebChat version.
wow, really, first time seeing this info, ms support engeneers sujjested to use botchat. Also what about this example https://blog.botframework.com/2018/09/01/using-webchat-with-azure-bot-services-authentication/ ?. The article seems to declare that its not safe to use secret directly in JS code and use controller for that, but in example botchat is used. 

Thank you

**Comment by EricDahlvang** [comment]
This ReadMe.md explains how to migrate from BotChat to WebChat: https://github.com/Microsoft/BotFramework-WebChat/blob/master/samples/01.c.getting-started-migration/README.md

**Comment by Unders0n** [comment]
@EricDahlvang Thought simple example is working, we have this extension in botchat.js so the chatbot started when page loads instead of first user's message:
`var botConnection = new BotChat.DirectLine({        
            token: '@Model.Token'           
        });
...
(function sendEvent() {
            botConnection
                .postActivity({
                    type: "event",
                    value: '@Model.GroupId.ToString()',
                    from: { id: '@Model.UserId', name: '@Model.UserId' },
                    name: "userLoadPage"
                })              
        })();`

I've tried to do something similar to that with WebChat:
 `var botConnection = window.WebChat.createDirectLine({ token: "@Model.Token" });
(function sendEvent() {
        botConnection
            .postActivity({
                type: "event",
                value: '@Model.GroupId.ToString()',
                from: { id: '@Model.UserId', name: '@Model.UserId' },
                name: "userLoadPage"
            });`

but failed.  maybe you could advise smth?

**Comment by EricDahlvang** [comment]
```js
<body>
    <div id="webchat" />
    <script src="https://cdn.botframework.com/botframework-webchat/latest/webchat.js"></script>
    <script>
        
        var botConnection = window.WebChat.createDirectLine({ token: "@Model.Token" });
        window.WebChat.renderWebChat({
            directLine: botConnection,
            userId: '@Model.UserId'
        }, document.getElementById('webchat'));

        (function sendEvent() {
            botConnection
                .postActivity({
                    type: "event",
                    value: 'test',
                    from: { id: '@Model.UserId', name: '@Model.UserId' },
                    name: "userLoadPage"
                }).subscribe(function (id) {
                    console.log('"trigger userLoadPage" sent');
                })
        })();
    </script>
</body>
```
Please ask usage questions on Stack Overflow in the future.

**Comment by Unders0n** [comment]
@EricDahlvang above example not working correctly, atleast events flow are not the same as in botchat. Event userLoadPage never hits server, though with it declared in JS i have one more UpdateConversation event with adding the user (still 1st event is just adding bot). But following logic is broken and welcome message duplicated. Where to dig?

**Comment by EricDahlvang** [comment]
@Unders0n I would need to see your entire .js code, as well as the bot code handling the userLoadPage event.  (Note: this method does not rely on conversation update, but uses the event for the welcome message instead.)

As stated previously, please use Stack Overflow for How To questions: https://stackoverflow.com/questions/tagged/botframework  The GitHub repositories are for bugs and feature requests.
