### ISSUE TITLE
[Question] prompts.choice is not working correctly with API.ai

### ISSUE THREAD

**Issue by amitbend** [Microsoft/BotBuilder#2987]
## System Information (Required)
* SDK Language: Node
* SDK Version: 8.3.4
* Development Environment: LOCALHOST, AZURE_BOT_SERVICE
## Issue Description
I recently added NLU to my messenger bot using API.ai. I have a choice prompt in my bot (`prompts.choice()`), with buttons `builder.ListStyle['button']`.

I noticed that few of the choices are not working - and `retryPrompt` is invoked, and it happens because they are being matched to an intent from API.ai.

I'm looking for a solution that will isolate prompts from the NLU model or a different workaround.

P.S. I'm using `IntentRecognizerSet` with 2 API.ai recognizers, maybe I can add the default recognizer as the first item in the set? (not sure how)

I tried to debug the library code and it seems like `onRecognize` function on `PromptChoice` detecting the right choice, and the issue comes somewhere later.

**Comment by nwhitmont** [comment]
duplicate of https://stackoverflow.com/questions/44650686/prompts-choice-is-not-working-correctly-with-nlu-api-ai

**Comment by amitbend** [comment]
@nwhitmont alright, closing

**Comment by amitbend** [comment]
Reopened - no response on stackoverflow.

**Comment by stevengum97** [comment]
Can you provide your code so we can see it?

**Comment by amitbend** [comment]
Sure,
the prompt looks like this: 
`        (session, results, next) => {
            builder.Prompts.choice(
                session,
                'Choose one:',
                Object.keys(choicesObj), {
                    maxRetries: 1,
                    retryPrompt: 'We do not have info regarding that subject',
                    listStyle: builder.ListStyle['button']
                });
        },`
It is a part of a library.

the recognizer looks like:
`
    var r1 = new apiairecognizer('key1');
    var r2 = new apiairecognizer('key2');

    let set = new builder.IntentRecognizerSet({ recognizeOrder: builder.RecognizeOrder.series,stopIfExactMatch: true })
    .recognizer(r1).recognizer(r2)
`

**Comment by stevengum97** [comment]
Just to clarify, the user's response  to the prompt is unrecognized because of the API.AI recognizers activating and returning matched intents?

How are you plugging `set` into your bot? Are you using [`bot.recognizers = set;`](https://github.com/Microsoft/BotBuilder/blob/master/Node/core/lib/bots/Library.js#L30) ?

**Comment by amitbend** [comment]
@stevengum97 yes, I can see there is a matched intent (without any action attached)
I'm plugging it to the bot this way: `bot.recognizer(set)`

**Comment by stevengum97** [comment]
@amitbend it looks like it's similar to #2839 except you're wanting the recognizers to *not* fire/return an intent? You're aiming to stay inside of your current prompt and move through it without any interruptions, if I understand correctly. 

To handle this using the regular LuisRecognizer, we would use [`.onEnabled()`](https://github.com/Microsoft/BotBuilder/blob/master/Node/core/lib/botbuilder.d.ts#L3547) (sample [here](https://github.com/Microsoft/BotBuilder/blob/master/Node/examples/feature-onEnabled/app.js)), but this  method doesn't exist in [api-ai-recognizer](https://github.com/GanadiniAkshay/ApiAiRecognizer/blob/master/index.js).

I recommend taking the source code from there and creating a custom recognizer/adding to the instantiated api-ai-recognizers a similar method. For the case that enables/disables the recognizer, a check on the dialogStack would work well. Check if its `length >= 1`, if so disable the recognizers, as you're in a dialog and don't want to be interrupted.

You could also create a [custom prompt](https://github.com/Microsoft/BotBuilder/issues/2741#issuecomment-300946349); this way you should be able to also ignore results from API.ai.

Since the issue is regarding api-ai-recognizer (third-party) and a solution exists for this case (`LuisRecognizer.onEnabled()`)in BotBuilder SDK, I'm closing this issue for now. An alternative you could work with is placing the recognizers into an IntentDialog instead of having them at bot level, but this would change other aspects of how the bot works.

**Comment by amitbend** [comment]
@stevengum97 thanks for the informative answer.
It seems to be a variation of #2839, in my case, it does not either switch to the other dialog that capture the intent or matching it to one of the choices.
I will check out the solutions that you've mentioned and provide an update later.

**Comment by vishmonne** [comment]
hi @stevengum  can u help me in how to disable the luisRecognizer using .onEnabled() . i am not finding the solution code anywhere. Would be really helpful

**Comment by EricDahlvang** [comment]
Hi @vishmonne 

The example @stevengum shared can be found here: https://github.com/Microsoft/BotBuilder-v3/blob/master/Node/examples/feature-onEnabled/app.js

Another example can be found here: https://github.com/Microsoft/BotBuilder/issues/2670#issuecomment-300275154

You can also use .onFilter, as explained here: https://github.com/Microsoft/BotBuilder/issues/3530#issuecomment-332584273

---

The Microsoft Bot Framework team prefers that **how to** questions be submitted on [Stack Overflow](http://stackoverflow.com/search?q=%23botframework) so the entire community can benefit from the answer.
