### ISSUE TITLE
[Question] Bot have not appeared in Skype directory

### ISSUE THREAD

**Issue by Cartman720** [Microsoft/BotBuilder#3013]
Hi

We have been published our app and it has been approved, but we can't search it on Skype, because there is no result for our bot called "Finbot".
Can you say me what we need to do to see it on Skype.

Here it says that we have approved
![image](https://user-images.githubusercontent.com/12465135/27451227-6f4a4a08-579f-11e7-86b6-7fab59f53bb9.png)

Here I couldn't find bot on Skype.
![image](https://user-images.githubusercontent.com/12465135/27450056-854d36c0-579b-11e7-927b-c92ff4279cbb.png)

**Comment by JasonSowers** [comment]
It can take up to 24 hours for your bot to be searchable.  How long has it been?

**Comment by JasonSowers** [comment]
The way you would you add your bot on Skype is to go to [this page]
(https://dev.botframework.com/bots) and select your bot.  In the channels tab click where is says skype:  
  
![selectskype](https://user-images.githubusercontent.com/6301037/27457300-0e6fc14a-5759-11e7-81e5-931700e4e930.PNG)
  
this should take you to the page where you can add your bot on skype:  
  
![skypeadd](https://user-images.githubusercontent.com/6301037/27457326-2aace7a2-5759-11e7-9b6b-0bf12607812a.PNG)

**Comment by nwhitmont** [comment]
Skype bots are only searchable in the bot directory if they are "Featured" or otherwise highlighted by the Skype business team. 

As you can see on the help page [What Skype bots are available?](https://support.skype.com/en/faq/FA34655/what-skype-bots-are-available#joinlinkbots) - not all bots can be directly added via the directory. In the section [What bots can be added directly that are not available in the Skype directory?](https://support.skype.com/en/faq/FA34655/what-skype-bots-are-available#joinlinkbots) you can see examples of non-directory bots which can only be added via web link. 

For Bot Framework bots, the same scenario applies.  Your bot will only be searchable in the Skype bot directory if it is published and is a "Featured" bot.  Otherwise, the official way to add the bot is to share the "join" URL generated on the "Channels" page of the [Bot Portal](https://botframework.com).

**Comment by Cartman720** [comment]
Thank you guys for explanation!

**Comment by martinoss** [comment]
@JasonSowers 
Is it possible to add a non published bot using a link to skype web, like it works for the android client for example?

**Comment by JasonSowers** [comment]
Yes it should be
