### ISSUE TITLE
[Question] How register bot for search in Skype

### ISSUE THREAD

**Issue by asubbotin** [Microsoft/BotBuilder#3034]
Hello,

Skype have button for search bots http://clip2net.com/s/3LxWwzf
Let me know, how i can register/add my bot for this search?

Thanks!

**Comment by nwhitmont** [comment]
Skype bots are only searchable in the bot directory if they are "Featured" or otherwise highlighted by the Skype business team.

As you can see on the help page What Skype bots are available? - not all bots can be directly added via the directory. In the section What bots can be added directly that are not available in the Skype directory? you can see examples of non-directory bots which can only be added via web link.

For Bot Framework bots, the same scenario applies. Your bot will only be searchable in the Skype bot directory if it is published and is a "Featured" bot. Otherwise, the official way to add the bot is to share the "join" URL generated on the "Channels" page of the Bot Portal.

To view your bot's Skype "join" URL, go to the Channels page in the Bot Portal, right click on the "Skype" text and select "Copy Link Address".

Example Skype bot add-to-contacts "join" URL:

`https://join.skype.com/bot/257389ac-afdb-473a-9b98-1234567890`
