### ISSUE TITLE
[Question] Emulator and Skype will render markdown on the message's "text" element but will ignore markdown on the attachment's "text" elements

### ISSUE THREAD

**Issue by naqushab** [Microsoft/BotBuilder#3036]
## System Information (Required)
* SDK Language: C#
* SDK Version: 3.8.2.0
* Development Environment: LOCALHOST

## Issue Description
As already mentioned, this is down to both the channel (client - e.g. emulator, skype, facebook, your own directline client) implementing markdown support, since the text is sent as markdown in the json response.

However, at the moment you'll probably find that both the emulator and skype will render markdown on the message's "text" element but will ignore markdown on the attachment's "text" elements, e.g.

## Code Example
```
HeroCard heroCard = new HeroCard()
{
    Text= "Booo - no *markdown* supported here",
    Buttons = cardButtons
};
```
vs

```
var reply = activity.CreateReply("**Lovely lovely markdown**\n\n *yey!*");

var heroCard = new HeroCard()
{
    Text = "Booo - no *markdown* supported here",
    Buttons = cardButtons
};

reply.Attachments = new List<Attachment> {
  hero.ToAttachment()
};
```

## Expected Behavior
It should support Markdown

## Actual Results
Emulator and Skype will render markdown on the message's "text" element but will ignore markdown on the attachment's "text" elements

**Comment by JasonSowers** [comment]
@naqushab are you requesting this as an enhancement or trying to figure out a different way?

**Comment by JasonSowers** [comment]
From the testing I did it does not seem that you can use markdown in the card itself.

**Comment by naqushab** [comment]
Yes. But I want to apply some styling, add a new line in card's text. Is there a way I can?

**Comment by JasonSowers** [comment]
Can you show me an example of what you mean by adding a new line?  If you are just trying to send a line break "\n\n" was the only thing I could ever get to work, but I don't think that is your question because you showed me "\n\n" in your example.  Also you may want to look at [Adaptive cards](http://adaptivecards.io/).  They have TextBlock elements that may be useful for you.  [Samples here](https://github.com/Microsoft/AdaptiveCards/tree/master/samples), [Cool blog here](https://blog.botframework.com/2017/06/07/Adaptive-Card-Dotnet/). Good luck!
