### ISSUE TITLE
[Question] botbuilder middleware called on bot.beginDialog

### ISSUE THREAD

**Issue by bilby91** [Microsoft/BotBuilder#3097]
## System Information (Required)
* SDK Language: NODE
* SDK Version: 3.8.4
* Development Environment: LOCALHOST

## Issue Description
I'm having a strange behaviour that I'm not sure if it is correct. I'm doing some tests with the `ConsoleConnector` and using a custom `botbuilder` middleware. 

I have a dialog that is started by the user and in that dialog, the bot writes a reply to the conversation and then starts a new dialog with different users:

```
  lib.dialog('/', async (session, args) => {
    const users = await getUsers

    users.forEach(async (u) => {
      try {
        const newAddress = {}
        bot.beginDialog(newAddress, 'start:/welcome')
      } catch (error) {
        console.log(error)
      }
    })

    return session.endDialog("start")
  })
```

When beginDialog is called I'm getting the event in the `botbuilder` middleware that I have. I thought that `botbuilder` middleware is only called when the user sends a message to the bot and not when the bot is sending a message to user. Should I expect messages on my middleware when my bot is starting a new conversation with users ? Should that message be intercepted only by the `send` middlewares ?

**Comment by nwhitmont** [comment]
@bilby91 Middleware can handle both types of messages, sent by bot, and sent by user. 

The `botbuilder` middleware intercepts incoming messages, while the `send` middleware intercepts outgoing messages. The terminology is a bit counter-intuitive since incoming vs sending is from the perspective of the user instead of the bot, so technically "incoming" is sent from bot-to-user, while "send" is sending from user-to-bot.  Maybe we can update the docs to clarify.

More info:
- Docs: [Node SDK - Intercepting messages](https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-intercept-messages)
- Code example: [BotBuilder-Samples/Node/capability-middlewareLogging](https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node/capability-middlewareLogging)

**Comment by nwhitmont** [comment]
reopen if you have more questions
