### ISSUE TITLE
[Question] Pick up Office 365 authentication to Identify User?

### ISSUE THREAD

**Issue by neetgupta7** [Microsoft/BotBuilder#3116]
Hello
Can a bot pick up Office 365 authentication to Identify User. And if its possible how does bot code pick that up. 
e.g. I have a sharepoint online website where we plan to put the webchat control. Since user has already authenticated we would like him to not provide any more info on webchat to identify himself.

**Comment by iMicknl** [comment]
I am not very familiar with Sharepoint, but it is possible to pass custom parameters to the WebChat in order to identify an user. You can't use the [WebChat](https://github.com/Microsoft/BotFramework-WebChat ) via iFrame, since you need to be in control of the settings. 

The [WebChat documentation ](https://github.com/Microsoft/BotFramework-WebChat#easy-in-your-non-react-website-run-webchat-inline) describes how to create a custom WebChat via the DirectLine API. You can use the user id or an event to pass the right parameters to your bot. Beware that this happens client side, so design it in a safe way and don't trust user input. Encrypt the token you use for example.

Read more about passing an auth event to WebChat: https://github.com/Microsoft/BotBuilder/issues/1366#issuecomment-263129728

**Comment by nwhitmont** [comment]
@neetgupta7 Are you using .NET or Node SDK?

**Comment by neetgupta7** [comment]
.net

**Comment by nwhitmont** [comment]
>Since user has already authenticated we would like him to not provide any more info on webchat to identify himself.

It sounds like you already have the solution to your auth problem. "Since the user has already authenticated"... you don't need to do anything except put your webchat page where only logged-in users can view it.

For more information on O365 auth strategies, see: [Using Office 365 modern authentication with Office clients](https://support.office.com/en-US/article/Using-Office-365-modern-authentication-with-Office-clients-776c0036-66fd-41cb-8928-5495c0f9168a)

**Comment by neetgupta7** [comment]
@nwhitmont user has authenticated on sharepoint portal .  It how do I pass that to Bot service to tell it who the user is. Not sure why this has been closed.

**Comment by SFHAJJI** [comment]
>  user has authenticated on sharepoint portal . It how do I pass that to Bot service to tell it who the user is. Not sure why this has been closed.

@neetgupta7 Have you found the solution to that please ? I'm currently trying do that and i haven't found anything yet.
