### ISSUE TITLE
[Question] Skype Bot Not showing in directory?

### ISSUE THREAD

**Issue by michaelhutchful** [Microsoft/BotBuilder#3139]
Hi, I have published my bot, it says approved in the portal, but I can't still see it in Skype. I have search for articles on the publishing process, but I can't find much. My question is when do I see it in the the Skype directory or why can't I see it even after it is approved?

**Comment by nwhitmont** [comment]
Skype bots are only searchable in the bot directory if they are "Featured" or otherwise highlighted by the Skype business team. 

As you can see on the help page [What Skype bots are available?](https://support.skype.com/en/faq/FA34655/what-skype-bots-are-available#joinlinkbots) - not all bots can be directly added via the directory. In the section [What bots can be added directly that are not available in the Skype directory?](https://support.skype.com/en/faq/FA34655/what-skype-bots-are-available#joinlinkbots) you can see examples of non-directory bots which can only be added via web link. 

For Bot Framework bots, the same scenario applies.  Your bot will only be searchable in the Skype bot directory if it is published and is a "Featured" bot.  Otherwise, the official way to add the bot is to share the "join" URL generated on the "Channels" page of the [Bot Portal](https://botframework.com).

To view your bot's Skype "join" URL, go to the Channels page in the Bot Portal, right click on the "Skype" text and select "Copy Link Address".

Example Skype bot add-to-contacts "join" URL:

    `https://join.skype.com/bot/257389ac-afdb-473a-9b98-1234567890`
