### ISSUE TITLE
[Question] Pass data from web page to bot & start root dialog based on input data?

### ISSUE THREAD

**Issue by sayyednazeer** [Microsoft/BotBuilder#3140]
## System Information (Required)
* SDK Language:  .NET/C# 
* Development Environment:  LOCALHOST, AZURE_BOT_SERVICE

## Question Description

I am having a asp.net webpage after filling sum data on my page and then on click of submit button.
I want  to land the user to a new page over where he can see the BOT and do the conversation.

But before that i want to transfer some data from my webpage to BOT, because in my BOT i have two ROOTDIALOGE class.

1. GeneralTalkLuisDialog
2. BusinessTalkLuisDialog

so based on that data i want to call my dialog

## Code Example

A rough example
```cs
string myWebPageData="Business"

If(myWebPageData=="General")
{
  await SendAsync(activity, (scope) => new GeneralTalkLuisDialog());
}
elseif(myWebPageData=="Business")
{
  await SendAsync(activity, (scope) => new BusinessTalkLuisDialog());
}
else
{
 await SendAsync(activity, (scope) => new GreetingLuisDialog());
}
```
I am using Default WebChat for UI <iframe>.....</iframe>

**Comment by michaelhutchful** [comment]
I had a similar problem, i needed to pass sensitive data from a web page to the bot. What I did was create a new API controller in the bot and then call the end point from your web page.

API Controller C#

Regards Michael 

Sent from my Windows 10 phone

From: sayyednazeer
Sent: 15 July 2017 13:27
To: Microsoft/BotBuilder
Cc: Subscribed
Subject: [Microsoft/BotBuilder] C# PASS DATA FROM WEBPAGE TO BOT AND CALLEDROOTDIALOGE Based on data (#3140)

System Information (Required)
• SDK Language: .NET/C#
• Development Environment: LOCALHOST, AZURE_BOT_SERVICE
Question Description
I am having a asp.net webpage after filling sum data on my page and then on click of submit button.
I want to land the user to a new page over where he can see the BOT and do the conversation.
But before that i want to transfer some data from my webpage to BOT, because in my BOT i have two ROOTDIALOGE class.
1. GeneralTalkLuisDialog
2. BusinessTalkLuisDialog
so based on that data i want to call my dialog
Code Example
A rough example
string myWebPageData="Business"
If(myWebPageData="General")
{
await SendAsync(activity, (scope) => new GeneralTalkLuisDialog());
}
elseif(myWebPageData="Business")
{
await SendAsync(activity, (scope) => new BusinessTalkLuisDialog());
}
else
{
await SendAsync(activity, (scope) => new GreetingLuisDialog());
}
I am using Default WebChat for UI <iframe>.....</iframe>

**Comment by sayyednazeer** [comment]
@michaelhutchful 

can you show me some code example

**Comment by sayyednazeer** [comment]
@michaelhutchful 

Show me some sample code please ....

**Comment by michaelhutchful** [comment]
I will try and create a sample for you after work

Sent from Mail for Windows 10

**Comment by sayyednazeer** [comment]
@michaelhutchful 

Any update..?

**Comment by michaelhutchful** [comment]
Hi

https://github.com/michaelhutchful/PostDataToBot

I read through your question, I might have misunderstood it. But here is a bot with a rest API endpoint that allows you to send data to it. That’s is what you want right?

Sent from Mail for Windows 10

**Comment by JasonSowers** [comment]
@michaelhutchful  take a look at the [readme here](https://github.com/Microsoft/BotFramework-WebChat)  Towards the bottom of the page there is a section called **The Backchannel**  this may be what you are looking for to solve your problem

**Comment by michaelhutchful** [comment]
Very interesting, I didn’t even know this existed. Thanks so much

Sent from Mail for Windows 10

**Comment by sayyednazeer** [comment]
Thanks
@michaelhutchful  and @JasonSowers 

Ill check this.
