### ISSUE TITLE
Unable to give a delayed response after a form is completed

### ISSUE THREAD

**Issue by JasonBSteele** [Microsoft/BotBuilder#316]
Please refer to my SO post http://stackoverflow.com/questions/37243415/how-do-i-give-a-delayed-response-in-microsoft-bot-framework in which I explain that after completing a Form I give a message saying "thank you, please wait" and then I want to post another message 5 seconds later with the result of a calculation.

**Comment by willportnoy** [comment]
Two possible issues:

1. If the first message is delayed until the second message is sent, that's because we're saving one message to return as the inline message reply within the http method call.  You can fix this issue by using the AlwaysSendDirect_BotToUser IBotToUser implementation.

2. If you get "access denied", it could be that the IConnectorClient is instantiated without the proper credentials.  By default, these were coming from the app.config, but it's possible you may have decorated your controller with the credentials instead (and these would not be available to the IConnectorClient.  I recently committed a change so that the credentials were instantiated through the container, so that they could be overridden.

**Comment by JasonBSteele** [comment]
Thanks Will:

1. Not sure how to use the AlwaysSendDirect_BotToUser implementation from within my root LuisDialog.
2. The credentials are in the Web.Config and the only attribute on the controller is [BotAuthentication] .
@ejadib kindly responded to my SO post with a solution that appears to solve my issue:

> Try instantiating the client in the following way

```
using (var scope = DialogModule.BeginLifetimeScope(Conversation.Container, message))
{
     var client = scope.Resolve<IConnectorClient>();
     client.Messages.SendMessage(message);
}
```
But I'm not sure why this works or is necessary.
Thanks.

**Comment by willportnoy** [comment]
If you use the Task.Delay(TimeSpan).ContinueWith(_ => { context.PostAsync() } ) pattern, that ContinueWith method executes after the http response has finished and it likely confuses the IBotToUser implementation (it saves one message to return inline with incoming http request) and the message gets lost.  Instantiating the connector client directly allow you to send whatever message you like, even if it's a method that executes long after the initial http post has completed.
