### ISSUE TITLE
[Question] Skype does not send all messages to the bot

### ISSUE THREAD

**Issue by guathan** [Microsoft/BotBuilder#3207]
I have integration of other channels that works perfectly, however skype doing test it does not send all the messages to the BOT, for example I sent the following message:
1
2
3
4
5
6
7
8
9

And it just fell on the bot to 2 and 6. What can it be?

**Comment by nwhitmont** [comment]
@guathan 
1. Are you using .NET or Node SDK for Bot Builder?
2. Please post your bot code that produces the error so we can better assist you.
3. What is your bot name, bot handle and App ID as you registered the bot in the Bot Portal at https://dev.botframework.com?
4. Do you see any errors/warnings in the Skype section of the Channels page on Bot Portal? What are they? Include screenshot of errors.

**Comment by guathan** [comment]
1. Are you using .NET or Node SDK for Bot Builder?
_.NET

2. Please post your bot code that produces the error so we can better assist you.
[MessagesController.zip](https://github.com/Microsoft/BotBuilder/files/1179709/MessagesController.zip)


3. What is your bot name, bot handle and App ID as you registered the bot in the Bot Portal at https://dev.botframework.com?
Name - NOVIGO_HOMOLOG
_MicrosoftAppId - 5bd6648c-af09-4b9b-9761-289feef6a49b_

4. Do you see any errors/warnings in the Skype section of the Channels page on Bot Portal? What are they? Include screenshot of errors.
_No, there are no errors_No, there are no errors

**Comment by EricDahlvang** [comment]
Hi @guathan 

Is your bot currently published?  I tried communicating with it via webchat and skype, but neither of them successfully send a message.  Also, https://[yourboturi]/api/messages is not reachable.

**Comment by guathan** [comment]
I just created the bot in dev.botframework nothing else (since it already comes with skype and webchat) but the ip points to my machine and I only leave running the application when I go to test

**Comment by nwhitmont** [comment]
@guathan It sounds like the errors your are experiencing are due to your bot not being deployed to Azure cloud or published to Skype channel. 

If you want better reliability in your bot's message delivery, you need to deploy your bot to Azure or other cloud provider, and then publish your bot on the Skype channel. 

To publish your bot on Skype channel, navigate to the "Channels" page for your bot in the Bot Portal at https://dev.botframework.com and click the "Edit" pencil icon on the right-hand side of the page. Then click on the "Publish" option in the top nav menu, and fill out the required details, then click "Submit for Review" button at the bottom of the page.
![edit skype channel settings](https://user-images.githubusercontent.com/3075047/28734153-6d4d38e4-7394-11e7-8fa5-4eb1d5d6c0b7.png)
![select publish options](https://user-images.githubusercontent.com/3075047/28734157-7234037e-7394-11e7-8875-fe2f43b059ec.png)
![submit for review](https://user-images.githubusercontent.com/3075047/28734162-76755adc-7394-11e7-9765-2ed7360914d4.png)
