### ISSUE TITLE
[Feature Request] User-configurable Direct Line timeout duration

### ISSUE THREAD

**Issue by nwhitmont** [Microsoft/BotBuilder#3220]
As a user of the Bot Connector REST API, aka Direct Line, I would like to have the ability to configure the timeout length in seconds.

Thumbs up this comment to vote.

**Comment by McBacker** [comment]
I have opened an issue that also refers to the 15 seconds timeout. With the direct line channel you can send the message you want to the user when a timeout occurs...

If we at least could send a better message than "POST to xxxBot timed out after 15s" when using channels like Telegram and Facebook.

**Comment by nwhitmont** [comment]
relates to #3122

**Comment by BelvedereHenrique** [comment]
I'm having some trouble with that. Since there is no way to configure the timeout, DirectLine keep sending double, sometimes even triple messages to my bot.
Seens like it's trying again because the bot took too long to respond.
Is there any workaround on that for now?

**Comment by Ma3yTa** [comment]
@eanders-MS Is it possible to configure timeout for Telegram channel https://ibb.co/kN3osb ?

**Comment by eanders-MS** [comment]
@Ma3yTa What are you trying to accomplish? (Also, it is better to open a new issue than piggyback this one)

**Comment by Ma3yTa** [comment]
@eanders-MS I am trying to avoid messages like 'POST to nowinfinity_assistant timed out after 15s'. 
I opened new isssue https://github.com/Microsoft/BotBuilder/issues/3767

**Comment by wladneto** [comment]
Any good solution?

**Comment by benbrown** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team

**Comment by timkernighan** [comment]
@benbrown the same problem exists within v4. There is unnecessary messages about POST to endpoint failed (in Facebook and Telegram) with no way to suppress these messages or Increase timeout. Should I open a new issue, or is it better to reopen this one?

**Comment by Kadae** [comment]
Hahaha, 100500 years of this issues exists and Microsoft still closing eyes on this.

**Comment by Kadae** [comment]
The year is 2021. Still no fixes on this and issue is closed.

![source5loo](https://user-images.githubusercontent.com/965894/109418243-26c94e80-79e9-11eb-9275-5113de173df0.gif)

**Comment by Kadae** [comment]
Hello, @EricDahlvang!

Ok, don't touch 15 seconds timeout, but just make it silent and visible for developers only, not to the users. I just want to catch and hide this 500, 504, 503 errors from bot's messages, but I can't.
All what I have is "onTurnErrorHandler", but I can't hide timeout errors...

Why bot SENDING THIS timeout message to the user? Why bot report this back to the client right to the chats?
This is a only one problem for me in BotFramework, and this problem for me exists almost 4 years and looks like only one option is simple - just don't use BotFramework with Azure...

**Comment by EricDahlvang** [comment]
I do not understand.  I am not aware of a problem which has existed for four years but remains unsolved.  The Bot Framework protocol is restful, with a maximum time per call determined by the service between the client and the bot.  Not every activity type is a two way POST.  In the case of 'invoke' activities, the processing through the pipeline is synchronous. 

It sounds like the timeout errors you are referring to are from the service to the client?  Which client are you using, and which SDK?

Some other, in process methods, for handling long running operations include this dotnet sample:
https://github.com/microsoft/BotBuilder-Samples/tree/main/experimental/immediate-accept-adapter/csharp_dotnetcore

The javascript sdk provides an 'immediateAccept' parameter, for the Adapter:
https://github.com/microsoft/botbuilder-js/pull/2950

These are not published in the documentation, because long running operations should not be performed within the bot's web application, but rather via an external process, as demonstrated in this doc: https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-long-operations-guidance?view=azure-bot-service-4.0

**Comment by Kadae** [comment]
![image](https://user-images.githubusercontent.com/965894/109776629-9ecf8880-7c24-11eb-9ccd-44df50d5ffea.png)

**Comment by EricDahlvang** [comment]
Okay, this looks like an exception returned from the service when it cannot reach the bot.

For a feature request, or to file a bug against the channel service, please open an issue here:

https://github.com/microsoft/BotFramework-Services/issues
