### ISSUE TITLE
Missing buttons for Prompts.choice on Telegram

### ISSUE THREAD

**Issue by mikkhait** [Microsoft/BotBuilder#325]
I'm pretty sure it's a bug, but I kind of like it as a feature. Perhaps we can have a setting for it, something like:

```
session.Prompts.choice({showChoicesOnRePrompt: false})
```

**Telegram**
![screenshot 2016-05-20 13 53 32](https://cloud.githubusercontent.com/assets/1232731/15441878/57491cd2-1e92-11e6-9a48-32c3213e4ac7.png)

**Messenger**
![screenshot 2016-05-20 13 53 22](https://cloud.githubusercontent.com/assets/1232731/15441877/5744752e-1e92-11e6-95cc-ca42ce1748e2.png)

**Comment by tomlm** [comment]
Telegram should have given you a custom keyboard.  Did you not get a keyboard?

**Comment by eanders-MS** [comment]
@mikkhait Please check my understanding: Did Telegram show buttons for the initial prompt, but fail to display them on retry?

**Comment by mikkhait** [comment]
Actually, I never seen custom keyword from BotBuilder, I assumed it was per design. I get _on-screen_buttons
![screenshot 2016-05-20 14 17 21](https://cloud.githubusercontent.com/assets/1232731/15442387/aac35384-1e95-11e6-86b5-1152a3243ec2.png)

**Comment by mikkhait** [comment]
@eanders-MS, you are correct

**Comment by Stevenic** [comment]
It's possible I broke something telegram related. I've been re-working the prompts quite a bit. The buttons probably aren't showing up on re-prompt as that was a change I made.  The default ListStyle for Prompts.choice() & Prompts.confirm() is auto which means I pick the layout style. I do use buttons on Telegram but I don't show them on a re-prompt. I should probably apply the same logic I apply for Facebook which is to show them if there are 3 or less buttons.

**Comment by Stevenic** [comment]
I checked in a fix for this. The keyboard will always be shown on re-prompt like it does for telegram.  My original intention was to change the behavior for messenger. On messenger there's no real value in showing buttons more then once to the user since they're displayed inline and don't disappear. For Kik and Telegram where they use keyboards we do want to reshow the keyboard for re-prompts.  On messenger I do have an optimization to show buttons  with the reprompt if there are 3 or less buttons.

**Comment by Stevenic** [comment]
This will go out with next release.

**Comment by mikkhait** [comment]
Thanks @Stevenic
