### ISSUE TITLE
[Question] Error: "There was an error sending message to your bot. HTTP status code Unauthorised"

### ISSUE THREAD

**Issue by SyedAbdullahQamar** [Microsoft/BotBuilder#3279]
![screenshot_2](https://user-images.githubusercontent.com/30691226/29020541-d701ca5e-7b7b-11e7-92dc-d567c38105c8.png)

AppID = 51931722-cd5e-474f-8cdc-43612b0dd4e8
BotHandle = bots_m3tech
URL = https://bots.m3tech.com.pk/api/messages

I am getting this error "There was an error sending this message to your bot: HTTP status code Unauthorized."
I published my bot application on my Virtual Machine's IIS server with proper AppID and Password and register the URL but still unable to connect to start conversation with bot through Skype.
Note: I am using a bot template in Visual Studio 2015 with Microsoft.Bot.Builder version 3.9.0.

Kindly help me to solve these issues because now i am totally exhausted with Microsoft bot application. It seems that i will never be able to connect my simple bot application to the Skype.

**Comment by SyedAbdullahQamar** [comment]
![screenshot_3](https://user-images.githubusercontent.com/30691226/29020677-4522a8f0-7b7c-11e7-8cd7-1524104f32c6.png)

Is this part also important to fill or is it optional?

**Comment by JasonSowers** [comment]
Do you have a valid certificate on your VM?

**Comment by nwhitmont** [comment]
@SyedAbdullahQamar You will need a valid SSL certificate in order to ensure your bot's traffic is encrypted. 

The Bot Framework works with bots deployed on any cloud hosting service, as long as you have an internet-accessible endpoint and a valid SSL certificate.

The Bot Framework requires that the x.509v3 certificate exposed by your endpoint be current and valid. Most of the checks for "current and valid" are standard checks for server SSL certificates: the Certificate Name must match the hostname, it must not be expired, it must not be listed in a CRL, it must have the correct set of EKUs, etc.

Most importantly, your SSL certificate must chain to a root certificate authority trusted by Microsoft. The latest list of these CAs is available here: http://social.technet.microsoft.com/wiki/contents/articles/31634.microsoft-trusted-root-certificate-program-participants-v-2016-april.aspx

For more information on deploying your bot, see: https://docs.microsoft.com/en-us/bot-framework/deploy-bot-overview

Application Insights configuration is optional.

**Comment by SyedAbdullahQamar** [comment]
Yes i have a valid SSL on my VM.

**Comment by SyedAbdullahQamar** [comment]
Alhamdulillah my bot successfully added to the Skype and its working fine. Thanks alot for your cooperation guys. The issue was incorrect server time.

**Comment by JasonSowers** [comment]
Glad you got it working, good luck!
