### ISSUE TITLE
Prompt reminder

### ISSUE THREAD

**Issue by mikkhait** [Microsoft/BotBuilder#333]
I would like to have an option to send a _reminder_ to a user if he/she hasn't responded to a prompt for _n_ amount of time. Do you guys think this would be a good option to implement?

Give a text prompt
  and prompt text is "2x2=?"
When _n_ minutes passed
I want to send a reminder "Need a hint?"

If this is not a good fit for the framework, how to I go about implementing it?

**Comment by tkbox9** [comment]
Well, if I got it right. I believe you have a few options to do that. I guess the simplest one would be to implement a timer based event and check once the time is up if you got an answer from your question or make it invalid with a cancellation token if you receive it before time is up.

http://msdn.microsoft.com/en-us/library/system.timers.timer(v=vs.71).aspx

**Comment by willportnoy** [comment]
@tkbox9 is correct in that you can start a timer, and then use IConnectorClient to send "out of band" messages to gently prod the users to responding to a prompt.

What is less clear is how to change the dialog state based on timer expiration - we have some thoughts on responding to external events (such as the passage of time), but nothing concrete yet.

Tell me if you have any difficulties with the timer approach.

**Comment by mikkhait** [comment]
Thanks for the suggestions. I am, however, using a nodejs version. Let me give it a bit more thought, perhaps we can get @Stevenic involved too :)

**Comment by Stevenic** [comment]
@mikkhait as @willportnoy says this is kind of tricky because what you're wanting to do is gently re-prompt without advancing the dialog stack. I was just commenting on issue #361 about work I'm planning to add something I call __web actions__ which will provide a way to call into the middle of a waterfall based on some external event. That's so that you can continue a waterfall after sending a user a login link but the same work might help out here. As I do that work I'll think about using it to let you trigger a re-prompt but in the meantime you could look at the `basics-naturalLanguage` example to see how to trigger a proactive message using an external timer. The con here is that it uses `bot.beginDialog()` which will wipe out your dialog stack.  I've been planning to add a `bot.send()` which won't so I could potentially accelerate that work. This is all timely stuff as I'm about to re-write a bunch stuff in this area.

@willportnoy this all probably ties into the re-prompt work we've been talking about with IScorable.  The same re-prompt event that we'd trigger when coming out of a capture we could also let you trigger manually via an external timer event.  For me this might just surface via some `bot.reprompt()` method.

**Comment by mikkhait** [comment]
Got it. Thanks. I understand the direction now.

**Comment by v-thgratMSGit** [comment]
Closing this issue. Please open a new issue for further discussion if necessary. @Stevenic - reopen if you'd like to and/or provide the status of this enhancement.  Thanks!
