### ISSUE TITLE
[Question] Why does the Dialog flow start over when I send two consecutive messages to the bot?

### ISSUE THREAD

**Issue by mpicciolli** [Microsoft/BotBuilder#3408]
## Bot Info 
* Bot : https://mywellnesspartner-reavie2017-bot.azurewebsites.net
* SDK Platform: Node.js
* SDK Version: 3.9.0
* Active Channels: Skype, Facebook
* Deployment Environment: Azure App Service

## Issue Description
When I send two consecutive messages the dialog starts over.

## Example
![image](https://user-images.githubusercontent.com/17593928/29964906-f3f59962-8f0b-11e7-827d-14f7c79f7900.png)

## Expected Behavior
Why  doesn't the dialog flow continue ?

**Comment by stevengum97** [comment]
@mpicciolli, can you provide either the code or an example of code that generates this issue?

**Comment by mpicciolli** [comment]
Below, the example of code that generates this issue :

```
const builder = require("botbuilder");
const library = new builder.Library('welcome');
const practicalGuideService = require('../services/practicalGuide');
const bot = require("../");

const DEFAULT_PRACTICAL_GUIDE_1 = process.env.DEFAULT_PRACTICAL_GUIDE_1;
const DEFAULT_PRACTICAL_GUIDE_2 = process.env.DEFAULT_PRACTICAL_GUIDE_2;

library.dialog('showWelcomeMessage', [
    (session, args, next) => {
        bot.sendTyping(session, 3000).then(function () {
            session.send("welcome_title");
            bot.sendTyping(session, 5000).then(function () {
                session.send("welcome_subtitle");
                bot.sendTyping(session, 7000).then(function () {
                    builder.Prompts.text(session, "welcome_question");
                });
            });
        });
    },
    (session, args, next) => {
        bot.sendTyping(session, 3000).then(function () {
            builder.Prompts.myLuisPromptConfirm(session, "welcome_question_start_questionnaire", { listStyle: builder.ListStyle.none });
        });
    },
    (session, args, next) => {
        if (args.response) {
            session.send("welcome_start_questionnaire");
            session.beginDialog("questionnaire:newTechnoQuestionnaire");
        }
        else {
            bot.sendTyping(session, 3000).then(function () {
                session.send("welcome_end");

                practicalGuideService.getAll(session).then(practicalGuides => {

                    practicalGuides = practicalGuides.filter(practicalGuide => {
                        return practicalGuide.code == DEFAULT_PRACTICAL_GUIDE_1 || practicalGuide.code == DEFAULT_PRACTICAL_GUIDE_2
                    });

                    bot.sendTyping(session, 3000).then(function () {
                        session.beginDialog("practicalGuide:showPracticalGuide", { practicalGuides: practicalGuides });
                    });
                }).catch(err => {
                    session.send('Failed with message: %s', err.message);
                    session.endDialog();
                })

                session.endConversation();
            });
        }
    }
]).triggerAction({ matches: 'Greetings' });

module.exports = library;
```

Function to Send typing ;

```
function sendTyping(session, milliseconds) {
    session.sendTyping();
    return new Promise(function (resolve) {
        setTimeout(resolve, milliseconds)
    });
}
```

**Comment by nwhitmont** [comment]
@mpicciolli Lorsque j'ai testé votre bot, l'interaction de l'utilisateur était déroutante à cause du délai entre les messages. Peut-être supprimer le délai (aka sendTyping ()) entre les messages envoyés par le bot? De cette façon, l'utilisateur sait que le bot est en train de "parler" avant d'envoyer le message suivant.

Si vous avez une invite ouverte, ou si vous attendez que l'utilisateur réponde à une question, il est normal que le bot le reprogramme si l'utilisateur ne saisit pas la phrase attendue.

Il est possible que votre problème ne soit pas technique, mais plutôt un problème de conception. Je vous recommande de supprimer tous les sendTyping et retards des messages de votre bot et de voir comment cela peut changer et / ou améliorer l'expérience de conception de la conversation bot.

----
When I tested your bot, the user interaction was confusing because of the delay between messages.  Maybe remove the delay (aka sendTyping()) between messages sent by the bot? This way the user knows the bot is done "talking" before they send the next message.

If you have an open prompt, aka  you are waiting for the user to answer a question, then it is totally normal behavior for the bot to reprompt if the user does not enter the expected phrase. 

It's possible that your problem is not technical, but rather a design problem. I recommend you remove all the sendTyping and delays from your bot's messages and see how that can change and/or improve the bot conversation design experience.

**Comment by mpicciolli** [comment]
Thks @nwhitmont, when i remove all sendTyping, I don't have this problem. Unless, when you develop bots, you have to keep in mind that the bot have to look like an human. So delay between messages. is very important to humanize the conversation...

Maybe, have you a better solution to use sendTyping  function ?

**Comment by nwhitmont** [comment]
If you want to have a bot "look like a human" - that is a great goal, but I wouldn't sacrifice the actual functionality to achieve that goal. 

You will need to find another method to simulate those characteristics that doesn't impede the functioning of the bot itself.
