### ISSUE TITLE
[WebChat] Customization with Extending TypeScripts?

### ISSUE THREAD

**Issue by sreeharikm** [Microsoft/BotBuilder#3417]
We are using WebChat to build a custom UI for the bot. There are some requirements to display thumbnail/hero cards with additional text fields and image fields. Currently, we tried updating the tsx files from the repository, built it and created the botchat.js. Kindly clarify the below queries.

1. Is this the recommended method of extending the TypeScripts? If yes, how do we make the src code up to date with the updates in repository? 
2. Tried extending a file (say ActivityView.tsx and created ActivityViewExt.tsx) for implementing our custom changes, but the new file is not being taken up in the build.

Regards
Sreehari

**Comment by nwhitmont** [comment]
@danmarshall thoughts?

**Comment by nwhitmont** [comment]
@sreeharikm If you need to design custom card layouts, use the [Adaptive Cards](https://adaptivecards.io) JSON spec.

You can find examples and a layout visualizer here:
http://adaptivecards.io/visualizer/

**Comment by sreeharikm** [comment]
Thanks for the update, will check on Adaptive Cards.

**Comment by sreeharikm** [comment]
@danmarshall Tried the Adaptive Cards, the HttpAction is not working. The sample code give in the [documentation](https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-add-rich-card-attachments#adaptive-card) itself has the issue.

Any suggestions on the extending type scripts for custom functionalities? The worry is how do we incorporate further changes to the source code.

**Comment by danmarshall** [comment]
Hi @sreeharikm if you are only needing to add text and image fields then using AdaptiveCards will be an easier situation for you if you are concerned with code maintenance.

> The worry is how do we merge further updates if we directly modify the source code

This is a primary function of GitHub. Recommend you read GitHub's [Working with forks](https://help.github.com/articles/working-with-forks/) pages, with attention to *Syncing a fork*.

I'm going to close this issue here in BotBuilder, since this is related to Web Chat only. Feel free to open a new issue in the [Web Chat repo](https://github.com/Microsoft/BotFramework-WebChat).
