### ISSUE TITLE
[Question] Options in DialogTestBase?

### ISSUE THREAD

**Issue by AvishagCs** [Microsoft/BotBuilder#3420]
In DialogTestBase we have:
public enum Options { None = 0, Reflection = 1, ScopedQueue = 2, MockConnectorFactory = 4, ResolveDialogFromContainer = 8, LastWriteWinsCachingBotDataStore = 16 };

what is the difference between them and when I should prefer one to another?

Thanks.

**Comment by nwhitmont** [comment]
@AvishagCs Are you using .NET or Node.js SDK for BotBuilder?

**Comment by EricDahlvang** [comment]
Hi @AvishagCs 

There is no documentation explaining how the DialogTestBase Options are used.  However, looking through the source code here on GitHub, it is possible to determine when to use which options:

**Reflection**: instruct the DialogTestBase to use the ReflectionSurrogateModule class  (found here: https://github.com/Microsoft/BotBuilder/blob/fdb443a3257dd62e2bd87727afdea793820a2ec7/CSharp/Library/Microsoft.Bot.Builder.Autofac/Fibers/FiberModule.cs#L170 )  ReflectionSurrogateModule registers the StoreInstanceByFieldsSurrogate with AutoFac.  This will cause the BotBuilder to serialize fields using reflection.

**ScopedQueue**: instruct the DialogTestBase to queue messages in an InstancePerLifetimeScope.  More information about autofac scoping can be found here: http://docs.autofac.org/en/latest/lifetime/instance-scope.html#instance-per-lifetime-scope

**MockConnectorFactory**: this option does not appear to be used, since every call to DialogTestBase currently uses the MockConnectorFactory class (#LN 68).

**ResolveDialogFromContainer**: when provided, this option instructs DialogTestBase to use only DialogModule (and NOT DialogModule_MakeRoot).  You can see these classes here: https://github.com/Microsoft/BotBuilder/blob/31048a2173313c81a2db47efce6a8a869b4ec284/CSharp/Library/Microsoft.Bot.Builder.Autofac/Dialogs/DialogModule.cs  Currently, DialogModule_MakeRoot registers DialogModule, as well as a default IDialog<object>.  It also appears, based on the //TODO's present in DialogModule_MakeRoot, that the author of this code has some improvements in mind (not fully implemented).

**LastWriteWinsCachingBotDataStore**: instructs the DialogTestBase to change the CachingBotDataStoreConsistencyPolicy to LastWriteWins. The CachingBotDataStoreConsistencyPolicy is useful in determining how state conflicts are resolved.  For more information: https://docs.microsoft.com/en-us/bot-framework/troubleshoot-general-problems#how-can-i-fix-precondition-failed-412-or-conflict-409-errors

----
Note: The Microsoft Bot Framework team prefers that **how to** and **clarification** questions be submitted on [Stack Overflow](http://stackoverflow.com/search?q=%23botframework). The official [Bot Framework Github](https://github.com/Microsoft/BotBuilder/issues) repo  is the preferred platform for submitting **bug fixes and feature requests**.
