### ISSUE TITLE
[Question] Not able to connect Bot after deploying on Azure?

### ISSUE THREAD

**Issue by ersachit** [Microsoft/BotBuilder#3424]
Hi @nwhitmont, @JasonSowers I have created a Bot in **node.js**. Things are working fine when I run my bot using ngrok or when deploy it on heroku but it doesn't work when I deployed it on Azure. I am getting Error- cannot /GET message when I hit the url https://testbotquo.azurewebsites.net. I am not sure what could be the issue as I have got all success message as shown in [this](https://blog.botframework.com/2017/04/27/Deploying-Botframework-To-Azure-On-Linux/) tutorial.

Here I am giving details of my bot~
name- TestBotQuo
AppId- ad8927a9-c732-49db-a817-4da75c49d643
Bot handle- test_q_bot 
Url- http://testbotquo.azurewebsites.net

Also when I am trying to access the bot on bot framework using Test button, I am getting 'couldn't send retry' message.

Please check and let me know if you need any other information

**Comment by nwhitmont** [comment]
@ersachit The "cannot GET /" error is expected behavior unless you have specifically configured a default route handler (which is not necessary for the bot to function, but is nice to have).

Example:
```js
// configure a root status handler so we know our bot server is online
botServer.get('/', function (request, response, next) {
    let statusInfo = {
        name: 'botframework-azure-on-linux-starter',
        status: 'online',
        time: moment().format('MMM Do YYYY, hh:mm:ss')
    }
    response.send(200, statusInfo);
    next();
});
```

Also, sometimes it takes a minute for your deployment to update, depending on how recently you last deployed. 

Try deploying this example bot and let me know if that works.
https://github.com/nwhitmont/botframework-azure-on-linux-starter

**Comment by ersachit** [comment]
Thanks @nwhitmont for sharing the useful information. I got the issue, it was related to my github repository. Now things are working fine.
