### ISSUE TITLE
 I tried to connect to the web service , Facing issue like "WSDoAllReceiver: Request does not contain required Security header" error 

### ISSUE THREAD

**Issue by RaoVenka** [Microsoft/BotBuilder#3435]
In Bot application , I have consumed web service , through web service  calling the [web methods] , i have faced issue like " Exception: WSDoAllReceiver: Request does not contain required Security header
[File of type 'text/plain']" 

When I look at the code, everything seems fine to me. However, it is throwing "WSDoAllReceiver: Request does not contain required Security header" error everytime I tried to connect to the web service.

The same i have tested in Soap UI , everything is working fine after entering the user name and password .
could you please let me know whether i can pass user name and password in soap header , please provide some samples too.

Thanks & Regards ,
Venkateswara

**Comment by EricDahlvang** [comment]
Hi @RaoVenka 

Would you please provide the following information, so we can better assist you:

## Bot Info 
* Bot handle: 
* App ID: 
* SDK Platform: 
* SDK Version: 
* Active Channels: 
* Deployment Environment: 

## Issue Description


## Code Example


## Reproduction Steps
1.
2.
3.

## Expected Behavior


## Actual Results
