### ISSUE TITLE
[Feature Request] Edit Message Event (MS Teams)

### ISSUE THREAD

**Issue by santiagodoldan** [Microsoft/BotBuilder#3446]
## Bot Info
* SDK Platform: Node.js
* SDK Version: 3.8.4
* Active Channels: MS Teams, Slack

## Issue Description
I just wanted to know if it's going to be possible to get an event when a message is edited in MS Teams.

I found this post in stackoverflow https://stackoverflow.com/questions/40976069/microsoft-bot-framework-message-edit-event but it was created 9 months ago, maybe something changed.

Thanks

**Comment by nwhitmont** [comment]
@santiagodoldan You are talking about an outgoing webhook, which is not currently supported. Only incoming webhooks are supported.

**Comment by jmnsf** [comment]
@nwhitmont can you elaborate why this is different from a message added event? It's still a user action on the Teams client, it just changes an existing message instead of creating a new one.

I second the request for this feature. Sometimes large edits are made by users that could change the content of the message entirely, and not only are we unable to see those edits, but we don't even know they happened in the first place.
