### ISSUE TITLE
[Question] After installed the Bot application in IIS Server  I have faced issue like "The bot is remote, but the callback URL is localhost. Without tunneling software you will not receive replies"

### ISSUE THREAD

**Issue by RaoVenka** [Microsoft/BotBuilder#3461]
I have installed Bot application in IIS Service (i.e corporate server).

I tried to connect emulator with server name (Even I tried Server IP Address Also) I have faced issue like " The bot is remote, but the callback URL is localhost. Without tunneling software you will not receive replies. ".

Please find below Error screen shot for the same.

![image](https://user-images.githubusercontent.com/28774238/30425188-f65ac6f0-9965-11e7-8bd4-2ba3e39e192b.png)

I have configured ngrok (latest version ) also my machine not remote machine(Client server ).

The Same Code I have tried with localhost i was able reply the receive messages and expected as working fine.

Could you please help me to resolve the above error . Could you please some samples too . 

In IIS any settings i need to change or anything else i need to configure the setting to allow the network access or firewall access .

Thanks & Regards ,
Venkateswara

**Comment by EricDahlvang** [comment]
Please provide the following information, so we can better assist you:

* Bot handle: 
* Microsoft App ID: 
* Node or .NET SDK Platform: 
* Bot Builder SDK Version: 

Which machine are you running the emulator on?

Which machine are you running ngrok on?

Is the Microsoft App ID and Microsoft App Password present in the web.config (assuming this is a .net bot)?

This documentation might be helpful: https://docs.microsoft.com/en-us/bot-framework/debug-bots-emulator#remotehost

-----
The Bot Framework works with bots deployed on any cloud hosting service, as long as you have an internet-accessible endpoint and a valid SSL certificate.

The Bot Framework requires that the x.509v3 certificate exposed by your endpoint be current and valid. Most of the checks for "current and valid" are standard checks for server SSL certificates: the Certificate Name must match the hostname, it must not be expired, it must not be listed in a CRL, it must have the correct set of EKUs, etc.

Most importantly, your SSL certificate must chain to a root certificate authority trusted by Microsoft. The latest list of these CAs is available here:

http://social.technet.microsoft.com/wiki/contents/articles/31634.microsoft-trusted-root-certificate-program-participants-v-2016-april.aspx

**Comment by RaoVenka** [comment]
Ngrok and emulator are installed in my local machine. 
Is it mandatory to install  these two(ngrok and emulator ) into remote server instead of local machine. Please suggest me .

**Comment by EricDahlvang** [comment]
Ngrok is for tunnelling traffic. It is normally used for testing locally, when the bot is hosted locally.  If your bot is hosted on a corporate server, that might be the issue. Is the server accessible from the internet? Does it have a valid certificate as explained above?

**Comment by RaoVenka** [comment]
Could you please let me know which certificates i need to install in corporate server to resolve above mentioned issue.

How SSL certificate must chain to a root certificate authority trusted by Microsoft. Could you please provide some steps too.

Thanks & Regards ,
Venkateswara

**Comment by EricDahlvang** [comment]
Microsoft Trusted Root Certificate authorities list can be obtained here: http://social.technet.microsoft.com/wiki/contents/articles/31634.microsoft-trusted-root-certificate-program-participants-v-2016-april.aspx  

There are steps for installing a certificate here: https://technet.microsoft.com/en-us/library/cc754841(v=ws.11).aspx  and https://msdn.microsoft.com/en-us/library/cc750534.aspx

If you are not experienced with SSL and certificates, it might be better to have someone (corporate network administrator) assist you.

**Comment by OliverDolan** [comment]
I am also having a similar issue as described here, I am running the same code via visual studio on my local dev pc (win10) and on a cloud server (win server 2012) also started by visual studio. 

If i use ngrok command line and run via visual studio f5 (run) button things work fine on my dev pc, messages from both sides.

If i mimic the same setup on the server and also update the botframework website with different ngrok endpoint information I just get 401 all the time.

I have looked in the ngrok web interface and the packets look close enough that you could fairly say there were the same when using a diff tool. Slight differences in timestamps and the bearer token was partially different but most likely I assumed that would be normal due to different devices? 

To me it seems to be something strange when deployed on the server 2012 machine, no idea why it wont work... 

It is very strange to recieve 401 from everywhere even the bot framework test chat cannot post one way even though the endpoint is available from many devices and firewall disabled etc..

The fun thing is it is complaining about the credentials but they are stored in the web.config and retrieved via svn checkout so almost certainly are the same as well.
