### ISSUE TITLE
How to get notified when a response fails recognizer validation?

### ISSUE THREAD

**Issue by wbreza** [Microsoft/BotBuilder#348]
I have a series of forms with various data types.  I would like a way to receive a callback, capture exception or subscribe to an event when a message fails to match a recognizer.

ex) User answers a "date" field with a non-date value.  Right now my fields validate method only fires when the data type passes the underlying recognizer.

I've searched through the various APIs/docs and am unable to figure out a way to achieve this without wrapping the recognizer on all fields.

**Comment by chrimc62** [comment]
There is no way of doing this right now--sorry about that... :-(  Can you give me an idea of what specifically you are trying to do?  It is a little more difficult than it appears since "help" is not understood by the date time recognizer but falls back to a command recognizer.  If I understand your requirements better I can either create something specifically for this or keep it in mind for the more general approaches below.

Moving forward there will likely be a couple of choices:
1) We are slowly switching to dependency injection everywhere so that would allow you to wrap and replace something like the choice recognizer used in FormFlow.
2) We have started work on how to fall back to other dialogs.  (Look at IScoreable in the current SDK.)  We have not fully documented this or changed all the built-in dialogs to participate in it.  Once that work is done, other dialogs would have the chance to handle a message.
3) I eventually want to make it so you can plug in arbitrary dialogs into FormFlow steps.

**Comment by wbreza** [comment]
It is a bit involved but the basic idea is that I want to track how many invalid responses users get.  If it is detected that the user is having a hard time or is asking some other non-anticipated question in the middle of a form that we can route the user to a real person for support.

**Comment by chrimc62** [comment]
Your best bet with the current SDK is to implement IBotToUser to make your own middle ware that can examine every input and output message.  If you see something like "ice cream is not a choice" you can escalate to your human.
