### ISSUE TITLE
Facebook Messenger Connector Question

### ISSUE THREAD

**Issue by mikkhait** [Microsoft/BotBuilder#349]
This is not related to the framework, but rather Bot Connector Platform.

I was just curious, Having done integration with FB directly for our other bots we only needed to have _Facebook Page Access Token_ and _Verification_Token_.

When connecting via Bot Connector, I'm being asked for Facebook Page ID, Facebook App ID and Facebook Secret.

Could you shed some light why?

Thanks
<img width="906" alt="napkin 2 05-25-16 5 00 53 pm" src="https://cloud.githubusercontent.com/assets/1232731/15559894/f0a7d6dc-229a-11e6-9ca0-153c33135aa6.png">

**Comment by FX1** [comment]
Questions should not be answered here but...

This info is needed so that the bot knows where to get its code cause all the code is put on your page.
The app secrete is like a password hash that hasn't been decrypted yet.
Page id is for the code of your personal info and where all the code gets stored.
facebook access token is just to tell facebook that its a bot and it should be allowed.

The difference between Facebook access token and verify token is that microsoft verifies that the bot is active with verify token and facebook verifies its a bot with facebook access token giving it access.

all the facebook id and pages are for info about your bot that you give to other people so you would have to make a page about your bot and give it that url and id.

**Comment by tomlm** [comment]
Facebook requires you to call an API to associate the pageid with the appid.  
We call that API for you, which means we need the pageId

**Comment by mikkhait** [comment]
thanks @tomlm
