### ISSUE TITLE
Exception: Entry point was not found.

### ISSUE THREAD

**Issue by Enghouse-CCSP-PS** [Microsoft/BotBuilder#3523]
Hello, 
We are using self hosted environment, loading dialogs dynamically and currently at version 3.9.0, which is worked fine so far. However when we tried to update to 3.9.1 we've got following issue:
Exception: Entry point was not found.
 at Microsoft.Bot.Builder.FormFlow.IFormBuilder`1.Build(Assembly resourceAssembly, String resourceName)\r\n
 at FirstImplementation.FirstDialog.BuildJsonForm(String strPath)

        private IForm<JObject> BuildJsonForm(string strPath)
        {
            using (var stream = File.OpenRead(strPath))
            {
                var schema = JObject.Parse(new StreamReader(stream).ReadToEnd());
                var formBuilder = new FormBuilderJson(schema);
                var addFields = formBuilder.AddRemainingFields();
                var build = addFields.Build();
                return build;
            }
        }

I've tried to [have a look](https://github.com/Microsoft/BotBuilder/compare/botbuilder@3.9...botbuilder@3.9.1) where can possible be a problem, but seems like nothing related was changed. Any thoughts on this?

Still haven't tried 3.10.1, since it's not on NuGet yet

**Comment by EricDahlvang** [comment]
@Enghouse-CCSP-PS please share the .json of the form you're loading.

**Comment by Enghouse-CCSP-PS** [comment]
[ServiceSelect.txt](https://github.com/Microsoft/BotBuilder/files/1366665/ServiceSelect.txt) (Extension should be changed to .json) - this is the loaded dialog
[CustomerEntryDialog.txt](https://github.com/Microsoft/BotBuilder/files/1366663/CustomerEntryDialog.txt) (Extension should be changed to .cs) - this is the class implementing IDialog<object> for this dialog

**Comment by Enghouse-CCSP-PS** [comment]
Now tested with 3.11.0 from nuget and getting the same issue. 
Any help?

**Comment by vovanb** [comment]
@EricDahlvang any update? Why new version broke existing bot and no release notes what has been changed?

**Comment by EricDahlvang** [comment]
@vovanb I'm not sure what has changed that could be causing this.  I realize there are no release notes, and this is causing frustration.  The Bot Framework team does their best to not break existing bots.  Nonetheless, please keep in mind that the Microsoft Bot Builder is currently a preview product (hopefully will be out of preview later this year).

@Enghouse-CCSP-PS I took the [AnnotatedSandwichBot](https://github.com/Microsoft/BotBuilder/tree/ff6f0159e7207fb228620af9d6a49b960a4c9c3a/CSharp/Samples/AnnotatedSandwichBot) sample, changed the MessagesController to use **MakeJsonRootDialog**, removed the references to the local Builder, Builder.Autofac, Connector, and Formflow.Json.  Then, added Microsoft.Bot.Builder v3.11 and Microsoft.Bot.Builder.FormFlow.Json v3.1.3.  The bot functions as expected. I'm unable to reproduce the issue here. 

When you updated to 3.11.0, did you also update Microsoft.Bot.Builder.FormFlow.Json to the latest version? https://www.nuget.org/packages/Microsoft.Bot.Builder.FormFlow.Json/

Can you provide a stack trace, when you receive "Entry point was not found"?

**Comment by Enghouse-CCSP-PS** [comment]
@EricDahlvang Thanks for starting an investigation.
To your question, everything related to MS Bot was updated from NuGet, and FormFlow.Json was last updated in May, so we are definitely using the latest one. 
Attaching trace and FirstDialog.cs file (since stack goes from there) hopefully it will explain something.

[Trace.txt](https://github.com/Microsoft/BotBuilder/files/1389927/Trace.txt)
[FirstDialog.cs.txt](https://github.com/Microsoft/BotBuilder/files/1389930/FirstDialog.cs.txt)

**Comment by EricDahlvang** [comment]
@Enghouse-CCSP-PS It seems there have been no changes to the relevant files in the SDK and I'm unable to reproduce this.    

Are you able to share your complete bot code?

**Comment by Enghouse-CCSP-PS** [comment]
@EricDahlvang yes, can we send it privately?

**Comment by EricDahlvang** [comment]
@Enghouse-CCSP-PS Yes, please find my email address on my GitHub profile page: https://github.com/EricDahlvang

**Comment by EricDahlvang** [comment]
@Enghouse-CCSP-PS 

Have you tried the newest .FormFlow.Json?
 https://www.nuget.org/packages/Microsoft.Bot.Builder.FormFlow.Json/3.12.2.4

Please let me know if you are still experiencing this problem with the latest libraries.

**Comment by Enghouse-CCSP-PS** [comment]
We've used sources for couple of versions, but now with the latest version on NuGet it's working good. Seems like issue is fixed and should be closed.
Thanks.
