### ISSUE TITLE
LuisRecognizer : how to change the default threshold from 0.1 to something else?

### ISSUE THREAD

**Issue by ubreddy** [Microsoft/BotBuilder#3530]
## Bot Info 
* Bot handle: 
* App ID: 
* SDK Platform: nodejs
* SDK Version: 3.9.1
* Active Channels: web
* Deployment Environment: azure

## Issue Description

Could not find a property or method that would set the default threshold to recognize intent. i.e. if the intent score is less than threshold None intent should be picked.
## Code Example

recognizers.push(new builder.LuisRecognizer(commonModel));
    let commonIntentDialog = new builder.IntentDialog({ recognizeMode: builder.RecognizeMode.onBegin, recognizers: recognizers });
    
## Reproduction Steps
1.
2.
3.

**Comment by stevengum97** [comment]
You're not placing the threshold inside of the LuisRecognizer itself. This is due to if you're using more than one intent recognizer, you're going to want to handle all of the scores together as opposed to setting thresholds for each recognizer individually. 

In this case, since you're using the IntentDialog class you'll want to set your threshold in [`IIntentDialogOptions`][IIDO] under the property [`intentThreshold`][Threshold]. 

```js
recognizers.push(new builder.LuisRecognizer(commonModel));
let commonIntentDialog = new builder.IntentDialog({ 
  recognizeMode: builder.RecognizeMode.onBegin,
  recognizers: recognizers,
  intentThreshold: 0.6 // arbitrarily selected
});
```

You can also shorten your code by doing something like the following:

```js
let recognizers = [ new builder.LuisRecognizer(commonModel) ]; // removes recognizers.push()
let commonIntentDialog = new builder.IntentDialog({
  recognizeMode: builder.RecognizeMode.onBegin,
  recognizers: recognizers,
  intentThreshold: 0.6
});
```

Lastly, if you do wish to set it up on an individual recognizer level, you can also use the `.onFilter()` method. By using this method you can manually bump up any scores to the threshold you wish to implement.

```js
let recognizer = new builder.LuisRecognizer(commonModel)
  .onFilter(function(context, result, callback) {
    if (result.intent != 'None' && result.score < 0.6) {
      callback(null, { score: 0.6, intent: result.intent });
    } else {
      callback(null, result);
    }
  });

let recognizers = [ recognizer ]; 
let commonIntentDialog = new builder.IntentDialog({
  recognizeMode: builder.RecognizeMode.onBegin,
  recognizers: recognizers,
  intentThreshold: 0.6
});
```

  [IIDO]:https://docs.botframework.com/en-us/node/builder/chat-reference/interfaces/_botbuilder_d_.iintentdialogoptions.html
  [Threshold]:https://docs.botframework.com/en-us/node/builder/chat-reference/interfaces/_botbuilder_d_.iintentdialogoptions.html#intentthreshold

**Comment by ubreddy** [comment]
Thank you. this works.
