### ISSUE TITLE
[Direct Line] How to trigger specific dialogs via URL endpoint?

### ISSUE THREAD

**Issue by Kannaj** [Microsoft/BotBuilder#3665]
## Bot Info 
* App ID: 745ff47b-893c-4438-a83d-699bd57b86ec
* SDK Platform: Node.js
* Active Channels: Skype,Direct Line, etc
* Deployment Environment: Auzure Bot Service

## Issue Description
I'm currently maintaining two repos with one handling the bot logic and one for a custom chat interface via the Directline API. One roadblock i'm facing is that i would like to trigger a specific dialog if the user enters a custom URL such as `https://foo.com/?dialog=bar` which in the case would trigger the `bar` dialog. Since the directline repo will not have access to the Bot object , is there anyway i can send a POST request to the bot repo (along with conversation ID and User ID) to trigger specific dialogs?

## Code Example
If both the bot and directline reside in the same repo , the code will probably look something like this
```javascript
return new Promise((resolve, reject)=>{
        var _directlineAddress = {
            bot: {"id":config.BOT.ID, "name": config.BOT.HANDLE},
            channelId: "directline",
            serviceUrl: config.BOT.DIRECTLINE_URL,
            useAuth: true,
            user:{"id": userId}, 
            "conversation": {"id": conversationId}                                    
        }
        if(params.options){
            var _re = /^\?(\w+)*=(\w+)*/
            var _programType = _re.exec(params.options);

            if (_programType[1] === "foo") {
                var _dialogId = "*:/foo";
            }
            else {
                var _dialogId = "*:/" + _programType[1];
            }

        } else {
            var _dialogId = "*:/";           
        }
        bot.beginDialog(_directlineAddress, _dialogId, _specialParams, function(err){
            else{
                resolve();
            }
        });
    })
};
```

but i do not have access to the bot object anymore , is it possible to send a POST request somehow to the bot to start the specific dialog?

**Comment by nwhitmont** [comment]
@Kannaj Check out this article on [Sending Proactive Messages](https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-proactive-messages) - it explains a lot of the concepts you need to be familiar with in order to achieve your goals here.

You will also find a great code example demonstrating proactive messages here:
https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node/core-proactiveMessages

There is also a demonstration of sending dialog-based proactive message here:
https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node/core-proactiveMessages/startNewDialog

The key element is to save the user's address information, found in the `session.message.address` object, so that your bot can know where to send the message later.  As long as you have the users address information, you can trigger a proactive message via a custom URL endpoint defined by your bot.
