### ISSUE TITLE
Expose Message property of DialogContext

### ISSUE THREAD

**Issue by DavePilks** [Microsoft/BotBuilder#368]
There is a private field on the `DialogContext` object that contains the `Message`. Is there a reason that this is not exposed? It has some pretty useful information that we could make use of.

**Comment by willportnoy** [comment]
The Message is usually passed directly to the Dialog on the resume callback MessageReceived (after context.Wait(MessageReceived) is scheduled).

We don't expose that Message because there isn't always a message - for example, in a proactive bot, the bot isn't running because it was sent a message, since it is initiating the conversation.

**Comment by willportnoy** [comment]
I'm going to close this item for now - feel free to re-open to discuss further.
