### ISSUE TITLE
[Direct Line] My bot's first message appears very slow?

### ISSUE THREAD

**Issue by mitijain123** [Microsoft/BotBuilder#3717]
## Bot Info
* SDK Platform: Node.js
* SDK Version: 3.10.1
* Active Channels: Direct Line
* Deployment Environment: Amazon

My First message appears very slow, all other message are relatively fast.
Let me know how can I improve the performance for bot builder.

When Bot WebChat Direct Line is getting connected to  BotBuilder, it make a api call
https://directline.botframework.com/v3/directline/conversations , is there a way I can bypass it.

**Comment by iantje31** [comment]
I noticed the same behaviour

**Comment by nwhitmont** [comment]
@mitijain123 This is a known issue with Direct Line. 

It's not a good idea to try to disable API calls because your bot will not function correctly.

It is totally normal for the first message on conversation initiation to take longer to resolve. Once the conversation gets going, there shouldn't be any such issues.

One way to address this is to ping your bot on regular intervals using automated scripts.

**Comment by mitijain123** [comment]
@nwhitmont How do we tell a new user that the first message of the bot will take longer than usual?  The new user will not be aware that we are processing the first message.
