### ISSUE TITLE
[Question] The bot suddenly stopped working?

### ISSUE THREAD

**Issue by zxy66481** [Microsoft/BotBuilder#3719]
I did not modify any code, before or after the good now no matter what is sent can not be sent, error messages for the server internal error, Luis Service has been purchased, but still can not be resolved, but also updated Luis's key and ID, ask for help, thank you very much
![_20171106154148](https://user-images.githubusercontent.com/32949019/32430136-e71966d4-c308-11e7-93c2-693a00ce04a1.png)

**Comment by nwhitmont** [comment]
@zxy66481 Please provide your bot's App ID so we can better assist you.

For reference, are you developing with .NET or Node.js SDK for BotBuilder?

**Comment by zxy66481** [comment]
. NET robot, ID I can't provide, preliminary judgment is Luis's problem

**Comment by EricDahlvang** [comment]
Hi @zxy66481 

Thanks for reporting your issue to us. However, there is currently no known system wide problem that explains what you are experiencing.  We need more information in order to assist you.  We would not ask for the app id if there were a valid reason to keep it private (notice we never ask for the Microsoft App Password, or channel secrets, as these should be kept private).

If you cannot provide us with the information we've requested in the New Issue template https://github.com/Microsoft/BotBuilder/issues/new then please suggest to us how we should help you resolve this issue?

**Comment by zxy66481** [comment]
I'm now releasing the robot and testing it, when I send messages more than once, there will be one or two times to return the correct information, the other time to return to my robot code has a problem, so you can prove that the code is not a problem, I think it should be Luis has failed, but has purchased the Luis Service, and updated the key, But the problem persists, please help me, thank you very much @EricDahlvang 
![_20171107094952](https://user-images.githubusercontent.com/32949019/32473102-c8773ae2-c3a0-11e7-9359-a719f27eafcd.png)

**Comment by zxy66481** [comment]
I have found the cause of the problem is Luis exceeded the quota, but I have already purchased the service, please help me, thank you very much!

**Comment by EricDahlvang** [comment]
@zxy66481 Maybe something here will help: https://docs.microsoft.com/en-us/azure/cognitive-services/luis/manage-keys

**Comment by zxy66481** [comment]
Thank you for your help, the problem has been solved
