### ISSUE TITLE
[Question] How to create callback for an external webpage to use a AJAX request to continue the Conversation?

### ISSUE THREAD

**Issue by KeirSweeney** [Microsoft/BotBuilder#3731]
## Bot Info 
* SDK Platform: .NET
* SDK Version: 3.11.0
* Active Channels: Web Chat, FB
* Deployment Environment:  Azure App Service

## Issue Description

I'm trying to create a custom callback URL for an external web view once an action has been completed on that page. I created a separate Controller Action to handle the API call. The conversation reference is passed to the web view and then the conversation reference is sent back to the bot. I need the bot to wait for the response from the web view and then continue the conversation depending on the response however I am not sure how to ask the bot to wait for a response from an external source? Currently I am calling the controller in code to try and trigger the ResumeAsync however it is not working.

## Code Example
``` 
private async Task MessageReceivedAsync(IDialogContext context, IAwaitable<IMessageActivity> result)
        {
            var messagesController = new MessagesController();
            var message = await result;
            var reference = new ConversationReference(context.Activity.Id, context.Activity.From, context.Activity.Recipient, context.Activity.Conversation, context.Activity.ChannelId, context.Activity.ServiceUrl);

            await messagesController.Callback(reference);
        }
 ```

```        
[HttpPost]
[Route("api/callback")]
public async Task <HttpResponseMessage> Callback (ConversationReference reference)
{
    var activity = reference.GetPostToUserMessage();
    activity.Text = "Test";
    await Conversation.ResumeAsync(reference, activity);
    return Request.CreateResponse(HttpStatusCode.OK);
} 
```

## Expected Behavior
When the "api/callback" action is called, the conversation continues from where it left off.

## Actual Results
No exceptions are thrown, after ` await Conversation.ResumeAsync(reference, activity);` executes, a step into/over breaks doesn't show the next step/ what is executed next.

If anyone else has suggestions of an alternative way to do this, I am all ears.

**Comment by JasonSowers** [comment]
If you haven't already I would try debugging with the SDK to see if you can get any more information about what exactly is happening.  There is a good guide here https://blog.botframework.com/2017/07/03/debug-bot-builder-source/.  See if that helps at all and let us know.

**Comment by KeirSweeney** [comment]
Thanks for the tip @JasonSowers. I added the projects and stepped through. The code hangs on the line `await gate.Gate.WaitAsync(token);` in the below function:
```
async Task<IDisposable> IScope<T>.WithScopeAsync(T item, CancellationToken token)
{
    // manage reference count under global mutex
    KeyedGate gate;
    lock (this.gateByItem)
    {
        gate = this.gateByItem.GetOrAdd(item, _ => new KeyedGate());
        ++gate.ReferenceCount;
    }

    // wait to enter this item's semaphore outside of global mutex
    await gate.Gate.WaitAsync(token);

    return new Releaser(this, item);
}
```
After that line is called no other code is executed, this one is baffling me :(

**Comment by EricDahlvang** [comment]
These samples on Proactive Messaging might help: https://github.com/Microsoft/BotBuilder-Samples/tree/45d0f8767d6b71b3a11b060c893521d5150ede7f/CSharp/core-proactiveMessages

There's also this example, that uses ConversationReference: https://github.com/Microsoft/BotBuilder-Samples/blob/6b3df2c0b323d56de5620d9cc82b876367c009ff/CSharp/core-CreateNewConversation/README.md

I'm not sure I fully understand the problem scenario you are solving.  The code posted in the MessageReceivedAsync method of the code example provided, appears to be attempting to resume a conversation while in the middle of an existing dialog of the same conversation.  Since the ConversationId of the activity being processed by MessageReceivedAsync is the same as the ConversationId of the activity being processed by Callback, there is a deadlock.  Only one message per conversation can be processed at a time.  There is a semaphore keyed on ConversationId in LocalMutualExclusion  https://github.com/Microsoft/BotBuilder/blob/497252e8d9949be20baa2cebaa6ce56de04461cf/CSharp/Library/Microsoft.Bot.Builder/Base/Scope.cs#L64 (this is why gate.Gate.WaitAsync() is "hanging").

**Comment by KeirSweeney** [comment]
@EricDahlvang Yes you are correct. I realised this error and refactored my implementation and now it's working as expected. 
I solved this by serialising the ConversationReference and Activity to a JSON object, exposed a separate endpoint in the Bot Application and posted that JSON data to it using Postman. The function then deserialized the JSON, and called Coversation.ResumeAsync with the deserialized parameters. It continued the conversation that was waiting and worked as intended.

Thank you for your help on this.
