### ISSUE TITLE
[Node.js SDK, FB Messenger] Why are my bot changes are not getting deployed to Messenger immediately?

### ISSUE THREAD

**Issue by mitijain123** [Microsoft/BotBuilder#3768]
SDK Platform: Node.js
SDK Version: 3.10.1
Active Channels: Facebook Messenger
Deployment Environment: Amazon

When I had published my bot server, I had set the welcome message as "Welcome to luxury experiences. Tell us what you’d like to do."
Facebbok Messenger also got the same welcome message.

But then we changed the welcome message from server to "Welcome to a world of luxury experiences"
Facebbok Messenger getting the old message as "Welcome to luxury experiences. Tell us what you’d like to do.".

I want to know what can be the issue here, It is working fine with DirectLine Channel.

**Comment by tiloc** [comment]
+1. I had the same issue a while back. I had related it to the support at the bot framework portal. We were never able to find the root cause, but it disappeared after approx. 1 day. My suspicion was that due to some reliability/distribution magic on Azure it was still pointing to an outdated instance of my software for a while, but that could never be confirmed. BTW: The Skype channel also happened to be affected, while DirectLine / Web Chat were not.

**Comment by nwhitmont** [comment]
@mitijain123 Thanks for reporting the issue. 

For reference, what duration of time are we talking about here?  It's not uncommon for there to be a delay propagating out the changes to external channels like Messenger. 

Were the changes still not visible after 1 hour? 6 hours? 12 hours? more than 24 hours?  Please be more specific.

**Comment by mitijain123** [comment]
@nwhitmont sorry for late reply.

It is more then 24 hours now and still not reflecting.

**Comment by mitijain123** [comment]
@nwhitmont any solution for this? we are still facing this issue.

**Comment by JasonSowers** [comment]
Please open a new issue with you are still experiencing problems.  There's not much we can help with on this issue since AWS is your deployment environment and the channel is Facebook.  This seems completely unrelated to the botbuilder SDK.
