### ISSUE TITLE
[WebChat] Issues with "welcome message" onConversationUpdate?

### ISSUE THREAD

**Issue by Enghouse-CCSP-PS** [Microsoft/BotBuilder#3770]
* SDK Platform: .NET 
* SDK Version: 3.11.0.0
* Active Channels: WebChat
* Deployment Environment:  ngrok 

## Issue Description
In implementation of Welcome Message on ActivityTypes.ConversationUpdate  we return JSON dialog (the example from https://github.com/Microsoft/BotBuilder/tree/master/CSharp/Samples/AnnotatedSandwichBot as is). 
With Emulator all was working fine, but when testing in webchat it displayed first time on ConversationUpdate, but after selecting first choice in menu, selection ignored and dialog reloaded again, and then it is working ok.

## Code Example
```cs
       public async Task<HttpResponseMessage> Post([FromBody]Activity activity)
        {
            if (activity.Type == ActivityTypes.Message)
            {
                //ConnectorClient connector = new ConnectorClient(new Uri(activity.ServiceUrl));
                // calculate something for us to return
                //int length = (activity.Text ?? string.Empty).Length;

                // return our reply to the user
                //Activity reply = activity.CreateReply($"You sent {activity.Text} which was {length} characters");
                //await connector.Conversations.ReplyToActivityAsync(reply);

                await Conversation.SendAsync(activity, MakeJsonRootDialog);
            }
            if (activity.Type == ActivityTypes.DeleteUserData)
            {
                // Implement user deletion here
                // If we handle user deletion, return a real message
            }

            else if (activity.Type == ActivityTypes.ConversationUpdate)
            {
                IConversationUpdateActivity iConversationUpdated = activity;
                if (iConversationUpdated != null)
                {
                    ConnectorClient connector = new ConnectorClient(new System.Uri(activity.ServiceUrl));

                    foreach (var member in iConversationUpdated.MembersAdded ?? System.Array.Empty<ChannelAccount>())
                    {
                        // if the bot is added, then
                        if (member.Id == iConversationUpdated.Recipient.Id)
                        {
                            await Conversation.SendAsync(activity, MakeJsonRootDialog);
                        }
                    }
                }
            }

            else if (activity.Type == ActivityTypes.ContactRelationUpdate)
            {
                // Handle add/remove from contact lists
                // Activity.From + Activity.Action represent what happened
            }
            else if (activity.Type == ActivityTypes.Typing)
            {
                // Handle knowing tha the user is typing
            }
            else if (activity.Type == ActivityTypes.Ping)
            {
            }
            
                
            
            var response = Request.CreateResponse(HttpStatusCode.OK);
            return response;
        }
```
## Reproduction Steps
1. Start over in WebChat Test
2. Select Any options
3. Dialog reloaded again

## Expected Behavior
Same as in Emulator we expect that Dialog will be fully functional in ActivityTypes.ConversationUpdate event same as in ActivityTypes.Message

## Actual Results

![bot](https://user-images.githubusercontent.com/30227436/32737146-f7df800e-c8a1-11e7-8d2b-ea066a607ecb.gif)

**Comment by JasonSowers** [comment]
This is probably caused by having this line of code twice `await Conversation.SendAsync(activity, MakeJsonRootDialog);`  Without having your full project I cannot confirm this 100%.  To me it seems your flow is working like this, the user connects => send the welcome message (in your case start a form) the user clicks a button, and a message is sent.  At this point, your code executes this line again `await Conversation.SendAsync(activity, MakeJsonRootDialog);` which starts the form over then proceeds to flow as expected after that.

My suggestion is to change the code in your welcome message to something else.  Maybe you could prompt "Would you like a sandwich" with a yes and no button or "Please type anything to get started."

**Comment by Enghouse-CCSP-PS** [comment]
Thanks for reply. What if I want to use same dialog in welcome and not "something else" ? And why is Emulator behavior different from Webchat?
Attached solution
[jsonSample.zip](https://github.com/Microsoft/BotBuilder/files/1479008/jsonSample.zip)

**Comment by JasonSowers** [comment]
I was unable to get you bot working in webchat at all, I think you may have some issues with your web config. The keys "MicrosoftAppId" and "MicrosoftAppPassword" were all lowercase as well as the value for MicrosoftAppId "cnrnq64xxxxxxxxxxxxxxxx".  Try generating a new password I've never seen a password with no capital letters.  

to answer your questions:

1. you should be able to use the dialog as your greeting.  In this case you would not need to call the dialog again in this snippet
```cs
            if (activity.Type == ActivityTypes.Message)
            {
                await Conversation.SendAsync(activity, MakeJsonRootDialog);
            }
```
2. All channels are different unfortunately.  In this case, Its hard for me to test what is causing the difference in behavior because of the web config issues explained above.  I cannot get web chat working at all.

3.  Thank you for providing your code, it makes it much easier to assist you 👍

**Comment by vovanb** [comment]
#1 so what should I do when activity.Type == ActivityTypes.Message ? Can you provide recommended workaround?
#2 bot was working fine with my web.config (the gif screenshot has been taken then) , I will change password again np, however I hope you can test bot if you will use your own credentials . 
It is just make additional step in our qa , that emulator is not 100% same as webchat ... or may be it is a spot to defect?
#3 all code from annotated bot sample
Thanks a lot for reopening issue and support.

**Comment by JasonSowers** [comment]
I have been looking into this most of the day and trying to figure out a way to accomplish the behavior you are looking for in webchat.  Unfortunately, you will not be able to accomplish the same behavior as the emulator in webchat.  The root of the issue is how directline processes the conversation updates.  After talking to the webchat team this is a known issue that we hope to address in the future but have no timeline for. 

I realize this isnt what you would like to do, but I really think the best solution is to have some sort of actual greeting that forces the user to respond, either a prompt or something like "What is your name" or "Type anything to get started".  Then you could fire off the form dialog and it would behave as you want it to.  Sorry we do not have a better answer for you.
