### ISSUE TITLE
[Question]How do you start a dialog via a backchannel triggered event?

### ISSUE THREAD

**Issue by jfantell** [Microsoft/BotBuilder#3779]
SDK Platform: Node.js
SDK Version: 3.11.0
Active Channels: web, direct line
Deployment Environment: localhost

Question:
How do you start a dialog via a backchannel triggered event? I tried doing bot.beginDialog('Welcome-Dialog') and event.beginDialog('Welcome-Dialog') without any luck.

```
bot.on("event", function (event) {
    var msg = new builder.Message().address(event.address);
    msg.textLocale("en-us");
    if (event.name === "buttonClicked") {
        msg.text("Hi "+ event.value.name");
        bot.send(msg);
    }
   bot.begin('Welcome-Dialog')
});

bot.dialog('Welcome-Dialog', function(session,args) {
    /* Dialog flow logic */
}).triggerAction( { matches: 'Hi' } );
```

**Comment by Aashish-Amber** [comment]
A working solution would be to store a map of user-id and session and then use seesion.send to send a dialog to the corresponding user .

**Comment by jfantell** [comment]
Thank you for your response, but I am not sure that I understand. Could you provide a brief example?

**Comment by nwhitmont** [comment]
@jfantell What are you trying to accomplish here exactly?

**Comment by nwhitmont** [comment]
@jfantell You need to call `bot.beginDialog()` with the correct arguments, including `address` and `dialogId`.

You can find the method signature via [VSCode](https://code.visualstudio.com/) intellisense:
![screen shot 2017-11-17 at 4 24 01 pm](https://user-images.githubusercontent.com/3075047/32974550-f7f7f462-cbb3-11e7-80fc-61ac263dc5b6.png)


in the Typescript SDK reference doc:
https://docs.botframework.com/en-us/node/builder/chat-reference/classes/_botbuilder_d_.universalbot.html#begindialog

or read the file here:
https://github.com/Microsoft/BotBuilder/blob/master/Node/core/src/bots/UniversalBot.ts#L243

Since the `bot` of type `UniversalBot` has no access to the session object, you need to grab the address from the `event.address` and pass it to beginDialog as the first argument. Eg: `bot.beginDialog(address, dialogId);`

**Comment by nwhitmont** [comment]
Hi @jfantell - Were you able to get it working using the info provided in my last comment?

Let me know if you still have questions.

**Comment by nwhitmont** [comment]
reopen if you're still having issues.
