### ISSUE TITLE
[Direct Line] Responses from our bot, back to the user via Direct Line takes 30 seconds to a minute to complete.

### ISSUE THREAD

**Issue by willemodendaal** [Microsoft/BotBuilder#3787]
## Bot Info 
* App ID:  0883292d-3fe6-41c8-9fda-f2c1adad4592
* SDK Platform: .NET
* SDK Version: 4.6.2
* Active Channels: Direct Line
* Deployment Environment: Azure App Service

## Issue Description
Calls from our bot back to the user (indirectly via DirectLine because that is the channel the user is using) take very long (30 seconds to a minute per message), causing the bot to throw an error after 15 seconds.

The problem started this morning, and impacts all our environments (including two production clients)

eg. Dependency calls as seen in appInsights:
2017-11-16T07:55:16.922 https://directline.botframework.com/v3/conversations/...convId.../activities/...activityid...
Duration: 50,591ms

## Code Example
Any post to the user, for example:
	await dc.PostAsync("Hello, welcome back");

## Expected Behavior
These requests typically take less than 1 second. More than 5 seconds starts to be a problem. 50 seconds is a big problem.

## Actual Results
Very slow responses from https://directline.botframework.com/v3

eg. Dependency calls as seen in appInsights:
2017-11-16T07:55:16.922 2017-11-16T07:55:16.922 https://directline.botframework.com/v3/conversations/...convId.../activities/...activityid...
Duration: 50,591ms

**Comment by tristanvandam** [comment]
@willemodendaal We are also experiencing this issue.

Our bot info is similar to yours:
SDK Platform: .NET
SDK Version: 4.6.2
Active Channels: Direct Line
Deployment Environment: Azure App Service

Our bot is operating at incredibly slow speeds between posting messages to users and we continuously receive 502 errors when using `directline` with the specific message `Retry message, could be 502 error from bot framework`.
We noticed the issue about 5 hours ago and has been persisting since.
We can hardly progress past one or two messages without being bombarded with errors. 
Any solution or quick fix on your side in order to get your bot stable or any other feedback received? Please let me know.

Appreciate it.
Tristan

**Comment by nwhitmont** [comment]
@willemodendaal @tristanvandam Thanks for reporting. I have escalated to the issue to our platform team for investigation.

**Comment by Fignewton5** [comment]
@willemodendaal Would you mind giving us your Bot name or App ID so we can investigate? Thanks.

**Comment by tristanvandam** [comment]
@Fignewton5 @nwhitmont 

AppID_dev: b41c930f-bb27-44cc-aa48-4938d024b293
AppID_qa: f20b587f-3aeb-4b55-bf81-657057cb7aa9

**Comment by droidpl** [comment]
It is also happening here. The Bot ids are:

**Comment by ederbond** [comment]
I'm having the same issues here with my bot build in .net and consuming via DirectLine-JS:
BotId: 0b0170f6-6a74-44a8-889d-2faa73ca62bb

**Comment by EricDahlvang** [comment]
@willemodendaal @droidpl Are you still having these issues?  

Have you implemented a custom state client in your bots?  This blog post walks through adding Azure Table Storage or Document Db (now CosmosDb).

**Comment by droidpl** [comment]
Hey @EricDahlvang, thanks for replying. I didn't see the issue again lately. Yes I have the state implemented on document db and the bot migrated. Had some issues with 502 Bad gateway and 500 internal errors while in the migration but seems that it was an issue already fixed on Microsoft bot side. I will keep monitoring.
