### ISSUE TITLE
[Azure Bot Service] Unable to save settings - Getting "CorrelationID" error when changing settings?

### ISSUE THREAD

**Issue by sharontf** [Microsoft/BotBuilder#3871]
## Bot Info 
* Active Channels: Teams
* Deployment Environment:  Azure Bot Service

## Issue Description
 
When making changes to the Settings tab on Azure Bot Service (just changing the Long description), an error pops up, and I cannot make any changes.
<img width="954" alt="azureprob" src="https://user-images.githubusercontent.com/34248220/33571079-bf0db47e-d8e3-11e7-8655-63d483eee0f8.png">

## Reproduction Steps
1. Go to settings
2. Type anything in to Long description
3. Click save changes

**Comment by tahsintahsin** [comment]
+1

**Comment by JasonSowers** [comment]
@mgbennet

**Comment by nwhitmont** [comment]
@sharontf Can you try "hard refresh" the page and try saving the settings again?

**Comment by mingweiw** [comment]
Can you force a hard refresh in your browser and try again? In Chrome, navigate the Settings tab, press F12 to open the dev console, then right click the refresh button and choose “empty cache and hard reload”. Then try make a change and save.

Thanks.

**Comment by sharontf** [comment]
The problem is still there for me. (I tried hard refreshing on both Chrome and Edge). I am trying on a different bot, and my CorrelationID error is now: |I3oKb.b9684672_

**Comment by mingweiw** [comment]
Can I make settings changes to SharonTestBot4 to try to debug this? Thanks.

**Comment by sharontf** [comment]
I deleted that bot, but created a new bot that has the same issue: SharonTestBot5
App ID: fc78f189-e3ea-414e-9b9e-cedcec5ce556

**Comment by mingweiw** [comment]
Can you attach a Fiddler trace of the "Save" operation? Or a HAR from Chrome? 

![image](https://user-images.githubusercontent.com/19695895/33582536-90006560-d90a-11e7-85a2-7dde7b819a43.png)

**Comment by sharontf** [comment]
@mingweiw  GitHub does not support .har files. Can I email it to you?

**Comment by mingweiw** [comment]
Yes, at mingweiw@microsoft.com. Thanks.

**Comment by madhurtanwani** [comment]
Same here: CorrelationID: |kn5cM.52bd6699_
Will email you the HAR file

**Comment by SyrianBallaS** [comment]
I have the same exact problem,

Not sure if it has to do with with app portal (click "Manage Microsoft App ID and password")
This happens when I try to put a redirect for Microsoft logins (https://**/signin-microsoft)

![image](https://user-images.githubusercontent.com/18649925/33589919-ced2d338-d949-11e7-9452-b0a2ae8fa680.png)



Changes a little bit based on what's changed.

![image](https://user-images.githubusercontent.com/18649925/33589589-79de447c-d947-11e7-99a6-2aea1556ade5.png)

### Don't change: 
CorrelationID: |tbw3xsCPVN4=.133f933_

### Admin
(remove) CorrelationID: |9BcCuxuZ6TE=.bdf82737_
(Add) CorrelationID: |o5HmyA2+sno=.133fe32_

### Application Insights Application ID
(Remove) CorrelationID: |M92AfBFsSeY=.134006b_
(Add) CorrelationID: |Z5F8vpRV6TM=.bdf82c46_

### Application Insights Instrumentation key
(Remove) CorrelationID: |6X2affNSkWQ=.1340215_
(Add) CorrelationID: |58OdaT22wUU=.bdf8397f_

### Messing Endpoint
(remove) CorrelationID: |R+bJ4j6lOdA=.bdf82fae_
{add) CorrelationID: |coOTj7CDV7Q=.bdf83777_

**Comment by SyrianBallaS** [comment]
Actually I might know the reason "not sure" but I got an email that azure is going under maintenance between  Monday, December 4, 2017 (today) to January 2018.

**Comment by FranckyC** [comment]
Same here even after tried every tips above.

**Comment by mingweiw** [comment]
Sorry for the problem. We've identified the issue and are working on a fix. I'll report back when it's fixed. Thanks!

**Comment by reshmamkumar** [comment]
Hi, I'm also facing similar kind of issue. When saving, there is no error message appearing, but data not saved. 
Error: 401
{code: "InvalidBotData", message: "readonly property being set - isDeveloperAppInsightsApiKeySet"}

**Comment by mingweiw** [comment]
The issue from Dec was fixed. Can you open a new issue and assign to mgbennet? Thanks.
