### ISSUE TITLE
[Question] Can the Agent(human) concurrent conversation with different user?

### ISSUE THREAD

**Issue by LimShengKai0524** [Microsoft/BotBuilder#3919]
i wish to implement the concurrent conversation with different user at the same time. It is possible for it. Looking forward for the reply. Thank you.

**Comment by FranciscoPonceGomez** [comment]
Hi @LimShengKai0524,

I am not sure of what you are asking. Could you please give us more information about your use case? What are you trying to achieve?

Regards,
Francisco

**Comment by LimShengKai0524** [comment]
Any Update? Thank you~

**Comment by JasonSowers** [comment]
What channel(s) are you using? If using something like directline I would think this would be entirely possible.  You may want to set up and enterprise service bus or some other sort of queueing system.  You would have to set up multiple clients so that you could manage multiple conversations on the human end.  I'm not really sure how this would work on other channels though.
