### ISSUE TITLE
[Skype Calling] Bot isn't able to answer group call, although it detects the call correctly?

### ISSUE THREAD

**Issue by metasonic** [Microsoft/BotBuilder#3955]
## Bot Info
* App ID: 65f8d2d5-7d21-4222-84ec-43fc5d4a5e50
* SDK Platform:  Node.js 
* SDK Version: 3.13.1
* Active Channels: Skype 
* Deployment Environment: localtunnel

## Issue Description
The bot isn't able to answer a Skype group call, although it detects the call correctly, as a result the user is unable to track when a group calls starts / ends using the bot

## Code Example
```javascript
// Create calling bot
var connector = new calling.CallConnector({
    callbackUrl: 'https://x.localtunnel.me/api/calls',
    appId: '65f8d2d5-7d21-4222-84ec-43fc5d4a5e50',
    appPassword: 'xxxxxxxxxxxxx'
});

var bot = new calling.UniversalCallBot(connector);
server.post('/api/calls', connector.listen());

// Add root dialog
bot.dialog('/', function (session) {
    console.log(session.message);
    session.send('Watson... come here!');
});
```

## Reproduction Steps
1. Make sure Real Time Media is enabled
2. Start the bot
3. Start a group call
4. Answer the group call

## Expected Behavior
The bot should be able to join the call, even if he is unable to stream video or audio

## Actual Results
The bot detects the call but he is unable to join it

## Use cases
1. Record meetings call duration -> for time tracking
2. Record customers call duration -> for billing
3. Display a list of available operators -> track what operators are opened and how long there calls last

**Comment by nwhitmont** [comment]
@metasonic Group calls are not currently supported for bots due to privacy reasons. 

Group calling for media bots has been disabled because the Skype clients do not have currently have the appropriate privacy controls in place to inform the participants that a bot can hear and/or see them. There is no timeframe available regarding when calling/real-time media bots will be supported in group calls. For now, calling and real-time media bots are allowed only in 1-to-1 Skype calls. We apologize for any inconvenience this may cause.

**Comment by nwhitmont** [comment]
relates to: https://github.com/Microsoft/BotBuilder-RealTimeMediaCalling/issues/22

**Comment by metasonic** [comment]
@nwhitmont Thanks for the answer, thought that relates only to CSharp as from the looks of it NodeJs is not able to access media in a group call.
