### ISSUE TITLE
[FormFlow] The text is truncated on FB Messenger?

### ISSUE THREAD

**Issue by farrukhpisces** [Microsoft/BotBuilder#3958]
I'm using formflow for my questionnaire using bot framework.All is working fine but when i use my bot with facebook messenger on mobile text truncate. Questions as well as their options.
For example:
[Prompt("How soon after you wake up do you have your first smoke?  {||}")]
 public TimeToFirstSmoke TimeToFirstSmoke;
And my options are
public enum TimeToFirstSmoke
    {
        [Describe(description: "Less than 5 Minutes")]
        LessThan5Minutes = 1,
        [Describe(description: "Between 6 to 30 minutes")]
        Between6to30minutes = 2,
        [Describe(description: "Between 31 to 60 minutes")]
        Between31to60minutes = 3,
        [Describe(description: "More than 61 minutes")]
        MoreThan61Minutes = 4

    };

now when i recive this message  on facebook messenger the option come like this "Between 31 to 60.."
i'm using auto with herocards with buttons
Please help me with that
Thanks in advance

**Comment by msmohan** [comment]
@farrukhpisces can you please share your code with me? I will try to repro and help you with it?

**Comment by JasonSowers** [comment]
Using a hero card, if the text is too long on a hero card button for the display it will be automatically truncated.  This varies channel to channel as well as desktop to mobile.  If you do not want your text truncated your best bet is to use text rather than a hero card, you also may want to try [adaptive cards](http://adaptivecards.io/) and see if those work for you.  As far as I know, there is no workaround for this.
