### ISSUE TITLE
No scope with a Tag matching 'Microsoft.Bot.Builder.Dialogs.Internals.DialogModule' is visible from the scope in which the instance was requested. 

### ISSUE THREAD

**Issue by whatsdis** [Microsoft/BotBuilder#404]
okay I it's the following line that causes the above error (I am using Bot.Builder 1.2.1)

`var connectorType = HttpContext.Current.Request.IsLocal ? ConnectorType.Emulator : ConnectorType.Cloud;`

` var client = Conversation.Container.Resolve<IConnectorClient>(TypedParameter.From(connectorType));`

previously I had this which worked fine in Bot.Builder 1.0.1

` var client = Conversation.ResumeContainer.Resolve<IConnectorClient>(TypedParameter.From(connectorType));`

and I can't find any examples regarding this

**Comment by willportnoy** [comment]
Don't resolve things directly from the Container - start a nested ILifetimeScope with a Message.

For example:

using (var scope = DialogModule.BeginLifetimeScope(container, toBot))

The resolution of dependencies heavily dependent on Message being available, so we made that explicit - otherwise, you'd have to ensure that Message were passed as an Autofac parameter through all dependency resolutions that needed it.
