### ISSUE TITLE
[Question] Is Node.js a first class citizen?

### ISSUE THREAD

**Issue by ioudas** [Microsoft/BotBuilder#4056]
[Node.Js API documentation](https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-overview) seems to be much richer than [its .NET brother](https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-overview).

Is Node.Js treated as first class citizen by bot builder framework maintainer team? Is it better in long term to adopt Node.Js API over .NET?

**Comment by FranciscoPonceGomez** [comment]
Hi ioudas,

If it looks like documentation is more extensive for Node.js SDK than for .NET SDK, this might be because some actions need more explanation in one SDK than the other. 
There is no better SDK and I can assure you that we are investing as much time in the .NET SDK than in the Node.js SDK. Just choose the one that you are more confortable with or more usefull for your project. 
In the next iteration of the SDK we are trying to make them more homogeneous, to function alike. You probably won't have the feeling in the future that one has more features or is better/more powerful than the other.

Regards,
Francisco

**Comment by nwhitmont** [comment]
Yes - Both .NET and Node.js SDKs are "first class citizens" - Use the programming language that is best suited to your skills and project needs.
