### ISSUE TITLE
[LUIS] Updating LUIS w/o UI efforts

### ISSUE THREAD

**Issue by rjgmail88** [Microsoft/BotBuilder#4153]
## Bot Info
* SDK Platform:  Node.js 
* Active Channels: Cortana
* Deployment Environment: Azure Bot Service, Azure App Service 

## Issue Description

Recently, we have started developing Cortana Skill with the help of Bot framework and LUIS for NLP. I would like to know if there is any programatic way to update existing LUIS model with new intent, entities and utterances & train+publish. We would like to reduce the manual effort of updating LUIS model every day when new feature/skill is being registered.

**Comment by stevengum97** [comment]
@rjgmail88 there isn't a Node.js SDK for it _yet_ (unlike for [.NET](https://github.com/Azure/azure-rest-api-specs/tree/current/specification/cognitiveservices/data-plane/LUIS/Programmatic)), but what you're ultimately asking for are the [Programmatic APIs](https://westus.dev.cognitive.microsoft.com/docs/services/5890b47c39e2bb17b84a55ff/operations/5890b47c39e2bb052c5b9c2f). In the mean time, you can install a package like `request` or `fetch` to perform the API calls. There are also code snippets for JavaScript if you scroll down to the bottom of each API page.

Lastly, you need to get your [Programmatic API Key](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/manage-keys#programmatic-key) (_not_ your Azure Subscription Key) to perform the Programmatic API calls, otherwise you will receive 401 Unauthorized responses.

**Comment by stevengum97** [comment]
Closing thread as @rjgmail88 and I spoke privately. For future inquiries regarding this and potential samples, there exists samples for the .NET and Node.js SDKs that can be found in the [LUIS-Samples repository](https://github.com/Microsoft/LUIS-Samples/tree/master/bot-integration-samples/hotel-finder).
