### ISSUE TITLE
Is there a way to set a tooltip on suggested action buttons to be different to the button title?

### ISSUE THREAD

**Issue by dividor** [Microsoft/BotBuilder#4203]
## Bot Info
* SDK Platform: node
* SDK Version: 3.14
* Active Channels: Webchat
* Deployment Environment: Azure Bot Service

## Issue Description
We are using [suggested actions](https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-send-suggested-actions), they are really great. We would like to have tooltips on the buttons, to give the user a bit more information on what each button does. There are already tooltips, but they just default to the title of the button.

Is there a way to set a tooltip on suggested action buttons to be different to the button title?

## Code Example

[suggested actions](https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-send-suggested-actions)

For example, we would need a tool tip on ...

`builder.CardAction.imBack(session, "productId=1&color=green", "Green"),`

**Comment by dividor** [comment]
I just edited my question to clarify we'd need a tooltip on imBack. Anyone know if this is possible please?

**Comment by JasonSowers** [comment]
There is no out of the box solution for this in webchat.  You could create a custom build of webchat that could accomplish this.  If this is something you are interested I would suggest inquiring if anyone has already done so on the [webchat repo](https://github.com/Microsoft/BotFramework-WebChat).  Since this is a question specific to webchat itself you may find more help over there from those experts.  Good Luck
