### ISSUE TITLE
How to programatically close Webview on click?

### ISSUE THREAD

**Issue by nachoku** [Microsoft/BotBuilder#4233]
## Bot Info
* SDK Platform: NodeJS
* Active Channels: Facebook
* Deployment Environment: Local

## Issue Description
Cant figure out how to close webview when someone submits a form. Using Angular app for Webview- so need to know how to do it on JS.

## Expected Behavior
Automatically close webview on submitting form.

**Comment by nodeomega** [comment]
Which version of AngularJS are you using?

**Comment by nachoku** [comment]
Angular 3

**Comment by nodeomega** [comment]
Upon further review, this issue is not a BotBuilder issue, but is more an Angular/JS issue.  I would recommend opening a question regarding this issue on Stack Overflow regarding this Angular-related question.

Also, I did not notice any documentation regarding Angular 3, as Angular progressed from version 2 to 4 directly.

If there are any further issues with BotBuilder specifically, feel free to open a new request.
