### ISSUE TITLE
Store messages in my own SQL Database without Using Azure Services

### ISSUE THREAD

**Issue by JulzB** [Microsoft/BotBuilder#4288]
In order to storage some information (User Id, Messages from the user, date) im using a class that implements SqlConnection and a method to execute a StoreProcedure in my database. The problem here is when I test the bot in local with the emulator  it works (Data get stored ), but when I publish my bot in azure i get this message from the bot.

![capturabot](https://user-images.githubusercontent.com/27872004/37224568-2172fe6a-2391-11e8-8988-d8edc5f86b45.PNG)

**Comment by JasonSowers** [comment]
please provide the following information so we can better assist you.  You have provided no details that will help us diagnose the problem.
## Bot Info
* SDK Platform: 
* SDK Version: 
* Active Channels: 
* Deployment Environment: 

## Issue Description


## Code Example


## Reproduction Steps
1.
2.
3.

## Expected Behavior


## Actual Results
