### ISSUE TITLE
Prompt Choice Dialog on startup

### ISSUE THREAD

**Issue by waleedabuyahia** [Microsoft/BotBuilder#4358]
## Bot Info
SDK Platform: .Net
SDK Version: 3.14.1.1
Active Channels: Emulator, Skype, Webchat

## Issue Description

I need to prompt choice dialog whenever the bot is startup, I do not want to wait for input from the user, My requirement is to show a welcome message and let the user choice the language which he needs to chat with. 

where I need to add my prompt dialog, and if is in the message controller it self how I will instantiate the dialog context object.

**Comment by tiloc** [comment]
The ContosoFlowerBot sample illustrates how to show a welcome dialog at startup (check out its MessageController). This doesn't work equally well on all channels, as some of them don't really have a concept of the beginning of a conversation. It works well with Web Chat and emulator.

**Comment by EricDahlvang** [comment]
@waleedabuyahia For webchat, please see the answer here: https://github.com/Microsoft/BotBuilder/issues/4245

The issue is that when the user is added to the conversation using the WebChat channel, an event is sent to the bot but it does not contain enough information to initialize the state service data bags.

**Comment by EricDahlvang** [comment]
Closing due to age and inactivity.  Please open a new issue if you are still having problems with prompt choice on startup.
