### ISSUE TITLE
Non blocking prompt ?

### ISSUE THREAD

**Issue by JpEncausse** [Microsoft/BotBuilder#437]
Hi,
I'm using 1.0.1 with latest emulator

In a Waterfall of function I do:
1. builder.Prompts.text(session, ask);
2. handle result
3. builder.Prompts.text(session, ask);
4. handle result
...

Emulator do not wait 1. and call 2. and 3.

**Comment by Stevenic** [comment]
Can you share your code?

**Comment by JpEncausse** [comment]
This one is a little bit too large but in a Nutshell:
https://gist.github.com/JpEncausse/14df74bef812ef87536e623606320900

I create Question objects from a JSON description. The idea is to split content from code (content is pulled from a Google Spreadsheet)

Each Question has 2 functions `doAsk()` and `do Answer()` I join in a Waterfall array all couple of function.

```
var dialog = new builder.CommandDialog();
dialog.matches('.*', mate.getWaterfall());
bot.add(mate.getPath(), dialog);
```
It works very well in 0.x but break in 1.0. I read the changelogs  but do not see what i'm doing wrong.

It seems the first `doAsk()` / `do Answer()` / `doAsk()` are called rightaway like if the waterfall were asynchronous.

The top trigger is a LUIS Dialog doing:

```
dialog.on(intent, [function(session, args, next){
     session.beginDialog(path);
     next();
}]);

```

**Comment by Stevenic** [comment]
I like the approach... Hats off for that.  Nothing is jumping out at me for why its not working. I notice you do this bypass() check up front the could short circuit to the next step.  The other thing I noticed is that every time you call `next()` you don't pass a result so that means when you're going from `doAsk()` to `doAnswer()` you're going to have an empty `results.response`. That could be tripping up your logic too. 

Have you tried setting a break point and just stepping through the calls? The waterfall logic isn't that complex so you should be able to just step into `next()` and see why its skipping prompts.

**Comment by v-thgratMSGit** [comment]
Closing this issue. Thanks!
