### ISSUE TITLE
[Question] Can we transfer conversation context and state across different channels?

### ISSUE THREAD

**Issue by sajal2692** [Microsoft/BotBuilder#4384]
## Bot Info
* SDK Platform: Node.js
* Active Channels: Skype, Facebook Messenger, WebChat
* Deployment Environment: Azure App Service

## Issue Description
I have a requirement that a user can start a conversation with the chatbot on Skype, then continue the conversation on Facebook messenger. Is this scenario doable with the current node.js sdk?

**Comment by hpksp** [comment]
I would also like to know the answer for this. If this is not possible with current implementation, is there any plan to support this feature in upcoming versions?

**Comment by EricDahlvang** [comment]
This would be a fairly complex process, but possible.  You would need to write code to map the identities of the Skype user and Messenger user to the same userid, and also map conversationids.  This would involve something like: when the customer completes signing in from the 2nd channel, you would need to manually synchronize the state from the new conversation with that from the previous conversation.  (the dialog stack is stored in the state service)

We have some documentation that discusses how the state service works:
https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-state
https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-state

As well as some blog posts about using BobBuilder-Azure:
https://blog.botframework.com/2017/07/21/saving-state-azure-nodejs/
https://blog.botframework.com/2017/07/18/Saving-State-Azure-Extensions/

**Comment by hpksp** [comment]
@EricDahlvang Does this mean we have to modify the bot builder SDK to make this work?

**Comment by EricDahlvang** [comment]
I don't believe that would be necessary.  But, you would need to either change the id's of the first connection's stored UserData, ConversationData and PrivateConversationData to the new ids in the state store, or duplicate them into the 2nd connection's corresponding data bags.  

Here's an outline:
1) user signs into your bot using BotAuth on Facebook
2) user is at the 4th step in a waterfall or FormFlow dialog
3) user signs into your bot using BotAuth on Skype
4) at this point you either duplicate the state data from the Facebook conversations (so the new conversation is at the same state), or you change the id's of the data bags to the Skype ids so the new conversation automatically picks up the previous state (this would have to be done at the right time, based on the sdk)

Maybe someone from the community has already written a bot that does this.  

(if you are trying to display message history in the different channels, that is not really possible since they each have their own internal design for history.  you can certainly map state though, using the outline above)

I'm closing this issue, as it is not a bug or feature request.  In the future, please ask "how to" questions on Stack Overflow: https://stackoverflow.com/questions/tagged/botframework  The Bot Framework team prefers to reserve the GitHub BotBuilder repository for feature requests and issues.

**Comment by sajal2692** [comment]
Thanks for your thoughts on the topic @EricDahlvang. This gives me a good starting point.
