### ISSUE TITLE
[Azure Bot Service] Got 500 Error code during Bot migration to GA Bot service

### ISSUE THREAD

**Issue by edanilenko34** [Microsoft/BotBuilder#4395]
## Bot Info
* SDK Platform: Node.js
* SDK Version: botbuilder 3.13.1, botbiolder-azure 3.0.2
* Active Channels: Skype, Telegram, Facebook
* Deployment Environment: Azure Bot Service

## Issue Description
During migration I've got message with 500 error code. Seems it was in process of file copying to created instance.

## Reproduction Steps
1. Press button "Migrate" in portal.azure.com or botframework site
2. after couple of minutes see Error popup.
3.

## Expected Behavior
Success migration

## Actual Results
Migration is not completed.

**Comment by stevengum97** [comment]
@edanilenko34, thanks for reporting this issue we are currently investigating.

**Comment by Andrea-Orimoto** [comment]
@edanilenko34, what is the botId?

**Comment by edanilenko34** [comment]
The BotID is 4949893f-f14b-4e63-b274-05fc8854c728

**Comment by Andrea-Orimoto** [comment]
hi @edanilenko34, we think we have found the issue, if you want the long explanation please check this related issue #4227.

The short version is:
1. Use FuncPack
2. Use an App Service name you never used before when you migrate (e.g. instead of vlgtrans-upgrade, use vlgtrans-upgrade1)

Let me know if you have any questions.
Andrea

**Comment by Andrea-Orimoto** [comment]
One more important step I just discovered. Once you move to funcpack, delete the node_modules folder from the app service prior to migration. A function using funcpack does not need the node_modules anymore, and that folder might cause the timeout during migration.

**Comment by Andrea-Orimoto** [comment]
hi @edanilenko34, were you able to try this? Let me know if you have any questions.

**Comment by fanidamj** [comment]
@edanilenko34 Closing the issue assuming it as resolved. Please open a new issue if you have any.

**Comment by Andrea-Orimoto** [comment]
The bot has not been migrated yet, reopening this issue.

@edanilenko34, here's what you need to do in order to migrate succesfully:

1. move your code to funcpack https://github.com/Azure/azure-functions-pack
2. remove the node_modules folder from the app service (or add it to .gitignore)
3. wait until mid this week (ETA 5/17), we're deploying another fix that addresses a timeout issue during migration
4. migrate your bot

I'm available to get on a screen share session if needed.
Let me know if you have any questions, and thanks for your patience.
Andrea

**Comment by JasonSowers** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
