### ISSUE TITLE
[Question] Do I need to migrate to new Azure account?

### ISSUE THREAD

**Issue by chinchang** [Microsoft/BotBuilder#4398]
## Bot Info
* SDK Platform: Node.js (bot-builder)
* SDK Version: 3.8.3
* Active Channels: Skype, Slack
* Deployment Environment: Private server

## Issue Description
Since I have my bot-builder bot deployed on my own server, do I need to do this Azure migration?

**Comment by fanidamj** [comment]
All Azure Bot Service (Preview) bots created in the Bot Framework Portal must migrate to the new Bot Service in Azure by 3/31/2018. However, registration bots connected only to these channels are not required to migrate: Teams, Skype, or Cortana. Since you have Slack along with Skype, it is required to [migrate](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-migrate-bot). It is important to prevent any service interruption in future. Hope this helps!!
