### ISSUE TITLE
Bot won't respond on Skype but works perfectly on webchat

### ISSUE THREAD

**Issue by AkshayKanchan** [Microsoft/BotBuilder#4478]
Bot Info
* SDK Platform: Node.js
* SDK Version: 3.13.1
* Active Channels: Skype, WebChat
* Deployment Environment: Azure Bot Service
* AppID: 2bd48edc-0592-4c7c-ac08-64416f66212c

Chatbot works on webChat as expected but won't respond on Skype channel, I have tried debugging the issue and learned that there's no request received by my bot but if I try with webchat everything works perfectly as expected.

**Comment by nodeomega** [comment]
Do you have a code sample available to share?  That should help us narrow down where the issue lies.

**Comment by AkshayKanchan** [comment]
`bot.use({
    botbuilder: (session, next) => {
        session.sendTyping();
        console.log(session.message); 
        next();
    },
    send: (event, next) => {
        console.log(event);
        next();
    }
})`

Let me know if any specific block of code required.

**Comment by nodeomega** [comment]
Apologies for the delay in getting back to you.  I've tried your code sample and am getting a response from my version of a bot in Skype as well as Webchat.  Do you have more to go by?

**Comment by AkshayKanchan** [comment]
It started working after I followed **EricDahlvang** comment "_Sometimes Skype doesn't propagate the settings. This can usually be remedied by changing the messaging endpoint and saving, then changing it back._"
(from: [https://github.com/Microsoft/BotBuilder/issues/3281](url))

But I am sure there's a permanent solution for this.

**Comment by nodeomega** [comment]
I am not aware of a permanent solution as far as that goes as of yet.  Since using @EricDahlvang workaround, has the issue recurred?

**Comment by nodeomega** [comment]
Here's more of what I know:  The Skype team is aware of the issue that you were having, and as far as I know are working on a fix for it.  It may already be fixed, but I am not 100% sure on that.

As there is little more I can do on my end regarding this issue, and since we have a viable workaround for the time being at least, I will be closing this issue.  If the issue persists, you are more than welcome to reopen this and we can take another look at this.
