### ISSUE TITLE
Launch URL within bot application

### ISSUE THREAD

**Issue by Zhashkha** [Microsoft/BotBuilder#4498]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.14.1
* Active Channels: Emulator, FB
* Deployment Environment: Azure Bot Service, Azure App Service, local development with Emulator

## Issue Description
Hi guys,

I want to launch URL with default browser from within bot application. I don't want to use openUrl card action type, because I'm catching click event with global handlers, then I'm doing some business logic, that should be issued before URL launch and only after that I want to launch URL. Simple Process.Start(url); doesn't work with FB channel, but works with Emulator. Any ideas ? Thanks in advance.

**Comment by JasonSowers** [comment]
This is a security limitation of the Facebook platform. You will not be able to accomplish this without using a button, or having the user click a link.  It is my assumption they do this to prevent malicious pages being opened automatically.

**Comment by Zhashkha** [comment]
Hi Jason,

thanks for reply. So if I get you right, there is no chance to run some logic after any event (button click event in first place) and then launch URL on FB platform. If no, then at least can I catch any kind of response at server side from OpenUrl action type button click ?

**Comment by JasonSowers** [comment]
Are the links you are opening web pages that you control?  can you catch something on the other side i.e. put something in a query string?  You will not be able to catch anything on the bot side because the button click all happens on the front end.  

 I'm not exactly sure of what exactly you are trying to capture or what your business logic looks like, and if the answer to my first question is no, consider this code:
```cs
            if (context.Activity.AsMessageActivity().Text.ToLowerInvariant().Contains("github"))
            {
                context.ConversationData.SetValue("Site", "GitHub");                
                var reply = activity.CreateReply();
                reply.Attachments.Add(Utility.GetHeroCard(Utility.GetButtons()));
                await context.PostAsync(reply);
            }
```
a herocard is just an attachment to an activity.  in which you could set a value in one of the state databags like `UserData` or `ConversationData`. you can then later see if the state value exists and run some logic off of that.  There may be other ways to accomplish this, but this is the thing that first came to mind.  There is no built-in feature to do what you are trying to do in the channel you are trying to do it. What you really need here to circumvent Facebook's behavior is to have 2 action types fire at once.  Then you could have a messagback event fire a value to your bot letting you know the button was clicked and then you can run your business logic.  Unfortunately, we have not implemented this in bot framework. 

This would probably be a great question for stack overflow to see if someone has come up with a solution to this problem.

**Comment by JasonSowers** [comment]
Check out this example https://github.com/JasonSowers/BF-302RedirectExample

**Comment by Zhashkha** [comment]
Hi Jason,

let me be honest I've tried this approach some period ago and it didn't work. But now it works and I simply don't understand why (I don't remember exactly, it was kinda redirection issues). Anyway thanks a lot for your contribution, everything worked perfectly.

**Comment by JasonSowers** [comment]
Great, good luck.
