### ISSUE TITLE
[LUIS] Wrong results from the Spanish version - LUIS apps

### ISSUE THREAD

**Issue by jdnichollsc** [Microsoft/BotBuilder#4508]
## Bot Info
* SDK Platform: Node.js
* SDK Version: 3.13.1 (npm)
* Active Channels: All
* Deployment Environment: local development with Emulator, Web App Bot
* LUIS language: Spanish

## Issue Description
We don't have prebuild domains for Spanish. And using Simple entities we can't use spaces, double quotes to get all the info.

## Code Example
https://github.com/proyecto26/Bot-Framework/blob/master/src/nodejs/bot/dialogs/movieBook.js#L9

## Reproduction Steps
1. Download the template https://github.com/proyecto26/Bot-Framework/ (src/nodejs)
2. Change the language to Spanish (Select Spanish from the menu)
3. Type any of the following examples:
> reservar boletos para Avengers Infinity War

return **avengers**
> reservar boletos para "Avengers Infinity War"

return **"**

## Expected Behavior
Return all the info with spaces in the Spanish version. Example:
> reservar boletos para Avengers Infinity War

return **avengers infinity war**

## Actual Results
If the entity has spaces only get the first part. With doubles quotes only return the first quote

I'm not sure if this bug is for this team or the team of LUIS, let me know if the repo is other one.

Thanks in advance, Nicholls

**Comment by fanidamj** [comment]
Can you please let us know if it is Spanish (Spain) or Spanish (Mexico)?

**Comment by jdnichollsc** [comment]
Spanish (Spain)
<img width="573" alt="luis spanish app" src="https://user-images.githubusercontent.com/2154886/39158067-9bb243e2-4723-11e8-8111-8b93a5def823.png">

Thanks for the help!

**Comment by fanidamj** [comment]
The case is a movie ticket reservation intent, and the problem is in handling multi-word movie names which is not a bug. But it does look like a case that could be covered with the new [Patterns feature ](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-how-to-model-intent-pattern)(using [pattern.any](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-tutorial-pattern#use-a-patternany-entity-to-find-free-form-entities-in-a-pattern) and optional tokens for the quotes). If you add the pattern.any entities to your LUIS app, you can't label utterances with these entities. They are only valid in patterns. Hope this helps!!

**Comment by jdnichollsc** [comment]
But with the english version works as expected

<img width="1285" alt="movie tickets english" src="https://user-images.githubusercontent.com/2154886/39930339-1172b83e-5500-11e8-800e-163b5f5a40e2.png">

And the response (multi-word movie names)
<img width="1097" alt="captura de pantalla 2018-05-11 a la s 9 56 36 a m" src="https://user-images.githubusercontent.com/2154886/39930953-a75398e0-5501-11e8-84cf-35afeed5392b.png">

The code for both luis apps is the same:
```
var intent = args.intent
var title = builder.EntityRecognizer.findEntity(intent.entities, 'MovieTickets.MovieTitle')

var movie = session.dialogData.movie = {
  title: title ? title.entity : ''
}
```

Let me know what you think
Thanks lady in advance, Nicholls

**Comment by fanidamj** [comment]
English works as expected because [prebuilt domains are supported in English](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-reference-prebuilt-domains) and not supported in Spanish. 
![movieticketspanish](https://user-images.githubusercontent.com/16520557/40040622-d36da918-57cf-11e8-874d-cc001be022b7.PNG)
Since the prebuilt domain used for English are not supported in Spanish, the way to recognize multi words intent is to use [patterns.any](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-tutorial-pattern#use-a-patternany-entity-to-find-free-form-entities-in-a-pattern) as mentioned above. Hope this help!!

**Comment by jdnichollsc** [comment]
@fanidamj Ohh thanks for your help lady!
