### ISSUE TITLE
Node Multiple Replies not working

### ISSUE THREAD

**Issue by srijiths** [Microsoft/BotBuilder#451]
I am trying to send multiple replies from the bot side. Below code works some time but not working always. Not sure whats the reason for that. Below is my code. Is this the correct approach ?
```
function(session) {
session.send("Please wait");
builder.Prompts.text("option 1");
session.send("Option 2");
}
```
I tried series of session.send , its not working. Above sequence works, not always

**Comment by Stevenic** [comment]
The dialog or waterfall step is technically over when you call `builder.Prompts.text()` so that should be the last thing you do in a step. I would rework my step to be:
```
function(session) {
    session.send("Please wait");
    session.send("Option 1");
    builder.Prompts.text(session, "option 2");
}
```

**Comment by srijiths** [comment]
Yes @Stevenic it works. Thank You

**Comment by srijiths** [comment]
Hi @Stevenic , I am not sure why its not working always. Please see the screen shots.

Emulator : 
![01](https://cloud.githubusercontent.com/assets/1046319/15998460/25d6c500-315c-11e6-81c4-088c5907a7c3.png)

Web Chat UI :
![02](https://cloud.githubusercontent.com/assets/1046319/15998462/2abdab38-315c-11e6-91d6-c98ec7fea035.png)

The same bot flow works some time and here is the screen shot.
![011](https://cloud.githubusercontent.com/assets/1046319/15998472/3cc6f794-315c-11e6-9657-08271a37140b.png)

Here is my code snippet which does this. The logic is it looks for a course and its pre requisites. If user already have any skills from that then we need to remove that from pre prequisites. And display the prompts.  Thank You

**Comment by Stevenic** [comment]
I'm not sure to be honest... Your logic looks pretty solid. I wish I could step into it with a debugger. Short of being able to do that I might suggest that you re-work your code to where you find all of the data first and then send all of the messages second.  This would eliminate any timing issue that might be going on.

If it helps I can tell you that I've completely re-written the way the session object batches up and delivers multiple messages in the 2.x version of the SDK that I'm working on. This new version should be ready in a couple of weeks and it will likely fix your issue. I realize that doesn't help much now which is why I suggest just reorganizing your code to do all calculations first.

**Comment by srijiths** [comment]
Thanks @Stevenic I tried re-organize the code as you suggested. Same issue. But its weird, some time multiple session.send is working and some time's not. I just done a quick workaround by combining all the prompt messages as a single message and send it once. Glad that the 2.x version will release soon. Thank You.

**Comment by Stevenic** [comment]
Ok... Lets definitely revisit this after 2.x is released it changes everything internally so should address the issue.
