### ISSUE TITLE
[C#] confirm/prompt generated as button.

### ISSUE THREAD

**Issue by ankitbko** [Microsoft/BotBuilder#456]
Is there any way to make IFormBuilder.Confirm() or PromptDialog.Confirm() generate Yes/No button? As the input is restricted to Yes or No, it seems buttons are more appropriate making it explicit to user what to enter, essentially preventing him from entering something as "yes..." or any variant of it.

**Comment by chrimc62** [comment]
[Template(TemplateUsage.Confirmation, "Is this your selection? {||}")]
In FormFlow, adding the {||} means the choices will be shown and since the default ChoiceStyle is Auto you will get buttons when supported and otherwise inline text, i.e. (1. Yes, 2. No). 

You can also use the PromptStyler to get buttons in PromptDialog.Confirm().
