### ISSUE TITLE
[Feature Request] Support Slack's `app_mention` Event

### ISSUE THREAD

**Issue by burkeholland** [Microsoft/BotBuilder#4662]
## Bot Info
* SDK Platform: Node.js
* SDK Version: 3.14.0
* Active Channels: Slack
* Deployment Environment: Azure Bot Service

## Issue Description
Add support for the `app_mention` event in Slack. Right now subscribing to `app_mention` doesn't do anything. This means that the bot has to be specifically coded for Slack. It would be nice if there was an option to just have the bot respond whenever it was mentioned in a channel instead of all the time.

## Expected Behavior
Adding in the `app_mention` event in Slack would trigger a response from Bot Service whenever a bot is mentioned.

## Actual Results
Bot Service doesn't receive the `app_mention` event so there is no response from the bot when mentioning if `channel.messages` is turned off. If it is turned on, the bot answers to all messages, not just ones where it is mentioned.

**Comment by nyxsys** [comment]
Turning on the `app_mention` event while `channel.messages` is on adds an item to the array "entities" that includes a field type within the message object when sent via slack. Unfortunately there is no current way to automatically filter only these messages without additional slack specific code.  However, when this event is on, it is possible to create [middleware](https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-intercept-messages?view=azure-bot-service-3.0) ([v4 version](https://github.com/Microsoft/botbuilder-js/wiki/Creating-Middleware#implementing-your-own-middleware)) that checks if slack messages include this field with a mention.
Here's an example middleware implementation using v3 (requires using a message to avoid resetting the current dialog, however session.reset() can be used if all dialogs are 1-step)

```
var util = require('util');

module.exports = {
    isMentioned: function(session, next) {
        if (session.address.channelId === 'slack' && 
            !(
                session.entities[0] && session.entities[0].type === 'mention' && 
                session.entities[0].text === util.format("@%s",session.address.bot.name)
            )){
            console.log("not mentioned");
            session.send(); //send empty message if a slack message didn't include a mention
	 }
	else{
            console.log('mentioned');
            next();
        }
    }
}
```

We will look into including this natively later on. I will update if this is possible in v3 without sending a message. That said, it is already possible to do this in v4 without sending a message. (similar to the implementation above, but with "return" instead of sesssion.send())

**Comment by nyxsys** [comment]
Turning on the `app_mention` event while `channel.messages` is on adds an item to the array "entities" that includes a field type within the message object when sent via slack. Unfortunately there is no current way to automatically filter only these messages without additional slack specific code.  However, when this event is on, it is possible to create [middleware](https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-intercept-messages?view=azure-bot-service-3.0) ([v4 version](https://github.com/Microsoft/botbuilder-js/wiki/Creating-Middleware#implementing-your-own-middleware)) that checks if slack messages include this field with a mention.
Here's an example middleware implementation using v3:

```
var util = require('util');

module.exports = {
    isMentioned: function(session, next) {
        try{
            if (session.address.channelId === 'slack' && 
                !(
                    session.entities[0] && 
                    session.entities[0].type === 'mention' && 
                    session.entities[0].text === util.format("@%s",session.address.bot.name)
                )){
                console.log("not mentioned");
            }
            else{
                console.log('mentioned');
                next();
            }
         }
         catch(err){
             console.error(err);
         }
    }
}
```

We will look into including this natively later on.

**Comment by burkeholland** [comment]
Thanks! I'll look into the middleware solution.

**Comment by JasonSowers** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
