### ISSUE TITLE
[Direct Line, .NET] Getting HTTP status code Forbidden while calling bot via Direct line connection.

### ISSUE THREAD

**Issue by whizlingo** [Microsoft/BotBuilder#4711]
## Bot Info
* SDK Platform: .NET
* Active Channels: Direct line.
* Deployment Environment:  ASE Azure App Service

## Issue Description
We have a xamarin app which connects to the BOT via Direct line connection. We randomly see  "There was an error sending this message to your bot: HTTP status code Forbidden" in the direct line channel logs. It goes off and comes back up randomly. This happened more frequently yesterday. I have seen it working more consistently in web chat though. Can you explain the cause of this and possible remediation ?. Could this be due to some Azure paas service upgrade for bot ?.

**Comment by whizlingo** [comment]
Below are the error details -`<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
 <html xmlns="http://www.w3.org/1999/xhtml">
 <head>
 <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
 <title>403 - Forbidden: Access is denied.</title>
 <style type="text/css">
 
 </style>
 </head>
 <body>
 <div id="header"><h1>Server Error</h1></div>
 <div id="content">
 <div class="content-container"><fieldset>
 <h2>403 - Forbidden: Access is denied.</h2>
 <h3>You do not have permission to view this directory or page using the credentials that you supplied.</h3>
 </fieldset></div>
 </div>
 </body>
 </html>`

**Comment by stevengum97** [comment]
Duplicate of Stack Overflow question: https://stackoverflow.com/questions/50739300/azure-bot-service-direct-line-api-v3-0-constantly-throwing-403-error-on-starting

Closing issue.

**Comment by whizlingo** [comment]
I do not think it is a duplicate , i am not using the token approach but client id and password and like insaid, it fails randomly every once in a while and not a consistent issue.

**Comment by Archit454** [comment]
Hi. I am facing an issue like **ERROR: that connector: receive - invalid token. Check bot's app ID & Password** in the command prompt while running node js code. But after sometimes the issue is getting resolved automatically and the bot is working fine. I have connected with Direct Line Channel and when I am checking there it is stating that **There was an error sending this message to your bot: HTTP status code Forbidden**. This is occurring randomly and after a few hours, it is getting resolved automatically. I am giving correct AppId and Password within the node js code. I am unable to understand the issue of why I am facing frequently for a few hours. Can anyone help me with understanding in this

**Comment by EricDahlvang** [comment]
@Archit454  Please open a new issue https://github.com/Microsoft/BotBuilder/issues/new

**Comment by Archit454** [comment]
Yeah Opened Eric. Thank you
