### ISSUE TITLE
Image "Tap" Not working in Facebook Messenger

### ISSUE THREAD

**Issue by odannyc** [Microsoft/BotBuilder#4735]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.15
* Active Channels: facebook messenger
* Deployment Environment: local

## Issue Description
I created a hero card with an image, the image contains a "Tap" so when a person taps on the image, it should go to some url. It works in the emulator correctly but not in Facebook Messenger. 

## Code Example
```csharp
            Activity reply = activity.CreateReply();
            HeroCard heroCard = new HeroCard
            {
                Title = "a random title",
                Images = new List<CardImage>
                {
                    new CardImage
                    {
                        Url = "https://images-na.ssl-images-amazon.com/images/I/41wp0Rb%2Bl9L._SX425_.jpg",
                        Tap = new CardAction
                        {
                            Type = ActionTypes.OpenUrl,
                            Value = "https://google.com"
                        }
                    }
                }
            };
            reply.Attachments = new List<Attachment>
            {
                heroCard.ToAttachment()
            };

            await context.PostAsync(reply);
```

**Comment by JasonSowers** [comment]
In order to accomplish this, you will need to move your `Tap` `CardAction` to a `HeroCard` property rather than a `CardImage` property like this:

```cs
            Activity reply = activity.CreateReply();

                 var card = new HeroCard
                {
                    Title = "title",
                    Text = "text",
                    Images = new List<CardImage>()
                    {
                        new CardImage(url: @"https://images-na.ssl-images-amazon.com/images/I/41wp0Rb%2Bl9L._SX425_.jpg")
                    },
                    Buttons = new List<CardAction> {new CardAction(ActionTypes.OpenUrl,"button", text: "button", value:@"https://www.bing.com"),
                    },
                    Tap = new CardAction(ActionTypes.OpenUrl, value: @"https://www.google.com/")
                 };

            reply.Attachments.Add(card.ToAttachment());
            await context.PostAsync(reply);
```
This seemed odd that it wasn't working on FB as I thought it would so I looked over their API to see if there was something we could do on our end to include this at the `CardImage` level.  After reviewing the [Generic template API documentation](https://developers.facebook.com/docs/messenger-platform/send-messages/template/generic), which is what our HeroCards translate to in facebook speech it seems that there is no properties you can set at the image level.  So it appears that ths is not something we can add.  So adding the Tap at the card level is the way to accomplish this.  I tested it with buttons of with `ActionType.OpenURL` and the buttons still worked as expected in tandem with the click of the image.
