### ISSUE TITLE
Web chat Iframe issue in IE 11

### ISSUE THREAD

**Issue by Jagan-rajan** [Microsoft/BotBuilder#4750]
## Bot Info
* SDK Platform:  .NET 
* Active Channels: WebChat
* Deployment Environment: Azure Bot Service,

## Issue Description
I have embedded my Webchat window into my website. Everything is working fine on chrome.
But in IE, I am getting an error continously. PFA

![ie error](https://user-images.githubusercontent.com/39727039/41519190-3928765a-72e4-11e8-99e9-053c454e0d69.jpg)

I want to resolve this issue from code and do not want my users to do any settings on their respective browsers. Is there any solution for this?.

**Comment by nyxsys** [comment]
Try adding this line to your html for your website:


Per [this stackoverflow answer](https://stackoverflow.com/questions/7038724/how-to-automatically-allow-blocked-content-in-ie).

If this alone does not work try adding [the webchat inline rather than in an iframe](https://github.com/Microsoft/BotFramework-WebChat#easy-in-your-non-react-website-run-web-chat-inline).
