### ISSUE TITLE
How to identify message coming from user is first message in conversation

### ISSUE THREAD

**Issue by amitkadu** [Microsoft/BotBuilder#4771]
I have to write business logic at MessageController for very first message in conversation.
How to identify that which one is first message for that particular conversation.
I tried to explore Activity but didnt get any help.
I am using Bot Framework - C#.

**Comment by ukphillips** [comment]
I don't think there is anything in the framework that would help you...I would recommend just setting a variable on the conversation data when you receive a message, on all subsequent messages you can just check for the existence of that value. If it's not there you know it's the first message.

something like this should work: 

```
 using (var scope = DialogModule.BeginLifetimeScope(Conversation.Container, activity))
                {
                    var botDataStore = scope.Resolve<IBotDataStore<BotData>>();
                    var key = Address.FromActivity(activity);

                    var data = await botDataStore.LoadAsync(key, BotStoreType.BotConversationData, CancellationToken.None);

                    //set data for the conversation
                    isFirstMessage = data.GetProperty<bool?>("NotFirstMessage") == null;

                    if (isFirstMessage)
                    {
                        //DO SOMETHING FOR THE FIRST MESSAGE 

                        //THEN SET THE FLAG
                        data.SetProperty<bool>("NotFirstMessage", true);
                        await botDataStore.SaveAsync(key, BotStoreType.BotConversationData, data, CancellationToken.None);
                        await botDataStore.FlushAsync(key, CancellationToken.None);
                    }
                }
```

**Comment by amitkadu** [comment]
Thanks for reply, I already tried with this but while testing I found that once variable gets set it will persist its value. after IIS restart as well.
Can you please tell me where this NotFirstMessage variable get storage.

**Comment by rainmakerho** [comment]
Hi @amitkadu , maybe you can save state to SQL Server. Please ref  [Saving State data in SQL with .NET](https://blog.botframework.com/2017/07/26/saving-state-sql-dotnet/)

**Comment by ukphillips** [comment]
@amitkadu this depends on how you configure it, without setting anything up I think it uses in memory by default. Just to be clear is your issue that the value is still there or that it is missing on subsequent requests?

I would highly recommend using an external data storage mechanism for your bot regardless (https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-state?view=azure-bot-service-3.0) 

For your use case you want the message to be there after the first message is received, so I'm assuming you mean the problem is that the message is missing. Because you are storing it on the conversation data (if the data is persisted in an external data store), every request in that conversation should have the value there. Make sure you have wired up the DI for the external provider. Here is an example: 

```
    public class WebApiApplication : System.Web.HttpApplication
    {
        protected void Application_Start()
        {
            GlobalConfiguration.Configure(WebApiConfig.Register);
            var store = new TableBotDataStore(ConfigurationManager.ConnectionStrings["StorageConnectionString"].ConnectionString);

            Conversation.UpdateContainer(
           builder =>
           {
               builder.Register(c => store)
                         .Keyed<IBotDataStore<BotData>>(AzureModule.Key_DataStore)
                         .AsSelf()
                         .SingleInstance();

               builder.Register(c => new CachingBotDataStore(store,
                          CachingBotDataStoreConsistencyPolicy
                          .ETagBasedConsistency))
                          .As<IBotDataStore<BotData>>()
                          .AsSelf()
                          .SingleInstance();


           });
            
        }
    }
```

Note this example is using the TableBotDataStore from the Bot.Builder.Azure nuget package (https://github.com/Microsoft/BotBuilder-Azure)

**Comment by EricDahlvang** [comment]
Closing.  This question looks like it has been answered.

---
The Microsoft Bot Framework team prefers that **how to** questions be submitted on [Stack Overflow](http://stackoverflow.com/search?q=%23botframework). The official [Bot Framework Github](https://github.com/Microsoft/BotBuilder/issues) repo  is the preferred platform for submitting **bug fixes and feature requests**.
