### ISSUE TITLE
Creation of List cards in MS Teams does not send Response Body

### ISSUE THREAD

**Issue by kartiksgayatri** [Microsoft/BotBuilder#4796]
## Bot Info
* SDK Platform: JAVA
* SDK Version: 
* Active Channels: MS Teams
* Deployment Environment: local development with Emulator

## Issue Description
Whenever a List Card is created, the bot framework does not sent response body and Activity ID. Where as, for Adaptive cards I get the response body and Activity ID

## Code Example
Using Retrofit, a post call is executed to the "v3/conversations/{conversationId}/activities/{activityId}" passing the necessary parameter and the body contains Activity of List card.

The same call is used for creating Adaptive Cards.

## Reproduction Steps
1.
2.
3.

## Expected Behavior
Response Body along with Activity ID to be returned after successfully creating List Card

**Comment by stevengum** [comment]
@kartiksgayatri, Since you're not using the BotBuilder SDK and are using [Retrofit](http://square.github.io/retrofit/) to create a HTTP client for Java, we ask that you post your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/botframework). There you will be more likely to receive assistance from not only the Bot Framework community, but also the Retrofit, Java and Stack Overflow communities. When posting a question on Stack Overflow, please make sure to add your code that produces this issue.

Additionally, the Bot Framework protocol does not support a "List card" so I'm not sure what you're asking about. 

If you do wish to use Java when developing Bot Framework bots, you might be interested in our [botbuilder-java][botbuilder-java] project that is currently in preview.

The Microsoft Bot Framework team prefers that ["How To"](https://stackoverflow.com/help/how-to-ask) questions be submitted on Stack Overflow. The official [Bot Framework GitHub][issues] repository is the preferred platform for submitting **bug fixes and feature requests**.

Closing issue.

  [botbuilder-java]: https://github.com/Microsoft/botbuilder-java/
   [issues]: https://github.com/Microsoft/BotBuilder/issues
