### ISSUE TITLE
Unable to find ARM templates for Microsoft Bot Services in NODEJS

### ISSUE THREAD

**Issue by vinayjayaram** [Microsoft/BotBuilder#4812]
We are looking for Microsoft.Botservices template  in the link below https://azure.microsoft.com/en-in/resources/templates/ …  help us in getting the required sample template. We are specifically looking for NODEJS platform

**Comment by JasonSowers** [comment]
I am inquiring about this and will update you when I have more information.

**Comment by carlosscastro** [comment]
Hello @vinayjayaram !

We don't have templates in that gallery. Many of the nodejs samples have a deploy button such as this: https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node/cards-RichCards.

Generally, instead of ARM templates, we recommend using our Azure CLI extension to deploy bots. Here is an [article ](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tools-az-cli?view=azure-bot-service-3.0)to get you started (particularly the usage of the 'az' command).

**Comment by amitbend** [comment]
@carlosscastro what's the status of the Azure CLI for the Botservice? It seemed to be very buggy the last time I've used it

**Comment by stevengum** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
