### ISSUE TITLE
Remove mention of name at answer

### ISSUE THREAD

**Issue by yss14** [Microsoft/BotBuilder#483]
Is there a possibility or setting removing the "@name" in front of the answer of a bot in a group chat (in my case it's telegram)?

![alt text](https://picload.org/image/rgwdgorw/mentionnamebot.png)

**Comment by eanders-MS** [comment]
We prepend the recipient to make it clear who the bot is responding to. I'm curious as to why this is undesirable in your scenario. Can you tell me more about what you're doing?

**Comment by yss14** [comment]
Basically my bot is a simple echo bot which listen for some predefined keywords and than echos some prefinded phrases. So the users don't write directly to the bot because it listen to the whole group conversation and if a message contains a keyword his respsonse will be without a certain context.
It would be nice on the developer side if you can choose if the bot mentions the user or not.

**Comment by Kadae** [comment]
I have the same problem too. One month ago my bot works fine. But then Azure acc stopped and I change the payment method. After that I used the same code, but now it's works wrong.

> Me: hi
> Bot @Firstname Secondname hi!

> User add to this group...
> Bot @$service$ hi!

I re-created Azure app, re-created bot with C# App in VS, re-created bot in Telegram. But can't find were is this bug to fix it...

I'm using default C# app: http://aka.ms/bf-bc-vstemplate
I also tryed to publish default code, but it's the same problem. Looks like something permanently broken with my bot account Azure or, maybe, in Telegram and GroupMe (because in Slack everything is ok)?.

**Comment by yss14** [comment]
Thanks for considering my issue and fixing the "@mention" in the Bot Framework :)

**Comment by Kadae** [comment]
Yep, thank you!

**Comment by eanders-MS** [comment]
Sorry to get your hopes up! It's a new bug that it we're no longer mentioning the name. This functionality will be restored shortly. Apologies. But I've forwarded your request to the team, and it is a reasonable request I think.

**Comment by eanders-MS** [comment]
Closing.

**Comment by etriebe** [comment]
Is this expected to be fixed? This causes issues because GroupMe will only render an image URL if it is the only text in the message.

**Comment by Kadae** [comment]
etriebe, this is fixed for me. Bot answer without fake mention in answer.

**Comment by etriebe** [comment]
@Kadae I'm not so sure from the reply above...

> Sorry to get your hopes up! It's a new bug that it we're no longer mentioning the name. This functionality will be restored shortly. Apologies. But I've forwarded your request to the team, and it is a reasonable request I think.
