### ISSUE TITLE
HTTP status code GatewayTimeout (Is error in Azure Channel Registration?)

### ISSUE THREAD

**Issue by wladneto** [Microsoft/BotBuilder#4833]
## Bot Info
* SDK Platform:  .NET 
* SDK Version: 3.12.2.4
* Active Channels: Telegram, FacebookMesseger and Slack
* Deployment Environment:  Azure Web App and Bot Channels Registration

## Issue Description
I have a chatbot in production (more than a month), and yesterday at night I've had some issues regarding exceptions being thrown within the chatbot, resulting in the "Sorry my bot code is having an issue" message.
It´s happen only in production... In localhost works normally.
My application is in South Central US region...

Is it an problem with the registration channel in azure?

## Reproduction Steps
1. Send a message in production (in any channel)
2. Bot response - POST to BotXPTO timeout after 15s or Sorry, my bot code is having an issue

## Expected Behavior
Solve that situation... :(

## Actual Results
Channel Registration (Azure)
![image](https://user-images.githubusercontent.com/15970264/42379009-c9acbf00-80ff-11e8-9c63-750571662ab8.png)
![image](https://user-images.githubusercontent.com/15970264/42379324-b6eb48e0-8100-11e8-9a21-3fb3d87ffc42.png)
![image](https://user-images.githubusercontent.com/15970264/42379374-cf9ce3da-8100-11e8-88e7-b64cffb2d48b.png)

**Comment by ItsMeArthur** [comment]
Hi @wladneto. I have already reported this on issue #4559. It's a really weird issue and really critical IMO. I have more than 10 bot facing this problem right now, and it seems like from yesterday to today the problem has really worsened.

**Comment by wladneto** [comment]
@ItsMeArthur pois é... rssss será que algum erro na conectividade do Brasil?

**Comment by 14geronimo** [comment]
I'm having the same issue. Was working fine before lunch ~1 h ago, I wanted to do a demo back from lunch, now I keep getting these Gateway errors. I get them in both Web App and Skype channels.

I restarted the App Service, since then the Web Chat channel is fine (both within Azure Portal and from a webpage embedded iframe. But the Skype channel is still kaput, I keep getting "Sorry, my bot code is having an issue."

Using West Europe region for the app, eu.luis.ai and spell check.

**Comment by ItsMeArthur** [comment]
@wladneto No issue que abri tem um cara até do Japão reportando o problema... Só espero que resolvam logo. Tá complicado pra quem tem bot em produção. O cliente não quer nem saber o que raios é Bot Connector.

**Comment by wladneto** [comment]
@josephktcheung it´s a good news... so the problem is real for MS. Thanks for sharing and we waiting the answer

**Comment by wladneto** [comment]
Does anyone know anything that can replace this part of channel registration? 
Apparently the problem is in connecting the channel registration with the web application.

**Comment by Carlosfbotelho** [comment]
Já tentei fazer o update de todos os pacotes no Nuget mas não ajudou nada. Sin, acho que o problema é geral. Nos aqui na Europa também temos a mesma situação. Também já tentei a solução do informático (reset ao serviço do app) mas no progress. Acho que foi o Microsoft que meteu água. Não me serve de muito, mas ... espero que os gajos em redmond não demorem muito a arrumar isto.

**Comment by wladneto** [comment]
new return from bot... :(  
POST to the bot's endpoint failed with HTTP status 401

**Comment by Carlosfbotelho** [comment]
That's wrong creds ... no?

**Comment by josephktcheung** [comment]
our bots seems to be working again now. Will wait for MS's reply nonetheless.

**Comment by wladneto** [comment]
no changes
 :( @Carlosfbotelho

**Comment by vincec-msft** [comment]
The Bot Framework team is aware of issues with the State Service which would affect bots on all channels. Calls to GetConversationDataWithHttpMessagesAsync and similar functions may take a long time or timeout entirely. Since most channels only wait 15 seconds for the bot to reply this could result in errors in both the client and the bot.

We created a hot fix and are expediting it through testing right now. It should be pushed to production world-wide in a few hours. Sorry for the impact and the delay!

Please note that the default State Store is not meant for Production use and has no guarantee of performance or availability. Bot developers should look at moving their bots to a dedicated State Store to insulate their bots from State Store problems.

https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-state?view=azure-bot-service-3.0

**Comment by josephktcheung** [comment]
@vincec-msft thanks for the reply! We've been using dynamodb for our bot's storage, so I'm not sure previous errors happened in my bots were caused by the issues with the State Service. Anyway let's hope that this error won't happen again after the fix.

**Comment by vincec-msft** [comment]
Hmm, if you're already using a dedicated State Store then there might be another issue lurking. If you post a time (UTC), channel, and part of a conversation id (just the first or last couple characters should be fine) I'll look deeper.

**Comment by Bairdsy** [comment]
It seems to be failing again, :(

**Comment by Carlosfbotelho** [comment]
@vincef-msft, thanks for looking into the issue. It worked fine for couple hours but now seems to have returned. The same gateway timeout error. Did you guys change anything ?
Best,
Carlos

**Comment by josephktcheung** [comment]
@vincec-msft here's the last error info:

conversation id: 1695************-************4886
utc time: 2018-07-06T04:48:47.266Z
channel: facebook

**Comment by Carlosfbotelho** [comment]
I get unauthorised errors interleaved with gateaway timeout

**Comment by josephktcheung** [comment]
@vincec-msft This is what I found from azure app insight:
Status code: GatewayTimeout
Exception type: Microsoft.Bot.Schema.BotTimeoutException
Failed method: Microsoft.Bot.ChannelConnector.BotAPI+<PostActivityToBotAsync>d__30.MoveNext
Call stack:
Microsoft.Bot.Schema.BotTimeoutException:
   at Microsoft.Bot.ChannelConnector.BotAPI+<PostActivityToBotAsync>d__30.MoveNext (Microsoft.Bot.ChannelConnector, Version=3.2.2.2, Culture=neutral, PublicKeyToken=null)

**Comment by josephktcheung** [comment]
Besides, I’m using node.js V3 of BotBuilder FYI

**Comment by wladneto** [comment]
My bot came back to life alone ... :) 
Problem solved...
@ItsMeArthur  voltou aí também?
THANKS

**Comment by Carlosfbotelho** [comment]
Aqui voltou .. espero que se aguente

**Comment by vincec-msft** [comment]
We rolled out a fix at 2018-07-06T17:55:00Z. The service is stable again. Please let me know if you see any more persistent timeouts.

**Comment by neetgupta7** [comment]
Bots up and running again. Thanks a lot.

**Comment by wladneto** [comment]
Thanks @vincec-msft  :)

**Comment by ItsMeArthur** [comment]
@vincec-msft My production bots are using **custom state storage with Azure Tables**. I have some POC's using the Bot State Manager, and they were also affected by this issue. As I have stated on issue #4559 this is something that keeps happening from time to time, but in a smaller scale. This is the second time I've had problems that have affected all (or most of) of my chatbots. The first time was reported on issue #4645.

I really would like to see this looked into, since when I have 10 or 15 production chatbots down, and I can't do anything about it, this it's really shaking up my confidence in the service, and I hope you guys can understand that. My team has more than 30 chatbots in the pipeline to be developed this year, and this error occurring randomly it's really making us became hesitant on taking up these projects.

@wladneto Voltou sim. Agora é torcer para que continuem verificando. Esse problema tem ocorrido de maneira aleatória a um bom tempo, na realidade desde que comecei a trabalhar com a Bot Framework a quase dois anos atrás. Você já notou isso acontecendo antes?

**Comment by wladneto** [comment]
@ItsMeArthur sim já havia percebido, mas eram poucas ocorrências (pelo menos neste bot). Só percebi mesmo com maior frequência, depois que passaram de 100 usuários e umas 50 requisições simultâneas. Assim como você disse ai em cima estou bem preocupado em usar o BotFramework em outros projetos depois deste ocorrido.
Depois quero uma aula de como usar o State Storage da forma que recomendaram, pois ainda não fiz no bot. Quando tiverem a aula me avise, vc é da cedro neh? ;)

**Comment by vincec-msft** [comment]
@ItsMeArthur , I fully understand your concerns and want you to be confident in the Bot Framework. Believe me, no one is more frustrated with instability than I am. We've been rolling out incremental fixes over the last couple weeks with the latest going out yesterday. Unfortunately, an unrelated issue came up after that deployment and we hotfixed that this morning. The stability looks good now but I'm watching it closely. There is no excuse for the problems you're seeing and it is the team's and my own top priority to solve them.

Keep opening issues when you see this sort of problem and mention me so I'm sure to see it. Thanks!

**Comment by wladneto** [comment]
@vincec-msft today i received some messages in channel registration like "There was an error sending this message to your bot: HTTP status code GatewayTimeout" :(

**Comment by vincec-msft** [comment]
@wladneto , sorry to hear that. There's nothing I can do without a time (UTC), channel, and part of a conversation id (just the first or last couple characters should be fine). Please share those and I'll see if this is a regression or something new.

**Comment by pojdrovic** [comment]
I am getting errors like this _all the time_ over the past few days on the twilio and telegram channel. Some messages go through fine and get a response back in the roughly 0.5 seconds it usually takes, but every few messages, i'll get a gatewaytimeout error like the guys above me, and it will persist for a few minutes. Then, all the responses will arrive to the user at the same time. Almost as if something is stuck, the message responses get queued up, and once it's unstuck they are fired off at the same time. I know it can't be a code problem on my end because it's working perfectly in emulator, online chat, and azure portal test chat.

**Comment by pojdrovic** [comment]
<img width="649" alt="Screen Shot 2019-11-12 at 4 36 44 PM" src="https://user-images.githubusercontent.com/10575273/68712891-a6b87480-056a-11ea-9a01-781802cdccc4.png">
This screenshot shows the error results I get back from the app log stream

**Comment by pojdrovic** [comment]
And the delay _always_ happens when context.sendActivity(message) or it's dialog counterparts are called. @vincec-msft

**Comment by pojdrovic** [comment]
<img width="656" alt="Screen Shot 2019-11-12 at 6 34 04 PM" src="https://user-images.githubusercontent.com/10575273/68720006-e176d880-057b-11ea-8985-2184830cfb75.png">
<img width="647" alt="Screen Shot 2019-11-12 at 6 34 17 PM" src="https://user-images.githubusercontent.com/10575273/68720007-e176d880-057b-11ea-88b0-1a69f65c29a9.png">
Sometimes I see the following behavior as well. I know that the API calls I'm making aren't the cause of the timeouts because in the instances where it times out, i can verify that the API call took less than a second and that the timeout occurs when botframework is returning a response

**Comment by Kadae** [comment]
Year 2021. Still problem exists.

**Comment by didz-br** [comment]
@vincec-msft Hi Vince

I´m experiencing this same issues from time to time as shown in the picture below. The bot works fine the most of the time, except when this "Gateway Timeout" happens. I´ll be glad if you can take a look ! Thanks

![Captura de tela 2021-11-05 191504](https://user-images.githubusercontent.com/21314049/140584425-c233e024-67da-4aec-b6c5-8902bd39bdfa.png)

**Comment by vincec-msft** [comment]
> I´m experiencing this same issues from time to time as shown in the picture below. The bot works fine the most of the time, except when this "Gateway Timeout" happens.

@didz-br: This issue is 2 years old and Closed. And I no longer work on the Bot Framework.
Please open a new issue and someone on the team will take a look. Thanks.
