### ISSUE TITLE
[Feature Request] Ability to inspect JSON sent to channel

### ISSUE THREAD

**Issue by JasonSowers** [Microsoft/BotBuilder#4858]
RIght now customers do not have a way to inspect the JSON the connector sends to a channel.  We can only inspect the JSON we send to the connector from the bot.  It would be helpful to be able to inspect this in general, but especially in a situation where `ChannelData`/`sourceEvent` is being utilized.

Related issues:
#4854

**Comment by josephktcheung** [comment]
Thanks @JasonSowers for opening this feature request. I copied what I described in #4854 here for easier reference.

The following `sourceEvent` works but its format is different from the one suggested by Facebook.

```ts
const message = new Message(session);

message.sourceEvent({
  facebook: {
    tag: 'NON_PROMOTIONAL_SUBSCRIPTION',
    messaging_type: 'MESSAGE_TAG',
    attachment: {
      type: 'template',
      payload: {
        template_type: 'button',
        text: 'Button template',
        buttons: [
          {
            type: 'web_url',
            url: 'https://google.com',
            title: 'Google',
            messenger_extensions: true,
            webview_share_button: 'hide',
            webview_height_ratio: 'full',
          },
        ],
      },
    },
  },
});

session.send(message);
```
Facebook's template type message format https://developers.facebook.com/docs/messenger-platform/send-messages/templates#sending_a_message_template:
```ts
{
  "recipient":{
    "id":"<PSID>"
  },
  "message":{
    "attachment":{
      "type":"template",
      "payload":{
        "template_type":"<TEMPLATE_TYPE>",
        ...
      }
    }
  }
}
```
and to use message tag the format is like this https://developers.facebook.com/docs/messenger-platform/send-messages/message-tags#Sending:
```
curl -X POST -H "Content-Type: application/json" -d '{
  "recipient": { 
    "id": "<PSID>"
  },
  "message":{
    ...
  },
  "messaging_type": "MESSAGE_TAG",
  "tag": "SHIPPING_UPDATE"
}' "https://graph.facebook.com/v2.6/me/messages?access_token=<PAGE_ACCESS_TOKEN>"  
```
So one would expect in botbuilder we should construct the `sourceEvent` like this (nesting `attachment` in `message`):
```ts
message.sourceEvent({
  facebook: {
    tag: 'NON_PROMOTIONAL_SUBSCRIPTION',
    messaging_type: 'MESSAGE_TAG',
    message: {
      attachment: {
        type: 'template',
        payload: {
          template_type: 'button',
          text: 'Button template',
          buttons: [
            {
              type: 'web_url',
              url: 'https://google.com',
              title: 'Google',
              messenger_extensions: true,
              webview_share_button: 'hide',
              webview_height_ratio: 'full',
            },
          ],
        },
      },
    },
  },
});
```
But in reality `attachment` doesn't need to be nested in `message`. My guess is that MS pick certain attributes from `sourceEvent` and put them in `message` object and set the other attributes at the same level of `message`?
That's why letting us know the final JSON message created by bot framework that get sent to the channel looks like would be very helpful, since we know how to construct `sourceEvent` correctly.

**Comment by stevengum** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
