### ISSUE TITLE
[FormFlow] TemplateUsage.EnumOneNumberHelp null reference when using {&}

### ISSUE THREAD

**Issue by glasody** [Microsoft/BotBuilder#4865]
## Bot Info
* SDK Platform: .Net
* SDK Version: 3.15.3
* Active Channels: Facebook
* Deployment Environment: Azure App Service, Bot Channel Registrations.

## Issue Description
When using a template attribute for an enum property/field, and trying to change the TemplateUsage.EnumOneNumberHelp, if I use {&} in the string prompt it throws a null exception.
If I run it without placing a {&} in the TemplateUsage.EnumOneNumberHelp it works.

The {&} works as expected when used in other TemplateUsage e.g. StringHelp

## Code Example
```csharp
[Serializable]
public class BugForm {
  public enum GenderChoice {
    [Describe ("Female")]
    Female = 1, [Describe ("Male")]
    Male, [Describe ("Gender diverse")]
    GenderDiverse
  }

  [Prompt ("What {&} do you identify as? {||}", ChoiceStyle = ChoiceStyleOptions.Buttons)]
  [Describe ("Gender")]
  [Terms ("Gender")]
  [Template (TemplateUsage.NotUnderstood, "I'm sorry, I did not understand that. What {&} do you identify as? {||}")]
  [Template (TemplateUsage.Help, "You are filling in the {&} field.\n{0}\n{1}")]
  [Template (TemplateUsage.EnumOneNumberHelp, "Please select the {&} you identify as.")]
  public GenderChoice Gender { get; set; }

  public static IForm<BugForm> BuildForm () {
    return new FormBuilder<BugForm> ()
      .Field (new FieldReflector<BugForm> (nameof (Gender))
        .SetType (null))
      .Build ();
  }
}
```

## Reproduction Steps
1. Create a simple bot solution
2. Create a FormFlow with a custom Enum field and add the Template attribute with TemplateUsage.EnumOneNumberHelp, in the pattern string type a string with {&} included.
3. Run the form and type help when prompted for that field

## Expected Behavior
Show help with custom string and {&} replaced with field name like the StringHelp Template

## Actual Results
Null reference exception is thrown when help is typed which causes the form to exit.

**Comment by corinagum** [comment]
Hi glasody, 

Thank you for your question. The intended functionality of EnumOneNumberHelp is to make a list of the types that are available in that field and the numbers that can be used to select them, as opposed to listing the field. As such using {&} (referencing the describe of the field), is unavailable, and should be instead used to list the numbers a user may enter to make a selection, as well as the types within the field themselves. 

[As seen here on the IFormBuilder](https://github.com/Microsoft/BotBuilder/blob/b7b2abbd089b0c0b91f367e4355743f7171dbc26/CSharp/Library/Microsoft.Bot.Builder/FormFlow/IFormBuilder.cs#L357), {0}, {1}, and {2} are the available options in this attribute, and list the minimum number, maximum number, and description of all possible words, respectively. 

In your example, you are actually using Help in the way I would recommend as your solution. The default message for EnumOneNumberHelp is:

> You can enter a number {0} - {1} or words from the descriptions. ({2}).

In your gender example, that message is thus:

> You can enter a number 1 - 3 or words from the descriptions. (Female, Male or Gender Diverse)

This line actually appears under the Help line when called, which indicates to the user that you are filling out the (Gender) field. Because of this, referencing the field name describe attribute is not intended or necessary.

Hope that helps. Please let me know if you have questions.
