### ISSUE TITLE
Prompt Dialog in Microsoft.Bot.Connector.AspNetCore version 2.0.1.x

### ISSUE THREAD

**Issue by huyjack178** [Microsoft/BotBuilder#4895]
I want to send a message Prompt dialog when using Microsoft.Bot.Connector.AspNetCore version 2.0.1.9 but don't find any related document. Can anyone help me?

**Comment by JasonSowers** [comment]
Unfortunately, you cannot do this out of the box, Dialogs are not supported in v3 of the SDK with ASP.Net Core. Since under the hood prompts are essentially just dialogs, this is not supported.  There is a workaround in v3 a customer was able to find in #3941 that you may be able to use to accomplish this.  Also if you are looking to use Asp.Net Core I would look into using our [v4 SDK](https://github.com/Microsoft/BotBuilder-dotnet) which fully supports it.
