### ISSUE TITLE
My bot just vanished from dev.botframework.com

### ISSUE THREAD

**Issue by andrecarlucci** [Microsoft/BotBuilder#4913]
## Bot Info
* SDK Platform:  .net
* Active Channels: Skype
* Deployment Environment: Azure App Service

## Issue Description
I'm logging on dev.botframework.com and I get the message:
"You don't have any bots or skills yet."

This the Id:
<add key="MicrosoftAppId" value="9803b489-6ac4-4766-b505-f9b3ae1a61f1" />

**Comment by EricDahlvang** [comment]
Is your bot available in the Azure Portal?

**Comment by andrecarlucci** [comment]
I have a appservice there with the .net part.
I haven't touch it for ages, it was working just fine.

**Comment by EricDahlvang** [comment]
Please share the Bot Handle, and MicrosoftAppId for the bot.

**Comment by andrecarlucci** [comment]
E-mail sent :)

**Comment by EricDahlvang** [comment]
Investigating...

**Comment by EricDahlvang** [comment]
Closing this issue.  Future communications will be via email.

**Comment by sashavtyurina** [comment]
I'm having the same issue. 
Would you mind sharing what the solution to your problem was?

Details: I had a bot created on azure through Cognitive Services, added a Cortana channel. It worked fine on all devices. I made some changes and published it from Visual Studio again. Result: works as expected on Azure in "Test in Web Chat" tab, but when I try to access it through my phone or desktop Cortana app, it returns with a message:  _Uh oh, there's a problem with the skill you've selected. Please try again later._
