### ISSUE TITLE
[Feature Request] Connects bots to channels programmatically

### ISSUE THREAD

**Issue by fmaker** [Microsoft/BotBuilder#4930]
Currently it is a manual process to connect a Bot to a channel using the Azure portal. I need to be able to connect my bot to Facebook pages programatically. Now that multiple Facebook pages are supported I can do this manually, but if my user changes the page they want to connect to I have to update it manually.

**Comment by EricDahlvang** [comment]
Hi @fmaker 

Programmatic channel configuration would be done with AzureCli, which is in the BotBuilder-Tools repository.  Please move this issue to that repo: https://github.com/Microsoft/botbuilder-tools/issues

**Comment by rasikas** [comment]
I have a question related to channels and using bot SDK outside azure, Is there a sample code which shows how to connect the bot sdk with facebook channel without deploying it to Azure ? ex: running as a standalone node app and connect facebook callback?. The reason is I [checked this sample ](https://github.com/Microsoft/BotBuilder/blob/master/Node/examples/demo-facebook/app.js) and inside the logic I can't see it has a facebook channel specific connector is used. So my question is does bot SDK core automatically understand how to interpret messages comming from any channel (in this case facebook) or does this conversion done by the channel connectors only available in Azure deployment? - Thanks

**Comment by EricDahlvang** [comment]
@rasikas  The Microsoft Bot Framework channel connectors convert the various messages from the platform specific type to the Activity Schema, then forward the message to the bot.  Channel specific properties can usually be found in the activitie's ChannelData property.  Using the Microsoft Bot Framework to connect to a channel requires a Bot Channel Registration on Azure so the channel connectors are able to determine where to send the message.  In order to use the Bot Builder SDK without a bot registration, you would need to write your own channel connector service.  However, that would still not be enough ... since  things like this are baked directly into the SDK: https://github.com/Microsoft/BotBuilder/blob/master/Node/core/lib/bots/ChatConnector.js#L23
