### ISSUE TITLE
Offline Bot

### ISSUE THREAD

**Issue by HekMe** [Microsoft/BotBuilder#4979]
Hello,
is there any option to run these bots offline?
We have private network without client access to internet, and we'd like to make web chatbot(hosted on one of our terminal servers) for our clients. 
Is it possible?

Thanks

**Comment by EricDahlvang** [comment]
On premise hosting is possible, but currently the hosting server must have an internet accessible endpoint and a valid cert from one of the Microsoft Trusted Certificate Authorities.  Entirely on prem, without internet access, is officially not an option.  The connector services require an internet connection in order to send messages to the bot's endpoint.

That said, there are some community written options such as: https://www.npmjs.com/package/offline-directline  However, this is not officially supported by Microsoft.
