### ISSUE TITLE
Conversation state can't gotten in IActivityLogger.LogAsync botframework c#

### ISSUE THREAD

**Issue by xiaolangxyz** [Microsoft/BotBuilder#5016]
## Bot Info
* SDK Platform: .NET 
* SDK Version:  SDK version 3
* Active Channels: Emulator
* Deployment Environment: local development with Emulator

## Issue Description
Q1: I have set some data in a conversation, but it can't be gotten in IActivityLogger.LogAsync.
Q2: I think I can get state data like [this][1] . But Vistual Studio told me not to use it anymore. What's the new way?

  [1]: https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-state?view=azure-bot-service-3.0#get-state-data

## Code Example
![1](https://user-images.githubusercontent.com/40823365/44763417-220c5100-ab86-11e8-8b38-91a3426308f7.PNG)
![2](https://user-images.githubusercontent.com/40823365/44763418-23d61480-ab86-11e8-9975-20dc1b2d5a31.PNG)

**Comment by EricDahlvang** [comment]
activity.GetStateClient() will retrieve an interface for interacting with the default state service.  However, the default state service has been deprecated: https://blog.botframework.com/2017/12/19/bot-state-service-will-soon-retired-march-31st-2018/

State should be retrieved like this:

```cs
using (var scope = DialogModule.BeginLifetimeScope(Conversation.Container, msg))
{
            var botData = scope.Resolve<IBotData>();
            await botData.LoadAsync(new System.Threading.CancellationToken());

            var userData = botData.UserData;
            var userData = botData.PrivateConversationData;
            var userData = botData.ConversationData;            
}
```

However, if you do this in IActivityLogger.LogAsync, the loaded IBotData will not contain the information you've just added because the state is not persisted until the dialog turn is complete, which doesn't happen until after the .LogAsync method.

This issue has come up before, and some workarounds are described here: https://github.com/Microsoft/BotBuilder/issues/4007

---
The Microsoft Bot Framework team prefers that **how to** questions be submitted on [Stack Overflow](http://stackoverflow.com/search?q=%23botframework). The official [Bot Framework Github](https://github.com/Microsoft/BotBuilder/issues) repo  is the preferred platform for submitting **bug fixes and feature requests**.  
 
I have closed this issue. Please feel free to resubmit your question over on Stack Overflow and one of our support engineers will help you out as soon as possible.

**Comment by xiaolangxyz** [comment]
@EricDahlvang I got it. Actually I'm trying to add a Time Out Dialog.  So I have to record the time when user send a message to a Bot. I thought IActivityLogger is the best place to record it. But I still have no idea where to store it. Can you give me some suggestions?

**Comment by EricDahlvang** [comment]
Some example for how to time out a conversation can be found in this repository: https://github.com/EricDahlvang/EndConversationTest
