### ISSUE TITLE
Skype: How to get full certified/full trust to bot?

### ISSUE THREAD

**Issue by Sopholos** [Microsoft/BotBuilder#5033]
## Bot Info
* SDK Platform:  .NET Framework
* SDK Version: 3.16
* Active Channels: Skype
* Deployment Environment: Azure Bot Service (via Azure App Service?. I'm deploying to app. but managing channels in bot)

## Issue Description
I know at least two bots with full access to all group messages: Skype Translator and Sameroom
But when I'm trying to add my bot I got message from skype that bot will receive only direct messages (with nick)

## Code Example
Standard bot project draft from Azure Bot Services: SimpleEcho

## Reproduction Steps
1. Save skype bot channel
2. Add to any group
3. Type any words

## Expected Behavior
Bot does not receive messages

## Actual Results
Bot must receive any message

I need to know how could I receive all messages?
As I see other bots (even NOT from Microsoft) could be able to work as expected so there must be some way to enable that. I does not found anything in docs or google.

**Comment by EricDahlvang** [comment]
This is not a feature generally available.  I think Sameroom has partnered with Skype, and is using an undocumented API.  I don't know what it is, or how to enable this for your bot.  I do know this is not a feature generally available, and there are no plans in place to enable it for all bots.  Closing this issue, since there isn't anything for anyone to do here.
