### ISSUE TITLE
Bot works locally, but not working after publishing to web app bot

### ISSUE THREAD

**Issue by asichaib** [Microsoft/BotBuilder#5034]
## Bot Info
* SDK Platform:  .NET 
* SDK Version: 3.16.0.38344
* Active Channels:  Web Chat 
* Deployment Environment:  Azure Web App Bot 

## Issue Description
The bot is working locally. When I publish it and try it with web chat channel, it says "couldn't send" and I've this error in the channel log "There was an error sending this message to your bot: HTTP status code InternalServerError". 

## Reproduction Steps
1.
2.
3.

**Comment by rosskyl** [comment]
Make sure when you deploy to Azure, you select the option to "Remove additional files at destination". You can check this by going into your publish profile, clicking on "Configure", "Settings", then "File Publish Options".

The reason this needs to be done is the bot you created in azure has a bot already deployed and there are issues with overlapping content.

**Comment by asichaib** [comment]
@rosskyl  Thanks for your response. The option is already checked :)

**Comment by jwiley84** [comment]
Hi @asichaib! 

I'm assuming you're using Azure's 'Test in Web Chat' feature?  What shows when you look at the developer console (F12 on Chrome)?

**Comment by asichaib** [comment]
@jwiley84 I'm using the Test in web chat integrated in Azure portal

**Comment by asichaib** [comment]
Thanks. The errors are:
500 Internal server error
<title>Could not load file or assembly 'Autofac, Version=3.5.0.0, Culture=neutral, PublicKeyToken=17863af14b0044da' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)</title>


And 

502 bad gateway

**Comment by jwiley84** [comment]
@asichaib, what version of Autofac are you using, in your Nuget package manager? And what version is listed in your web.config. I've had occasions where I'm using 4.8 in the package manager and 3.5 in my web.config, which can cause this error. If this is the case, you can manually change your web.config file to match, and then republish to Azure and it should fix this.

**Comment by abhishekkant** [comment]
Hi Everyone

We are also facing the same issue. However, in our case the bot has been working in the past. We have made no code changes and approx on Sept 1, the bot started problems calling the external API. The few initial calls that don't call an external API are working well. Our bot environment: 
SDK Platform: .NET
SDK Version: 3.15.3.0
Active Channels: Web Chat or DirectLine
Deployment Environment: Azure Web App Bot

We can see error: "There was an error sending this message to your bot: HTTP status code GatewayTimeout" in the Channels settings.

In addition, our error logging infrastructure is showing the following: 
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond x.x.x.x:443   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)   --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)   --- End of inner exception stack trace ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at Services.RaiseSR.<CustomerDetails>d__3.MoveNext()

Checking the bot from local development machine throws no such errors. 

Also, we created a new Web App Service and deployed the bot code there. Testing from Bot Emulator threw the same error again.

There is no NSG or Virtual Network configured with the bot.

Can someone suggest a course of investigation/ action?

Cheers
Abhishek

**Comment by jwiley84** [comment]
Hi @abhishekkant! 

That actually isn't the same thing at all. Can you open a separate github issue, please?

**Comment by jwiley84** [comment]
Hi @asichaib ! Just checking to see if you're still having this issue.

**Comment by johnataylor** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
