### ISSUE TITLE
conversationId is private

### ISSUE THREAD

**Issue by huajunzhao** [Microsoft/BotBuilder#5055]
## Bot Info
* SDK Platform: 
* SDK Version: 
* Active Channels: 
* Deployment Environment: 

## Issue Description

We're trying to add the below code in Chat.tsx to resume the conversation history in webchat.

```js
 const botConnection = new BotChat.DirectLine({
        secret: 'XXXXXXXXXXXXXXXXXXXXXX',
        conversationId: localStorage.conversationId,
        watermark: "01",
        webSocket: false,
        pollingInterval: 5000
    });

BotChat.App({
    botConnection: botConnection
    ,user: { id: 'USER_ID', name: 'User' },
    resize: 'detect'
}, document.getElementById("chatdiv"));

botConnection.connectionStatus$.subscribe(function (status) {
    if (status == 2) {  // wait for connection is 'OnLine' to send data to bot
        var convId = **botConnection.conversationId**;
        if (convId !== localStorage.conversationId) {
                     localStorage.setItem('conversationId', convId);
         }
    }
});
```

## Reproduction Steps
1.  
2.
3.

## Expected Behavior

Be able to get the conversation after botconnection is created. Any suggestions?

## Actual Results

Getting the build error Property 'conversationId' does not exist on type 'IBotConnection'

**Comment by Kartik1607** [comment]
Looking at current implementation of [Directline](https://github.com/Microsoft/BotFramework-DirectLineJS), it seems one of the viable option is to [subscribe to activity observable](https://github.com/Microsoft/BotFramework-DirectLineJS/blob/master/src/directLine.ts#L298) which is public. You can consume the observable once which will provide you [conversation id](https://github.com/Microsoft/BotFramework-DirectLineJS/blob/master/src/directLine.ts#L209).

**Comment by tomlm** [comment]
This issue was moved to Microsoft/BotBuilder-V3#1

**Comment by EricDahlvang** [comment]
Hi @huajunzhao 

conversationId is private on DirectLineJs https://github.com/Microsoft/BotFramework-DirectLineJS/blob/master/src/directLine.ts#L303 IBotConnection  This PR would make it public: https://github.com/Microsoft/BotFramework-DirectLineJS/pull/49  

Client side code can handle this.  (It shouldn't be necessary to alter Chat.tsx )

The method described by @Kartik1607 would be something like: 
```js
        botConnection.activity$.take(1).subscribe(function (activity) {
            var convId = activity.conversation.id;
            console.log('"activity$.subscribe" received activity with conversation.id value: ' + convId);
            if (convId !== localStorage.conversationId) {
                localStorage.setItem('conversationId', convId);
            }
        });
```

Also, you might want to use watermark: "" instead of "01".

---
If you require further assistance with WebChat questions, please ask on this repository: https://github.com/Microsoft/BotFramework-WebChat/issues or StackOverflow: https://stackoverflow.com/questions/tagged/botframework
