### ISSUE TITLE
How can i inject different dependencies  with autofac.

### ISSUE THREAD

**Issue by Dorentin1997** [Microsoft/BotBuilder#5086]
I have a bootstraper class that i run i soon as application start, usually i register services, repositories and other classes there and set an dependency resolver, and in controllers i use constructor inject to get the services and repositories. Can someone give me an example how can i do the same thing in bot framework. 
In the message controller i need to resolve a service which creates some logs and saves them in Database.

**Comment by tomlm** [comment]
I am closing this due to the fact that this repos issues are for platform DCRs only.

In addition, the post is:

a.  it doesn't identify the SDK

b. it is a request for help and those should be done via stack overflow.


To get help with an issue with your bot
* ["How To"](https://stackoverflow.com/help/how-to-ask) questions should be submitted on [Stack Overflow](https://stackoverflow.com/questions/tagged/botframework).

To file an issue against a component please go to the components repo
* [Create Azure Bot Framework Service or Channel issue](https://github.com/Microsoft/botframework-services/issues/new/choose)
* [Create Bot Builder Tools issue](https://github.com/Microsoft/botbuilder-tools/issues/new/choose)
* [Create Bot Builder SDK V3 (.NET or Javascript) issue](https://github.com/Microsoft/botbuilder-V3/issues/new/choose)
* [Create Bot Builder SDK V4 .NET issue](https://github.com/Microsoft/botbuilder-dotnet/issues/new/choose)
* [Create Bot Builder SDK V4 Javascript issue](https://github.com/Microsoft/botbuilder-js/issues/new/choose)
* [Create Bot Builder SDK V4 Java issue](https://github.com/Microsoft/botbuilder-java/issues/new/choose)
* [Create Bot Builder SDK V4 Python issue](https://github.com/Microsoft/botbuilder-python/issues/new/choose)
