### ISSUE TITLE
ADDV2 authentication Sign in wroking in  emulator but it is not working in published bot in msteams. No pop  up open on click of sign in

### ISSUE THREAD

**Issue by poonam0025** [Microsoft/BotBuilder#5103]
## This is not for asking questions or filing bugs

To get help with an issue with your bot
* ["How To"](https://stackoverflow.com/help/how-to-ask) questions should be submitted on [Stack Overflow](https://stackoverflow.com/questions/tagged/botframework).

To file an issue against a component please go to the components repo
* [Create Azure Bot Framework Service or Channel issue](https://github.com/Microsoft/botframework-services/issues/new/choose)
* [Create Bot Builder Tools issue](https://github.com/Microsoft/botbuilder-tools/issues/new/choose)
* [Create Bot Builder SDK V3 (.NET or Javascript) issue](https://github.com/Microsoft/botbuilder-V3/issues/new/choose)
* [Create Bot Builder SDK V4 .NET issue](https://github.com/Microsoft/botbuilder-dotnet/issues/new/choose)
* [Create Bot Builder SDK V4 Javascript issue](https://github.com/Microsoft/botbuilder-js/issues/new/choose)
* [Create Bot Builder SDK V4 Java issue](https://github.com/Microsoft/botbuilder-java/issues/new/choose)
* [Create Bot Builder SDK V4 Python issue](https://github.com/Microsoft/botbuilder-python/issues/new/choose)

## Issue
*Describe the issue you are addressing*

## Proposed change
*Describe the proposed solution*

## Component Impact 
*Describe which components need to be updated*

## Customer Impact 
*Describe the impact on customers*

## Tracking Status
**Dotnet SDK**
- [ ] PR
- [ ] Merged

**Javascript SDK**
- [ ] PR
- [ ] Merged

**Java SDK**
- [ ] PR
- [ ] Merged

**Python SDK**
- [ ] PR
- [ ] Merged

**Emulator**
- [ ] PR
- [ ] Merged

**Samples**
- [ ] PR
- [ ] Merged

**Docs**
- [ ] PR
- [ ] Merged

**Tools**
- [ ] PR
- [ ] Merged

[dcr]

**Comment by v-kydela** [comment]
Hi @poonam0025. I'm closing this issue because this repo is for DCR's only.

To file an issue against a component please go to the components repo
* [Create Azure Bot Framework Service or Channel issue](https://github.com/Microsoft/botframework-services/issues/new/choose)
* [Create Bot Builder Tools issue](https://github.com/Microsoft/botbuilder-tools/issues/new/choose)
* [Create Bot Builder SDK V3 (.NET or Javascript) issue](https://github.com/Microsoft/botbuilder-V3/issues/new/choose)
* [Create Bot Builder SDK V4 .NET issue](https://github.com/Microsoft/botbuilder-dotnet/issues/new/choose)
* [Create Bot Builder SDK V4 Javascript issue](https://github.com/Microsoft/botbuilder-js/issues/new/choose)
* [Create Bot Builder SDK V4 Java issue](https://github.com/Microsoft/botbuilder-java/issues/new/choose)
* [Create Bot Builder SDK V4 Python issue](https://github.com/Microsoft/botbuilder-python/issues/new/choose)

**Comment by v-kydela** [comment]
Also consider:
* ["How To"](https://stackoverflow.com/help/how-to-ask) questions should be submitted on [Stack Overflow](https://stackoverflow.com/questions/tagged/botframework).
