### ISSUE TITLE
DCR: Add new BotState.delete() method

### ISSUE THREAD

**Issue by Stevenic** [Microsoft/BotBuilder#5175]
## Issue
There is currently no way to delete the backing storage object for a `BotState` instance without having to go through the `Storage` provider directly.

## Proposed change
I propose that we add a new `BotState.delete()` method which lets the developer easily delete a states backing storage object.  We should then update our samples to show this as the recommended way of handing things like end-of-conversation or turn errors.  The primary benefits of this method over the current `BotState.clear()` method are:

- Physically removes the conversations object from storage, helping to reduce the number of old state objects being stored.
- Doesn't require dev to also call `BotState.saveChanges()` like clear() does.

## Component Impact 
Just the `BotState` class.

## Customer Impact 
*Describe the impact on customers*

## Tracking Status
**Dotnet SDK**
- [ ] PR
- [ ] Merged

**Javascript SDK**
- [ ] PR
- [ ] Merged

**Java SDK**
- [ ] PR
- [ ] Merged

**Python SDK**
- [ ] PR
- [ ] Merged

**Emulator**
- [ ] PR
- [ ] Merged

**Samples**
- [ ] PR
- [ ] Merged

**Docs**
- [ ] PR
- [ ] Merged

**Tools**
- [ ] PR
- [ ] Merged

[dcr]

**Comment by drub0y** [comment]
So, ok, `clear` is going to remain and retain it's current functionality of simply removing the cached state, right? I ask because you had this bullet point to differentiate it from `delete` that is confusing:

> Doesn't require dev to also call BotState.saveChanges() like clear() does.

To the best of my understanding of the C# code right now, `clear` will _never_ ever cause anything to change _even if_ you call `saveChanges`. So when I read that bullet point I'm not sure if there's still some misunderstanding of what `clear` currently does or if maybe it's behaving slightly differently/more correctly in JavaScript land. In .NET land it literally just constructs a new cache entry that, unless _further_ mutated from that point, will never cause an overwrite even if a call to `saveChanges` was made.

So I guess I would support a `delete` for the main reason that you say it will wipe itself immediately which feels right, but I still wonder where that leaves `clear`. Should it be fixed so it clears the cache correctly or should its behavior remain as it is today which is kinda "weird"... especially in the way it was being used in the `OnTurnError` callback examples that prompted this discussion.

**Comment by Stevenic** [comment]
> So, ok, `clear` is going to remain and retain it's current functionality of simply removing the cached state, right?

Yes... that's correct. The `clear` method will stay and retain it's current **expected** behavior.



> To the best of my understanding of the C# code right now, `clear` will _never_ ever cause anything to change _even if_ you call `saveChanges`. 

That's a bug. Calling `clear` and then `saveChanges` should overwrite the current state object.  @johnataylor and I both have fixes in the pipe for this.

**Comment by drub0y** [comment]
Ok, see my comments on @johnataylor's [PR](https://github.com/Microsoft/botbuilder-dotnet/pull/1172)  because, in its current state, I don't believe the fix achieves what you're saying here.
