### ISSUE TITLE
is there a way to access session.conversationData while intercepting 'send' hook from middleware?

### ISSUE THREAD

**Issue by ghost1996110** [Microsoft/BotBuilder#5186]
bot.use({
  botbuilder (session, next) {
    logger.info("MESSAGE RECEIVED:" + session.message.text);
    next();
  },

  send (event, next) {
    logger.info("MESSAGE SENT:" + event.text);
    next();
  }
});

is there a way to access session in send hook in middleware ?

**Comment by jwiley84** [comment]
This repo is currently only taking Design Change Requests (DCR) issues. For submitting **bug fixes** and **feature requests**, please go to the following repo [Botbuilder-js](https://github.com/Microsoft/Botbuilder-js). Otherwise, the Microsoft Bot Framework team prefers that **how to** questions be submitted on [Stack Overflow](http://stackoverflow.com/search?q=%23botframework).
