### ISSUE TITLE
Author the 4.2 release notes for JS and C# Release

### ISSUE THREAD

**Issue by cleemullins** [Microsoft/BotBuilder#5197]
Tracking item for authoring detailed release notes as part of the 4.2 C# and JS SDK Release process.

**Comment by yochay** [comment]
@cleemullins  i've sent these file via email - copying here for ref


> dotnet release note

# Release 4.1 (Dec 14)
In this release the team focused on enhancing monitroing, telemetry and analytics capabilaties of the SDK by improving the integration with Azure App Insights. We have streamlined the integration and default telemetry emitted from the SDK. This include (Waterfall) dialog instrumentation, docs and examples for querying data, and a PowerBid dashboard. As with any release, we fixed a [number of bugs](https://github.com/Microsoft/botbuilder-dotnet/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A4.2+label%3Abug), conitnue improve LUIS and QnA integration and further clean our engineering practices.  There were additional updates across addigional area like Language, Prompt and Dialogs, and Connectors and Adapters.

Review all changes that wen into 4.2 in the detailed [Change Log]()
See the list of all [issues](https://github.com/Microsoft/botbuilder-dotnet/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A4.2+)


> dotnet 4.2 change log

# V4.2.0

## Monitroing, Telemetry and Analytics
- Application Insights build fixes [[PR 1221]](https://github.com/Microsoft/botbuilder-dotnet/pull/1221)
- Application Insights integration : ASP.Net Core review [[PR 1168]](https://github.com/Microsoft/botbuilder-dotnet/pull/1168)
- Renamed ApplicationInsights projects to have ".Integration" in them. [[PR 1217]](https://github.com/Microsoft/botbuilder-dotnet/pull/1217)
- Update AppInsights .Net Core 2 project for packaging [[PR 1216]](https://github.com/Microsoft/botbuilder-dotnet/pull/1216)
- Log TraceTelemetry with Application Insights telemetry [[PR 1213]](https://github.com/Microsoft/botbuilder-dotnet/pull/1213)
- Add DialogSet.SetTelemetryClient(), and modify ComponentDialog [[PR 1210]](https://github.com/Microsoft/botbuilder-dotnet/pull/1210)
- Replace await with ContinueWith in Transcript middleware [[PR 1212]](https://github.com/Microsoft/botbuilder-dotnet/pull/1212)
- Dialog exposing Logger property IBotTelemetryClient [[PR 1179]](https://github.com/Microsoft/botbuilder-dotnet/pull/1179)
- Add WaterfallDialog StartEvent for VA [[PR 1198]](https://github.com/Microsoft/botbuilder-dotnet/pull/1198)
- Telemetry: Add instanceId to WaterfallDialog logging [[PR 1196]](https://github.com/Microsoft/botbuilder-dotnet/pull/1196)
- Add user agent header to QnA calls [[PR 1201]](https://github.com/Microsoft/botbuilder-dotnet/pull/1201)
- Add user agent to LUIS calls [[PR 1199]](https://github.com/Microsoft/botbuilder-dotnet/pull/1199)

## Language (LUIS, Recognizers, QnA)
- Add options to individual QnAMaker calls [[PR 1200]](https://github.com/Microsoft/botbuilder-dotnet/pull/1200)
- Role instead of entity type as property name in composites. [[PR 1094]](https://github.com/Microsoft/botbuilder-dotnet/pull/1094)

## Prompts and Dialogs
- Dix for confirm prompt exception when locale on activity was empty string [[PR 1178]](https://github.com/Microsoft/botbuilder-dotnet/pull/1178)

## State and Storage
- Add Delete function to BotState for parity with JavaScript [[PR 1215]](https://github.com/Microsoft/botbuilder-dotnet/pull/1215)
- Make CosmosDB provider consistent with Blob Storage provider [[PR 1181]](https://github.com/Microsoft/botbuilder-dotnet/pull/1181)
- Dixed force flag on save following clear [[PR 1172]](https://github.com/Microsoft/botbuilder-dotnet/pull/1172)
- Adds integration extensions for IServiceCollection [[PR 1103]](https://github.com/Microsoft/botbuilder-dotnet/pull/1103)
- Obsolete the BotFrameworkOptions::State property [[PR 1102]](https://github.com/Microsoft/botbuilder-dotnet/pull/1102)

## Connectors and Adapters
- Allow the serviceUrl to be null in the response from a CreateConversation call [[PR 1193]](https://github.com/Microsoft/botbuilder-dotnet/pull/1193)
- Updating to validate JWT tokens from the emulator [[PR 1174]](https://github.com/Microsoft/botbuilder-dotnet/pull/1174)
- Update connector lib with latest swagger [[PR 1078]](https://github.com/Microsoft/botbuilder-dotnet/pull/1078)
- Add reply conversation ref method to activity [[PR 1194]](https://github.com/Microsoft/botbuilder-dotnet/pull/1194)

## Engineering (Build, Automatio, Tests)
- Adding 'channelService' property to the bot file's endpoint service type [[PR 1163]](https://github.com/Microsoft/botbuilder-dotnet/pull/1163)
- Update packages and fix compiler warning [[PR 1104]](https://github.com/Microsoft/botbuilder-dotnet/pull/1104)
- Cherry-pick pull request #1076 from 4.1 for US Gov Data centers [[PR 1077]](https://github.com/Microsoft/botbuilder-dotnet/pull/1077)
- Regen Swagger components, add autorest.csharp as a pinned devDependency [[PR 1208]](https://github.com/Microsoft/botbuilder-dotnet/pull/1208)

## General
- Change serialization settings so anonymous supported [[PR 1096]](https://github.com/Microsoft/botbuilder-dotnet/pull/1096)


> *****************************************************************

> JS release note

# Release 4.1 (Dec 14)
In this release the team focused on enhancing monitroing, telemetry and analytics capabilaties of the SDK by improving the integration with Azure App Insights. We have streamlined the integration and default telemetry emitted from the SDK. This include (Waterfall) dialog instrumentation, docs and examples for querying data, and a PowerBid dashboard. As with any release, we fixed a [number of bugs](https://github.com/Microsoft/botbuilder-js/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A4.2+label%3Abug), conitnue improve LUIS and QnA integration and further clean our engineering practices.  There were additional updates across addigional area like Language, Prompt and Dialogs, and Connectors and Adapters.

Review all changes that wen into 4.2 in the detailed [Change Log]()
See the list of all [issues](https://github.com/Microsoft/botbuilder-js/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A4.2+)


> JS Change Log
# V4.2.0

## Monitroing, Telemetry and Analytics
- Add AppInsights package into build publish step [[PR 688]](https://github.com/Microsoft/botbuilder-js/pull/688)
- add user agent header to LUIS [[PR 677]](https://github.com/Microsoft/botbuilder-js/pull/677)
- Add BotTelemetry instrumentation and utilities [[PR 662]](https://github.com/Microsoft/botbuilder-js/pull/662)
- [Breaking Change] change PagedResult and TranscriptInfo to interfaces [[PR 664]](https://github.com/Microsoft/botbuilder-js/pull/664)
- Fix require of cls-hooked [[PR 689]](https://github.com/Microsoft/botbuilder-js/pull/689)
- add console.error for async TranscriptLogger.logActivity() impl in TranscriptLoggerMiddleware [[PR 669]](https://github.com/Microsoft/botbuilder-js/pull/669)


## Language (LUIS, Recognizers, QnA)
- QnAMaker - Add getAnswers(), fix options in constructor, add metadata, create queryQnaMakerService() [[PR 683]](https://github.com/Microsoft/botbuilder-js/pull/683)
- Role instead of entity type as property name in composites. [[PR 622]](https://github.com/Microsoft/botbuilder-js/pull/622)

## Prompts and Dialogs
- fix confirm prompt when invalid locale used with number selection [[PR 654]](https://github.com/Microsoft/botbuilder-js/pull/654)
- ActivityPrompt wasn't using retryPrompt if specified. [[PR 673]](https://github.com/Microsoft/botbuilder-js/pull/673)

## State and Storage
- add overloads to BotStatePropertAccessor.get() [[PR 647]](https://github.com/Microsoft/botbuilder-js/pull/647)
- clear state fix [[PR 636]](https://github.com/Microsoft/botbuilder-js/pull/636)
- Correct NO_KEY messages in State classes for issue #610 [[PR 631]](https://github.com/Microsoft/botbuilder-js/pull/631)
- Added BotState.delete() method and tests [[PR 679]](https://github.com/Microsoft/botbuilder-js/pull/679)

## Connectors and Adapters
- update model_fixes.js to set CardAction.channelData as an optional property [[PR 659]](https://github.com/Microsoft/botbuilder-js/pull/659)
- Updates to validate emulator JWT tokens from US Gov [[PR 638]](https://github.com/Microsoft/botbuilder-js/pull/638)
- Update swagger to 10/30 snapshot [[PR 601]](https://github.com/Microsoft/botbuilder-js/pull/601)
- Add getReplyConversationReference [[PR 657]](https://github.com/Microsoft/botbuilder-js/pull/657)


## Engineering (Build, Automatio, Tests)
- Improve swagger-generation process for bf-connector & bf-schema libraries [[PR 666]](https://github.com/Microsoft/botbuilder-js/pull/666)
- Lock internal dependencies to patch version [[PR 656]](https://github.com/Microsoft/botbuilder-js/pull/656)
- Fixes #640 - Use of deprecated methods causing Warnings during build� [[PR 653]](https://github.com/Microsoft/botbuilder-js/pull/653)
- Pin ms-rest-js and ms-rest-azure-js in botframework-connector and botframework-schema [[PR 644]](https://github.com/Microsoft/botbuilder-js/pull/644)
- Add channelService to endpoint service of bot configuration file [[PR 633]](https://github.com/Microsoft/botbuilder-js/pull/633)
- Mime: Update to 1.4.1 for security vulnerability [[PR 616]](https://github.com/Microsoft/botbuilder-js/pull/616)
- Fixing auth tests that were using expired tokens [[PR 650]](https://github.com/Microsoft/botbuilder-js/pull/650)
- Remove request dependency from botframework-connector library [[PR 619]](https://github.com/Microsoft/botbuilder-js/pull/619)

## General
- Add await to showTypingMiddleware call to sendActivity [[PR 672]](https://github.com/Microsoft/botbuilder-js/pull/672)
- Correct improper use of await in function declarations [[PR 617]](https://github.com/Microsoft/botbuilder-js/pull/617)

**Comment by yochay** [comment]
completed with 4.2 releases
- https://github.com/Microsoft/botbuilder-dotnet/releases/tag/4.2
- https://github.com/Microsoft/botbuilder-js/releases/tag/4.2
