### ISSUE TITLE
Instructions required for deploying bot created with microsoft bot framework to jabber application

### ISSUE THREAD

**Issue by analyticalgagan** [Microsoft/BotBuilder#5221]
Hello Team,

we need instructoins on how to deploy bot which we had created using microsoft bot framework SDK  v3 kit to jabber application.

Complete documentation or steps would be appreciated.

Regards,
Gagandeep Singh

**Comment by tdurnford** [comment]
The Microsoft Bot Framework team prefers that **how to** questions are submitted on [Stack Overflow](http://stackoverflow.com/search?q=%23botframework), and since it appears that you have already posted your [question](https://stackoverflow.com/questions/53743096/deploying-microsoft-bot-to-jabber) there, I am closing this issue.

Even though you have asked your question on Stack Overflow, it looks like another user has placed it on hold due to a lack of detail.   I would recommend adding steps you have tried and where your approach has fallen short so we can best assist you in solving your issue.
