### ISSUE TITLE
directline api 502 bad gateway

### ISSUE THREAD

**Issue by alexandruf** [Microsoft/BotBuilder#5262]
Hi guys , direct line seems to have some problems today. I get 502 from time to time.
![errordirectline](https://user-images.githubusercontent.com/9558775/51542805-c7410200-1e64-11e9-81fa-4b6eed830dbb.png)

I'm not sure if I have to open a ticket on azure directly.
Can you please have a look?

**Comment by EricDahlvang** [comment]
We are investigating this, and will get back to you shortly.

**Comment by alexandruf** [comment]
Hi Eric! Thank you for looking into this!

I am using an old version of Bot Builder: 3.11.0 with connector on 3.11.1
For state, I use REDIS.
Application Insights is not configured unfortunately.

I received 502 bad gateway intermittently from 14:00 UTC to approx. 15:00 UTC.

Usually, when this happens, there is a direct line issue and I follow this page (happened quite rarely lately).

Giving the fact that you state that errors are not related with Direct Line, let me ask you this:

What is your recommendation regarding dynamic port range?
When you are making authenticated calls repeatedly to the same server (Direct Line), you are making and closing connections repeatedly.
That connection stays in TIME_WAIT for 240 seconds by default.

Max dynamic port is 5000. So you get to use from 1024 to 5000 (approx. 4000 ports). This means 16 web service calls per second until you get a socket exception. It may be…my case (I am not sure .. dealing with async methods, I can see that exception only in visual studio if a check Common Language Runtime Exception ..maybe is another solution to this).

Anyway, what is your take on this? Should I raise the max range to 65534?
Should I decrease the TIME_WAIT to a lower value?
Whats the risk in doing so?

Alex

**Comment by EricDahlvang** [comment]
The port exhaustion issues in BotBuilder V3 have be resolved in BotBuilder V4 by ensuring HttpClients are static.  You should be able to write your Redis state store implementation to use a static HttpClient as well.

I'm not sure what to recommend for TIME_WAIT or port ranges.  Making these changes is only a stop-gap solution anyway, pushing off the real issue.  There are workarounds for V3 sdk port exhaustion such as: https://github.com/Microsoft/BotBuilder/issues/4075#issuecomment-360724246 and https://github.com/Microsoft/BotBuilder/issues/4901 But, if your bot is receiving enough traffic that this issue is a problem in production, then I recommend upgrading your bot to use the V4 sdk (this is a long term solution).
