### ISSUE TITLE
Bot unable to receive attached files in Teams (Windows)

### ISSUE THREAD

**Issue by andrewchungxam** [Microsoft/BotBuilder#5269]
Attaching file (in my case, for a barcode scan) does not work.  Other conversations work, but the Dialog does not recognize or do anything with image (works fine in emulator).  

Image is uploaded via (Paperclip -> Upload from computer -> Pick Image).

This is a One-on-One Bot.

There was a similar issue reported for v3 of the Bot Framework (https://github.com/Microsoft/BotBuilder/issues/4282).  

Thank you!

**Comment by CoHealer** [comment]
@dmvtech, have you found anything yet?

**Comment by dmvtech** [comment]
Have been working with @andrewchungxam outside this thread. I have made some progress, but a few hurdles to work over.

**Comment by dmvtech** [comment]
hi @andrewchungxam.

I attempted to reproduce with your code, but was hitting issues getting it up and running in Azure. Once done, you can debug the bot using the Teams channel using Ngrok. See more info here (though some of this blog article are a little outdated):
https://blog.botframework.com/2017/10/19/debug-channel-locally-using-ngrok/

You can attempt to debug on your bot you have running and connected to Teams. Make sure that you also have your appId and appPassword specified for the "development" endpoint, otherwise you make get 403. 

I can continue to investigate on my end.

**Comment by andrewchungxam** [comment]
Hi dmvtech - it should be okay to publish (as a check though) -- does the project name have any spaces (I deleted any numbers and space from the beginning of published project name)?  Also, does the BOT file have the "production" endpoint with the appropriate AppId and ProjectID filled out from the Azure portal?  With the above, it should publish fine.

**Comment by CoHealer** [comment]
@andrewchungxam, dmvtech is out for this week but he will reach out to you first thing on Monday.

**Comment by dmvtech** [comment]
Still working on this one. Working to get his bot running in Azure so that I can debug.

**Comment by dmvtech** [comment]
Able to get Andrew up and running with Ngrok debugging. Also, changed one important line in code to get download url with auth token.

var remoteFileUrl = ((JObject)file.Content)["downloadUrl"].ToString();

instead of 

var remoteFileUrl = file.ContentUrl;

**Comment by CoHealer** [comment]
Great work @dmvtech, thank you!
