### ISSUE TITLE
Azure Bot service [Skype for Business Hybrid]

### ISSUE THREAD

**Issue by ramkrish88** [Microsoft/BotBuilder#5272]
SDK Platform: Nodejs
SDK Version: botbuilder 3.14.0
Active Channels: Skype for business
Deployment Environment: On-prem Docker
APPID: ab48b91c-78d9-45f2-a2a4-3799b3699caf

From Skype for business we are unable to reach the bot getting error "This message wasn't sent to bot"
But from the bot we are able to send message to a particular user after which that user is able to send messages to the bot for that particular session.

I presume this might be because of how we did the registration. There was a weeks gap between the online registration & on-prem registration. Not sure if this is because of this. Is there any way that this could be resolved from MSFT end where it does no require a new registration.. maybe kind of refreshing the trusted api registration?

**Comment by EricDahlvang** [comment]
As far as I know, there are still some propagation issues with Skype for Business bots (preview) related to hybrid environment configurations.  Please review the answers here: https://github.com/Microsoft/BotBuilder/issues/4647#issuecomment-397411409 and let us know if that helps.

**Comment by EricDahlvang** [comment]
This is the first time I've heard of your specific issue with a Skype for Business bot.  

Other things to try, or consider:
 -  Open a ticket with Skype for Business support: https://support.office.com/en-us/skype-for-business (they will most likely have suggestions for how to turn on tracing, and assist with debugging this issue)

 - Start over from the beginning, following these instructions carefully: https://docs.microsoft.com/en-us/skype-sdk/skype-for-business-bot-framework/docs/bot-hybrid-support

- Upgrade the bot builder sdk to the latest v3 version: https://www.npmjs.com/package/botbuilder/v/3.16.0

Skype for Business hybrid connected bots are functioning as designed.  This issue seems very specific to your configuration or environment and the Bot Framework support team does not have the tools to assist with your root cause investigation as this is not a supported scenario (someone on the Skype for Business team may be able to assist more than us).  I'm sorry I couldn't help with this.

**Comment by ramkrish88** [comment]
@EricDahlvang , thanks for the guidance. Will have our alliance team reach out to SFB support team.
