### ISSUE TITLE
Integrate Bot Framework with DialogFlow

### ISSUE THREAD

**Issue by felipemmasan** [Microsoft/BotBuilder#5301]
## Issue
I'm trying to integrate DialogFlow with V4 SDK .Net, but it's not possible. I researched but found no way to enable this integration with the V4 version of the .Net SDK.

## Proposed change

Enable integration with DialogFlow

**Comment by v-kydela** [comment]
Hello, which V4 SDK are you using (C#, etc.)? And what sort of integration are you looking for? Do you want Dialogflow to handle language processing in place of LUIS?

**Comment by felipemmasan** [comment]
C# SDK.

YES, i want to use dialogflow in place of LUIS. I have found some articles how to use in V3. But, in V4, not.

**Comment by deepanigi** [comment]
> C# SDK.
> 
> YES, i want to use dialogflow in place of LUIS. I have found some articles how to use in V3. But, in V4, not.

@felipemmasan  I had used the following dialog flow npm package to interact with Dialogflow from V4 .

[https://www.npmjs.com/package/dialogflow](https://www.npmjs.com/package/dialogflow)

**Comment by v-kydela** [comment]
@deepanigi - He is using C#, not Node.

For C#, there is a DialogFlow NuGet package. There's documentation here: https://developers.google.com/api-client-library/dotnet/apis/dialogflow/v2

**Comment by felipemmasan** [comment]
> @deepanigi - He is using C#, not Node.
> 
> For C#, there is a DialogFlow NuGet package. There's documentation here: https://developers.google.com/api-client-library/dotnet/apis/dialogflow/v2

I know @deepanigi , but on V4, I don't find how to change the message/api method to use this SDK.

**Comment by v-kydela** [comment]
@felipemmasan - Can you show me what articles you found to do it in V3?

**Comment by felipemmasan** [comment]
@v-kydela , I Found this one:
https://www.codeproject.com/Articles/1276434/Your-First-Chatbot-using-Microsoft-s-Bot-Framewo-2

**Comment by v-kydela** [comment]
@felipemmasan - I want to clarify something here. You said you wanted your bot to use Dialogflow instead of LUIS, but that is not what is happening in that article. Instead of calling Dialogflow from a Bot Framework app, it's calling the Bot Framework from a Dialogflow app. It's backwards.

I want to make sure I still understand what you're trying to do. You do not want to do what that article is doing. Instead you want to call Dialogflow in the same way a V4 bot calls LUIS like this:

```C#
var luisResults = await _services.LuisServices[LuisConfiguration].RecognizeAsync(dc.Context, cancellationToken).ConfigureAwait(false);
```

Is that correct?

**Comment by felipemmasan** [comment]
@v-kydela, I'm trying to use the same as in the article I sent. The replacement of Luis by DialogFlow occurs when DialogFlow invokes the api that would be exposed by the BotFramework, the intents(which would be identified by Luis) have already been identified by DialogFlow and are part of the information that it sends in Json to the API

**Comment by v-kydela** [comment]
All right. This article explains how to set up a Dialogflow webhook in ASP.NET Core: https://meteatamel.wordpress.com/2018/09/24/dialogflow-fulfillment-with-c-and-app-engine/

**Comment by v-kydela** [comment]
@felipemmasan - Did that resolve your issue?

**Comment by felipemmasan** [comment]
Yeah @v-kydela , I'm trying to use the Microsoft Bot Framework, but using this will do the work too. Tks

**Comment by v-kydela** [comment]
All right, I should explain that the Bot Framework doesn't really have anything to do with Dialogflow webhooks. Our BotBuilder SDK works by setting up an endpoint to receive activity objects that it incorporates into turn contexts, etc. None of that applies when your endpoint is receiving Dialogflow webhook requests instead of Bot Framework activities. The article you linked by Akhil Mittal starts off with a Bot Framework bot, but all the code he uses to respond to a Dialogflow request has nothing to do with the Bot Framework.

All the same, I'm happy to help and I'm glad your issue could be resolved.

**Comment by felipemmasan** [comment]
ok! Tks @v-kydela !

**Comment by love2dishtech** [comment]
Apologies for responding to an old thread. But wondering, if its possible to use the Microsoft Bot frameworks to build bots for Alexa and Google Assistants. 

Essentially one approach I can think of is - it might need to have the bot state machine managed by the bot framework, while the messaging middleware handled by the bot service and a proxy for interfacing channels with Alexa and Google Actions.

But, wondering if such an integration already exists, or if anyone exploring that path. Appreciate some directions.

**Comment by cleemullins** [comment]
Yes, with some conditions. The open-source community has build adapters for this. 
[Alexa in C#](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/tree/develop/libraries/Bot.Builder.Community.Adapters.Alexa)

[Google Home in C#](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/tree/develop/libraries/Bot.Builder.Community.Adapters.Google)
