### ISSUE TITLE
Input Adaptive Card is displayed again after click of Submit button in Bot Framework

### ISSUE THREAD

**Issue by paulcam206** [Microsoft/BotBuilder#5322]
@ashay-maheshwari commented on [Thu Feb 28 2019](https://github.com/Microsoft/AdaptiveCards/issues/2490)

# Platform

* Microsoft Bot Framework - Node JS SDK 3.0

# Author or host

Bot in Webchat as well as emulator is displayed with the Adaptive card

# Issue
I am using Input Adaptive Card in bot framework Node JS SDK 3.0
The card on submit action is displayed again in the webchat or bot emulator.

# Code

```node
// Add dialog to return list of shirts available
bot.dialog('show_shirts', function (session) {
    var card_json = {
        "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
        "type": "AdaptiveCard",
        "version": "1.0",
        "body": [
            {
                "type": "TextBlock",
                "text": "Ticket Incident Details"
            },
            {
                "type": "Input.Text",
                "id": "incidentTitle",
                "placeholder": "Title of incident"
            },
            {
                "type": "Input.Text",
                "id": "incidentDescription",
                "placeholder": "Description of your incident"
            }
        ],
        "actions": [
            {
                "type": "Action.Submit",
                "title": "Submit",
                "data": {
                    "x": 13
                }
            }
        ]
    }
    var adaptiveCardMessage = new builder.Message(session)
        .addAttachment({
            contentType: "application/vnd.microsoft.card.adaptive",
            content: card_json
        });
    session.send(adaptiveCardMessage);
    session.replaceDialog('values')

    if (session.message && session.message.value) {
        // A Card's Submit Action obj was received
        processSubmitAction(session, session.message.value);
        session.send("Something")
        return;
    }

    //console.log(card_json.actions.data.first);
}).triggerAction({ matches: /^(show|list)/i });
```

* Images 
![image](https://user-images.githubusercontent.com/16608791/53567735-24c41f00-3b86-11e9-8538-c1920d548122.png)

---

@paulcam206 commented on [Wed Mar 06 2019](https://github.com/Microsoft/AdaptiveCards/issues/2490#issuecomment-470216379)

This would appear to be an issue with Bot Framework...

**Comment by v-kydela** [comment]
Hello @ashay-maheshwari 

Let me see if I understand your issue. When you click the submit button, control flows back to the `show_shirts` dialog and the adaptive card is sent again. Is that correct?

I will need to see your `values` dialog to be sure, but I'm betting the issue that that the `values` dialog is putting your `show_shirts` dialog back on the stack. Otherwise, `values` should be the root dialog since it replaces `show_shirts` which must the the root dialog since it's triggered by a `triggerAction`.

You seem to be misunderstanding how control is supposed to flow in a bot. You presumably want this code to execute only after the response from the adaptive card is sent:

```node
if (session.message && session.message.value) {
    // A Card's Submit Action obj was received
    processSubmitAction(session, session.message.value);
    session.send("Something")
    return;
}
```

But it's in the same waterfall step as the adaptive card, so it must necessarily be executed on the same turn as when the adaptive card is sent.

**Comment by v-kydela** [comment]
@ashay-maheshwari - Do you still need help?

**Comment by v-kydela** [comment]
@ashay-maheshwari - I need to close this issue due to inactivity. Please feel free to let us know if you still need help.

**Comment by Takechico** [comment]
I have the same issue. Could you help please?   I think the problems occurs in OnTurnAsync method. 
My OnTurnAsync code : 

public override async Task OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken = default(CancellationToken))
        {
            await base.OnTurnAsync(turnContext, cancellationToken);

            // Serialize value

            var activity = turnContext.Activity;


            if (string.IsNullOrWhiteSpace(activity.Text) && activity.Value != null)
            {
                await ConversationState.SaveChangesAsync(turnContext, false, cancellationToken);
                await UserState.SaveChangesAsync(turnContext, false, cancellationToken);
                activity.Text = JsonConvert.SerializeObject(activity.Value);
            
            }

else{
       // Save any state changes that might have occured during the turn.
            //await ConversationState.SaveChangesAsync(turnContext, false, cancellationToken);
            //await UserState.SaveChangesAsync(turnContext, false, cancellationToken);
}
![Card](https://user-images.githubusercontent.com/44839444/62771368-ba54ca80-baa5-11e9-9818-527670aab9a3.jpg)

**Comment by v-kydela** [comment]
@Takechico - You are commenting on a closed issue, and this is not an appropriate place to ask how-to questions. Please ask your question on [Stack Overflow](https://stackoverflow.com/questions/ask) and make sure to format your code so that it is easy to read. If you believe your question is related to this issue then the appropriate action is to link to this issue in your question.
