### ISSUE TITLE
QnAMaker.GetAnswersAsync() takes a TurnContext instead of a string

### ISSUE THREAD

**Issue by KatieProchilo** [Microsoft/BotBuilder#5344]
## Issue
*Describe the issue you are addressing*
QnAMaker.GetAnswersAsync() just takes a TurnContext, and assumes you want to query QnAMaker using the text in the TurnContext. But you may want to call QnAMaker with a modified version of the text, or a different string altogether. It would be better if GetAnswersAsync() took a string instead, as it would provide more flexibility to customers.

## Proposed change
*Describe the proposed solution*
GetAnswers() should take a string.

## Tracking Status
**Dotnet SDK**
- [ ] PR
- [ ] Merged

**Javascript SDK**
- [ ] PR
- [ ] Merged

**Java SDK**
- [ ] PR
- [ ] Merged

**Python SDK**
- [ ] PR
- [ ] Merged

**Samples**
- [ ] PR
- [ ] Merged

**Docs**
- [ ] PR
- [ ] Merged

**Tools**
- [ ] PR
- [ ] Merged

[dcr]

**Comment by Zerryth** [comment]
What exactly is preventing you from manipulating the text you receive before calling `GetAnswersAsync() `in your bot code? 

`GetAnswersAsync()` requires a turn context, because without it the class wouldn't be able to emit any trace info. In fact, this is why on then node side, originally it had a `generateAnswer()` method that took a string instead of TurnContext that as of v 4.2 has been deprecated in favor of the new `getAnswers()` method. You can see that in the deprecated `generateAnswers()` code that there isn't a way that QnAMaker can emit trace info w/o turn context

**Comment by navzam** [comment]
@Zerryth Do you mean modifying `turnContext.Activity.Text` before calling `GetAnswersAsync()`? The incoming activity feels like it should be treated as read-only, to avoid messing up other code that relies on the original incoming text. Couldn't `GetAnswersAsync()` take both a `TurnContext` (for emitting trace info) and a `string` (for calling QnA Maker)?

**Comment by kannanambadi** [comment]
I am facing an issue when chat bot is integrated into MS teams channels. Chat bot name gets appended with the query text within turncontext object, which in turn provides wrong responses from QnA. I want to remove the mentions from query before calling QnA Service for responses. Please help.

**Comment by Zerryth** [comment]
@kannanambadi please open a new issue for your problem in the appropriate repo (i.e. if you're using the dotnet vs js SDK, post your issue in either [botbuilder-dotnet](https://github.com/microsoft/botbuilder-dotnet) or [botbuilder-js](https://github.com/microsoft/botbuilder-js) repo)

Be sure to include the steps you took and bot code, so the team can actually get a repro on the issue to dig down to a solution
