### ISSUE TITLE
[NodeJS] How to validate input on Prompts.text

### ISSUE THREAD

**Issue by AVenezuela** [Microsoft/BotBuilder#56]
Hi,

First, I must congratulate you guys for the excellent work :)

I'm trying to validate an input from a Prompts.text, if it's invalid I'll keep asking for a valid text.
How can I acomplish that ?

**Comment by Stevenic** [comment]
So thanks :) and first let me ask... I've been contemplating adding a Prompts.pattern() that would take a RegEx and only return when the pattern is matched. Would that cover your needs in this case?

Now how to do custom input validation. I was planning to add an example of this (which I will) but here's the basics of how I think you could do it. I would create a new dialog like below:

    bot.add('/myCustomPrompt', function (session, results) {
        var valid = false;
        if (results && results.response) {
            // validate response
            valid = (results.response == '42');
        }
        if (!valid) {
            builder.Prompts.text(session, 'what's the meaning of life?');
        } else {
            session.endDialog(results);
        }
    });

To call your custom prompt just say session.beginDialog('/myCustomPrompt'); in a waterfall and your validated results will be passed to the next step of the waterfall.

You can further customize this by passing in additional arguments in the beginDialog() call but you'll have to keep in mind that your initial args and the results from the call to Prompts.text() are going to come back in via the same param of your custom prompts dialog handler. That's why I added the second clause of the if test to look for results.response.  There's also a results.resumed you can look for which is probably a more accurate test.  If you look at the src for BotBuilder look at how DialogAction.waterfall() is implemented. Its a good example of a single closure that knows if it's being called initially or with the result of a prompt.

Hope that helps.

**Comment by Stevenic** [comment]
Sorry... I can never help myself with these kind of questions :) Here's a slight variant that uses session.dialogData to know how many times its prompted the user and will eventually give up.

    bot.add('/myCustomPrompt', function (session, results) {
        var valid = false;
        if (results && results.response) {
            // validate response
            valid = (results.response == '42');
        }
        if (valid || (results && results.resumed == builder.ResumeReason.canceled)) {
            session.endDialog(results);
        } else {
            if (!session.dialogData.promptCount) {
                session.dialogData.promptCount = 1;
                builder.Prompts.text(session, 'What's the meaning of life?');
            } else if (session.dialogData.promptCount < 5) {
                session.dialogData.promptCount++;
                builder.Prompts.text(session, 'Sorry that's not it. Guess again. What's the meaning of life?);
            } else {
                session.endDialog({ resumed: builder.ResumeReason.notCompleted });
            }
        }
    });

This version also accounts for the user saying "nevermind" to cancel the prompt.

**Comment by Stevenic** [comment]
I just checked in a new example for how to create a validated prompt. We were talking about it and I think we're going to add new DialogAction.validatedPrompt() that streamlines most of the boilerplate code from the example and lets you define a custom prompt by simply providing the validation function as a closure.

**Comment by AVenezuela** [comment]
Hi,
Thanks for the answer. The second option you gave worked well.
But the possibility to provide a validation function will be great.
Thanks again
