### ISSUE TITLE
.NET pendant to node.js 

### ISSUE THREAD

**Issue by drei13s** [Microsoft/BotBuilder#623]
The node js code I found in the docs:
```
intents.matches('SetAlarm', [
    function (session, args, next) {
        var time = builder.EntityRecognizer.resolveTime(args.entities);
        if (!time) {
            builder.Prompts.time(session, 'What time would you like to set the alarm for?');
        } else {
            // Saving date as a timestamp between turns as session.dialogData could get serialized.
            session.dialogData.timestamp = time.getTime();
            next();
        }
    },
    function (session, results) {
        var time;
        if (results.response) {
            time = builder.EntityRecognizer.resolveTime([results.response]);
        } else if (session.dialogData.timestamp) {
            time = new Date(session.dialogData.timestamp);
        }
        
        // Set the alarm
        if (time) {

            // .... save alarm
            
            // Send confirmation to user
            var isAM = time.getHours() < 12;
            session.send('Setting alarm for %d/%d/%d %d:%02d%s',
                time.getMonth() + 1, time.getDate(), time.getFullYear(),
                isAM ? time.getHours() : time.getHours() - 12, time.getMinutes(), isAM ? 'am' : 'pm');
        } else {
            session.send('Ok... no problem.');
        }
    }
]);
```

Alright, the intents.match is the Attribute [LuisIntent(..)] in C#, but what is the equivalent method to "next()". For me the node.js code looks like "some kind" of Form in C# but there isn't any possibility yet that I know of to **easily** use LUIS with Forms. Or is there something? Also resolveTime is something that would be useful for C#.

**Comment by msft-shahins** [comment]
For FromFlow you can implement custom recognizer by implementing [IRecognize<T>](https://github.com/Microsoft/BotBuilder/blob/407920a67af2ada0ec5a3c9f8d33b67e2d3fdba8/CSharp/Library/FormFlow/IRecognize.cs) for different fields and use your custom Luis models to do term extraction based on reported Luis entities. 

Also, in your intent handlers in C# you can use context.call(...), context.forwrad(...) to call into any child dialog or call into any arbitrary function that you have in your class. No need for having `next()` since the intent handlers in C# are not modeled as waterfalls. You can look at [SimpleAlarmDialog](https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Samples/SimpleAlarmBot/SimpleAlarmDialog.cs) for an example of LuisDialog in C# or [PizzaOrderDialog](https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Samples/PizzaBot/PizzaOrderDialog.cs) for a LuisDialog that initializes a form. 

for resolveTime, you can either use chronic library to parse the incoming query and also we are working on adding a data/time resolver for Luis DateTime resolutions. (issue #772).
