### ISSUE TITLE
V3: UserData not being saved

### ISSUE THREAD

**Issue by NanashiGIT** [Microsoft/BotBuilder#643]
Hello!
Ive updated to V3 but im facing the issue, that the user data is not being saved.
My code:
```cs
StateClient stateClient = activity.GetStateClient();
BotData userData = await stateClient.BotState.GetUserDataAsync(activity.ChannelId, UserId);
if (!userData.GetProperty<bool>("MailAddressRequested"))
    {
         userData.SetProperty<bool>("MailAddressRequested", true);
         await stateClient.BotState.SetUserDataAsync(activity.ChannelId, activity.From.Id, userData);
```
**------------------------Update----------------------**
If i do:
```cs
await stateClient.BotState.SetUserDataAsync(activity.ChannelId, activity.From.Id, userData);
BotData userData2 = await stateClient.BotState.GetUserDataAsync(activity.ChannelId, UserId);
```
botdata2 is not empty. but when i send another message, the data is gone. An im 100% sure that the UserId is still the same and i dont delete any data anywhere.
**------------------------------------------------------------**

Everytime the user data is empty. What am i doing wrong?

Also im getting an exception (i tested that only with the emulator) when i send a message:
"iisexpress.exe Warning: 0 : Invalid token. System.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException: IDX10500: Signature validation failed. Unable to resolve SecurityKeyIdentifier: 'SecurityKeyIdentifier
"

Could this be the issue?
Im 100% apid and app password are correct. I mean it does communicate.

Any idea?

Greetings.

**Comment by Luis-Jovel** [comment]
Got the same issue, although in my case, the bot state it's empty the first and second times

**Comment by msft-shahins** [comment]
I assume that you are making the direct state api calls within the builder dialog. Before release 3.1 of builder, builder was using a [LastWriteWins](https://github.com/Microsoft/BotBuilder/blob/44d9667878759f9676c615365a818525ffe00ebd/CSharp/Library/Dialogs/BotData.cs#L240) policy for its implementation of IBotDataStore and as a result if you make calls directly to StateApi with in your code, the data will be overwritten by the PersistentDialogTask of the builder when it flushes different IBotDataBags. Starting nuget 3.1, the default implementation changed to `ETagBasedConsistency` and as a result you will get a `precondition failed` exception when the PersistentDialogTask tries to persist data bag that conflict with the data that is already persisted in state api service. 

I highly recommend using IDataBags in the IDialogContext rather than using state client directly.

**Comment by kenakamu** [comment]
Can you point me where I can get that IDataBag information, please?

**Comment by brandonh-msft** [comment]
@kenakamu 

I believe what @msft-shahins is referring to is using
`context.UserData`
`context.ConversationData`
and/or
`context.PrivateConversationData`

to do your data storage instead of `activity.GetStateClient()` and/or `activity.Get...Data...()` methods

**Comment by kenakamu** [comment]
Thanks. How we play with state client in message controller rather than in a dialog? I got same error when saving user data

**Comment by brandonh-msft** [comment]
@kenakamu 
to use state storage in the controller, you call `activity.GetStateClient().BotState` and use that object to manipulate the various state repositories. But as @msft-shahins said, it's recommended to do your state data manipulation within dialogs (`IDialogContext` and my previous reply) vs w/in the controller via `Activity`

**Comment by irwinwilliams** [comment]
This sample from, Tsuyoshi Matsuzaki, https://blogs.msdn.microsoft.com/tsmatsuz/2016/09/06/microsoft-bot-framework-bot-with-authentication-and-signin-login/ uses activity.GetStateClient ... and associated strategies to save an access token.  Is there an alternative way to do this, as it doesn't seem like the token I'm generating is being persisted, either.
