### ISSUE TITLE
C# Mutiple Dialogs with Luis Integrated

### ISSUE THREAD

**Issue by b4usat** [Microsoft/BotBuilder#674]
Hi
I am building a bot which will have multiple usecases to which i would like to Chain the Dialog classes for each usecase(LUIS inherited). I couldn't see any possible way to do that. Can anyone please help me out for that. Referring to PizzaBot sample, there is only one `Echodialog `class with FormFlow. In similar fashion i want to intialize different classes with different formflows. Is that possible?

**Comment by willportnoy** [comment]
Yes, you can have multiple child dialog that you IDialogStack.Call from the intent methods of a single LuisDialog.  Those child dialogs can be form flow dialogs or any other dialog - you could follow this code as an example:

https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Samples/PizzaBot/PizzaOrderDialog.cs#L60

**Comment by willportnoy** [comment]
I'm going to close this issue - feel free to open a new issue for further discussion.

**Comment by xolutionke** [comment]
5

**Comment by SohiniAch93** [comment]
Hi 
I am building a bot to build a flight booking system. I wanted to know if there is any way i can send continuous user  responses to Luis and fetch intents and entities. Not just the first user response but  all his responses throughout the conversation. Does this make sense?

**Comment by prashantkhandelwal** [comment]
@SohiniAch93 Whenever a message is sent to the bot and if the bot uses LUIS, then the message will be sent to LUIS and it will return the intent and entities which you should be handling in the bot code. You need to be more specific when you say that you want to send continuous user response. What I understood is that you want to collect all the messages from the user and then bulk send it to LUIS instead of handling individual messages. If this is the case then be advised of rate limiting: https://docs.microsoft.com/en-us/bot-framework/bot-service-resources-bot-framework-faq#rate-limiting

Also, your question is not related to BotBuilder issues. Please try to ask such questions on community channels like Stackoverflow or on some other technical forums.

**Comment by saikatbh94** [comment]
Hi, I am building a LUIS bot. Here, I have to use multiple dialogs to handle different intents. For example, if the LuisIntent is "Confirmation", i have to handle it in the file ConfirmDialog.cs, and if the LuisIntent is "PersonMerge", then I have to handle it in the file PersonMergeDialog.cs. Please tell me how to do this type of work. I will have a RootLuisDialog.cs, but still some intents will be handled like i just said, and the others will be handled in RootLuisDialog.cs. So please if anyone can help me with this issue, then i will be grateful. Thank you in advance.

**Comment by saikatbh94** [comment]
I had another query. I heard and read about LuisRequest class. I wanted to know whether I can use this class to query a Luis app within any method. Example:
[LuisIntent("Greet")
public async Task GreetIntent(IDialogContext context, LuisResult result)
{
  await context.PostAsync("Hi, how can i help you?");
 // Here within this method, i want to give the luis app another query by using LuisRequest
 // Can I do this? 
}

**Comment by SATACHAKRA** [comment]
Hope u get the answer here.!!!!
