### ISSUE TITLE
Bot Connector not forwarding messages like "[A]: B"

### ISSUE THREAD

**Issue by Thegaram** [Microsoft/BotBuilder#696]
Messages of the format `"[A]: B"` or `"[A]:B"` (where `A` and `B` are nonempty strings and `A` is surrounded by brackets) sent from the bot don't reach the client. I experience this on multiple channels (tested on Facebook, Skype, Slack and Kik). There's no exception on the bot side and the messages seem normal (no serialization error here), so I suppose the problem is on the Bot Connector Service side. I am using V3.

(Use case: I wanted to send messages like this from my bot: `"[name]: message"`, but they never arrived.)

**Comment by willportnoy** [comment]
This seems likely to be caused by the markdown interpretation:

http://docs.botframework.com/en-us/csharp/builder/sdkreference/activities.html#markdown

where brackets are used for url links.

**Comment by Thegaram** [comment]
Hmm makes sense, forgot that Markdown is the default. So I guess in my case it's a parse error as there's no URL after the brackets, and the Connector does actually forward a message (with an empty string) that is not displayed by most channels. Wouldn't it be better to give an error message in this case?

**Comment by willportnoy** [comment]
Perhaps, or at least a warning.  It depends on what you feel about the https://en.wikipedia.org/wiki/Robustness_principle.

**Comment by Thegaram** [comment]
I think if some information from the bot doesn't reach the client, it shouldn't be silently ignored. But an error message towards the client also doesn't seem good. Maybe reply 400 to the bot?

**Comment by brene** [comment]
I like the thought that it shouldn't be silently ignored but if you have a bot, you wouldn't want it to crash during production because of some exception you didn't catch. Since in languages like javascript, you are not forced to handle the exceptions, you could easily make the mistake of not knowing that there is an exception to be thrown. 

I do agree that this can be handled better. session.send(...) should be a Promise and when calling then it can receive a function taking error as a variable. I think this would be a good solution:
```javanscript
session.send("[A]: B").then(function(error){
  if (error) {
    // handle error
  }
});
```
or just pass the error handling as an argument itself.
```javascript
session.send("[A]: B", function(error) {
  // handle error
});
```

**Comment by willportnoy** [comment]
Thank you for the suggestion of "stricter error checking for markdown syntax errors", we've added it to our backlog.
