### ISSUE TITLE
Skype web not showing cards or images

### ISSUE THREAD

**Issue by possan** [Microsoft/BotBuilder#720]
I suspect that i am not using the latest Skype web version, but how do i verify that i have switched to the correct version?

The only indication of a version number in the HTML is one in the feedback url and that says `0.219.0`

The cards i send shows up just fine in the Slack integration.

**Comment by garypretty** [comment]
Right now the normal web client for Skype doesn't support cards.  If you wanted to test your bot with Skype web then you can use the developer version by signing into slype at [](https://web.skype.com)
and then once signed in go to [](https://web.skype.com/en/?ecsoverride=developer) which will give you the developer version.

Hope that helps.

**Comment by possan** [comment]
Yes exactly, i have done that quite a few times and i still don't see any cards, how do i actually verify that i am using the developer version?

**Comment by DirkSonguer** [comment]
I have the same issue, it just says "has sent you a message".

Also, is there any ETA when any of the desktop (Mac, Windows) or mobile (iOS, Android, Win) will support cards?

**Comment by suprak** [comment]
Specifically,

When do we expect the Bot Framework and Skype fully aligned so that we can use Skype to test the full feature set of Cards, Actions, etc? Even with v3 of bot framework, Skype still doesn't support or supports very poorly the framework's capabilities.

**Comment by dagerikhl** [comment]
I'm having the exact same issue(s). Cards are working fine in Slack and the Emulator, but using Skype gives erronous or no results. Normal text-messages are working fine with Skype. Specifically:
### Case
I write a simple command to my bot on Skype.
#### Expected behaviour
The bot should send back an Activity with a List of HeroCard attached, and the AttachmentLayout-property set to "carousel". This should be displayed as a carousel of cards on platforms supporting carousel, and as a list of cards on platforms that do not.
#### Actual behaviour
* **Bot Emulator:** The activity is sent back successfully, and displayed as a carousel of cards.
* **Slack:** The activity is sent back successfully, and displayed as a list of cards, due to lack of support for carousel.
* **Skype Desktop v. 7.25.0.106:** A single image of two polaroid pictures is sent back from the bot with an "Open"-link. This picture seems like a placeholder from Skype, and is not something from my application.
  * Opening the link sends me to [Skype downloads](https://www.skype.com/en/download-skype/skype-for-computer/?nonce=yKm8HLGryDih3fhoIseK).
* **Skype Web Chat v. 1.51.74, asset v. 0.0.296:** Bot sends back a text-message saying "Sent you a message".
* **Skype Web Chat v. 1.51.74, asset v. 0.0.296 (with `?ecsoverride=developer`):** Same as above.

**Comment by brene** [comment]
If you are using builder.Prompts.choice(...) and want to make it works on Skype. For now, you can just add a listStyle as an argument.
```javascript
builder.Prompts.choice(session, "Which one?", ["A","B","C"], {listStyle: builder.ListStyle["inline"]});
```
This will display the choices as a string and not a card view. Essentially, if you want to get a fast deployment version up and running, this is your best chance of making it work. We'll have to wait for Skype's full rollout of Cards & Carousels to use choice without specifying the style.

**Comment by possan** [comment]
Thanks to the newly updated iOS version just released, i can now continue testing!

http://blogs.skype.com/2016/07/20/skype-6-20-for-ios-find-bots-improved-notifications-and-chat/

**Comment by frisco82** [comment]
PC was updated today with cards support

**Comment by alokraj68** [comment]
Is it solved? today when I tried hero cards, the cards are not showing up in skype. but it shows up in bot emulator. I have opened an issue on the same.

https://github.com/Microsoft/BotBuilder/issues/1518

**Comment by gviddy** [comment]
Skype preview and Skype desktop do not show images for me. However Facebook and Web Chat show images ok.

Is there anything special I need to set to get Skype to work? I am using carousel...

**Comment by dagerikhl** [comment]
How many cards are you sending in the carousel, @gviddy? I think Skype neglects to show any carousel with more than 5 cards. No error message, it just never gets displayed.

**Comment by brene** [comment]
Hi @dagerikhl I'm a PM at Skype and I'd love to know more about this issue. Which Skype client are you using? Web/Windows/Mac/iOS/Android?

**Comment by dagerikhl** [comment]
Unfortunately, it's been a couple of months since I developed with the system. But I used a bot I had created quite recently, and it worked fine _(as long as there were no more than 5 cards in the carousel)_ on both Skype for Windows and Skype for Android. And unfortunately, Skype has updated on both my Windows and Android since then, so I can't give you an exact version number.

I was made aware of the problem (or decision) concerning more than 5 cards here: [Microsoft/BotBuilder-Samples/Node/cards-CarouselCards#outcome](https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node/cards-CarouselCards#outcome):
> Note: At the time of writing this sample, there is a limit on the amount of cards that can be stacked in a carousel. For Facebook, attachments carousel is mapped to the Generic Template which has a limit of 10 elements. For Skype, there's a limit of 5 elements in the carousel.

**Comment by brene** [comment]
@dagerikhl I just looped back with the engineers. This value is out-of-date and we already created a pull request to update the value from 5 to 10. Thanks for tip though!

**Comment by gviddy** [comment]
![image](https://cloud.githubusercontent.com/assets/14090370/21052364/610ef6f0-be70-11e6-9277-d5bd0b987d33.png)

@dagerikhl
This is what I get in Skype Preview on desktop, and similar on the normal desktop app, all latest versions. However the images show up fine in all variations of Facebook Messenger (app, web, etc)....

**Comment by brene** [comment]
@gviddy We'd love to help you out. Do you happen to have the code snippet that you send? Are the images that you are referencing on HTTP/HTTPS?

**Comment by gviddy** [comment]
Thanks.. Images are HTTPS .... I will show you my code and here is an example of the URL I am hitting ... Again it shows ok in Messenger, Webchat Emulator, just no image in Skype (as above)....

"https://directorycdn.blob.core.windows.net/images/organisations/106428/logo-queensland_police-citizens_youth_welfare_association06072016073459.jpg"

`Activity replyToConversation = (Activity)context.MakeMessage();
replyToConversation.Recipient = replyToConversation.Recipient;
replyToConversation.Type = "message";

replyToConversation.Attachments = new List<Attachment>();
replyToConversation.AttachmentLayout = "carousel";      // AttachmentLayout options are 'list' or 'carousel'

List<CardImage> cardImageList = new List<CardImage>();
cardImageList.Add(new CardImage(organisation.ImageUrl));

List<CardAction> cardActionList = new List<CardAction>();
cardActionList.Add(new CardAction("openUrl", "Website", null, organisation.Url));
if( string.IsNullOrEmpty(organisation.Phone) == false)
	cardActionList.Add(new CardAction("call", "Phone", null, "tel:"+organisation.Phone));
	
// show a hero card
HeroCard heroCard = new HeroCard(organisation.Title, organisation.Subtitle, null, cardImageList, cardActionList, null);
Attachment attachment = heroCard.ToAttachment();
replyToConversation.Attachments.Add(attachment);

await context.PostAsync(replyToConversation);`

**Comment by brene** [comment]
@gviddy Great! I'll follow-up with the team on Monday!

**Comment by gviddy** [comment]
Update, this is now working for me.... I am however now using a real-time online image re-sizer URL to resize my image on the fly..

So my URL from above is now:
`https://images1-focus-opensocial.googleusercontent.com/gadgets/proxy?url=https://directorycdn.blob.core.windows.net/images/organisations/106428/logo-queensland_police-citizens_youth_welfare_association06072016073459.jpg&container=focus&resize_w=560&resize_h=292`

and I now get images in Skype ...

![image](https://cloud.githubusercontent.com/assets/14090370/21087502/172e79ee-c072-11e6-867b-b7a1ee7f7478.png)

**Comment by AnithaJothi** [comment]
Hi, I am trying to display 4 Hero Cards (Rich cards) in a plain web chat channel. They seem appear properly in the emulator, however they don't appear as cards in web chat! Instead they appear as a series of text and images! Any help is much appreciated!

**Comment by brene** [comment]
@AnithaJothi please open a new issue at https://github.com/Microsoft/BotFramework-WebChat/issues since this is related to the webchat
