### ISSUE TITLE
Customize Formflow: Confirmations/Prompts

### ISSUE THREAD

**Issue by NanashiGIT** [Microsoft/BotBuilder#736]
Hello!
Im trying to customize a Formflow in the sense that i want it to be more understanding.
For example, im using LUIS.
When a user confirms an entered value, i dont jsut want the confirmation to accept "Yes, yep,..." and so on. I want it to understand "Yes, i am sure!" or something similar.
Is there a way to intepret the confirmation by my own?
(That question also applies to Confirmation-Dialogs)

Also the prompt for the user, telling him to enter the value for the property.
I know that i can create a custom prompt for a property, but that one is fixed. 
Right now its like:
"Please enter value A"
*enters wrong value*
"The entered value is wrong. Try again!" (a message i sent during verification)
"Please enter value A" ( <-- not wanted)

I dont want it to prompt that value over and over again. Is there a way to modify that behaviour?

Greetings

**Comment by willportnoy** [comment]
For the prompt dialogs, we store the list of "yes" answers in a resource that can be customized:

https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Dialogs/PromptDialog.cs#L419

FormFlow uses the same resource:

https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/FormFlow/IFormBuilder.cs#L292

**Comment by ankitbko** [comment]
Well, it would be nice if there is a way to customize without changing the resource and rebuilding the sdk. From my experience, I had to customize this for most of my bot as conversationally user replies more like "yes please" (more formal) or sometimes just "ya". Then this leads me to always have direct reference to sdk rather than just getting nuget package.
In the similar line, it would be great if we could specify regex so that I can take care of inputs like "yes pls" (I know, but there are people who do this :sweat_smile:)

**Comment by chrimc62** [comment]
The prompts are not fixed, they are defined by templates.  You can find documentation here: https://docs.botframework.com/en-us/csharp/builder/sdkreference/forms.html#attributes
As to not prompting again and again, what behavior would you like to do?  Most anything is possible, but it depending on your goal it be necessary to define your own field and override some methods.

**Comment by chrimc62** [comment]
You do not have to change the resource--just change the value from Builder.Configuration.  The strings matched are also regex's so you should be able to supply one.

**Comment by ankitbko** [comment]
@chrimc62 Thanks, I didn't knew this. This should definitely go into docs. 
Is it also customizable in PromptDialog.Confirm? Because in [PromptDialog.cs#L419](https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Dialogs/PromptDialog.cs#L419) I see that it always reads from Resource rather than PromptOptions.Options

**Comment by chrimc62** [comment]
That is a bug I will fix in the next release.  There is a static Options which is initialized from the resources but is where this should come from.  I also see it is not a regex, so I will look into to see if we want to make that a regex here as well.

**Comment by gianvi** [comment]
Hi, can you suggest me which configuration need to be set to change the "What do you want to change?" after saying no in confirmation at the end of the formflow?
Thx

**Comment by willportnoy** [comment]
@gianvi please ask your usage question on stack overflow - we're trying to reserve GitHub for bug reports.

**Comment by bothandler** [comment]
Hi, even if I change builder.Configuration.Yes to include new values, "xxx, is not a confirmation option" message keeps coming. Can you suggest if its a bug or am i missing anything

![5-9-2017 3-03-09 am](https://cloud.githubusercontent.com/assets/24786490/25826469/97d34942-3464-11e7-93ec-c6e7a9090596.png)
![5-9-2017 3-05-40 am](https://cloud.githubusercontent.com/assets/24786490/25826473/9acfbe28-3464-11e7-81ea-c7131e5251c0.png)

**Comment by bothandler** [comment]
works with this approach - https://stackoverflow.com/questions/42947804/change-confirm-options-in-botframework-formflow
