### ISSUE TITLE
anonymous method closures that capture the environment are not serializable, consider removing environment capture or using a reflection serialization surrogate

### ISSUE THREAD

**Issue by vrmmoreira** [Microsoft/BotBuilder#833]
when i try to pass arguments to a formflow like this:

await Conversation.SendAsync(activity, () => (MakeRootDialog(interactionId, userId)));

i get the exception:
anonymous method closures that capture the environment are not serializable, consider removing environment capture or using a reflection serialization surrogate

how can i do this, thanks

**Comment by willportnoy** [comment]
You can register the reflection serialization surrogate by adding it to the Autofac container.  Here is how we do it for tests:

https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Tests/Microsoft.Bot.Builder.Tests/DialogTestBase.cs#L80

However, we don't necessarily recommend its use because there is a risk that it may serialize more than you expect, since it's trivially easy to capture some variable in a closure.

Can you obtain interactionId and userId from within an IDialog, and start the FormFlow from within that IDialog?

**Comment by willportnoy** [comment]
I'm going to close this issue, but feel free to open a new issue for further discussions.

**Comment by villasv** [comment]
I came across this problem when trying to build my own way of building a form flow with dialogs (because of LUIS and more versatility, like not responding to certain messages). The idea was this:

        public async Task YesOrNoQuestion(
            IDialogContext questionContext,
            string question,
            Func<IDialogContext, Task> positiveCallback,
            Func<IDialogContext, Task> negativeCallback
        )
        {
            await Say(questionContext, question);
            ResumeAfter<IMessageActivity> yesOrNo = async (answerContext, awaitable) =>
            {
                var message = await awaitable;
                var intent = await LUIS.GetIntent(message.Text);
                if (intent == Intent.Agree)
                {
                    await Say(answerContext, "Então vamos lá. Vamos começar com histórias de sucesso suas.");
                    await Say(answerContext, "Positive");
                    await positiveCallback(answerContext);
                }
                else
                {
                    await Say(answerContext, "Negative.");
                    await negativeCallback(answerContext);
                }
            };
            questionContext.Wait(yesOrNo);
        }

But because of `negativeCallback` and `positiveCallback` I need to capture the environment. What do you suggest? It's not clear to me how to register on Autofac from the example.

**Comment by vamsitp** [comment]
How about using the `originalContext.UserData.SetValue()` to set/pass on the variables that we need later and then fetch them back using the `passedOnContext's.UserData.Get()`?

**Comment by willportnoy** [comment]
@villasv you can update the container like this:

~~~~
var builder = new ContainerBuilder();
builder.RegisterModule(new ReflectionSurrogateModule());
builder.Update(Conversation.Container);
~~~~~
