### ISSUE TITLE
How does the Conversation.SendAsync handle replies

### ISSUE THREAD

**Issue by mephisto83** [Microsoft/BotBuilder#888]
How does the Conversation.SendAsync handle replies?. I have overridden the IBotToUser interface and intercept the messages. 

When I send in the first message to a LuisDialog the correct intent is matched. Then I call the Conversation.SendAsync with the same IActivityMessage output only updating the text. The callback in the LuisDialog is never called. 

I can't figure out how to control the flow of messages through the dialog. In V1, the message contain the stack and state but now doesn't have contain anything. How are messages supposed to reach the correct dialog callback?

**Comment by willportnoy** [comment]
The IDialogContext passed to each dialog method is also an implementation of IBotToUser.  Any messages you want to send to the user should go through IBotToUser.PostAsync.

You should only call Conversation.SendAsync at the top-level of the code, so that it can resolve IPostToBot to Post the incoming message to the bot.
