### ISSUE TITLE
[Question] NodeJS. Make a bot with several IntentDialogs in a Library

### ISSUE THREAD

**Issue by jmendiara** [Microsoft/BotBuilder#892]
I want to have several [`Library`](https://docs.botframework.com/en-us/node/builder/calling-reference/classes/_botbuilder_d_.library.html) implementing this pattern
```ts
// library-A node module
import * as BotBuilder from 'botbuilder';

const library = new BotBuilder.Library('A');
const recognizer = new BotBuilder.LuisRecognizer('...');
const intents = new BotBuilder.IntentDialog({ recognizers: [recognizer] });

intents.matches('intent.A', ...);

library.dialog('/', intents);

export default library;
```
```ts
// libraryB node-module uses, for example, some cortana intents
...
library.dialog('/', intents);

export default library;
```
and finally I want to write a bot that can use all this libraries intents all together, get the best match for all of them, and proceed with the dialog.

example
```ts
import * as BotBuilder from 'botbuilder';
import LibraryA from 'library-A';
import LibraryB from 'library-B';

const bot = new BotBuilder.UniversalBot(new BotBuilder.ChatConnector({...}));
bot.library(LibraryA);
bot.library(LibraryB);

// now I want to use those intent dialogs from libraries to ask LUIS in parallel 
// and exectute the best match intent from the chosen library  
bot.dialog('/', new CompositeIntentDialog([LibraryA.dialog('/'), LibraryB.dialog('/')]);
```

Is it possible to achieve this with the current `IntentDialog` implementation ?

**Comment by Stevenic** [comment]
This is possible but its a little clumsy and we're certainly not optimized for it.  You can do it with just a simple waterfall step for your root dialog.  

You would need to use a library like async.js and loop over all of the root dialogs like you show in your example.  This dialogs aren't loaded yet so you're trying to judge which should be loaded. To do that you can call the `dialog.recognize()` method. You need to pass this method a context object which you'll need to manually build `var ctx = { message: session.message, dialogData: {}, activeDialog: false };` should do.  The second parameter is a callback that will receive a recognition result.  All you care about is the `result.score` value. Which ever library returns the highest score is the one you should start. If anyone returns a score of 1.0 you can short circuit and pick that library immediately.

To start the library you currently need to call `session.beginDialog('<libName>:/');`. I'm planning to add a new beginLibrary() method that formalizes this a bit more but beginDialog() works for now.

The other thing is the IntentDialog at the root of each of your libraries needs to be created with `recognizeMode: builder.RecognizeMode.onBegin` otherwise they won't re-evaluate the current message when you start them.  That's the other thing... You're currently going to end up running through recognition twice which kind of sucks performance wise. I have a change coming in the near future that will add caching at the recognition level so the performance hit should go away soon.

The other caveat is that this is a completely unsupported scenario right now so I can't guarantee I won't break you at some point in the future. Feel free to post your federation code back here and I'll review it.

**Comment by Andrea-Orimoto** [comment]
Assuming steve's answer clarified your issue. Please reply to this issue asking us to reopen if needed. Thanks!
