### ISSUE TITLE
Node: Stick to semver or clarify your release strategy

### ISSUE THREAD

**Issue by jmendiara** [Microsoft/BotBuilder#911]
NodeJS developers and npm ecosystem follow [semver](http://semver.org/) for versioning. This implies the [following rules when releasing code](https://docs.npmjs.com/getting-started/semantic-versioning):

> * Bug fixes and other minor changes: Patch release, increment the last number, e.g. 1.0.1
* New features which don't break existing features: Minor release, increment the middle number, e.g. 1.1.0
* Changes which break backwards compatibility: Major release, increment the first number, e.g. 2.0.0

Your latest release [3.2.1](https://github.com/Microsoft/BotBuilder/releases/tag/botbuilder%403.2.1) seems to have **Breaking Changes**. So, following semver rules, this release should be `4.0.0` 

**Who is affected by this issue?**
Developers having in their `package.json` the *default* update strategy used by npm when typing `npm install --save botbuilder`. That strategy uses `^` as the version management strategy, meaning you want to have always the latest version with bugfixes and new features **without** breaking changes

**What are the implications of this last release?**
Devs that have 
```json
"dependencies": {
  "botbuilder": "^3.0.0"  
}
```
will install your breaking change release on a fresh installation (created by an automatic release processes, for example), and potentially will have a broken bot.

*Solution*:
1) Stick to semver for nodejs: There is not an equivalence in features between C# and NodeJS SDKs, and you will always have specific technology bugs, that can cause to release patch versions independently. *This is the default strategy for nodejs open source projects*
2) If you don't want to follow semver (hope you dont), please, state clearly somewhere in the documentation your release strategy, and give an advice to your users about how to proceed with the dependencies

**Comment by danmarshall** [comment]
Thanks @jmendiara - we're aware of semantic versioning and try to stick to it. In the 3.2.1 release notes, the listed breaking changes shouldn't have affected many developers:

 "These changes shouldn't effect many people as its likely you were already re-evaluating the matched expression if you needed the capture data."

"This should only be a breaking change if you are using multiple IntentDialogs to scope down from a general model to a more specialized model. "

Generally we are trying to provide a better experience for 99% of our developers, and if we updated the major number, they would not have gotten these changes.

**Comment by Stevenic** [comment]
Yes... We're still in preview mode even though we're at version 3.  At this point we're likely to have numerous more breaking changes. We're trying to keep them as small as possible and only making them when we can't avoid it. 

For this particular release the breaking changes were actually bug fixes.  For a small number of users these could have been desired behaviour so we provided an alternate way of achieving that behaviour while we fixed the issue effecting a fairly large number of users.  My goal would be to not release another breaking change for 3.x but while I don't see that happening I can't promise it wont. We've added a ton of new features and have many more we're planning to add. I can promise if we think a breaking change will affect more than a handful of users we won't do it.  And by handful I mean less than 10.  Of the 2 breaking changes we made this update I'd suspect 1 affected exactly 0 people and the other affected maybe 3 or 4. I'm sorry if you were one of those affected but the bug we fixed with the IntentDialog recognition mode was particularly nasty.  The change I made was the best compromise I could think of.

**Comment by Stevenic** [comment]
I should also point out that the only reason we're at version 3.x is because of external forces. If I had my way we'd still be 0.x.x something

**Comment by jmendiara** [comment]
> I should also point out that the only reason we're at version 3.x is because of external forces. If I had my way we'd still be 0.x.x

Unfortunately, there are backwards incompatible changes in almost every release, something inherent to `0.x.x` releases
The lack of unit testing does not give also some kind of security about maintainers will not break things unintentionally, both in TS and JS 

Therefore, our team has fixed the version in the `package.json` and we are tracking carefully every new release done, and we'd recommend to other devs to do so.

Hope this situation changes in the near future. **Keep growing and enhancing the FW!** And don't forget that the community can help maintainers if they publish a roadmap and ask for help.
