### ISSUE TITLE
Direct Line Connector performance very slow

### ISSUE THREAD

**Issue by CameronVetter** [Microsoft/BotBuilder#915]
I have created a simple echo bot and published it into the bot framework  (Bot handle is P14)  When I run it on my local box with the emulator, responses are fast and feel instant.  When I use a client through the Direct Line Connector with the deployed bot in the cloud response times are often 1-3 seconds.  I investigated with Application Insights and found that the majority of the time is spent in directline.botframwork.com with that part of the call change taking on average 500 ms, with peaks of 1-2 seconds and occasionally failing completely.  Any suggestions on how to get better performance out of the direct line connector?

**Comment by dandriscoll** [comment]
The core of the Direct Line protocol takes, on average, around 200ms to accept and "send" the message. However, there are two features in the protocol to make lives easier for client developers that inflate this value.

First, we guarantee message ordering so clients don't have to deal with messages appearing in the past. This can introduce delays as we reorder calls, especially under heavy contention.

Second, we pass the bot's return status back to the client. This means the POST includes transit time to Direct Line (X ms), overhead/authorization/storage (200ms), transit time to the bot (Y ms), processing time within the bot (Z ms). If you're including the reply time, there's an additional transit time back from the bot (Y ms) and storage (200ms).

The two variables you have the most control over are the location of the bot (which affects the variable Y) and the total time it takes for your bot to respond (Z). Hosting your bot in North America will affect variable Y. I've seen bots hosted in Hong Kong whose conversations take 5000ms or more because the trans-Pacific calls can take 1500ms.

In most cases, you don't get to control where the client is, so I don't think X is a variable you can control too much unless you have a user in North America accessing a webpage in Europe which calls back into Direct Line.

(We're planning to add more datacenters over time.)

**Comment by dandriscoll** [comment]
I took another pass through the code on Sunday after responding and was able to trim another ~80ms from the core DirectLine write. The remaining time spent in the call is transit and in the bot itself.

I'll close this for now. Feel free to at-mention me if you want to discuss more, or open a new issue. Thanks!

**Comment by brendanarnold** [comment]
@dandriscoll my bot is hosted In western Europe on Azure, would moving the region to pacific USA make a significant difference to the Y time? Should I be doing this going forward?

**Comment by dandriscoll** [comment]
Yes. Hosting your bot in Azure West US is fastest at the moment.
