### ISSUE TITLE
Adding a keyboard attachment displays incorrectly on Telegram

### ISSUE THREAD

**Issue by MironV** [Microsoft/BotBuilder#935]
If you add a keyboard attachment to a message, on Telegram you get a weird "Options:" phantom text that follows the message text. The buttons for the keyboard are then shown as buttons rather than showing as a keyboard replacement in the actual keyboard.

**Comment by eanders-MS** [comment]
Sorry or the slow response! I just noticed this issue assigned to me.
Telegram has two types of keyboard: inline and reply. Inline keyboards appear in the chat stream, and scroll up when new messages arrive. Reply keyboards pop up like a traditional keyboard would, and disappear once the user makes a choice. Telegram requires inline keyboards to be accompanied by message text, which is why we send "Options:" if no other text is available. Telegram rejects the keyboard if no text accompanies it. The Bot Framework does not directly support the Telegram reply keyboard yet, but you can still display one using the channelData field of the message. The channelData field lets you send channel-native messages, allowing you do make use of channel-specific functionality not supported by the Bot Framework. Some documentation for this field exists here (not specific to C#, even though it is in the URL):
https://docs.botframework.com/en-us/csharp/builder/sdkreference/channels.html#customtelegrammessages

In the Node.js BotBuilder SDK, channelData is set via the sourceEvent field on the reply message.
Here's an example that would send a reply keyboard to Telegram from a bot built on the Node.js SDK (this keyboard would resemble a numeric keypad):
``` javascript
reply.sourceEvent = ({
	telegram: {
		method: "sendMessage",
		parameters: {
			text: "This is a reply keyboard",
			parse_mode: "Markdown",
			reply_markup: JSON.stringify({
				"keyboard": [
					[{ text: "1" }, { text: "2" }, { text: "3" }],
					[{ text: "4" }, { text: "5" }, { text: "6" }],
					[{ text: "7" }, { text: "8" }, { text: "9" }],
					[{ text: "*" }, { text: "0" }, { text: "#" }]
				]
			})
		}
	}
});
```
Eric

**Comment by eanders-MS** [comment]
@MironV Closing this issue now. Please drop a comment here if you'd like to pursue the topic further.
